Repository kubernetes-sigs/kubespray, pull requests merged in 2018-06, with the labels that each got.

#2838 Remove the HUGE gitlab logo
  README.md
Labels: cncf-cla: yes, size/XS

#2841 Add label to kubelet env for kubeadm deploy cluster
  roles/kubernetes/node/templates/kubelet.kubeadm.env.j2
Labels: cncf-cla: yes, size/S

#2828 Fix compare AnsibleUnsafeText with integer
  roles/kubernetes/preinstall/tasks/main.yml
Labels: cncf-cla: yes, size/XS

#2827 wip pr for improved cert sync
  library/vault_cert_issue.py
  roles/etcd/tasks/gen_certs_vault.yml
  roles/etcd/tasks/sync_etcd_master_certs.yml
  roles/etcd/tasks/sync_etcd_node_certs.yml
  roles/kubernetes/secrets/tasks/gen_certs_vault.yml
  roles/vault/tasks/shared/issue_cert.yml
Labels: cncf-cla: yes, size/L

#2819 Fix enough network address space assert
  roles/kubernetes/preinstall/tasks/verify-settings.yml
Labels: cncf-cla: yes, size/XS

#2849 Revert "wip pr for improved cert sync"
  library/vault_cert_issue.py
  roles/etcd/tasks/gen_certs_vault.yml
  roles/etcd/tasks/sync_etcd_master_certs.yml
  roles/etcd/tasks/sync_etcd_node_certs.yml
  roles/kubernetes/secrets/tasks/gen_certs_vault.yml
  roles/vault/tasks/shared/issue_cert.yml
Labels: cncf-cla: yes

#2852 Adding missing rkt template for etcd-events
  roles/etcd/templates/etcd-events-rkt.service.j2
Labels: cncf-cla: yes, size/M

#2851 Adding wait for vault up handler in service restart
  roles/vault/handlers/main.yml
Labels: cncf-cla: yes, size/XS

#2825 Changed /etc/systemd/system/docker.service.d/docker-options.conf file for successful parsing mount aguments
  roles/docker/templates/docker-options.conf.j2
Labels: cncf-cla: yes, size/XS

#2835 roles/kubernetes/client: kubeconfig template should use access_ip
  roles/kubernetes/client/tasks/main.yml
Labels: ci-triggered, cncf-cla: yes, size/XS

#2856 Upgrade Kubernetes to 10.0.4 and etcd to 3.2.18
  README.md
  inventory/sample/group_vars/k8s-cluster.yml
  roles/download/defaults/main.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: cncf-cla: yes, size/M

#2859 Fix nginx-proxy HA when kubeadm enable
  roles/kubernetes/kubeadm/tasks/main.yml
Labels: cncf-cla: yes, size/XS

#2872 Reconfigure kube-proxy to access kube-apiserver via the LB(kubeadm)
  roles/kubernetes/kubeadm/tasks/main.yml
Labels: cncf-cla: yes, size/S

#2857 ingress-nginx: Upgrade to 0.15.0
  README.md
  roles/download/defaults/main.yml
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/ingress-nginx-controller-ds.yml.j2
Labels: cncf-cla: yes, size/M

#2629 Fixup #2545, cephfs-provisioner: Individual Namespace for Add-on
  inventory/sample/group_vars/k8s-cluster.yml
  roles/kubernetes-apps/external_provisioner/cephfs_provisioner/defaults/main.yml
Labels: cncf-cla: yes, size/XS

#2860 cert-manager: Upgrade to v0.3.0
  README.md
  roles/download/defaults/main.yml
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/cert-manager-certificate-crd.yml.j2
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/cert-manager-clusterissuer-crd.yml.j2
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/cert-manager-clusterrole.yml.j2
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/cert-manager-clusterrolebinding.yml.j2
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/cert-manager-deploy.yml.j2
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/cert-manager-issuer-crd.yml.j2
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/cert-manager-sa.yml.j2
Labels: cncf-cla: yes, size/M

#2750 Add vm_name option to vsphere cloud provider config
  roles/kubernetes/node/templates/vsphere-cloud-config.j2
Labels: cncf-cla: yes, size/XS

#2876 parametrized iptables options for docker daemon
  inventory/sample/group_vars/k8s-cluster.yml
  roles/docker/defaults/main.yml
  roles/docker/templates/docker-options.conf.j2
Labels: cncf-cla: yes, size/XS

#2890 CoreDNS uses cluster_name instead of dns_domain
  roles/kubernetes-apps/ansible/templates/coredns-config.yml.j2
Labels: cncf-cla: yes, size/XS

#2844 Fix inconsistent variables in task name and task message
  roles/docker/defaults/main.yml
  roles/docker/tasks/set_facts_dns.yml
Labels: cncf-cla: yes, size/XS

#2894 Limit the maximum number of revisions saved per helm release
  roles/kubernetes-apps/helm/defaults/main.yml
  roles/kubernetes-apps/helm/tasks/main.yml
Labels: cncf-cla: yes, size/XS

#2899 Improve variable handling for disabling etcd events cluster
  cluster.yml
  roles/etcd/defaults/main.yml
  roles/kubernetes/master/templates/kubeadm-config.yaml.j2
  roles/kubernetes/master/templates/manifests/kube-apiserver.manifest.j2
  roles/kubespray-defaults/defaults/main.yaml
Labels: cncf-cla: yes, size/S

#2898 Enable by default the kubelet token auth
  roles/kubespray-defaults/defaults/main.yaml
Labels: cncf-cla: yes, size/XS

#2801 Fixed "network_plugin" variable
  roles/kubernetes/preinstall/tasks/verify-settings.yml
Labels: cncf-cla: yes, size/XS

#2737 Update kube-scheduler policy
  roles/kubernetes/master/templates/kube-scheduler-policy.yaml.j2
Labels: cncf-cla: yes, size/S

#2903 Add manage swap on the worker node
  roles/kubernetes/preinstall/tasks/main.yml
  roles/kubernetes/preinstall/tasks/swapoff.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: cncf-cla: yes, size/S

#2891 Fix the Python and pip version flag in the README
  README.md
Labels: cncf-cla: yes, size/XS

#2911 generate k8s certs bug
  roles/kubernetes/secrets/tasks/check-certs.yml
Labels: size/S

#2922 Add run_once to remove-node
  roles/remove-node/post-remove/tasks/main.yml
  roles/remove-node/pre-remove/tasks/main.yml
Labels: cncf-cla: yes, size/XS

#2338 allow for configurable openstack storage class
  roles/kubernetes-apps/persistent_volumes/openstack/defaults/main.yml
  roles/kubernetes-apps/persistent_volumes/openstack/tasks/main.yml
  roles/kubernetes-apps/persistent_volumes/openstack/templates/openstack-storage-class.yml
  roles/kubernetes-apps/persistent_volumes/openstack/templates/openstack-storage-class.yml.j2
Labels: cncf-cla: yes, size/M

#2763 Update efk stack
  roles/download/defaults/main.yml
  roles/kubernetes-apps/efk/elasticsearch/templates/efk-clusterrolebinding.yml
  roles/kubernetes-apps/efk/elasticsearch/templates/efk-sa.yml
  roles/kubernetes-apps/efk/elasticsearch/templates/elasticsearch-deployment.yml.j2
  roles/kubernetes-apps/efk/fluentd/defaults/main.yml
  roles/kubernetes-apps/efk/fluentd/templates/fluentd-config.yml.j2
  roles/kubernetes-apps/efk/fluentd/templates/fluentd-ds.yml.j2
  roles/kubernetes-apps/efk/kibana/defaults/main.yml
  roles/kubernetes-apps/efk/kibana/templates/kibana-deployment.yml.j2
Labels: cncf-cla: yes, size/L

#2795 Make Calico nodename overridable on bare metal
  roles/network_plugin/calico/defaults/main.yml
  roles/network_plugin/calico/templates/cni-calico.conflist.j2
Labels: cncf-cla: yes, size/XS

#2926 No need to install rkt on CoreOS
  roles/rkt/tasks/main.yml
Labels: cncf-cla: yes, size/XS

#2923 Adding uuidfile for rkt based vault to properly cleanup after itself
  roles/vault/templates/rkt.service.j2
Labels: cncf-cla: yes, size/M

#2941 Fix default value for dns_mode on the document
  docs/dns-stack.md
Labels: cncf-cla: yes, size/XS

#2945 Add rkt gc task
  roles/rkt/files/rkt-gc.sh
  roles/rkt/tasks/main.yml
Labels: cncf-cla: yes, size/S

#2921 fix template index out of range for pull images
  roles/download/tasks/set_docker_image_facts.yml
Labels: cncf-cla: yes, size/XS

#2918 fix add etcd_events_access_address
  roles/kubespray-defaults/defaults/main.yaml
Labels: cncf-cla: yes, size/XS
