Repository kubernetes-sigs/kubespray, pull requests merged in 2018-03, with the labels that each got.

#2385 Add etcd-events cluster for kube-apiserver
  roles/etcd/defaults/main.yml
  roles/etcd/handlers/main.yml
  roles/etcd/tasks/configure.yml
  roles/etcd/tasks/install_docker.yml
  roles/etcd/tasks/join_etcd-events_member.yml
  roles/etcd/tasks/join_etcd_member.yml
  roles/etcd/tasks/main.yml
  roles/etcd/tasks/refresh_config.yml
  roles/etcd/tasks/set_cluster_health.yml
  roles/etcd/templates/etcd-events-docker.service.j2
  roles/etcd/templates/etcd-events-host.service.j2
  roles/etcd/templates/etcd-events.env.j2
  roles/etcd/templates/etcd-events.j2
  roles/kubernetes/master/templates/manifests/kube-apiserver.manifest.j2
  roles/kubespray-defaults/defaults/main.yaml
  roles/reset/tasks/main.yml
  tests/files/gce_centos7-flannel-addons.yml
Labels: cncf-cla: yes, size/L

#2341 gather facts for all nodes, even if running for single one (--limit)
  cluster.yml
  upgrade-cluster.yml
Labels: cncf-cla: yes, size/S

#2294 Enable OOM killing
  roles/etcd/templates/etcd.j2
Labels: cncf-cla: yes, size/XS

#2376 Correct use of deprecated argument to TF/OpenStack module
  contrib/terraform/openstack/modules/network/main.tf
Labels: cncf-cla: yes, size/XS

#2406 Delete unused fedora docker repo
  roles/docker/vars/fedora-20.yml
  roles/docker/vars/fedora.yml
Labels: cncf-cla: yes, size/M

#2407 remove + groups['calico-rr']
  cluster.yml
  contrib/terraform/aws/templates/inventory.tpl
Labels: cncf-cla: yes, size/XS

#2408 Use proper lookup of etcd host for calico
  roles/network_plugin/calico/tasks/main.yml
Labels: cncf-cla: yes, size/XS

#2324 Integrate kubernetes/ingress-nginx 0.10.2 to Kubespray
  cluster.yml
  inventory/sample/group_vars/k8s-cluster.yml
  roles/kubernetes-apps/ingress_controller/ingress_nginx/README.md
  roles/kubernetes-apps/ingress_controller/ingress_nginx/defaults/main.yml
  roles/kubernetes-apps/ingress_controller/ingress_nginx/tasks/main.yml
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/ingress-nginx-clusterrole.yml.j2
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/ingress-nginx-clusterrolebinding.yml.j2
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/ingress-nginx-cm.yml.j2
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/ingress-nginx-controller-ds.yml.j2
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/ingress-nginx-default-backend-rs.yml.j2
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/ingress-nginx-default-backend-svc.yml.j2
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/ingress-nginx-ns.yml.j2
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/ingress-nginx-role.yml.j2
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/ingress-nginx-rolebinding.yml.j2
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/ingress-nginx-sa.yml.j2
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/ingress-nginx-tcp-servicecs-cm.yml.j2
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/ingress-nginx-udp-servicecs-cm.yml.j2
  roles/kubernetes-apps/ingress_controller/meta/main.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: cncf-cla: yes, size/XL

#2411 README.md update for default component versions
  README.md
Labels: cncf-cla: yes, size/XS

#2184 Added support for kubelet webhook authentication/authorization
  roles/kubernetes-apps/cluster_roles/tasks/main.yml
  roles/kubernetes-apps/cluster_roles/templates/node-webhook-cr.yml.j2
  roles/kubernetes-apps/cluster_roles/templates/node-webhook-crb.yml.j2
  roles/kubernetes/node/templates/kubelet.kubeadm.env.j2
  roles/kubernetes/node/templates/kubelet.standard.env.j2
  roles/kubespray-defaults/defaults/main.yaml
Labels: cncf-cla: yes, size/M

#2417 Fix kubespary rpm spec file some requires
  contrib/packaging/rpm/kubespray.spec
Labels: cncf-cla: yes, size/XS

#2421 Adding ssh_private_key_file to ProxyCommand
  roles/kubespray-defaults/defaults/main.yaml
Labels: cncf-cla: yes, size/XS

#2419 Add labels for ingress_nginx_namespace
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/ingress-nginx-controller-ds.yml.j2
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/ingress-nginx-ns.yml.j2
Labels: cncf-cla: yes, size/XS

#2403 Fix issues #2246
  README.md
  docs/atomic.md
Labels: cncf-cla: yes, size/XS

#2423 docker-ce instead of docker-engine repo
  roles/docker/defaults/main.yml
  roles/docker/vars/debian.yml
  roles/docker/vars/redhat.yml
  roles/docker/vars/ubuntu.yml
Labels: cncf-cla: yes, size/M

#2432 Remove DigitalOcean
  .gitlab-ci.yml
  README.md
Labels: cncf-cla: yes, size/S

#2425 Add Custom ConfigMap Support for ingress-nginx
  inventory/sample/group_vars/k8s-cluster.yml
  roles/kubernetes-apps/ingress_controller/ingress_nginx/defaults/main.yml
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/ingress-nginx-cm.yml.j2
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/ingress-nginx-tcp-servicecs-cm.yml.j2
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/ingress-nginx-udp-servicecs-cm.yml.j2
Labels: cncf-cla: yes, size/S

#2435 kube Module Enhancements
  library/kube.py
Labels: cncf-cla: yes, size/M

#2422 Enable OOM killing for etcd-events
  roles/etcd/templates/etcd-events.j2
Labels: cncf-cla: yes, size/XS

#2416 Remove nodes
  remove-node.yml
  roles/remove-node/post-remove/tasks/main.yml
  roles/remove-node/pre-remove/defaults/main.yml
  roles/remove-node/pre-remove/tasks/main.yml
Labels: cncf-cla: yes, size/M

#2440 clean http-proxy.conf
  roles/reset/tasks/main.yml
Labels: cncf-cla: yes, size/XS

#2433 Fix systemd version detection
  roles/docker/tasks/systemd.yml
Labels: cncf-cla: yes, size/XS

#2444 Prefix system:node CRB
  roles/kubernetes-apps/cluster_roles/tasks/main.yml
  roles/kubernetes-apps/cluster_roles/templates/node-crb.yml.j2
Labels: cncf-cla: yes, size/XS

#2445 Fix kubernetes cert permission sync
  roles/kubernetes/secrets/tasks/gen_certs_script.yml
Labels: cncf-cla: yes, size/XS

#2378 Update OpenStack contrib to use per-cluster inventory layout
  contrib/terraform/openstack/README.md
  contrib/terraform/openstack/group_vars
  contrib/terraform/openstack/sample-inventory/cluster.tf
  contrib/terraform/openstack/sample-inventory/group_vars
Labels: cncf-cla: yes, size/L

#2427 FIXUP #2424: local_provisioner directory should be created only if enabled
  inventory/sample/group_vars/k8s-cluster.yml
  roles/kubernetes-apps/external_provisioner/local_volume_provisioner/templates/local-volume-provisioner-ns.yml.j2
  roles/kubernetes/node/templates/kubelet-container.j2
  roles/kubernetes/node/templates/kubelet.rkt.service.j2
  roles/kubernetes/preinstall/tasks/main.yml
Labels: cncf-cla: yes, size/S

#2295 Fix indexing of supplementary DNS in openssl.conf
  roles/kubernetes/secrets/templates/openssl.conf.j2
Labels: cncf-cla: yes, size/XS

#2452 Fix issues #2451 Support docker-ce and docker-engine
  roles/docker/defaults/main.yml
  roles/docker/tasks/main.yml
  roles/docker/templates/rh_docker.repo.j2
  roles/docker/vars/debian.yml
  roles/docker/vars/redhat.yml
  roles/docker/vars/ubuntu.yml
Labels: cncf-cla: yes, size/M

#2460 Fix yamllint roles error for #2188 commit
  roles/network_plugin/weave/tasks/main.yml
Labels: cncf-cla: yes, size/XS

#2458 use archive instead of command
  scripts/collect-info.yaml
Labels: cncf-cla: yes, size/XS

#2459 Add remove node to getting-started doc
  docs/getting-started.md
Labels: cncf-cla: yes, size/S

#2434 add support for azure vnetResourceGroup
  inventory/sample/group_vars/all.yml
  roles/kubernetes/preinstall/tasks/azure-credential-check.yml
  roles/kubernetes/preinstall/templates/azure-cloud-config.j2
Labels: cncf-cla: yes, size/XS

#2467 Fix error in kubelet.kubeadm.env.j2
  roles/kubernetes/node/templates/kubelet.kubeadm.env.j2
Labels: cncf-cla: yes, size/XS

#2447 Fix indent in custom ConfigMap ingress-nginx
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/ingress-nginx-cm.yml.j2
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/ingress-nginx-tcp-servicecs-cm.yml.j2
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/ingress-nginx-udp-servicecs-cm.yml.j2
Labels: cncf-cla: yes, size/XS

#2428 Added option for encrypting secrets to etcd v.2
  inventory/sample/group_vars/k8s-cluster.yml
  roles/kubernetes/master/defaults/main.yml
  roles/kubernetes/master/tasks/encrypt-at-rest.yml
  roles/kubernetes/master/tasks/main.yml
  roles/kubernetes/master/templates/kubeadm-config.yaml.j2
  roles/kubernetes/master/templates/manifests/kube-apiserver.manifest.j2
  roles/kubernetes/master/templates/secrets_encryption.yaml.j2
Labels: cncf-cla: yes, size/M

#2472 Make sure output from extra args is strings
  roles/kubernetes/master/templates/kubeadm-config.yaml.j2
Labels: cncf-cla: yes, size/XS

#2461 Add support to kubeadm too
  roles/kubernetes/master/templates/kubeadm-config.yaml.j2
Labels: cncf-cla: yes, size/XS

#2457 Fix vsphere cloud_provider RBAC permissions
  roles/kubernetes-apps/cluster_roles/tasks/main.yml
  roles/kubernetes-apps/cluster_roles/templates/vsphere-rbac.yml.j2
Labels: cncf-cla: yes, size/M

#2462 Add CoreDNS support
  docs/dns-stack.md
  docs/vars.md
  inventory/sample/group_vars/k8s-cluster.yml
  roles/docker/tasks/set_facts_dns.yml
  roles/download/defaults/main.yml
  roles/kubernetes-apps/ansible/defaults/main.yml
  roles/kubernetes-apps/ansible/tasks/cleanup_dns.yml
  roles/kubernetes-apps/ansible/tasks/coredns.yml
  roles/kubernetes-apps/ansible/tasks/kubedns.yml
  roles/kubernetes-apps/ansible/tasks/main.yml
  roles/kubernetes-apps/ansible/templates/coredns-clusterrole.yml.j2
  roles/kubernetes-apps/ansible/templates/coredns-clusterrolebinding.yml.j2
  roles/kubernetes-apps/ansible/templates/coredns-config.yml.j2
  roles/kubernetes-apps/ansible/templates/coredns-deployment.yml.j2
  roles/kubernetes-apps/ansible/templates/coredns-sa.yml.j2
  roles/kubernetes-apps/ansible/templates/coredns-svc.yml.j2
  roles/kubernetes/node/templates/kubelet.kubeadm.env.j2
  roles/kubernetes/node/templates/kubelet.standard.env.j2
  roles/kubernetes/preinstall/tasks/set_resolv_facts.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: cncf-cla: yes, size/L

#2468 change expirations period for generated certificate from 10y to 100 years
  roles/etcd/files/make-ssl-etcd.sh
  roles/kubernetes/secrets/files/make-ssl.sh
  roles/network_plugin/contiv/files/generate-certificate.sh
Labels: cncf-cla: yes, size/S

#2347 Support multiple artifacts under individual inventory directory
  .gitignore
  docs/getting-started.md
  inventory/sample/group_vars/k8s-cluster.yml
  roles/kubernetes/client/defaults/main.yml
  roles/kubernetes/client/tasks/main.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: cncf-cla: yes, size/M

#2487 Mark "calico-rr" as optional in fact gather
  upgrade-cluster.yml
Labels: cncf-cla: yes, size/XS

#2485 Add --iface-regex options to flannel
  roles/network_plugin/flannel/defaults/main.yml
  roles/network_plugin/flannel/templates/cni-flannel.yml.j2
Labels: cncf-cla: yes, size/S

#2446 Credentials files should not be considered as inventory files
  ansible.cfg
  docs/getting-started.md
  docs/vars.md
  inventory/sample/group_vars/k8s-cluster.yml
  roles/kubernetes/master/defaults/main.yml
  roles/vault/defaults/main.yml
  tests/testcases/010_check-apiserver.yml
Labels: cncf-cla: yes, size/S

#2503 Fix duplicate --proxy-client-cert-file and --proxy-client-key-file
  roles/kubernetes/master/templates/manifests/kube-apiserver.manifest.j2
  roles/kubespray-defaults/defaults/main.yaml
Labels: cncf-cla: yes, size/XS

#2509 Update flannel version to v0.10.0
  README.md
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS

#2364 set local_release_dir in downloads to match others
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS

#2498 Upgraded kubernetes from 1.9.3 to 1.9.5
  README.md
  inventory/sample/group_vars/k8s-cluster.yml
  roles/download/defaults/main.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: size/S

#2508 Cilium v.1.0.0-rc8
  .gitlab-ci.yml
  roles/download/defaults/main.yml
  roles/network_plugin/cilium/templates/cilium-cr.yml.j2
  roles/network_plugin/cilium/templates/cilium-ds.yml.j2
  tests/files/gce_centos7-cilium.yml
  tests/files/gce_coreos-cilium.yml
  tests/files/gce_rhel7-cilium.yml
  tests/files/gce_ubuntu-cilium-sep.yml
Labels: cncf-cla: yes, size/M

#2489 Only copy tokens if tokens_list contains any
  roles/kubernetes/secrets/tasks/gen_tokens.yml
Labels: cncf-cla: yes, size/XS

#2490 Only apply roles from first master node to fix regression
  roles/kubernetes-apps/cluster_roles/tasks/main.yml
Labels: cncf-cla: yes, size/S

#2504 Update kube-apiserver.manifest.j2 and kubeadm-config.yaml.j2 to incorporate `endpoint-reconciler-type: lease`
  roles/kubernetes/master/templates/kubeadm-config.yaml.j2
  roles/kubernetes/master/templates/manifests/kube-apiserver.manifest.j2
Labels: cncf-cla: yes, size/XS

#2332 Registry Addon Fixup
  inventory/sample/group_vars/k8s-cluster.yml
  roles/kubernetes-apps/registry/README.md
  roles/kubernetes-apps/registry/defaults/main.yml
  roles/kubernetes-apps/registry/files/images/Dockerfile
  roles/kubernetes-apps/registry/files/images/Makefile
  roles/kubernetes-apps/registry/files/images/rootfs/bin/boot
  roles/kubernetes-apps/registry/files/images/rootfs/etc/nginx/conf.d/default.conf.in
  roles/kubernetes-apps/registry/files/images/rootfs/etc/nginx/docker-registry.conf
  roles/kubernetes-apps/registry/files/images/rootfs/etc/nginx/nginx.conf
  roles/kubernetes-apps/registry/tasks/main.yml
  roles/kubernetes-apps/registry/templates/auth/README.md
  roles/kubernetes-apps/registry/templates/auth/registry-auth-rc.yml.j2
  roles/kubernetes-apps/registry/templates/gcs/README.md
  roles/kubernetes-apps/registry/templates/gcs/registry-gcs-rc.yml.j2
  roles/kubernetes-apps/registry/templates/registry-ns.yml.j2
  roles/kubernetes-apps/registry/templates/registry-proxy-ds.yml.j2
  roles/kubernetes-apps/registry/templates/registry-pv.yml.j2
  roles/kubernetes-apps/registry/templates/registry-pvc.yml.j2
  roles/kubernetes-apps/registry/templates/registry-rs.yml.j2
  roles/kubernetes-apps/registry/templates/registry-svc.yml.j2
  roles/kubernetes-apps/registry/templates/tls/README.md
  roles/kubernetes-apps/registry/templates/tls/registry-tls-rc.yml.j2
  roles/kubernetes-apps/registry/templates/tls/registry-tls-svc.yml.j2
Labels: cncf-cla: yes, size/XL

#2333 CephFS Provisioner Addon Fixup
  roles/kubernetes-apps/external_provisioner/cephfs_provisioner/README.md
  roles/kubernetes-apps/external_provisioner/cephfs_provisioner/defaults/main.yml
  roles/kubernetes-apps/external_provisioner/cephfs_provisioner/tasks/main.yml
  roles/kubernetes-apps/external_provisioner/cephfs_provisioner/templates/cephfs-provisioner-clusterrole.yml.j2
  roles/kubernetes-apps/external_provisioner/cephfs_provisioner/templates/cephfs-provisioner-clusterrolebinding.yml.j2
  roles/kubernetes-apps/external_provisioner/cephfs_provisioner/templates/cephfs-provisioner-ns.yml.j2
  roles/kubernetes-apps/external_provisioner/cephfs_provisioner/templates/cephfs-provisioner-role.yml.j2
  roles/kubernetes-apps/external_provisioner/cephfs_provisioner/templates/cephfs-provisioner-rolebinding.yml.j2
  roles/kubernetes-apps/external_provisioner/cephfs_provisioner/templates/cephfs-provisioner-rs.yml.j2
  roles/kubernetes-apps/external_provisioner/cephfs_provisioner/templates/cephfs-provisioner-sa.yml.j2
  roles/kubernetes-apps/external_provisioner/cephfs_provisioner/templates/cephfs-provisioner-sc.yml.j2
  roles/kubernetes-apps/external_provisioner/cephfs_provisioner/templates/cephfs-provisioner-secret.yml.j2
  roles/kubernetes-apps/external_provisioner/meta/main.yml
  roles/kubernetes-apps/meta/main.yml
Labels: cncf-cla: yes, size/L

#2523 Upgrade Weave to 2.2.1
  README.md
  roles/download/defaults/main.yml
  roles/network_plugin/weave/defaults/main.yml
  roles/network_plugin/weave/templates/weave-net.yml.j2
  tests/files/gce_centos-weave-kubeadm.yml
  tests/files/gce_coreos-alpha-weave-ha.yml
  tests/files/gce_rhel7-weave.yml
  tests/files/gce_ubuntu-weave-sep.yml
Labels: cncf-cla: yes, size/M

#2521 optional calico_ip_auto_method variable with IP_AUTODETECTION_METHOD
  roles/network_plugin/calico/defaults/main.yml
  roles/network_plugin/calico/templates/calico-node.yml.j2
Labels: cncf-cla: yes, size/S

#2532 add etc tunning options
  roles/etcd/defaults/main.yml
  roles/etcd/templates/etcd-events.env.j2
  roles/etcd/templates/etcd.env.j2
  roles/etcd/templates/etcd.j2
Labels: cncf-cla: yes, size/S

#2529 Fixed inventory file creation
  contrib/azurerm/roles/generate-inventory_2/templates/inventory.j2
Labels: cncf-cla: yes, size/XS

#2526 Remove kibana_base_url
  roles/kubernetes-apps/efk/kibana/defaults/main.yml
Labels: cncf-cla: yes, size/XS

#2524 Set exact user for Kubelet services
  roles/kubernetes/node/templates/kubelet.docker.service.j2
  roles/kubernetes/node/templates/kubelet.host.service.j2
  roles/kubernetes/node/templates/kubelet.rkt.service.j2
Labels: cncf-cla: yes, size/XS

#2262 Update Calico and Canal
  roles/download/defaults/main.yml
  roles/network_plugin/calico/templates/calico-node.yml.j2
  roles/network_plugin/canal/templates/canal-node.yaml.j2
Labels: cncf-cla: yes, size/M

#2537 Fixup #2262: Update README.md for calico v2.6.8
  README.md
Labels: cncf-cla: yes, size/XS

#2492 gather all facts
  cluster.yml
Labels: cncf-cla: yes, size/XS

#2538 Fixup #2523: Upgrade Weave to 2.2.1
  roles/network_plugin/weave/tasks/main.yml
  roles/network_plugin/weave/templates/00-weave.conflist.j2
  roles/network_plugin/weave/templates/weave-net.yml.j2
Labels: cncf-cla: yes, size/XS

#2488 Dedicated node for ingress nginx controller
  inventory/sample/group_vars/k8s-cluster.yml
  inventory/sample/hosts.ini
  roles/kubernetes-apps/ingress_controller/ingress_nginx/defaults/main.yml
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/ingress-nginx-controller-ds.yml.j2
  roles/kubernetes/node/templates/kubelet.standard.env.j2
Labels: cncf-cla: yes, size/S

#2536 Remove old docker packages and other docker upgrade fixes
  roles/docker/defaults/main.yml
  roles/docker/tasks/main.yml
  roles/docker/tasks/pre-upgrade.yml
  roles/docker/vars/redhat.yml
Labels: cncf-cla: yes, size/M

#2548 Added a fix in openssl.conf template to check for loadbalancer IP.
  roles/kubernetes/secrets/templates/openssl.conf.j2
Labels: cncf-cla: yes, size/XS

#2540 Write cloud-config during kubelet configuration
  roles/kubernetes/node/tasks/main.yml
  roles/kubernetes/preinstall/tasks/main.yml
Labels: cncf-cla: yes, size/S

#2553 Added retries in pre-upgrade.yml and retries while applying kube-dns.yml
  roles/kubernetes-apps/ansible/tasks/main.yml
  roles/kubernetes/master/tasks/pre-upgrade.yml
Labels: cncf-cla: yes, size/XS

#2555 remove redundancy code
  roles/kubernetes/node/templates/manifests/kube-proxy.manifest.j2
Labels: cncf-cla: yes, size/XS

#2290 Node labels definition in kubelet params from inventory
  docs/vars.md
  roles/kubernetes/node/templates/kubelet.standard.env.j2
  tests/ansible.cfg
Labels: cncf-cla: yes, size/S

#2500 Add prometheus annotations to spec in ingress
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/ingress-nginx-controller-ds.yml.j2
Labels: cncf-cla: yes, size/XS

#2350 set nodeName to "{{ inventory_hostname }}" in kubeadm-config
  roles/kubernetes/master/templates/kubeadm-config.yaml.j2
Labels: cncf-cla: yes, size/XS

#2062 replace ansible.sudo by ansible.become for vagrant
  Vagrantfile
  docs/vagrant.md
Labels: cncf-cla: yes, size/S

#2525 Return subnet_id as defined in kubespray.tf
  contrib/terraform/openstack/modules/network/outputs.tf
Labels: cncf-cla: yes, size/XS

#2564 include do extension for jinja
  ansible.cfg
Labels: cncf-cla: yes, size/XS

#2557 Maybe vault health check needs delay
  roles/vault/tasks/cluster/systemd.yml
Labels: cncf-cla: yes, size/XS

#2561 only set no_proxy if other proxy vars are defined
  roles/kubespray-defaults/defaults/main.yaml
Labels: cncf-cla: yes, size/XS

#2544 Update openssl.conf to count better and work with Jinja 2.9
  roles/etcd/templates/openssl.conf.j2
  roles/kubernetes/master/templates/kubeadm-config.yaml.j2
  roles/kubernetes/secrets/templates/openssl.conf.j2
Labels: cncf-cla: yes, size/M

#2512 Switch hyperkube from CoreOS to Google
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS

#2562 Fix kubecert_node.results indexes
  roles/kubernetes/secrets/tasks/check-certs.yml
Labels: cncf-cla: yes, size/XS

#2566 Fix etcd from import task to include task
  roles/etcd/tasks/main.yml
Labels: cncf-cla: yes, size/S

#2565 Only download container/file if host is in defined group
  roles/download/defaults/main.yml
  roles/download/tasks/download_container.yml
  roles/download/tasks/download_file.yml
  roles/download/tasks/sync_container.yml
Labels: cncf-cla: yes, size/M

#2554 Fix kubespray's ServiceAccount token signing keys
  roles/kubernetes/master/tasks/kubeadm-migrate-certs.yml
  roles/kubernetes/master/templates/manifests/kube-apiserver.manifest.j2
  roles/kubernetes/master/templates/manifests/kube-controller-manager.manifest.j2
  roles/kubernetes/secrets/files/make-ssl.sh
  roles/kubernetes/secrets/tasks/gen_certs_script.yml
Labels: cncf-cla: yes, size/S

#2569 Allow ansible_ssh_private_key_file for Openstack
  contrib/terraform/openstack/ansible_bastion_template.txt
Labels: cncf-cla: yes, size/XS

#2567 node_labels documentation and kube-ingress label definition as role_node_label
  docs/vars.md
  roles/kubernetes/node/templates/kubelet.standard.env.j2
Labels: cncf-cla: yes, size/S

#2543 Integrate jetstack/cert-manager 0.2.3 to Kubespray
  inventory/sample/group_vars/k8s-cluster.yml
  roles/download/defaults/main.yml
  roles/etcd/defaults/main.yml
  roles/kubernetes-apps/ingress_controller/cert_manager/README.md
  roles/kubernetes-apps/ingress_controller/cert_manager/defaults/main.yml
  roles/kubernetes-apps/ingress_controller/cert_manager/tasks/main.yml
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/cert-manager-certificate-crd.yml.j2
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/cert-manager-clusterissuer-crd.yml.j2
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/cert-manager-clusterrole.yml.j2
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/cert-manager-clusterrolebinding.yml.j2
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/cert-manager-deploy.yml.j2
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/cert-manager-issuer-crd.yml.j2
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/cert-manager-ns.yml.j2
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/cert-manager-sa.yml.j2
  roles/kubernetes-apps/ingress_controller/meta/main.yml
  roles/kubernetes/master/defaults/main.yml
  roles/kubespray-defaults/defaults/main.yaml
  roles/network_plugin/calico/defaults/main.yml
  tests/files/gce_centos7-flannel-addons.yml
Labels: cncf-cla: yes, size/L

#2572 Update etcd deployment to use correct cert and key
  roles/etcd/handlers/backup.yml
  roles/etcd/tasks/configure.yml
  roles/etcd/tasks/join_etcd-events_member.yml
  roles/etcd/tasks/join_etcd_member.yml
  roles/etcd/tasks/join_member.yml
  roles/etcd/tasks/set_cluster_health.yml
Labels: cncf-cla: yes, size/M

#2547 prometheus operator, metrics for k8s cluster
  inventory/sample/group_vars/k8s-cluster.yml
  roles/kubernetes-apps/meta/main.yml
  roles/kubernetes-apps/metrics/defaults/main.yml
  roles/kubernetes-apps/metrics/tasks/main.yml
  tests/files/gce_centos7-flannel-addons.yml
Labels: cncf-cla: yes, size/M

#2571 ingress-nginx: container download related things should defined in the download role
  inventory/sample/hosts.ini
  roles/download/defaults/main.yml
  roles/kubernetes-apps/ingress_controller/ingress_nginx/defaults/main.yml
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/ingress-nginx-controller-ds.yml.j2
  roles/kubernetes/node/templates/kubelet.standard.env.j2
Labels: cncf-cla: yes, size/M
