Repository kubernetes-sigs/kubespray, pull requests merged in 2018-07, with the labels that each got.

#2917 Remove modprobe binary from kubelet rkt deployment
  roles/kubernetes/node/templates/kubelet.rkt.service.j2
Labels: cncf-cla: yes, size/XS

#2938 Fixup vault etcd check
  roles/vault/tasks/shared/check_etcd.yml
Labels: cncf-cla: yes, size/XS

#2924 fix the time of ca files are changed in make-ssl-etcd
  roles/etcd/files/make-ssl-etcd.sh
Labels: cncf-cla: yes, size/XS

#2952 Fix `coreos_dual` -> `coredns_dual` typo
  roles/docker/tasks/set_facts_dns.yml
Labels: cncf-cla: yes, size/XS

#2948 move node selection from --limit to --extra-vars=node<nodename>"
  docs/getting-started.md
  remove-node.yml
  roles/remove-node/post-remove/tasks/main.yml
  roles/remove-node/pre-remove/tasks/main.yml
Labels: cncf-cla: yes, size/S

#2951 cephfs-provisioner: Upgrade to 06fddbe2
  README.md
  extra_playbooks/build-cephfs-provisioner.yml
  inventory/sample/group_vars/k8s-cluster.yml
  roles/download/defaults/main.yml
  roles/kubernetes-apps/external_provisioner/cephfs_provisioner/defaults/main.yml
  roles/kubernetes-apps/external_provisioner/cephfs_provisioner/tasks/main.yml
  roles/kubernetes-apps/external_provisioner/cephfs_provisioner/templates/00-namespace.yml.j2
  roles/kubernetes-apps/external_provisioner/cephfs_provisioner/templates/clusterrole-cephfs-provisioner.yml.j2
  roles/kubernetes-apps/external_provisioner/cephfs_provisioner/templates/clusterrolebinding-cephfs-provisioner.yml.j2
  roles/kubernetes-apps/external_provisioner/cephfs_provisioner/templates/deploy-cephfs-provisioner.yml.j2
  roles/kubernetes-apps/external_provisioner/cephfs_provisioner/templates/role-cephfs-provisioner.yml.j2
  roles/kubernetes-apps/external_provisioner/cephfs_provisioner/templates/rolebinding-cephfs-provisioner.yml.j2
  roles/kubernetes-apps/external_provisioner/cephfs_provisioner/templates/sa-cephfs-provisioner.yml.j2
  roles/kubernetes-apps/external_provisioner/cephfs_provisioner/templates/sc-cephfs-provisioner.yml.j2
  roles/kubernetes-apps/external_provisioner/cephfs_provisioner/templates/secret-cephfs-provisioner.yml.j2
Labels: cncf-cla: yes, size/M

#2954 Update README.md
  README.md
Labels: cncf-cla: yes, size/XS

#2946 CheckNodePIDPressure is not supported in v1.10
  roles/kubernetes/master/templates/kube-scheduler-policy.yaml.j2
Labels: cncf-cla: yes, size/XS

#2966 Fix terraform env Not effective
  contrib/terraform/aws/README.md
Labels: cncf-cla: yes, size/XS

#2960 Add tags to deploy components by --tags option
  docs/upgrades.md
  roles/etcd/tasks/main.yml
  roles/kubernetes/node/tasks/install.yml
  roles/kubernetes/secrets/tasks/main.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: cncf-cla: yes, size/L

#2977 Fix 2976
  roles/download/tasks/main.yml
Labels: cncf-cla: yes, size/XS

#2975 Remove step that disables `kube_basic_auth`.
  roles/kubernetes/master/tasks/main.yml
Labels: cncf-cla: yes, size/XS

#2974 cephfs-provisioner: Upgrade to 1.1.0-k8s1.10
  README.md
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS

#2935 cert-manager: Upgrade to 0.3.2
  README.md
  roles/download/defaults/main.yml
  roles/kubernetes-apps/ingress_controller/cert_manager/tasks/main.yml
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/00-namespace.yml.j2
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/clusterrole-cert-manager.yml.j2
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/clusterrolebinding-cert-manager.yml.j2
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/crd-certificate.yml.j2
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/crd-clusterissuer.yml.j2
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/crd-issuer.yml.j2
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/deploy-cert-manager.yml.j2
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/sa-cert-manager.yml.j2
Labels: cncf-cla: yes, size/M

#2972 Force copy cni files
  roles/kubernetes/master/tasks/main.yml
  roles/network_plugin/calico/tasks/main.yml
  roles/network_plugin/canal/tasks/main.yml
  roles/network_plugin/cloud/tasks/main.yml
  roles/network_plugin/contiv/tasks/main.yml
  roles/network_plugin/weave/tasks/main.yml
Labels: cncf-cla: yes, size/S

#2984 add docker upgrade tag doc
  docs/upgrades.md
Labels: cncf-cla: yes, size/XS

#2985 Fix vault file owner issues and k8s apiserver cert creation
  roles/etcd/tasks/sync_etcd_master_certs.yml
  roles/kubernetes/secrets/tasks/gen_certs_vault.yml
  roles/vault/tasks/bootstrap/main.yml
  roles/vault/tasks/bootstrap/sync_vault_certs.yml
  roles/vault/tasks/shared/issue_cert.yml
Labels: cncf-cla: yes, size/S

#2995 Fixed kubectl path.
  roles/kubernetes/kubeadm/tasks/main.yml
Labels: cncf-cla: yes, size/XS

#2990 Include etcd and masters in adding node doc
  docs/getting-started.md
Labels: cncf-cla: yes, size/XS

#3018 Remove double slash
  roles/kubernetes/kubeadm/tasks/main.yml
Labels: cncf-cla: yes, size/XS

#3031 Fix label of registry in README
  roles/kubernetes-apps/registry/README.md
Labels: cncf-cla: yes, lgtm, size/S
