Repository kubernetes-sigs/kubespray, pull requests merged in 2018-12, with the labels that each got.

#3786 Use download binary instead of copying from the container
  roles/download/defaults/main.yml
  roles/network_plugin/calico/tasks/install.yml
  roles/network_plugin/canal/tasks/main.yml
  roles/network_plugin/cloud/tasks/main.yml
  roles/network_plugin/contiv/tasks/main.yml
  roles/network_plugin/flannel/tasks/pre-upgrade.yml
  roles/network_plugin/kube-router/tasks/main.yml
  roles/network_plugin/weave/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/L

#3788 Set configure-cloud-routes=false as default if no network plugin is used
  roles/kubernetes/master/templates/manifests/kube-controller-manager.manifest.j2
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3800 Cleanup defaults file from kubernetes-apps and add dashboard to download role
  docs/netcheck.md
  roles/download/defaults/main.yml
  roles/kubernetes-apps/ansible/defaults/main.yml
  roles/kubernetes-apps/ansible/templates/netchecker-agent-ds.yml.j2
  roles/kubernetes-apps/ansible/templates/netchecker-agent-hostnet-ds.yml.j2
  roles/kubernetes-apps/ansible/templates/netchecker-server-deployment.yml.j2
Labels: approved, cncf-cla: yes, lgtm, size/M

#3802 Remove iface kube-ipvs0 on reset when kube_proxy_mode is ipvs
  roles/reset/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3801 Fix basic auth tokens for kubeadm deployment.
  roles/kubernetes/master/meta/main.yml
  roles/kubernetes/secrets/tasks/main.yml
  roles/kubernetes/tokens/files/kube-gen-token.sh
  roles/kubernetes/tokens/tasks/check-tokens.yml
  roles/kubernetes/tokens/tasks/gen_tokens.yml
  roles/kubernetes/tokens/tasks/main.yml
  tests/files/gce_centos7-flannel-addons.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#3808 Fix ubuntu-contiv test failed
  tests/files/gce_ubuntu-contiv-sep.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3806 Reduce log spam of verbose tasks
  roles/etcd/tasks/gen_certs_script.yml
  roles/kubernetes-apps/ansible/tasks/main.yml
  roles/kubernetes-apps/cluster_roles/tasks/main.yml
  roles/kubernetes-apps/external_provisioner/local_volume_provisioner/tasks/main.yml
  roles/kubernetes-apps/network_plugin/calico/tasks/main.yml
  roles/kubernetes-apps/policy_controller/calico/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3813 Reset tasks specific to Calico
  roles/network_plugin/calico/tasks/reset.yml
  roles/reset/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3816 Reset: Check for kube-ipvs0 presence before removing it
  roles/reset/tasks/main.yml
Labels: approved, cherry-pick-approved, cncf-cla: yes, lgtm

#3836 Streamline path to certs dir
  roles/kubernetes-apps/ansible/defaults/main.yml
  roles/kubernetes/kubeadm/tasks/main.yml
  roles/kubernetes/master/defaults/main.yml
  roles/kubernetes/master/tasks/encrypt-at-rest.yml
  roles/kubernetes/master/templates/kubeadm-config.v1alpha1.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1alpha2.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1alpha3.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1beta1.yaml.j2
  roles/kubernetes/node/defaults/main.yml
  roles/kubernetes/preinstall/tasks/0050-create_directories.yml
  roles/kubespray-defaults/defaults/main.yaml
  roles/network_plugin/calico/defaults/main.yml
  roles/network_plugin/calico/rr/defaults/main.yml
  roles/network_plugin/canal/defaults/main.yml
  roles/network_plugin/cilium/defaults/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#3837 Added v1.10.11 v1.11.5 support
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3839 Fix apiServerCertSANs in kubeadm config file
  roles/kubernetes/master/tasks/kubeadm-setup.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3844 Add docker 18.09 support
  README.md
  roles/container-engine/docker/vars/debian.yml
  roles/container-engine/docker/vars/redhat.yml
  roles/container-engine/docker/vars/ubuntu-amd64.yml
  roles/container-engine/docker/vars/ubuntu-arm64.yml
  roles/container-engine/docker/vars/ubuntu-bionic.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3826 [doc] Remove mention of fuel in README
  README.md
Labels: approved, cncf-cla: yes, size/XS

#3843 Added RBAC rights for metrics_server
  roles/kubernetes-apps/metrics_server/templates/resource-reader.yaml.j2
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3845 Move node-cidr-mask-size to ControllerManagerextraArgs
  roles/kubernetes/master/templates/kubeadm-config.v1alpha1.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1alpha2.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1alpha3.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1beta1.yaml.j2
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3846 Fix setting host_architecture var for etcd
  roles/etcd/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3863 Remove vault role from inventory_builder
  contrib/inventory_builder/inventory.py
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3828 kube-router enable DSR
  inventory/sample/group_vars/k8s-cluster/k8s-net-kube-router.yml
  roles/network_plugin/kube-router/defaults/main.yml
  roles/network_plugin/kube-router/templates/kube-router.yml.j2
Labels: approved, cncf-cla: yes, lgtm, size/S

#3852 Add metrics service to kube-dns
  roles/kubernetes-apps/ansible/templates/kubedns-svc.yml.j2
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3869 Add proxy to /etc/apt/apt.conf for ubuntu
  roles/bootstrap-os/tasks/bootstrap-ubuntu.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3864 Fix disabling swap on ubuntu systems
  roles/kubernetes/preinstall/tasks/0010-swapoff.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3873 Adding is_atomic in centos bootstrap-os
  roles/bootstrap-os/tasks/bootstrap-centos.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3867 Metrics server resizer addon needs to target metrics server deployment
  roles/kubernetes-apps/metrics_server/templates/metrics-server-deployment.yaml.j2
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3848 Fix error with ipvs on cluster reset task
  roles/reset/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3882 dns_mode defaults to coredns
  docs/dns-stack.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3856 cri-o reset all containers and pods
  roles/reset/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#3884 Use recommended defaults for dns autoscale
  roles/kubernetes-apps/ansible/defaults/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3847 Fix assert condition for RBAC non-anonymous-auth
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3764 Load nf_conntrack module if nf_conntrack_ipv4 failed
  roles/kubernetes/node/tasks/main.yml
Labels: approved, cncf-cla: yes, size/S

#3868 Reapply win_node patches on cluster upgrade
  upgrade-cluster.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3893 add vars for cilium init container
  roles/download/defaults/main.yml
  roles/kubernetes/master/defaults/main.yml
  roles/kubernetes/node/tasks/main.yml
  roles/network_plugin/cilium/templates/cilium-ds.yml.j2
Labels: approved, cncf-cla: yes, lgtm, size/S

#3909 set kubespray-defaults kube_api_anonymous_auth to true
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3908 Fixup line breaks for kubeadm SANs
  roles/kubernetes/master/tasks/kubeadm-setup.yml
  roles/kubernetes/master/templates/kubeadm-config.v1alpha1.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1alpha2.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1alpha3.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1beta1.yaml.j2
Labels: approved, cncf-cla: yes, lgtm, size/S

#3915 Fix skip upgrade first master
  roles/kubernetes/kubeadm/tasks/main.yml
  roles/kubernetes/master/tasks/kubeadm-setup.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3914 Add images downloader to download roles
  roles/download/tasks/kubeadm_images.yml
  roles/download/tasks/main.yml
  roles/download/templates/kubeadm-images.yaml.j2
Labels: approved, cncf-cla: yes, lgtm, size/S

#3895 Upgrade kubernetes to v1.13.1
  .gitlab-ci.yml
  README.md
  inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml
  roles/download/defaults/main.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, size/M

#3919 Fix docker_options definition when docker_version is 'latest' rather …
  inventory/sample/group_vars/all/docker.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3906 Fix duplicate storage-backend
  roles/kubernetes/master/templates/kubeadm-config.v1alpha1.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1alpha2.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1alpha3.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1beta1.yaml.j2
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3933 Fix installation using CRIO about download images failed
  roles/download/templates/kubeadm-images.yaml.j2
Labels: approved, cncf-cla: yes, size/S

#3934 Delete unused controlPlane for join node
  roles/kubernetes/kubeadm/templates/kubeadm-client.conf.v1beta1.j2
Labels: approved, cncf-cla: yes, size/XS

#3929 Add k8s 1.12.4 checksums
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3936 Fix kubeadm images templates
  roles/download/templates/kubeadm-images.yaml.j2
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3938 Fix reconfigure and upgrade cluster
  extra_playbooks/upgrade-only-k8s.yml
  roles/kubernetes/master/defaults/main.yml
  roles/kubernetes/master/tasks/kubeadm-setup.yml
  roles/kubernetes/master/tasks/kubeadm-upgrade.yml
  roles/kubernetes/master/tasks/kubeadm-version.yml
  roles/kubernetes/master/tasks/pre-upgrade.yml
  upgrade-cluster.yml
Labels: approved, cncf-cla: yes, lgtm, size/L

#3888 controlPlaneEndpoint set up through load balancer should be possible …
  roles/kubernetes/kubeadm/templates/kubeadm-client.conf.v1alpha1.j2
  roles/kubernetes/kubeadm/templates/kubeadm-client.conf.v1alpha2.j2
  roles/kubernetes/kubeadm/templates/kubeadm-client.conf.v1alpha3.j2
  roles/kubernetes/kubeadm/templates/kubeadm-client.conf.v1beta1.j2
  roles/kubernetes/master/templates/kubeadm-config.v1alpha1.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1alpha2.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1alpha3.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1beta1.yaml.j2
Labels: approved, cncf-cla: yes, lgtm, size/S

#3931 Move nodelocal to its own section in the docs
  docs/dns-stack.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#3932 Add support http/https proxy for bootstrap-debian
  roles/bootstrap-os/tasks/bootstrap-debian.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#3941 Fix GPU node Scheduling
  roles/kubernetes/node/templates/kubelet.kubeadm.env.j2
Labels: approved, cncf-cla: yes, size/S

#3911 More Feature/2.8 backports for 2.8.1
  README.md
  roles/download/defaults/main.yml
  roles/kubernetes/master/tasks/kubeadm-setup.yml
  roles/kubernetes/master/templates/kubeadm-config.v1alpha1.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1alpha2.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1alpha3.yaml.j2
Labels: approved, cncf-cla: yes, lgtm, size/S

#3878 Grammar fixes for CRI-O documentation
  docs/cri-o.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#3939 Adds support for webhook token auth.
  roles/kubernetes/master/defaults/main.yml
  roles/kubernetes/master/tasks/main.yml
  roles/kubernetes/master/templates/kubeadm-config.v1alpha1.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1alpha2.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1alpha3.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1beta1.yaml.j2
  roles/kubernetes/master/templates/webhook-token-auth-config.yaml.j2
Labels: approved, cncf-cla: yes, lgtm, size/M

#3857 Added filters for integer conversion of kubelet_max_pods and kube_net…
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3901 Documented docker_version acceptable values
  docs/vars.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3940 Install python-pip from local yum repository
  roles/bootstrap-os/tasks/bootstrap-centos.yml
Labels: approved, cncf-cla: yes, lgtm, size/S
