Repository kubernetes-sigs/kubespray, pull requests merged in 2018-02, with the labels that each got.

#2256 Fix safe upgrade
  inventory/sample/group_vars/all.yml
  roles/kubernetes/kubeadm/tasks/main.yml
  roles/kubernetes/master/defaults/main.yml
  roles/kubernetes/master/templates/kubeadm-config.yaml.j2
  roles/kubespray-defaults/defaults/main.yaml
  roles/upgrade/post-upgrade/tasks/main.yml
Labels: cncf-cla: yes, size/S

#2293 Making node status and scheduling detection mo betta for upgrades
  roles/upgrade/post-upgrade/tasks/main.yml
  roles/upgrade/pre-upgrade/tasks/main.yml
Labels: cncf-cla: yes, size/S

#2287 Add optional StorageClass name with cephfs_provisioner_storage_class
  inventory/sample/group_vars/k8s-cluster.yml
  roles/kubernetes-apps/cephfs_provisioner/defaults/main.yml
  roles/kubernetes-apps/cephfs_provisioner/templates/cephfs-provisioner-sc.yml.j2
Labels: cncf-cla: yes, size/XS

#2299 Fix default_resolver is undefined
  roles/dnsmasq/templates/01-kube-dns.conf.j2
Labels: cncf-cla: yes, size/XS

#2298 Fix version comparison
  roles/kubernetes/master/templates/manifests/kube-apiserver.manifest.j2
Labels: cncf-cla: yes, size/XS

#2291 Added apiserver extra args variable for kubeadm config
  roles/kubernetes/master/defaults/main.yml
  roles/kubernetes/master/templates/kubeadm-config.yaml.j2
  roles/kubernetes/master/templates/manifests/kube-apiserver.manifest.j2
Labels: cncf-cla: yes, size/XS

#2311 Increased timeout values for k8s API server restart
  roles/kubernetes/master/handlers/main.yml
Labels: cncf-cla: yes, size/XS

#2313 Update default CONFIG_FILE for contrib/inventory_builder/inventory.py
  contrib/inventory_builder/inventory.py
Labels: cncf-cla: yes, size/XS

#2314 Update coreos-calico-aio scenario to test no group vars
  tests/cloud_playbooks/create-gce.yml
  tests/files/coreos-calico-aio.yml
Labels: cncf-cla: yes, size/XS

#2317 Additional CI platform (digital-ocean)
  .gitlab-ci.yml
  Dockerfile
  tests/Makefile
  tests/cloud_playbooks/create-do.yml
  tests/files/do_ubuntu-canal-ha.yml
  tests/files/gce_centos-weave-kubeadm.yml
  tests/files/gce_centos7-calico-ha.yml
  tests/files/gce_centos7-flannel-addons.yml
  tests/files/gce_coreos-alpha-weave-ha.yml
  tests/files/gce_coreos-calico-aio.yml
  tests/files/gce_coreos-canal.yml
  tests/files/gce_debian8-calico-upgrade.yml
  tests/files/gce_rhel7-canal-sep.yml
  tests/files/gce_rhel7-weave.yml
  tests/files/gce_ubuntu-canal-ha.yml
  tests/files/gce_ubuntu-canal-kubeadm.yml
  tests/files/gce_ubuntu-contiv-sep.yml
  tests/files/gce_ubuntu-flannel-sep.yml
  tests/files/gce_ubuntu-rkt-sep.yml
  tests/files/gce_ubuntu-vault-sep.yml
  tests/files/gce_ubuntu-weave-sep.yml
  tests/requirements.txt
  tests/templates/inventory-do.j2
Labels: cncf-cla: yes, size/L

#2285 Remove redundant python-apt install
  roles/kubernetes/preinstall/tasks/main.yml
Labels: cncf-cla: yes, size/XS

#2325 rollback to a two stage CI
  .gitlab-ci.yml
Labels: cncf-cla: yes, size/S

#2330 Update typo in the tag necessary for the ELB role
  docs/aws.md
Labels: cncf-cla: yes, size/XS

#2236 Added cilium support
  .gitlab-ci.yml
  README.md
  inventory/sample/group_vars/k8s-cluster.yml
  roles/download/defaults/main.yml
  roles/kubernetes-apps/network_plugin/cilium/tasks/main.yml
  roles/kubernetes-apps/network_plugin/meta/main.yml
  roles/kubernetes/master/templates/manifests/kube-controller-manager.manifest.j2
  roles/kubernetes/node/templates/kubelet.kubeadm.env.j2
  roles/kubernetes/node/templates/kubelet.rkt.service.j2
  roles/kubernetes/node/templates/kubelet.standard.env.j2
  roles/kubernetes/preinstall/tasks/main.yml
  roles/kubernetes/preinstall/tasks/verify-settings.yml
  roles/kubespray-defaults/defaults/main.yaml
  roles/network_plugin/cilium/defaults/main.yml
  roles/network_plugin/cilium/handlers/main.yml
  roles/network_plugin/cilium/tasks/main.yml
  roles/network_plugin/cilium/templates/cilium-config.yml.j2
  roles/network_plugin/cilium/templates/cilium-cr.yml.j2
  roles/network_plugin/cilium/templates/cilium-crb.yml.j2
  roles/network_plugin/cilium/templates/cilium-ds.yml.j2
  roles/network_plugin/cilium/templates/cilium-sa.yml.j2
  roles/network_plugin/meta/main.yml
  tests/files/gce_centos7-cilium.yml
  tests/files/gce_coreos-cilium.yml
  tests/files/gce_rhel7-cilium.yml
  tests/files/gce_ubuntu-cilium-sep.yml
Labels: cncf-cla: yes, size/L

#2312 Added iptables lock fix and ajusted oom-score
  roles/kubernetes/node/templates/manifests/kube-proxy.manifest.j2
Labels: cncf-cla: yes, size/XS

#2033 Update Terraform docs and authentication method
  contrib/terraform/openstack/.gitignore
  contrib/terraform/openstack/README.md
  contrib/terraform/openstack/kubespray.tf
  contrib/terraform/openstack/modules/compute/main.tf
  contrib/terraform/openstack/modules/compute/variables.tf
  contrib/terraform/openstack/modules/ips/main.tf
  contrib/terraform/openstack/modules/ips/outputs.tf
  contrib/terraform/openstack/modules/ips/variables.tf
  contrib/terraform/openstack/modules/network/main.tf
  contrib/terraform/openstack/modules/network/outputs.tf
  contrib/terraform/openstack/modules/network/variables.tf
  contrib/terraform/openstack/variables.tf
Labels: cncf-cla: yes, size/XL

#2315 Set filemode to 0640
  roles/kubernetes/master/tasks/users-file.yml
  roles/network_plugin/weave/tasks/main.yml
Labels: cncf-cla: yes, size/XS

#2356 Add health check to kube proxy
  roles/kubernetes/node/templates/manifests/kube-proxy.manifest.j2
Labels: cncf-cla: yes, size/S

#2359 Fixed generate front proxy client certs with vault
  roles/etcd/defaults/main.yml
  roles/kubernetes/secrets/tasks/gen_certs_vault.yml
  roles/kubernetes/secrets/tasks/sync_kube_master_certs.yml
  tests/files/gce_ubuntu-vault-sep.yml
Labels: cncf-cla: yes, size/S

#2361 Fixing credential lookup for fe proxy and vault
  roles/vault/defaults/main.yml
Labels: cncf-cla: yes, size/XS

#2358 Fixing cert name in calico when we delegate to etcd[0]
  roles/network_plugin/calico/tasks/main.yml
  roles/network_plugin/canal/tasks/main.yml
Labels: cncf-cla: yes, size/XS

#2357 Set TasksMax to infinity on any OS with systemd
  roles/docker/tasks/systemd.yml
  roles/docker/templates/docker.service.j2
Labels: cncf-cla: yes, size/XS

#2360 retry unmount kubelet dirs
  roles/reset/tasks/main.yml
Labels: cncf-cla: yes, size/XS

#2326 Fix link markdown markup
  docs/large-deployments.md
Labels: cncf-cla: yes, size/XS

#2323 Upgrade to Kubernetes v1.9.3
  README.md
  inventory/sample/group_vars/k8s-cluster.yml
  inventory/sample/hosts.ini
  roles/download/defaults/main.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: cncf-cla: yes, size/S

#2199 Fix run kubectl error
  roles/kubernetes/client/tasks/main.yml
Labels: cncf-cla: yes, size/XS

#2374 Fixing etcd certs for calico rr
  roles/network_plugin/calico/rr/tasks/main.yml
Labels: cncf-cla: yes, size/XS

#2382 Remove redundant spaces
  inventory/sample/group_vars/all.yml
Labels: cncf-cla: yes, size/XS

#2386 Use node cert for etcd tasks instead of delegating to first etcd
  roles/network_plugin/calico/rr/tasks/main.yml
  roles/network_plugin/calico/tasks/main.yml
  roles/network_plugin/canal/tasks/main.yml
Labels: cncf-cla: yes, size/S

#2373 Document sneaky etcd memory limit...
  inventory/sample/group_vars/all.yml
Labels: cncf-cla: yes, size/XS

#2363 default kube_proxy_mode in kubernetes-defaults
  roles/kubespray-defaults/defaults/main.yaml
Labels: cncf-cla: yes, size/XS

#2345 Add pre-upgrade task for moving credentials file
  .gitignore
  roles/kubernetes/preinstall/tasks/main.yml
  roles/kubernetes/preinstall/tasks/pre_upgrade.yml
Labels: cncf-cla: yes, size/S

#2393 Revert "Add pre-upgrade task for moving credentials file"
  .gitignore
  roles/kubernetes/preinstall/tasks/main.yml
  roles/kubernetes/preinstall/tasks/pre_upgrade.yml
Labels: cncf-cla: yes

#2391 Install latest version of Helm
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS

#2369 fix apiserver manifest when disabling insecure_port
  roles/kubernetes/master/templates/manifests/kube-apiserver.manifest.j2
Labels: cncf-cla: yes, size/XS
