Repository kubernetes-sigs/kubespray, pull requests merged in 2018-09, with the labels that each got.

#3207 Fix target hosts generation when /etc/hosts does not contain 127.0.0.1 or ::1
  roles/kubernetes/preinstall/tasks/0090-etchosts.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3217 Fix docker_options definition to remove newlines
  inventory/sample/group_vars/k8s-cluster.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3219 Fix ports for kubeadm client and master configs for ha setups
  roles/kubernetes/kubeadm/templates/kubeadm-client.conf.v1alpha1.j2
  roles/kubernetes/kubeadm/templates/kubeadm-client.conf.v1alpha2.j2
  roles/kubernetes/master/templates/kubeadm-config.v1alpha1.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1alpha2.yaml.j2
Labels: approved, cncf-cla: yes, lgtm, size/S

#3220 coredns: Upgrade to v1.2.2
  README.md
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3221 cephfs-provisioner: Upgrade to v2.1.0-k8s1.11
  README.md
  roles/download/defaults/main.yml
  roles/kubernetes-apps/external_provisioner/cephfs_provisioner/templates/clusterrole-cephfs-provisioner.yml.j2
  roles/kubernetes-apps/external_provisioner/cephfs_provisioner/templates/role-cephfs-provisioner.yml.j2
Labels: approved, cncf-cla: yes, lgtm, size/S

#3222 ingress-nginx: Upgrade to 0.19.0
  README.md
  roles/download/defaults/main.yml
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/clusterrole-ingress-nginx.yml.j2
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/clusterrolebinding-ingress-nginx.yml.j2
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/cm-ingress-nginx.yml.j2
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/cm-tcp-services.yml.j2
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/cm-udp-services.yml.j2
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/deploy-default-backend.yml.j2
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/ds-ingress-nginx-controller.yml.j2
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/role-ingress-nginx.yml.j2
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/rolebinding-ingress-nginx.yml.j2
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/sa-ingress-nginx.yml.j2
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/svc-default-backend.yml.j2
Labels: approved, cncf-cla: yes, lgtm, size/M

#3226 Always run helm init to allow for settings changes
  roles/kubernetes-apps/helm/tasks/main.yml
Labels: approved, cncf-cla: yes, size/S

#3210 Split group-variables
  inventory/sample/group_vars/all.yml
  inventory/sample/group_vars/all/all.yml
  inventory/sample/group_vars/all/azure.yml
  inventory/sample/group_vars/all/coreos.yml
  inventory/sample/group_vars/all/docker.yml
  inventory/sample/group_vars/all/oci.yml
  inventory/sample/group_vars/all/openstack.yml
  inventory/sample/group_vars/etcd.yml
  inventory/sample/group_vars/k8s-cluster/addons.yml
  inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml
  inventory/sample/hosts.ini
Labels: approved, cncf-cla: yes, lgtm, size/L

#3200 Required support to start working on windows node support
  cluster.yml
  roles/dnsmasq/templates/dnsmasq-autoscaler.yml.j2
  roles/dnsmasq/templates/dnsmasq-deploy.yml.j2
  roles/docker/tasks/main.yml
  roles/docker/templates/apt_preferences.d/debian_docker.j2
  roles/etcd/tasks/main.yml
  roles/kubernetes-apps/ansible/templates/kubedns-autoscaler.yml.j2
  roles/kubernetes-apps/ansible/templates/kubedns-deploy.yml.j2
  roles/kubernetes-apps/ansible/templates/netchecker-agent-ds.yml.j2
  roles/kubernetes-apps/ansible/templates/netchecker-agent-hostnet-ds.yml.j2
  roles/kubernetes-apps/efk/fluentd/templates/fluentd-ds.yml.j2
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/deploy-default-backend.yml.j2
  roles/kubernetes/master/tasks/kubeadm-setup.yml
  roles/kubernetes/node/templates/manifests/kube-proxy.manifest.j2
  roles/kubernetes/node/templates/manifests/nginx-proxy.manifest.j2
  roles/network_plugin/flannel/templates/cni-flannel.yml.j2
  roles/win_nodes/kubernetes_patch/defaults/main.yml
  roles/win_nodes/kubernetes_patch/files/nodeselector-os-linux-patch.json
  roles/win_nodes/kubernetes_patch/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#3151 Fix the jinja expression for openstack_tenant_id
  roles/kubernetes/node/defaults/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3178 Add azure-container-registry-config for Azure
  roles/kubernetes/node/templates/kubelet.standard.env.j2
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3232 Document correct var kubeadm_enabled
  docs/cri-o.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3229 Docker 18.06 for ubuntu versions before bionic
  roles/docker/vars/ubuntu-amd64.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3228 Introducing credentials_dir variable in order to be able to override it
  ansible.cfg
  docs/getting-started.md
  docs/vars.md
  inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml
  roles/kubernetes/master/defaults/main.yml
  roles/kubespray-defaults/defaults/main.yaml
  roles/vault/defaults/main.yml
  tests/testcases/010_check-apiserver.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#3027 MetalLB as loadbalancer for on premise deployments
  contrib/metallb/README.md
  contrib/metallb/metallb.yml
  contrib/metallb/roles/provision/defaults/main.yml
  contrib/metallb/roles/provision/tasks/main.yml
  contrib/metallb/roles/provision/templates/metallb-config.yml.j2
  contrib/metallb/roles/provision/templates/metallb.yml.j2
Labels: approved, cncf-cla: yes, lgtm, size/L

#3235 Emphasis on docker recommended version
  README.md
Labels: cncf-cla: yes, size/XS

#3233 Hint on ho to join the slack channel README.md
  README.md
Labels: cncf-cla: yes, size/XS

#3244 Reverts calico update to 3.2.0, fixes #3223
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/S

#3224 Fix feature-gates
  roles/kubernetes/master/templates/kubeadm-config.v1alpha1.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1alpha2.yaml.j2
Labels: approved, cncf-cla: yes, lgtm, size/S

#3122 resolve issues with new cacert feature
  roles/kubernetes/node/tasks/main.yml
  roles/kubernetes/preinstall/tasks/main.yml
Labels: cncf-cla: yes, lgtm, size/S

#3246 Upgrade pause image to 3.1
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3247 remove broken endifs in kubelet rkt mode
  roles/kubernetes/node/templates/kubelet.rkt.service.j2
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2931 Heketi/GlusterFS
  contrib/network-storage/heketi/README.md
  contrib/network-storage/heketi/heketi-tear-down.yml
  contrib/network-storage/heketi/heketi.yml
  contrib/network-storage/heketi/inventory.yml.sample
  contrib/network-storage/heketi/requirements.txt
  contrib/network-storage/heketi/roles/prepare/tasks/main.yml
  contrib/network-storage/heketi/roles/provision/defaults/main.yml
  contrib/network-storage/heketi/roles/provision/handlers/main.yml
  contrib/network-storage/heketi/roles/provision/tasks/bootstrap.yml
  contrib/network-storage/heketi/roles/provision/tasks/bootstrap/deploy.yml
  contrib/network-storage/heketi/roles/provision/tasks/bootstrap/storage.yml
  contrib/network-storage/heketi/roles/provision/tasks/bootstrap/tear-down.yml
  contrib/network-storage/heketi/roles/provision/tasks/bootstrap/topology.yml
  contrib/network-storage/heketi/roles/provision/tasks/bootstrap/volumes.yml
  contrib/network-storage/heketi/roles/provision/tasks/cleanup.yml
  contrib/network-storage/heketi/roles/provision/tasks/glusterfs.yml
  contrib/network-storage/heketi/roles/provision/tasks/glusterfs/label.yml
  contrib/network-storage/heketi/roles/provision/tasks/heketi.yml
  contrib/network-storage/heketi/roles/provision/tasks/main.yml
  contrib/network-storage/heketi/roles/provision/tasks/secret.yml
  contrib/network-storage/heketi/roles/provision/tasks/storage.yml
  contrib/network-storage/heketi/roles/provision/tasks/storageclass.yml
  contrib/network-storage/heketi/roles/provision/tasks/topology.yml
  contrib/network-storage/heketi/roles/provision/templates/glusterfs-daemonset.json.j2
  contrib/network-storage/heketi/roles/provision/templates/heketi-bootstrap.json.j2
  contrib/network-storage/heketi/roles/provision/templates/heketi-deployment.json.j2
  contrib/network-storage/heketi/roles/provision/templates/heketi-service-account.json.j2
  contrib/network-storage/heketi/roles/provision/templates/heketi-storage.json.j2
  contrib/network-storage/heketi/roles/provision/templates/heketi.json.j2
  contrib/network-storage/heketi/roles/provision/templates/storageclass.yml.j2
  contrib/network-storage/heketi/roles/provision/templates/topology.json.j2
  contrib/network-storage/heketi/roles/tear-down-disks/tasks/main.yml
  contrib/network-storage/heketi/roles/tear-down/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#3248 put back endif in kubelet rkt template
  roles/kubernetes/node/templates/kubelet.rkt.service.j2
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3253 Reduce instance sizes in gce
  tests/files/gce_centos7-flannel-addons.yml
  tests/files/gce_coreos-calico-aio.yml
  tests/files/gce_coreos-vault-upgrade.yml
  tests/files/gce_ubuntu18-flannel-aio.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3250 Fix openstack cacert task
  roles/kubernetes/node/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3249 Add missing variable kube_proxy_nodeport_addresses
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3256 [bugfix] heketi storageclass privilege
  contrib/network-storage/heketi/roles/provision/templates/storageclass.yml.j2
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3260 Add discovery_timeout to join configuration
  roles/kubernetes/kubeadm/defaults/main.yml
  roles/kubernetes/kubeadm/templates/kubeadm-client.conf.v1alpha2.j2
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3255 Fix calico health checks
  roles/kubernetes-apps/helm/tasks/main.yml
  roles/kubernetes/preinstall/tasks/0050-create_directories.yml
  roles/kubernetes/preinstall/tasks/0070-system-packages.yml
  roles/kubernetes/preinstall/tasks/0080-system-configurations.yml
  roles/network_plugin/calico/defaults/main.yml
  roles/network_plugin/calico/tasks/install.yml
  roles/network_plugin/calico/templates/calico-node.yml.j2
Labels: approved, cncf-cla: yes, lgtm, size/S

#3252 Remove insecure-port and insecure-bind-address when possible
  roles/kubernetes/master/templates/kubeadm-config.v1alpha1.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1alpha2.yaml.j2
  roles/kubernetes/master/templates/manifests/kube-apiserver.manifest.j2
Labels: approved, cncf-cla: yes, lgtm, size/S

#3257 [helm-tls] add option to secure helm tiller with tls
  roles/kubernetes-apps/helm/defaults/main.yml
  roles/kubernetes-apps/helm/files/helm-make-ssl.sh
  roles/kubernetes-apps/helm/tasks/gen_helm_tiller_certs.yml
  roles/kubernetes-apps/helm/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/L

#3276 Upgrade kubernetes to v1.11.3
  README.md
  inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml
  roles/download/defaults/main.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3270 Add insecure_registry config to docker options
  inventory/sample/group_vars/all/docker.yml
  roles/docker/.gitignore
  roles/docker/defaults/main.yml
  roles/download/defaults/main.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#3266 Precision on control machine mixed Ansible installation
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#3288 Revert "Remove insecure-port and insecure-bind-address when possible"
  roles/kubernetes/master/templates/kubeadm-config.v1alpha1.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1alpha2.yaml.j2
  roles/kubernetes/master/templates/manifests/kube-apiserver.manifest.j2
Labels: approved, cncf-cla: yes, size/S

#3286 Change update strategy to RollingUpdate
  roles/kubernetes-apps/policy_controller/calico/templates/calico-kube-controllers.yml.j2
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3261 Ensure etcd file permissions are correct when using vault
  roles/etcd/tasks/gen_certs_vault.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3283 Extra options for upgrade mode
  roles/upgrade/pre-upgrade/defaults/main.yml
  roles/upgrade/pre-upgrade/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3291 Remove --insecure-bind-address when insecure-port=0
  roles/kubernetes/master/templates/kubeadm-config.v1alpha1.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1alpha2.yaml.j2
  roles/kubernetes/master/templates/manifests/kube-apiserver.manifest.j2
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3243 Install Helm client on all masters
  cluster.yml
  roles/kubernetes-apps/helm/tasks/main.yml
  roles/kubernetes-apps/meta/main.yml
  upgrade-cluster.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#3262 [bugfix] Use bin_dir to find kubectl in contrib/metallb
  contrib/metallb/roles/provision/tasks/main.yml
  contrib/network-storage/heketi/roles/provision/tasks/storage.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1973 Replace the raw rsync command with the synchronize module
  roles/kubernetes/node/tasks/install.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3305 Fixes for upgrade mode
  roles/upgrade/pre-upgrade/defaults/main.yml
  roles/upgrade/pre-upgrade/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3258 absolute path for kubectl.
  roles/win_nodes/kubernetes_patch/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3265 [bugfix] fix path to metallb configuration
  contrib/metallb/roles/provision/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3315 Upgrade kubedns to 1.14.11
  roles/download/defaults/main.yml
  roles/kubernetes-apps/ansible/defaults/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3310 Document podsecuritypolicy_enabled and kubernetes_audit
  docs/vars.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#3309 Fix download file
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#2880 Fix #2261 by supporting Red Hat's limited PATH
  roles/kubernetes/node/tasks/main.yml
Labels: cncf-cla: yes, size/XS

#3287 Monitor CoreDNS over svc
  roles/kubernetes-apps/ansible/templates/coredns-svc.yml.j2
Labels: approved, cncf-cla: yes, lgtm, size/S

#3326 weave: Upgrade to 2.4.1
  README.md
  roles/download/defaults/main.yml
  roles/network_plugin/weave/templates/weave-net.yml.j2
Labels: approved, cncf-cla: yes, lgtm, size/S

#3324 cert-manager: Upgrade to 0.5.0
  README.md
  roles/download/defaults/main.yml
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/00-namespace.yml.j2
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/clusterrole-cert-manager.yml.j2
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/clusterrolebinding-cert-manager.yml.j2
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/crd-certificate.yml.j2
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/crd-clusterissuer.yml.j2
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/crd-issuer.yml.j2
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/deploy-cert-manager.yml.j2
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/sa-cert-manager.yml.j2
Labels: approved, cncf-cla: yes, lgtm, size/M

#3290 Fix upgrade k8s
  roles/etcd/tasks/install_host.yml
  roles/kubernetes/master/tasks/main.yml
  roles/kubernetes/node/tasks/install
  roles/kubernetes/node/tasks/install.yml
  roles/kubernetes/node/tasks/install_
  roles/kubernetes/node/tasks/install_host.yml
  upgrade-cluster.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#3316 Fix tiller override command
  roles/kubernetes-apps/helm/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3245 terraform.tfvars.example is not correct, remove.
  contrib/terraform/aws/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3227 Upgrade contiv to 1.2.1 with some enhancements
  docs/contiv.md
  inventory/sample/group_vars/all/all.yml
  roles/download/defaults/main.yml
  roles/kubernetes-apps/network_plugin/contiv/tasks/configure.yml
  roles/kubernetes-apps/network_plugin/contiv/tasks/main.yml
  roles/kubespray-defaults/defaults/main.yaml
  roles/network_plugin/contiv/defaults/main.yml
  roles/network_plugin/contiv/files/contiv-cleanup.sh
  roles/network_plugin/contiv/tasks/main.yml
  roles/network_plugin/contiv/tasks/pre-reset.yml
  roles/network_plugin/contiv/tasks/reset.yml
  roles/network_plugin/contiv/templates/contiv-api-proxy.yml.j2
  roles/network_plugin/contiv/templates/contiv-cleanup.yml.j2
  roles/network_plugin/contiv/templates/contiv-config.yml.j2
  roles/network_plugin/contiv/templates/contiv-etcd-proxy.yml.j2
  roles/network_plugin/contiv/templates/contiv-netmaster-clusterrole.yml.j2
  roles/network_plugin/contiv/templates/contiv-netmaster.yml.j2
  roles/network_plugin/contiv/templates/contiv-netplugin.yml.j2
  roles/network_plugin/contiv/templates/contiv-ovs.yml.j2
  roles/reset/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XL

#3320 Support dynamic kubelet config
  inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml
  roles/kubernetes/master/templates/kubeadm-config.v1alpha2.yaml.j2
  roles/kubernetes/node/tasks/main.yml
  roles/kubernetes/node/templates/kubelet.kubeadm.env.j2
  roles/kubespray-defaults/defaults/main.yaml
  tests/files/gce_centos-weave-kubeadm.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#3329 Keep list of k8s checksums for hyperkube and kubeadm
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#3345 Fix some typos
  docs/kubernetes-reliability.md
Labels: cncf-cla: yes, size/XS

#3347 Fix some typos
  docs/calico.md
  docs/weave.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#3344 Sync manifests from non-kubeadm to kubeadm deploy
  roles/kubernetes/master/templates/kubeadm-config.v1alpha1.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1alpha2.yaml.j2
  roles/kubernetes/master/templates/manifests/kube-apiserver.manifest.j2
  roles/kubernetes/master/templates/manifests/kube-controller-manager.manifest.j2
  roles/kubernetes/master/templates/manifests/kube-scheduler.manifest.j2
  roles/kubernetes/node/templates/kubelet.kubeadm.env.j2
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#3337 create separate options files for network plugins
  inventory/sample/group_vars/all/all.yml
  inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml
  inventory/sample/group_vars/k8s-cluster/k8s-net-calico.yml
  inventory/sample/group_vars/k8s-cluster/k8s-net-canal.yml
  inventory/sample/group_vars/k8s-cluster/k8s-net-cilium.yml
  inventory/sample/group_vars/k8s-cluster/k8s-net-contiv.yml
  inventory/sample/group_vars/k8s-cluster/k8s-net-flannel.yml
  inventory/sample/group_vars/k8s-cluster/k8s-net-weave.yml
Labels: approved, cncf-cla: yes, lgtm, size/L

#3348 Add support for kubelet_node_custom_flags
  docs/vars.md
  roles/kubernetes/node/defaults/main.yml
  roles/kubernetes/node/templates/kubelet.kubeadm.env.j2
  roles/kubernetes/node/templates/kubelet.standard.env.j2
Labels: approved, cncf-cla: yes, lgtm, size/S

#3350 Remove audit again from Kubeadm 1.10.x. Write mounts not supported un…
  roles/kubernetes/master/templates/kubeadm-config.v1alpha1.yaml.j2
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3340 Fixes Calico 3.x BGPPeer resources
  roles/network_plugin/calico/tasks/install.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3307 Calico version verification before cluster upgrade begin.
  docs/upgrades.md
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3149 fix the output of router_id with the right id
  contrib/terraform/openstack/modules/network/outputs.tf
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3354 Offline environment documentation
  docs/downloads.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#3353 fix openstack cli syntax
  docs/openstack.md
Labels: approved, cncf-cla: yes, size/XS

#3325 Make Felix healthhost configurable
  docs/calico.md
  roles/network_plugin/calico/defaults/main.yml
  roles/network_plugin/calico/templates/calico-node.yml.j2
Labels: approved, cncf-cla: yes, lgtm, size/S

#3225 Fix test readme formatting
  tests/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3143 add support for openstack trust to cloud provider config
  roles/kubernetes/node/tasks/openstack-credential-check.yml
  roles/kubernetes/node/templates/openstack-cloud-config.j2
Labels: cncf-cla: yes, lgtm, size/S

#3342 Add kubelet path for kubeadm.
  roles/kubernetes/kubeadm/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3304 Add support for GPU accelerator
  inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml
  roles/kubernetes-apps/container_engine_accelerator/meta/main.yml
  roles/kubernetes-apps/container_engine_accelerator/nvidia_gpu/defaults/main.yml
  roles/kubernetes-apps/container_engine_accelerator/nvidia_gpu/tasks/main.yml
  roles/kubernetes-apps/container_engine_accelerator/nvidia_gpu/templates/k8s-device-plugin-nvidia-daemonset.yml.j2
  roles/kubernetes-apps/container_engine_accelerator/nvidia_gpu/templates/nvidia-driver-install-daemonset.yml.j2
  roles/kubernetes-apps/container_engine_accelerator/nvidia_gpu/vars/centos-7.yml
  roles/kubernetes-apps/container_engine_accelerator/nvidia_gpu/vars/ubuntu-16.yml
  roles/kubernetes-apps/container_engine_accelerator/nvidia_gpu/vars/ubuntu-18.yml
  roles/kubernetes-apps/meta/main.yml
  roles/kubernetes/node/templates/kubelet.standard.env.j2
Labels: approved, cncf-cla: yes, lgtm, size/L

#3351 Mount basic auth or token auth dirs to support it on kubeadm deployments
  roles/kubernetes/master/templates/kubeadm-config.v1alpha1.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1alpha2.yaml.j2
Labels: approved, cncf-cla: yes, lgtm, size/S

#3355 Uses etcdv3 for calico 3 rr_v4 resources
  roles/network_plugin/calico/rr/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3280 Check `openstack_cacert` for empty string
  roles/kubernetes/master/templates/kubeadm-config.v1alpha1.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1alpha2.yaml.j2
  roles/kubernetes/master/templates/manifests/kube-controller-manager.manifest.j2
  roles/kubernetes/node/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3362 Fix some typos
  docs/ha-mode.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3363 Remove EFK from Kubespray
  inventory/sample/group_vars/k8s-cluster/addons.yml
  roles/download/defaults/main.yml
  roles/kubernetes-apps/efk/elasticsearch/defaults/main.yml
  roles/kubernetes-apps/efk/elasticsearch/meta/main.yml
  roles/kubernetes-apps/efk/elasticsearch/tasks/main.yml
  roles/kubernetes-apps/efk/elasticsearch/templates/efk-clusterrolebinding.yml
  roles/kubernetes-apps/efk/elasticsearch/templates/efk-sa.yml
  roles/kubernetes-apps/efk/elasticsearch/templates/elasticsearch-deployment.yml.j2
  roles/kubernetes-apps/efk/elasticsearch/templates/elasticsearch-service.yml.j2
  roles/kubernetes-apps/efk/fluentd/defaults/main.yml
  roles/kubernetes-apps/efk/fluentd/tasks/main.yml
  roles/kubernetes-apps/efk/fluentd/templates/fluentd-config.yml.j2
  roles/kubernetes-apps/efk/fluentd/templates/fluentd-ds.yml.j2
  roles/kubernetes-apps/efk/kibana/defaults/main.yml
  roles/kubernetes-apps/efk/kibana/tasks/main.yml
  roles/kubernetes-apps/efk/kibana/templates/kibana-deployment.yml.j2
  roles/kubernetes-apps/efk/kibana/templates/kibana-service.yml.j2
  roles/kubernetes-apps/efk/meta/main.yml
  roles/kubernetes-apps/meta/main.yml
  roles/kubernetes-apps/rotate_tokens/tasks/main.yml
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
  roles/kubespray-defaults/defaults/main.yaml
  tests/files/gce_centos7-flannel-addons.yml
Labels: approved, cncf-cla: yes, lgtm, size/XL

#3364 Remove duplicate persistent_volumes_enabled element in k8s-cluster.yml
  inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3366 Remove some useless files
  roles/kubernetes/node/tasks/install
  roles/kubernetes/node/tasks/install_
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1465 Support for AWS cloud-config
  docs/aws.md
  roles/kubernetes/master/templates/manifests/kube-apiserver.manifest.j2
  roles/kubernetes/master/templates/manifests/kube-controller-manager.manifest.j2
  roles/kubernetes/node/tasks/main.yml
  roles/kubernetes/node/templates/aws-cloud-config.j2
  roles/kubernetes/node/templates/kubelet.kubeadm.env.j2
  roles/kubernetes/node/templates/kubelet.standard.env.j2
Labels: cncf-cla: yes, size/M

#3368 Fix CI issue (Fedora task introduce new lookup plugin)
  roles/bootstrap-os/tasks/bootstrap-fedora.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3369 remove /var/lib/cni directory in reset playbook
  roles/reset/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3335 Fix/ubuntu xenial resolv conf
  roles/kubernetes/node/tasks/facts.yml
  roles/kubernetes/node/vars/ubuntu-18.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3370 Added download_validate_certs option
  inventory/sample/group_vars/all/all.yml
  roles/download/defaults/main.yml
  roles/download/tasks/download_file.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3367 Add check that kube-master, kube-node and etcd groups are not empty.
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3381 add CRI-O to README
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3382 Fix some typos
  roles/network_plugin/calico/tasks/check.yml
  roles/network_plugin/contiv/defaults/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3383 Sync manifests with kubeadm
  roles/kubernetes/master/defaults/main.yml
  roles/kubernetes/master/templates/kubeadm-config.v1alpha1.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1alpha2.yaml.j2
  roles/kubernetes/master/templates/manifests/kube-apiserver.manifest.j2
  roles/kubernetes/master/templates/manifests/kube-controller-manager.manifest.j2
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3389 Replaces nonexisting system_namespace variable
  inventory/sample/group_vars/k8s-cluster/addons.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3361 Adding pod priority for all the components.
  roles/dnsmasq/templates/dnsmasq-autoscaler.yml.j2
  roles/dnsmasq/templates/dnsmasq-deploy.yml.j2
  roles/kubernetes-apps/ansible/templates/coredns-deployment.yml.j2
  roles/kubernetes-apps/ansible/templates/dashboard.yml.j2
  roles/kubernetes-apps/ansible/templates/kubedns-autoscaler.yml.j2
  roles/kubernetes-apps/ansible/templates/kubedns-deploy.yml.j2
  roles/kubernetes-apps/ansible/templates/netchecker-agent-ds.yml.j2
  roles/kubernetes-apps/ansible/templates/netchecker-agent-hostnet-ds.yml.j2
  roles/kubernetes-apps/ansible/templates/netchecker-server-deployment.yml.j2
  roles/kubernetes-apps/cluster_roles/files/k8s-cluster-critical-pc.yml
  roles/kubernetes-apps/cluster_roles/tasks/main.yml
  roles/kubernetes-apps/external_provisioner/cephfs_provisioner/templates/deploy-cephfs-provisioner.yml.j2
  roles/kubernetes-apps/external_provisioner/local_volume_provisioner/templates/local-volume-provisioner-ds.yml.j2
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/deploy-cert-manager.yml.j2
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/deploy-default-backend.yml.j2
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/ds-ingress-nginx-controller.yml.j2
  roles/kubernetes-apps/policy_controller/calico/templates/calico-kube-controllers.yml.j2
  roles/kubernetes-apps/registry/templates/registry-proxy-ds.yml.j2
  roles/kubernetes-apps/registry/templates/registry-rs.yml.j2
  roles/kubernetes/master/templates/manifests/kube-apiserver.manifest.j2
  roles/kubernetes/master/templates/manifests/kube-controller-manager.manifest.j2
  roles/kubernetes/master/templates/manifests/kube-scheduler.manifest.j2
  roles/kubernetes/node/templates/manifests/kube-proxy.manifest.j2
  roles/kubernetes/node/templates/manifests/nginx-proxy.manifest.j2
  roles/kubespray-defaults/defaults/main.yaml
  roles/network_plugin/calico/templates/calico-node.yml.j2
  roles/network_plugin/canal/templates/canal-node.yaml.j2
  roles/network_plugin/cilium/templates/cilium-ds.yml.j2
  roles/network_plugin/contiv/templates/contiv-api-proxy.yml.j2
  roles/network_plugin/contiv/templates/contiv-cleanup.yml.j2
  roles/network_plugin/contiv/templates/contiv-etcd-proxy.yml.j2
  roles/network_plugin/contiv/templates/contiv-etcd.yml.j2
  roles/network_plugin/contiv/templates/contiv-netmaster.yml.j2
  roles/network_plugin/contiv/templates/contiv-netplugin.yml.j2
  roles/network_plugin/contiv/templates/contiv-ovs.yml.j2
  roles/network_plugin/flannel/templates/cni-flannel.yml.j2
  roles/network_plugin/weave/templates/weave-net.yml.j2
Labels: approved, cncf-cla: yes, lgtm, size/L

#3393 Ansible var should be quoted
  inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3377 UI is required for vault #3376
  roles/vault/defaults/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3378 Pip is required for vault #3376
  roles/bootstrap-os/tasks/bootstrap-centos.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3395 Fix docker role for ubuntu bionic that points to xenial
  roles/docker/vars/ubuntu-bionic.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3398 Fix README links to new inventory file paths.
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3313 update etcd
  roles/etcd/tasks/gen_certs_script.yml
  roles/etcd/tasks/install_host.yml
Labels: approved, cncf-cla: yes, lgtm, size/L

#3392 Resolve issues associated with Calico deployment in policy-only mode.
  roles/network_plugin/calico/templates/calico-config.yml.j2
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3400 Remove the redundant space
  roles/kubernetes/secrets/tasks/check-certs.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3402 Update CRI-O as experimental
  README.md
Labels: cncf-cla: yes, size/XS

#3401 skip-exists is an flag for create command, not for calicoctl
  roles/network_plugin/calico/tasks/install.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3391 All CNIs Pods: support ANY toleration.
  roles/network_plugin/calico/templates/calico-node.yml.j2
  roles/network_plugin/canal/templates/canal-node.yaml.j2
  roles/network_plugin/cilium/templates/cilium-ds.yml.j2
  roles/network_plugin/contiv/templates/contiv-api-proxy.yml.j2
  roles/network_plugin/contiv/templates/contiv-cleanup.yml.j2
  roles/network_plugin/contiv/templates/contiv-etcd.yml.j2
  roles/network_plugin/contiv/templates/contiv-netmaster.yml.j2
  roles/network_plugin/contiv/templates/contiv-netplugin.yml.j2
  roles/network_plugin/contiv/templates/contiv-ovs.yml.j2
  roles/network_plugin/flannel/templates/cni-flannel.yml.j2
  roles/network_plugin/weave/templates/weave-net.yml.j2
Labels: approved, cncf-cla: yes, lgtm, size/M

#2980 Better fix for openstack cinder zone issue using ignore-volume-az option
  inventory/sample/group_vars/all/openstack.yml
  roles/kubernetes/master/defaults/main.yml
  roles/kubernetes/master/tasks/static-pod-setup.yml
  roles/kubernetes/master/templates/kube-scheduler-policy.yaml.j2
  roles/kubernetes/master/templates/manifests/kube-scheduler.manifest.j2
  roles/kubernetes/node/templates/openstack-cloud-config.j2
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#3407 Upgrade kubedns and kubednsautoscaler
  roles/download/defaults/main.yml
  roles/kubernetes-apps/ansible/defaults/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2910 [contrib/terraform/openstack] Change from Nova security groups to Neutron
  contrib/terraform/openstack/README.md
  contrib/terraform/openstack/kubespray.tf
  contrib/terraform/openstack/modules/compute/main.tf
  contrib/terraform/openstack/modules/compute/variables.tf
  contrib/terraform/openstack/sample-inventory/cluster.tf
  contrib/terraform/openstack/variables.tf
Labels: cncf-cla: yes, size/L

#3404 Heketi: Fix `ready` to not to be an AnsibleUnsafeText
  contrib/network-storage/heketi/roles/provision/tasks/glusterfs.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3418 Remove the redundant space
  contrib/terraform/openstack/README.md
  docs/kubernetes-reliability.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3417 Fix netcheck agent/server image/tag variable names
  roles/download/defaults/main.yml
  roles/kubernetes-apps/ansible/defaults/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3420 remove the redundant space
  roles/kubernetes-apps/external_provisioner/cephfs_provisioner/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3419 fix typo: remove repeated words
  roles/cri-o/templates/crio.conf.j2
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3415 Fix the dic iteration method in the kubelet template
  roles/kubernetes/node/templates/kubelet.kubeadm.env.j2
  roles/kubernetes/node/templates/kubelet.standard.env.j2
Labels: approved, cncf-cla: yes, lgtm, size/XS
