Repository kubernetes-sigs/kubespray, pull requests merged in 2018-08, with the labels that each got.

#3033 add openstack security group for traffic to 30000-32767/tcp on worker nodes
  contrib/terraform/openstack/modules/compute/main.tf
Labels: cncf-cla: yes, lgtm, size/S

#3041 set LC_ALL=C for growpart
  roles/kubernetes/preinstall/tasks/growpart-azure-centos-7.yml
Labels: cncf-cla: yes, size/XS

#3044 Clarify etcd deployment script failure mechanism
  contrib/terraform/openstack/README.md
Labels: cncf-cla: yes, lgtm, size/XS

#3034 fix missing libraries on newer coreos versions
  roles/bootstrap-os/files/bootstrap.sh
Labels: cncf-cla: yes, lgtm, size/XS

#3064 Fix yaml roles error
  roles/kubernetes/preinstall/tasks/growpart-azure-centos-7.yml
Labels: cncf-cla: yes, size/XS

#3065 Service file binary place mismatch
  roles/vault/templates/host.service.j2
Labels: cncf-cla: yes, lgtm, size/XS

#3047 availability zones support for OpenStack
  contrib/terraform/openstack/kubespray.tf
  contrib/terraform/openstack/modules/compute/main.tf
  contrib/terraform/openstack/modules/compute/variables.tf
  contrib/terraform/openstack/variables.tf
Labels: cncf-cla: yes, lgtm, size/S

#3059 Fix a broken symbolic link for group_vars
  contrib/network-storage/glusterfs/group_vars
Labels: cncf-cla: yes, lgtm, size/XS

#3055 Add support for docker 17.09
  roles/docker/vars/debian.yml
  roles/docker/vars/redhat.yml
  roles/docker/vars/ubuntu.yml
Labels: cncf-cla: yes, lgtm, size/XS

#3050 update .gitignore
  .gitignore
Labels: cncf-cla: yes, lgtm, size/XS

#3015 Variablize kube_proxy_healthz_bind_address
  roles/kubernetes/node/defaults/main.yml
  roles/kubernetes/node/templates/manifests/kube-proxy.manifest.j2
Labels: cncf-cla: yes, lgtm, size/XS

#2994 dashboard_token_ttl option override possibility with default
  roles/kubernetes-apps/ansible/defaults/main.yml
  roles/kubernetes-apps/ansible/templates/dashboard.yml.j2
Labels: cncf-cla: yes, lgtm, size/XS

#2900 Configure openstack subnet cidr
  contrib/terraform/openstack/kubespray.tf
  contrib/terraform/openstack/modules/network/main.tf
  contrib/terraform/openstack/modules/network/variables.tf
  contrib/terraform/openstack/sample-inventory/cluster.tf
  contrib/terraform/openstack/variables.tf
Labels: cncf-cla: yes, size/S

#2875 Adding cluster_name to api cert alt name for vault
  roles/kubernetes/secrets/tasks/gen_certs_vault.yml
Labels: cncf-cla: yes, size/XS

#2342 allow for setting the cacert on openstack cloud provider
  roles/kubernetes/master/templates/kubeadm-config.yaml.j2
  roles/kubernetes/master/templates/manifests/kube-controller-manager.manifest.j2
  roles/kubernetes/node/defaults/main.yml
  roles/kubernetes/node/templates/openstack-cloud-config.j2
  roles/kubernetes/preinstall/tasks/main.yml
Labels: cncf-cla: yes, lgtm, size/M

#2997 cert-manager: Upgrade to 0.4.0
  README.md
  roles/download/defaults/main.yml
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/clusterrole-cert-manager.yml.j2
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/clusterrolebinding-cert-manager.yml.j2
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/crd-certificate.yml.j2
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/crd-clusterissuer.yml.j2
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/crd-issuer.yml.j2
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/deploy-cert-manager.yml.j2
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/sa-cert-manager.yml.j2
Labels: cncf-cla: yes, size/S

#3001 ingress-nginx: Upgrade to 0.17.1
  README.md
  roles/download/defaults/main.yml
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/ds-ingress-nginx-controller.yml.j2
Labels: cncf-cla: yes, size/XS

#3068 Enable swap
  roles/kubernetes/preinstall/tasks/verify-settings.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: cncf-cla: yes, size/XS

#3072 Add tags for coredns and kubedns
  roles/kubernetes-apps/ansible/tasks/kubedns.yml
  roles/kubernetes-apps/ansible/tasks/main.yml
Labels: cncf-cla: yes, size/XS

#3069 contrib/terraform/terraform.py: fix for Ansible 2.6.2+, issue #3067
  contrib/terraform/terraform.py
Labels: cncf-cla: yes, lgtm, size/XS

#3054 Add support for admission controllers in 1.10 and above
  roles/kubernetes/master/defaults/main.yml
  roles/kubernetes/master/templates/kubeadm-config.yaml.j2
  roles/kubernetes/master/templates/manifests/kube-apiserver.manifest.j2
Labels: cncf-cla: yes, size/S

#3037 Fixed checking skip_downloads condition.
  cluster.yml
  scale.yml
  upgrade-cluster.yml
Labels: cncf-cla: yes, size/XS

#2904 Only subdirectories in /var/lib/kubelet should be unmounted at reset time
  roles/reset/tasks/main.yml
Labels: cncf-cla: yes, size/XS

#3022 weave: Upgrade to 2.4.0
  README.md
  inventory/sample/group_vars/k8s-cluster.yml
  roles/download/defaults/main.yml
  roles/kubernetes-apps/network_plugin/weave/tasks/main.yml
  roles/network_plugin/weave/defaults/main.yml
  roles/network_plugin/weave/tasks/main.yml
  roles/network_plugin/weave/tasks/seed.yml
  roles/network_plugin/weave/templates/weave-net.yml.j2
Labels: cncf-cla: yes, lgtm, size/L

#3028 cilium v1.1.2
  README.md
  roles/download/defaults/main.yml
  roles/network_plugin/cilium/defaults/main.yml
  roles/network_plugin/cilium/templates/cilium-config.yml.j2
  roles/network_plugin/cilium/templates/cilium-cr.yml.j2
  roles/network_plugin/cilium/templates/cilium-crb.yml.j2
  roles/network_plugin/cilium/templates/cilium-ds.yml.j2
Labels: cncf-cla: yes, size/L

#2909 kubedns & kubedns-autoscaler: Stick to master nodes.
  roles/kubernetes-apps/ansible/templates/coredns-deployment.yml.j2
  roles/kubernetes-apps/ansible/templates/kubedns-autoscaler.yml.j2
  roles/kubernetes-apps/ansible/templates/kubedns-deploy.yml.j2
Labels: cncf-cla: yes, lgtm, size/M

#3066 fix bad conditional
  roles/kubernetes/kubeadm/tasks/main.yml
Labels: cncf-cla: yes, size/XS

#3087 bump upgrade tests to v2.5.0 commit
  .gitlab-ci.yml
Labels: cncf-cla: yes, size/XS

#3081 local-volume-provisioner: use mountPropagation HostToContainer and version bump
  roles/download/defaults/main.yml
  roles/kubernetes-apps/external_provisioner/local_volume_provisioner/README.md
  roles/kubernetes-apps/external_provisioner/local_volume_provisioner/templates/local-volume-provisioner-ds.yml.j2
Labels: cncf-cla: yes, size/S

#3091 Add the path to kubectl binary
  roles/remove-node/post-remove/tasks/main.yml
Labels: cncf-cla: yes, size/XS

#3078 Upgrade kubernetes to V1.11.x
  .gitlab-ci.yml
  README.md
  inventory/sample/group_vars/k8s-cluster.yml
  roles/download/defaults/main.yml
  roles/kubernetes/kubeadm/tasks/main.yml
  roles/kubernetes/kubeadm/templates/kubeadm-client.conf.v1alpha1.j2
  roles/kubernetes/kubeadm/templates/kubeadm-client.conf.v1alpha2.j2
  roles/kubernetes/master/tasks/kubeadm-setup.yml
  roles/kubernetes/master/templates/kubeadm-config.v1alpha1.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1alpha2.yaml.j2
  roles/kubernetes/node/tasks/main.yml
  roles/kubespray-defaults/defaults/main.yaml
  tests/files/gce_opensuse-canal.yml
Labels: cncf-cla: yes, size/L

#3108 Upgrade coredns to 1.1.3
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS

#3101 Uninstall old versions of Docker
  roles/docker/tasks/pre-upgrade.yml
Labels: cncf-cla: yes, size/XS

#3097 Define custom playbook in Vagrantfile
  Vagrantfile
Labels: cncf-cla: yes, size/XS

#3088 Disable locksmithd on CoreOS if coreos_auto_upgrade set to false
  inventory/sample/group_vars/all.yml
  roles/bootstrap-os/defaults/main.yml
  roles/bootstrap-os/tasks/bootstrap-coreos.yml
Labels: cncf-cla: yes, size/S

#2932 fluentd daemonset: do not set old nodeSelector.
  roles/kubernetes-apps/efk/fluentd/templates/fluentd-ds.yml.j2
Labels: cncf-cla: yes, size/XS

#3112 ingress-nginx: Upgrade to 0.18.0
  README.md
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS

#3111 cert-manager: Upgrade to 0.4.1
  README.md
  roles/download/defaults/main.yml
  roles/kubernetes-apps/ingress_controller/cert_manager/defaults/main.yml
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/clusterrole-cert-manager.yml.j2
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/clusterrolebinding-cert-manager.yml.j2
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/crd-certificate.yml.j2
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/crd-clusterissuer.yml.j2
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/crd-issuer.yml.j2
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/deploy-cert-manager.yml.j2
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/sa-cert-manager.yml.j2
Labels: cncf-cla: yes, size/M

#3113 Support audit
  inventory/sample/group_vars/k8s-cluster.yml
  roles/kubernetes/master/defaults/main.yml
  roles/kubernetes/master/tasks/kubeadm-setup.yml
  roles/kubernetes/master/tasks/static-pod-setup.yml
  roles/kubernetes/master/templates/apiserver-audit-policy.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1alpha2.yaml.j2
  roles/kubernetes/master/templates/manifests/kube-apiserver.manifest.j2
  tests/files/gce_centos-weave-kubeadm.yml
  tests/files/gce_centos7-flannel-addons.yml
Labels: cncf-cla: yes, size/L

#3116 Update OWNERS
  OWNERS
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/S

#3019 [contrib/terraform/openstack] Add supplementary node groups
  contrib/terraform/openstack/README.md
  contrib/terraform/openstack/kubespray.tf
  contrib/terraform/openstack/modules/compute/main.tf
  contrib/terraform/openstack/modules/compute/variables.tf
  contrib/terraform/openstack/variables.tf
Labels: cncf-cla: yes, size/S

#3043 Update openstack.md
  docs/openstack.md
Labels: cncf-cla: yes, size/S

#3114 Update CoreDNS to 1.2.0
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS

#3079 fix glusterfs ppa and glusterfs server command name errors
  contrib/network-storage/glusterfs/roles/glusterfs/client/defaults/main.yml
  contrib/network-storage/glusterfs/roles/glusterfs/server/defaults/main.yml
  contrib/network-storage/glusterfs/roles/glusterfs/server/vars/Debian.yml
Labels: cncf-cla: yes, size/XS

#3089 Remove erroneous cloud-config task
  roles/kubernetes/preinstall/tasks/main.yml
Labels: cncf-cla: yes, size/S

#1295 fix curl get calico status error ( error in tls version, centos 7.3 1611)
  roles/kubernetes/preinstall/defaults/main.yml
Labels: cncf-cla: yes, lgtm, size/XS

#2001 Update main.yml
  roles/docker/docker-storage/defaults/main.yml
Labels: cncf-cla: yes, lgtm, size/XS

#2025 contrib/terraform/aws: Make path to generated inventory configurable
  contrib/terraform/aws/create-infrastructure.tf
  contrib/terraform/aws/terraform.tfvars
  contrib/terraform/aws/variables.tf
Labels: cncf-cla: yes, size/XS

#2103 Update docker package info for aarch64
  roles/docker/tasks/main.yml
  roles/docker/vars/redhat-aarch64.yml
Labels: cncf-cla: yes, size/S

#2104 add support for non-amd64 arch gcr.io images
  roles/dnsmasq/defaults/main.yml
  roles/download/defaults/main.yml
  roles/kubernetes-apps/ansible/defaults/main.yml
  roles/vault/defaults/main.yml
Labels: cncf-cla: yes, size/M

#3126 add version to environment file
  roles/etcd/templates/etcd.env.j2
Labels: cncf-cla: yes, lgtm, size/XS

#3123 add until option for etcd backup commands
  roles/etcd/handlers/backup.yml
Labels: cncf-cla: yes, size/XS

#3120 cephfs-provisioner: Upgrade to v2.0.0-k8s1.11
  README.md
  roles/download/defaults/main.yml
  roles/kubernetes-apps/external_provisioner/cephfs_provisioner/tasks/main.yml
  roles/kubernetes-apps/external_provisioner/cephfs_provisioner/templates/clusterrole-cephfs-provisioner.yml.j2
  roles/kubernetes-apps/external_provisioner/cephfs_provisioner/templates/clusterrolebinding-cephfs-provisioner.yml.j2
  roles/kubernetes-apps/external_provisioner/cephfs_provisioner/templates/deploy-cephfs-provisioner.yml.j2
Labels: cncf-cla: yes, lgtm, size/M

#3119 add ignore_patterns to ansible.cfg
  ansible.cfg
Labels: cncf-cla: yes, lgtm, size/XS

#3105 Move network_plugin specific reset tasks to its role directory
  roles/network_plugin/cilium/tasks/reset.yml
  roles/network_plugin/cilium/tasks/reset_iface.yml
  roles/network_plugin/flannel/tasks/reset.yml
  roles/reset/tasks/main.yml
Labels: cncf-cla: yes, size/M

#3117 Audit support improvement
  roles/kubernetes/master/defaults/main.yml
  roles/kubernetes/master/tasks/kubeadm-setup.yml
  roles/kubernetes/master/tasks/static-pod-setup.yml
  roles/kubernetes/master/templates/kubeadm-config.v1alpha2.yaml.j2
  roles/kubernetes/master/templates/manifests/kube-apiserver.manifest.j2
Labels: cncf-cla: yes, lgtm, size/M

#3128 Remove unused configuration
  roles/kubernetes/kubeadm/tasks/main.yml
Labels: cncf-cla: yes, lgtm, size/XS

#3134 Fix pull dns image error
  roles/kubernetes-apps/ansible/defaults/main.yml
Labels: cncf-cla: yes, size/XS

#3137 Fix install nss
  roles/kubernetes/preinstall/defaults/main.yml
  roles/kubernetes/preinstall/vars/centos.yml
  roles/kubernetes/preinstall/vars/redhat.yml
Labels: cncf-cla: yes, size/XS

#3017 Fix kubeadm client conf
  roles/kubernetes/kubeadm/templates/kubeadm-client.conf.v1alpha1.j2
Labels: cncf-cla: yes, size/XS

#3139 cephfs-provisioner: Upgrade to v2.0.1-k8s1.11
  README.md
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS

#3135 Add bad hostname preflight check
  roles/kubernetes/preinstall/tasks/verify-settings.yml
Labels: cncf-cla: yes, size/XS

#3094 Add --dns-loop-detect to dnsmasq used in kube-dns
  roles/kubernetes-apps/ansible/templates/kubedns-deploy.yml.j2
Labels: cncf-cla: yes, size/XS

#3132 Custom audit policy
  roles/kubernetes/master/defaults/main.yml
  roles/kubernetes/master/templates/apiserver-audit-policy.yaml.j2
Labels: cncf-cla: yes, size/S

#3133 Audit log to stdout with kubeadm
  roles/kubernetes/master/defaults/main.yml
  roles/kubernetes/master/templates/kubeadm-config.v1alpha2.yaml.j2
Labels: cncf-cla: yes, size/S

#3130 Add kubeadm controlplaneEndpoint
  inventory/sample/group_vars/all.yml
  roles/kubernetes/kubeadm/tasks/main.yml
  roles/kubernetes/master/tasks/kubeadm-setup.yml
  roles/kubernetes/master/templates/kubeadm-config.v1alpha1.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1alpha2.yaml.j2
Labels: cncf-cla: yes, size/S

#3125 scaling: issue etcd certs for new nodes
  scale.yml
Labels: cncf-cla: yes, lgtm, size/XS

#3141 allow '.' in hostnames for verify bad hostnames
  roles/kubernetes/preinstall/tasks/verify-settings.yml
Labels: cncf-cla: yes, size/XS

#3155 Always create service account even rbac_enabled = false
  roles/dnsmasq/tasks/main.yml
  roles/dnsmasq/templates/dnsmasq-autoscaler.yml.j2
  roles/kubernetes-apps/ansible/defaults/main.yml
  roles/kubernetes-apps/ansible/tasks/coredns.yml
  roles/kubernetes-apps/ansible/tasks/kubedns.yml
  roles/kubernetes-apps/ansible/tasks/netchecker.yml
  roles/kubernetes-apps/ansible/templates/coredns-deployment.yml.j2
  roles/kubernetes-apps/ansible/templates/kubedns-autoscaler.yml.j2
  roles/kubernetes-apps/ansible/templates/kubedns-deploy.yml.j2
  roles/kubernetes-apps/ansible/templates/netchecker-server-deployment.yml.j2
  roles/kubernetes-apps/efk/elasticsearch/tasks/main.yml
  roles/kubernetes-apps/efk/elasticsearch/templates/elasticsearch-deployment.yml.j2
  roles/kubernetes-apps/efk/fluentd/templates/fluentd-ds.yml.j2
  roles/kubernetes-apps/efk/kibana/templates/kibana-deployment.yml.j2
  roles/kubernetes-apps/external_provisioner/cephfs_provisioner/templates/deploy-cephfs-provisioner.yml.j2
  roles/kubernetes-apps/helm/tasks/main.yml
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/ds-ingress-nginx-controller.yml.j2
  roles/kubernetes-apps/policy_controller/calico/defaults/main.yml
  roles/kubernetes-apps/policy_controller/calico/tasks/main.yml
  roles/kubernetes-apps/policy_controller/calico/templates/calico-kube-controllers.yml.j2
  roles/network_plugin/calico/defaults/main.yml
  roles/network_plugin/calico/tasks/main.yml
  roles/network_plugin/calico/templates/calico-node.yml.j2
  roles/network_plugin/canal/defaults/main.yml
  roles/network_plugin/canal/tasks/main.yml
  roles/network_plugin/canal/templates/canal-node.yaml.j2
  roles/network_plugin/cilium/defaults/main.yml
  roles/network_plugin/cilium/tasks/main.yml
  roles/network_plugin/cilium/templates/cilium-ds.yml.j2
  roles/network_plugin/contiv/templates/contiv-api-proxy.yml.j2
  roles/network_plugin/contiv/templates/contiv-netmaster.yml.j2
  roles/network_plugin/contiv/templates/contiv-netplugin.yml.j2
  roles/network_plugin/flannel/tasks/main.yml
  roles/network_plugin/flannel/templates/cni-flannel.yml.j2
Labels: approved, cncf-cla: yes, lgtm, size/M

#3162 Add ubuntu18 ci job
  .gitlab-ci.yml
  tests/files/gce_ubuntu18-flannel-aio.yml
Labels: cncf-cla: yes, size/M

#3165 Update ansible.md
  docs/ansible.md
Labels: cncf-cla: yes, size/XS

#3152 new cilium stable version: 1.2.0
  README.md
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, lgtm, size/XS

#3144 Fix install audit failed
  roles/kubernetes/master/defaults/main.yml
  roles/kubernetes/master/templates/apiserver-audit-policy.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1alpha2.yaml.j2
Labels: approved, cncf-cla: yes, lgtm, size/S

#3086 calico upgrade to v3
  README.md
  docs/calico.md
  inventory/sample/group_vars/k8s-cluster.yml
  roles/download/defaults/main.yml
  roles/kubernetes-apps/network_plugin/calico/tasks/main.yml
  roles/kubernetes-apps/policy_controller/calico/tasks/main.yml
  roles/kubernetes-apps/policy_controller/calico/templates/calico-kube-controllers.yml.j2
  roles/kubernetes-apps/policy_controller/calico/templates/calico-kube-cr.yml.j2
  roles/kubernetes/kubeadm/tasks/main.yml
  roles/kubernetes/node/templates/kubelet-container.j2
  roles/kubernetes/node/templates/kubelet.rkt.service.j2
  roles/kubernetes/preinstall/tasks/main.yml
  roles/kubernetes/preinstall/tasks/set_resolv_facts.yml
  roles/kubespray-defaults/defaults/main.yaml
  roles/network_plugin/calico/defaults/main.yml
  roles/network_plugin/calico/tasks/check.yml
  roles/network_plugin/calico/tasks/install.yml
  roles/network_plugin/calico/tasks/main.yml
  roles/network_plugin/calico/tasks/pre.yml
  roles/network_plugin/calico/tasks/upgrade.yml
  roles/network_plugin/calico/templates/calico-node.yml.j2
  roles/network_plugin/calico/templates/cni-calico.conflist.j2
  roles/network_plugin/calico/templates/etcdv2-store.yml.j2
  roles/network_plugin/calico/templates/etcdv3-store.yml.j2
  roles/network_plugin/canal/templates/canal-node.yaml.j2
  roles/reset/tasks/main.yml
  upgrade-cluster.yml
Labels: approved, cncf-cla: yes, lgtm, size/XL

#3142 Fix kubeadm LB configure
  roles/kubernetes/kubeadm/templates/kubeadm-client.conf.v1alpha1.j2
  roles/kubernetes/kubeadm/templates/kubeadm-client.conf.v1alpha2.j2
Labels: cncf-cla: yes, size/XS

#3147 gen_certs_script: refactor using stdin (Ansible 2.4+)
  roles/etcd/tasks/gen_certs_script.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#3163 Fix docker apt-repo for Ubuntu18
  roles/docker/tasks/main.yml
  roles/docker/vars/ubuntu-bionic.yml
Labels: cncf-cla: yes, size/M

#3174 Revert "gen_certs_script: refactor using stdin (Ansible 2.4+)"
  roles/etcd/tasks/gen_certs_script.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#3058 Add ETCD_QUOTA_BACKEND_BYTES environment variable
  inventory/sample/group_vars/all.yml
  roles/etcd/defaults/main.yml
  roles/etcd/templates/etcd-events.env.j2
  roles/etcd/templates/etcd.env.j2
Labels: approved, cncf-cla: yes, lgtm, size/S

#3173 Fix createhome directory for adduser role
  roles/adduser/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3158 Fix node hostname in glusterfs inventory.example
  contrib/network-storage/glusterfs/inventory.example
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3179 move ubuntu18 to CI part2
  .gitlab-ci.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3161 --nodeport-addresses added on kube-proxy.manifest.j2 and on k8s-cluster.yml
  inventory/sample/group_vars/k8s-cluster.yml
  roles/kubernetes/master/templates/kubeadm-config.v1alpha1.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1alpha2.yaml.j2
  roles/kubernetes/node/templates/manifests/kube-proxy.manifest.j2
Labels: approved, cncf-cla: yes, lgtm, size/S

#3153 Remove *_image_tag suffix from ReplicaSet/Deployment
  roles/kubernetes-apps/external_provisioner/cephfs_provisioner/templates/deploy-cephfs-provisioner.yml.j2
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/deploy-default-backend.yml.j2
  roles/kubernetes-apps/registry/templates/registry-rs.yml.j2
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2958 change the way that getting etcd_member_name
  README.md
  inventory/sample/hosts.ini
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3104 Use delegate_to: localhost instead of local_action
  roles/kubernetes/preinstall/tasks/pre_upgrade.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3095 Dnsmasq manifests should not have j2 extension but templates should
  roles/dnsmasq/tasks/main.yml
  roles/dnsmasq/templates/dnsmasq-clusterrolebinding.yml.j2
  roles/dnsmasq/templates/dnsmasq-deploy.yml.j2
  roles/dnsmasq/templates/dnsmasq-serviceaccount.yml.j2
  roles/dnsmasq/templates/dnsmasq-svc.yml.j2
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2474 Localhost in hosts files should be updated (if necessary), not overriden
  roles/kubernetes/preinstall/defaults/main.yml
  roles/kubernetes/preinstall/tasks/etchosts.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#3186 Fix localhost handling when /etc/hosts contains parenthesis
  roles/kubernetes/preinstall/tasks/etchosts.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3189 Up dashboard version to 1.10.0
  roles/kubernetes-apps/ansible/defaults/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3176 Add option to change the Tiller Deployment namespace.
  roles/kubernetes-apps/helm/defaults/main.yml
  roles/kubernetes-apps/helm/tasks/main.yml
  roles/kubernetes-apps/helm/templates/tiller-clusterrolebinding.yml
  roles/kubernetes-apps/helm/templates/tiller-clusterrolebinding.yml.j2
  roles/kubernetes-apps/helm/templates/tiller-namespace.yml.j2
  roles/kubernetes-apps/helm/templates/tiller-sa.yml.j2
Labels: approved, cncf-cla: yes, lgtm, size/M

#3061 cri-o support
  cluster.yml
  docs/cri-o.md
  inventory/sample/group_vars/all.yml
  inventory/sample/group_vars/k8s-cluster.yml
  roles/cri-o/defaults/main.yml
  roles/cri-o/files/mounts.conf
  roles/cri-o/tasks/main.yaml
  roles/cri-o/templates/crio.conf.j2
  roles/cri-o/vars/redhat.yml
  roles/download/defaults/main.yml
  roles/download/tasks/download_prep.yml
  roles/download/tasks/main.yml
  roles/etcd/tasks/install_host.yml
  roles/kubernetes/kubeadm/templates/kubeadm-client.conf.v1alpha2.j2
  roles/kubernetes/master/tasks/kubeadm-setup.yml
  roles/kubernetes/master/tasks/main.yml
  roles/kubernetes/master/templates/kubeadm-config.v1alpha1.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1alpha2.yaml.j2
  roles/kubernetes/node/defaults/main.yml
  roles/kubernetes/node/tasks/install_host.yml
  roles/kubernetes/node/templates/kubelet.kubeadm.env.j2
  roles/kubernetes/node/templates/kubelet.standard.env.j2
  roles/kubespray-defaults/defaults/main.yaml
  roles/reset/tasks/main.yml
  scale.yml
  upgrade-cluster.yml
Labels: approved, cncf-cla: yes, lgtm, size/XL

#3191 canal should mount xtables.lock to share the lock with other processe…
  roles/network_plugin/canal/templates/canal-node.yaml.j2
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3197 Enable kubeadm test
  .gitlab-ci.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3195 Fix some addons when PodSecurityPolicy is enabled
  roles/kubernetes-apps/external_provisioner/local_volume_provisioner/tasks/main.yml
  roles/kubernetes-apps/external_provisioner/local_volume_provisioner/templates/local-volume-provisioner-psp-role.yml.j2
  roles/kubernetes-apps/registry/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3198 Fix kubeadm v1alpha1 configure
  roles/kubernetes/master/templates/kubeadm-config.v1alpha1.yaml.j2
Labels: approved, cncf-cla: yes, lgtm, size/S

#3187 Fix kubeadm-config for audit-log-path and feature-gates
  roles/kubernetes/master/templates/kubeadm-config.v1alpha2.yaml.j2
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3185 Mount /root/.kube to helm container
  roles/kubernetes-apps/helm/templates/helm-container.j2
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3202 Fix ipvs by kubeadm v1alpha1
  roles/kubernetes/master/templates/kubeadm-config.v1alpha1.yaml.j2
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3204 Fix copy etcd-ssl-ca failed
  roles/kubernetes/master/tasks/kubeadm-setup.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3203 Update readme
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3209 etcd_events_access_address should be used for peer_url and client_url
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3208 Add documentation about having HA for etcd
  docs/ha-mode.md
  inventory/sample/group_vars/all.yml
  roles/etcd/defaults/main.yml
  roles/etcd/tasks/gen_certs_vault.yml
  roles/etcd/templates/openssl.conf.j2
Labels: approved, cncf-cla: yes, lgtm, size/M
