Repository kubernetes-sigs/kubespray, pull requests merged in 2018-05, with the labels that each got.

#2731 Fix broken terraform aws readme
  contrib/terraform/aws/README.md
Labels: cncf-cla: yes, size/XS

#2693 sync certs tasks (fix #2596 #2667)
  roles/kubernetes/secrets/tasks/check-certs.yml
  roles/kubernetes/secrets/tasks/gen_certs_script.yml
Labels: cncf-cla: yes, size/M

#2732 Update aws.md
  docs/aws.md
Labels: cncf-cla: yes, size/XS

#2738 tiny spacing change "can be"
  README.md
Labels: cncf-cla: yes, size/S

#2742 Update CoreDNS to version 1.1.2
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS

#2729 Use 'items()' for python compatibility
  roles/etcd/templates/etcd.env.j2
Labels: cncf-cla: yes, size/XS

#2600 Add Openstack tenant name
  roles/kubernetes/node/defaults/main.yml
  roles/kubernetes/node/templates/openstack-cloud-config.j2
Labels: cncf-cla: yes, size/XS

#2725 coreos: explicitely set pip executable.
  roles/bootstrap-os/tasks/bootstrap-coreos.yml
Labels: cncf-cla: yes, size/S

#2762 Fix path for pip and python when already bootstrapped
  roles/bootstrap-os/tasks/bootstrap-coreos.yml
Labels: cncf-cla: yes, size/XS

#2733 refactor vault role
  .gitlab-ci.yml
  requirements.txt
  roles/bootstrap-os/tasks/bootstrap-ubuntu.yml
  roles/dnsmasq/tasks/main.yml
  roles/download/defaults/main.yml
  roles/etcd/defaults/main.yml
  roles/kubernetes/master/defaults/main.yml
  roles/kubernetes/master/templates/manifests/kube-apiserver.manifest.j2
  roles/kubernetes/node/defaults/main.yml
  roles/kubernetes/preinstall/tasks/set_facts.yml
  roles/kubernetes/secrets/defaults/main.yml
  roles/kubernetes/secrets/tasks/gen_certs_script.yml
  roles/kubernetes/secrets/tasks/gen_certs_vault.yml
  roles/kubernetes/secrets/tasks/main.yml
  roles/vault/defaults/main.yml
  roles/vault/handlers/main.yml
  roles/vault/tasks/bootstrap/create_mounts.yml
  roles/vault/tasks/bootstrap/create_roles.yml
  roles/vault/tasks/bootstrap/gen_vault_certs.yml
  roles/vault/tasks/bootstrap/main.yml
  roles/vault/tasks/bootstrap/start_vault_temp.yml
  roles/vault/tasks/bootstrap/sync_etcd_certs.yml
  roles/vault/tasks/bootstrap/sync_secrets.yml
  roles/vault/tasks/bootstrap/sync_vault_certs.yml
  roles/vault/tasks/cluster/binary.yml
  roles/vault/tasks/cluster/configure.yml
  roles/vault/tasks/cluster/create_mounts.yml
  roles/vault/tasks/cluster/create_roles.yml
  roles/vault/tasks/cluster/init.yml
  roles/vault/tasks/cluster/main.yml
  roles/vault/tasks/cluster/systemd.yml
  roles/vault/tasks/cluster/unseal.yml
  roles/vault/tasks/main.yml
  roles/vault/tasks/shared/auth_backend.yml
  roles/vault/tasks/shared/cert_auth_mount.yml
  roles/vault/tasks/shared/check_etcd.yml
  roles/vault/tasks/shared/check_vault.yml
  roles/vault/tasks/shared/config_ca.yml
  roles/vault/tasks/shared/create_role.yml
  roles/vault/tasks/shared/find_leader.yml
  roles/vault/tasks/shared/gen_ca.yml
  roles/vault/tasks/shared/gen_userpass.yml
  roles/vault/tasks/shared/issue_cert.yml
  roles/vault/tasks/shared/pki_mount.yml
  roles/vault/tasks/shared/sync.yml
  roles/vault/tasks/shared/sync_file.yml
  roles/vault/templates/docker.service.j2
  roles/vault/templates/rkt.service.j2
  tests/files/gce_coreos-vault-upgrade.yml
Labels: cncf-cla: yes, size/XL

#2765 add svc to netchecker-service.default.svc.cluster.local
  docs/netcheck.md
Labels: cncf-cla: yes, size/XS

#2758 Fix privilege escalation timeout for remove-node playbook
  remove-node.yml
Labels: cncf-cla: yes, size/XS

#2757 Fix issue #2702: 'docker_bin_dir' is undefined when running ansible-playbook remove-node.yml
  remove-node.yml
Labels: cncf-cla: yes, size/XS

#2770 Restart scheduler when policy changes
  roles/kubernetes/master/tasks/static-pod-setup.yml
Labels: cncf-cla: yes, size/XS

#2779 Update README.md
  README.md
Labels: cncf-cla: yes, size/XS

#2782 Bump kube-dns to 1.14.10
  roles/download/defaults/main.yml
  roles/kubernetes-apps/ansible/defaults/main.yml
Labels: cncf-cla: yes, size/XS

#2772 make admin.conf -> .kube/config non-executable
  roles/kubernetes/client/tasks/main.yml
  roles/kubernetes/master/tasks/kubeadm-setup.yml
Labels: cncf-cla: yes, size/XS

#2748 Upgrade k8s to 1.10.2
  README.md
  inventory/sample/group_vars/k8s-cluster.yml
  roles/download/defaults/main.yml
  roles/kubernetes/master/templates/kubeadm-config.yaml.j2
  roles/kubernetes/node/templates/manifests/kube-proxy.manifest.j2
  roles/kubespray-defaults/defaults/main.yaml
  tests/files/gce_centos7-flannel-addons.yml
Labels: cncf-cla: yes, size/S

#2666 Added MountFlags variable to docker options
  inventory/sample/group_vars/k8s-cluster.yml
  roles/docker/templates/docker-options.conf.j2
  roles/kubespray-defaults/defaults/main.yaml
Labels: cncf-cla: yes, size/S

#2787 add posibility to provide different yum repository directory
  roles/docker/defaults/main.yml
  roles/docker/tasks/main.yml
Labels: cncf-cla: yes, size/XS

#2744 Remove unnecessary loadbalancer_apiserver binding on terraform AWS readme
  contrib/terraform/aws/README.md
Labels: cncf-cla: yes, size/XS

#2786 assert that number of pods on node does not exceed CIDR address range
  roles/kubernetes/node/defaults/main.yml
  roles/kubernetes/node/templates/kubelet.kubeadm.env.j2
  roles/kubernetes/node/templates/kubelet.standard.env.j2
  roles/kubernetes/preinstall/tasks/verify-settings.yml
Labels: cncf-cla: yes, size/S

#2777 Update README.md
  README.md
Labels: cncf-cla: yes, size/S

#2805 Update Helm to latest version 2.9.1
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS

#2806 Remove KPM support
  docs/ansible.md
  docs/roadmap.md
  inventory/sample/group_vars/all.yml
  roles/kubernetes-apps/kpm/library/kpm.py
  roles/kubernetes-apps/kpm/tasks/main.yml
  roles/kubernetes-apps/meta/main.yml
Labels: cncf-cla: yes, size/L

#2743 opensuse: Fix OpenSSL package name
  roles/kubernetes/preinstall/defaults/main.yml
Labels: cncf-cla: yes, size/XS

#2793 Set widely used header to execute python scripts in different OS
  contrib/inventory_builder/inventory.py
Labels: cncf-cla: yes, size/XS

#2812 Use relative paths for data_files in setup.cfg
  setup.cfg
Labels: cncf-cla: yes, size/S

#2822 contiv-etcd-init image as default instead hardcoded
  roles/download/defaults/main.yml
  roles/network_plugin/contiv/templates/contiv-etcd.yml.j2
Labels: cncf-cla: yes, size/S

#2833 Adding SECURITY_CONTACTS fixes #2816
  SECURITY_CONTACTS
Labels: cncf-cla: yes, size/S

#2821 Update README.md
  README.md
Labels: cncf-cla: yes, size/XS

#2823 Dashboard in cluster info
  roles/kubernetes-apps/ansible/templates/dashboard.yml.j2
Labels: cncf-cla: yes, lgtm, size/XS
