Repository kubernetes-sigs/kubespray, pull requests merged in 2019-11, with the labels that each got.

#5184 Deploy Cinder CSI driver to provision volumes over OpenStack
  docs/cinder-csi.md
  inventory/sample/group_vars/all/openstack.yml
  roles/kubernetes-apps/csi_driver/cinder/defaults/main.yml
  roles/kubernetes-apps/csi_driver/cinder/tasks/cinder-credential-check.yml
  roles/kubernetes-apps/csi_driver/cinder/tasks/main.yml
  roles/kubernetes-apps/csi_driver/cinder/templates/cinder-csi-cloud-config-secret.yml.j2
  roles/kubernetes-apps/csi_driver/cinder/templates/cinder-csi-cloud-config.j2
  roles/kubernetes-apps/csi_driver/cinder/templates/cinder-csi-controllerplugin-rbac.yml.j2
  roles/kubernetes-apps/csi_driver/cinder/templates/cinder-csi-controllerplugin.yml.j2
  roles/kubernetes-apps/csi_driver/cinder/templates/cinder-csi-driver.yml.j2
  roles/kubernetes-apps/csi_driver/cinder/templates/cinder-csi-nodeplugin-rbac.yml.j2
  roles/kubernetes-apps/csi_driver/cinder/templates/cinder-csi-nodeplugin.yml.j2
  roles/kubernetes-apps/meta/main.yml
  roles/kubernetes-apps/persistent_volumes/cinder-csi/defaults/main.yml
  roles/kubernetes-apps/persistent_volumes/cinder-csi/tasks/main.yml
  roles/kubernetes-apps/persistent_volumes/cinder-csi/templates/cinder-csi-storage-class.yml.j2
  roles/kubernetes-apps/persistent_volumes/meta/main.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XL

#5308 Scale down coredns created by kubeadm upgrade to 0 replicas
  roles/kubernetes/master/defaults/main/main.yml
  roles/kubernetes/master/tasks/kubeadm-upgrade.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5318 Enable systemd-resolved DNS resolution mode
  roles/kubernetes/preinstall/handlers/main.yml
  roles/kubernetes/preinstall/tasks/0040-set_facts.yml
  roles/kubernetes/preinstall/tasks/0061-systemd-resolved.yml
  roles/kubernetes/preinstall/tasks/main.yml
  roles/kubernetes/preinstall/templates/resolved.conf.j2
Labels: approved, cncf-cla: yes, lgtm, size/M

#5322 Remove unnecessary and risky reload network for resolvconf propagation
  roles/kubernetes/preinstall/handlers/main.yml
  roles/kubernetes/preinstall/tasks/0060-resolvconf.yml
  roles/kubernetes/preinstall/tasks/0100-dhclient-hooks.yml
  roles/kubernetes/preinstall/tasks/0110-dhclient-hooks-undo.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#5319 [FIX] fix incorrect link to downloads documentation
  docs/vagrant.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#5327 Skip coredns image when evaluating kubeadm images
  roles/download/tasks/prep_kubeadm_images.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5326 containerd installation on Debian
  roles/container-engine/containerd/defaults/main.yml
  roles/container-engine/containerd/vars/debian.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/M

#5300 Fixes issue #5299 (GlusterFS - "replica count should be greater than 1")
  contrib/network-storage/glusterfs/roles/glusterfs/server/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S

#5295 Add cilium_tunnel_mode variable to the cilium config
  roles/network_plugin/cilium/defaults/main.yml
  roles/network_plugin/cilium/templates/cilium-config.yml.j2
Labels: approved, cncf-cla: yes, kind/flake, lgtm, size/XS

#5287 Remove default docker_options from sample
  inventory/sample/group_vars/all/docker.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/S

#5305 Fix indentation in cilium-ds.yml template
  roles/network_plugin/cilium/templates/cilium-ds.yml.j2
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#5281 fix useradd etcd
  roles/adduser/defaults/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5241 Respect cri-tool supported version matrix
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#5321 Pass `ingress_nginx_extra_args` when deploying the nginx-ingress addon
  inventory/sample/group_vars/k8s-cluster/addons.yml
  roles/kubernetes-apps/ingress_controller/ingress_nginx/defaults/main.yml
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/ds-ingress-nginx-controller.yml.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#5332 Fix helm for Kubernetes 1.16.2
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#5274 library files added to setup.cfg
  setup.cfg
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5291 Fix calico name resolution
  roles/kubernetes-apps/policy_controller/calico/templates/calico-kube-controllers.yml.j2
  roles/network_plugin/calico/templates/calico-node.yml.j2
  roles/network_plugin/calico/templates/calico-typha.yml.j2
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5325 Set certs and files with kubeadm token to mode 0640
  roles/kubernetes/master/tasks/kubeadm-certificate.yml
  roles/kubernetes/master/tasks/kubeadm-fix-apiserver.yml
  roles/kubernetes/master/tasks/kubeadm-migrate-certs.yml
  roles/kubernetes/master/tasks/kubeadm-secondary-experimental.yml
  roles/kubernetes/master/tasks/kubeadm-secondary-legacy.yml
  roles/kubernetes/master/tasks/kubeadm-version.yml
Labels: approved, cncf-cla: yes, lgtm, security, size/XS

#5301 Added Amazon Linux 2 support for deploying with docker
  roles/container-engine/docker/vars/amazon.yml
  roles/kubernetes/preinstall/tasks/0080-system-configurations.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#5339 Do not run kubeadm upgrade on first deploy
  roles/kubernetes/master/tasks/kubeadm-setup.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5338 modify host.yml in README.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5344 scale down coredns on each master during graceful upgrade
  roles/kubernetes/master/tasks/kubeadm-upgrade.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5356 [FIX] fix match because trim removes leading/trailing whitespace
  roles/kubernetes/master/tasks/kubeadm-setup.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#5365 Purge inactive reviewers. Promote miouge1 to approver
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/S

#5341 containerd: update to 1.2.10
  roles/container-engine/containerd/defaults/main.yml
  roles/container-engine/containerd/vars/debian.yml
  roles/container-engine/containerd/vars/redhat.yml
  roles/container-engine/containerd/vars/ubuntu-amd64.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#5343 Upgrade to Kubernetes 1.15.6
  README.md
  inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml
  roles/download/defaults/main.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#5359 fix OWNERS syntax
  roles/network_plugin/kube-ovn/OWNERS
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#5357 update fedora atomic download url
  docs/atomic.md
Labels: approved, cncf-cla: yes, kind/cleanup, kind/documentation, lgtm, size/XS

#5384 add 1.16.3 checksums and set new version as default
  README.md
  inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml
  roles/download/defaults/main.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5364 CoreDNS deployment extra tolerations
  roles/kubernetes-apps/ansible/defaults/main.yml
  roles/kubernetes-apps/ansible/templates/coredns-deployment.yml.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#5377 kubernetes/masters: fix task name in kubeadm setup
  roles/kubernetes/master/tasks/kubeadm-setup.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#5390 update URL for Gluster Getting Started Guide
  contrib/network-storage/glusterfs/roles/glusterfs/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5378 Add support for k8s v1.17.0-rc.1, remove hyperkube
  roles/download/defaults/main.yml
  roles/download/templates/kubeadm-images.yaml.j2
  roles/kubernetes-apps/helm/tasks/install_host.yml
  roles/kubernetes/master/tasks/main.yml
  roles/kubernetes/master/templates/kubeadm-config.v1beta1.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1beta2.yaml.j2
  roles/kubernetes/node/tasks/install.yml
  roles/kubernetes/node/tasks/main.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L
