Repository kubernetes-sigs/kubespray, pull requests merged in 2019-06, with the labels that each got.

#4833 Avoid duplicating nameservers
  roles/kubernetes/preinstall/tasks/0040-set_facts.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4834 Move tf-ovh to part2
  .gitlab-ci/terraform.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#4835 Use short cluster_name for TF CI
  .gitlab-ci/terraform.yml
Labels: approved, cncf-cla: yes, kind/cleanup, kind/failing-test, lgtm, size/XS

#4832 Optionally skip predownload of kubeadm images
  roles/download/defaults/main.yml
  roles/download/tasks/main.yml
Labels: approved, cncf-cla: yes, size/XS

#4810 prefer_udp for upstream dns servers
  roles/kubernetes-apps/ansible/templates/coredns-config.yml.j2
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#4261 Add support for arm images for hyperkube, kubeadm and cni_binary
  roles/download/defaults/main.yml
  roles/kubernetes/preinstall/tasks/0040-set_facts.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#4840 Only create kubeadm compat cert dir link if it does not exist
  roles/kubernetes/preinstall/tasks/0050-create_directories.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#4839 Preinstall fails on checking etcd group length
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#4126 fix relative paths for bastion host template
  contrib/terraform/openstack/modules/compute/main.tf
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#4843 Set dnsPolicy to ClusterFirstWithHostNet when hostNetwork is true
  roles/kubernetes-apps/ansible/templates/netchecker-agent-hostnet-ds.yml.j2
  roles/kubernetes-apps/ansible/templates/netchecker-agent-hostnet-psp.yml.j2
  roles/kubernetes-apps/cloud_controller/oci/templates/oci-cloud-provider.yml.j2
  roles/kubernetes-apps/cluster_roles/templates/psp.yml.j2
  roles/kubernetes-apps/container_engine_accelerator/nvidia_gpu/templates/k8s-device-plugin-nvidia-daemonset.yml.j2
  roles/kubernetes-apps/container_engine_accelerator/nvidia_gpu/templates/nvidia-driver-install-daemonset.yml.j2
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/ds-ingress-nginx-controller.yml.j2
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/psp-ingress-nginx.yml.j2
  roles/kubernetes-apps/policy_controller/calico/templates/calico-kube-controllers.yml.j2
  roles/kubernetes-apps/registry/templates/registry-proxy-psp.yml.j2
  roles/kubernetes/node/templates/manifests/haproxy.manifest.j2
  roles/kubernetes/node/templates/manifests/nginx-proxy.manifest.j2
  roles/network_plugin/calico/templates/calico-node.yml.j2
  roles/network_plugin/calico/templates/calico-typha.yml.j2
  roles/network_plugin/canal/templates/canal-node.yaml.j2
  roles/network_plugin/cilium/templates/cilium-ds.yml.j2
  roles/network_plugin/contiv/templates/contiv-api-proxy.yml.j2
  roles/network_plugin/contiv/templates/contiv-cleanup.yml.j2
  roles/network_plugin/contiv/templates/contiv-etcd-proxy.yml.j2
  roles/network_plugin/contiv/templates/contiv-etcd.yml.j2
  roles/network_plugin/contiv/templates/contiv-netmaster.yml.j2
  roles/network_plugin/contiv/templates/contiv-netplugin.yml.j2
  roles/network_plugin/contiv/templates/contiv-ovs.yml.j2
  roles/network_plugin/flannel/templates/cni-flannel.yml.j2
  roles/network_plugin/kube-router/templates/kube-router.yml.j2
  roles/network_plugin/multus/templates/multus-daemonset.yml.j2
  roles/network_plugin/weave/templates/weave-net.yml.j2
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/M

#4844 Move moderator between part1 and part2
  .gitlab-ci.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#4820 use dpkg_selections module to hold docker-ce on Debian family hosts
  roles/container-engine/docker/tasks/main.yml
  roles/container-engine/docker/templates/apt_preferences.d/debian_docker.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#4842 Switch /root references to ansible_env.HOME
  roles/kubernetes-apps/helm/templates/helm-container.j2
  roles/kubernetes/client/tasks/main.yml
  roles/kubernetes/master/handlers/main.yml
  roles/kubernetes/master/tasks/kubeadm-cleanup-old-certs.yml
  roles/recover_control_plane/master/tasks/main.yml
  roles/reset/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S

#4845 Fixed missing meta for generic CNI network plugin
  roles/network_plugin/meta/main.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#4825 kube-router: Set ownership of /opt/cni/bin/* to kube
  roles/network_plugin/kube-router/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#4821 Make local volume provisioner dir mode a variable
  roles/kubernetes-apps/external_provisioner/local_volume_provisioner/tasks/main.yml
  roles/kubernetes/preinstall/tasks/0050-create_directories.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4849 Fix etcd_events_cluster_enabled in CI due to wrong var used
  tests/files/gce_centos7-flannel-addons.yml
  tests/files/packet_centos7-flannel-addons.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4853 update link to Weave Net Troubleshooting doc
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#4855 k8s 1.14.3
  README.md
  inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml
  roles/download/defaults/main.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#4857 Update dns-autoscaler.yml.j2
  roles/kubernetes-apps/ansible/templates/dns-autoscaler.yml.j2
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4850 Add missing checksums for kubeadm and hyperkube, bump default version to 1.14.3
  Dockerfile
  README.md
  inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml
  roles/download/defaults/main.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#4716 Add support for IPv6 for Openstack in terraform.py via metadata
  contrib/terraform/openstack/README.md
  contrib/terraform/terraform.py
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/M

#4859 Remove GCE tests as CNCF funding ended
  .gitlab-ci.yml
Labels: approved, cncf-cla: yes, kind/cleanup, kind/failing-test, lgtm, size/XS

#4852 Disable warning about group names with dash or dot
  ansible.cfg
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#4862 Ensure haproxy and nginx reload when config changes
  roles/kubernetes/node/tasks/loadbalancer/haproxy.yml
  roles/kubernetes/node/tasks/loadbalancer/nginx-proxy.yml
  roles/kubernetes/node/templates/manifests/haproxy.manifest.j2
  roles/kubernetes/node/templates/manifests/nginx-proxy.manifest.j2
Labels: approved, cncf-cla: yes, lgtm, size/M

#4863 Remove invalid field dnsPolicy from podSecurityPolicy
  roles/kubernetes-apps/cluster_roles/templates/psp.yml.j2
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4856 remove namespace from ClusterRole
  roles/kubernetes-apps/cluster_roles/templates/psp-cr.yml.j2
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4861 Rebase only on PRs
  tests/scripts/rebase.sh
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, size/S

#4828 Added file and container image caching
  Vagrantfile
  docs/downloads.md
  roles/download/defaults/main.yml
  roles/download/tasks/check_pull_required.yml
  roles/download/tasks/download_container.yml
  roles/download/tasks/download_file.yml
  roles/download/tasks/download_prep.yml
  roles/download/tasks/extract_file.yml
  roles/download/tasks/main.yml
  roles/download/tasks/prep_download.yml
  roles/download/tasks/prep_kubeadm_images.yml
  roles/download/tasks/set_container_facts.yml
  roles/download/tasks/set_docker_image_facts.yml
  roles/download/tasks/sync_container.yml
  roles/download/tasks/sync_file.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XL

#4860 Require min version of Kubernetes
  README.md
  roles/download/defaults/main.yml
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, kind/design, kind/feature, lgtm, size/M

#4307 Added configurable min memory assertions
  roles/kubernetes/preinstall/defaults/main.yml
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4864 Remove invalid field dnsPolicy from podSecurityPolicy
  roles/kubernetes-apps/ansible/templates/netchecker-agent-hostnet-psp.yml.j2
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/psp-ingress-nginx.yml.j2
  roles/kubernetes-apps/registry/templates/registry-proxy-psp.yml.j2
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#3719 updated vagrant doc
  contrib/misc/clusteradmin-rbac.yml
  docs/vagrant.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#4757 added the ability to define and deploy multiple address pools to metallb
  contrib/metallb/README.md
  contrib/metallb/roles/provision/defaults/main.yml
  contrib/metallb/roles/provision/templates/metallb-config.yml.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#4594 Enable Kube-Router on Packet CI
  .gitlab-ci/packet.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#4595 Enable packet_ubuntu-contiv-sep
  .gitlab-ci/packet.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#4867 Skip coredns phase when initializing other uninitialized masters
  roles/kubernetes/master/tasks/kubeadm-secondary-legacy.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4874 Cherry pick #4861 into release-2.10
  tests/scripts/rebase.sh
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, size/S

#4873 Cherry pick #4783 into release-2.10
  requirements.txt
  tests/requirements.txt
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S

#4877 Cherry pick #4857 #4859 #4867 into release-2.10
  .gitlab-ci.yml
  roles/kubernetes-apps/ansible/templates/dns-autoscaler.yml.j2
  roles/kubernetes/master/tasks/kubeadm-secondary-legacy.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4883 Update ansible version
  requirements.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4878 CNI plugins: use last version 0.8.1
  README.md
  roles/download/defaults/main.yml
  roles/kubernetes-apps/network_plugin/cni/tasks/main.yml
  roles/network_plugin/cloud/tasks/main.yml
  roles/network_plugin/cni/tasks/main.yml
  roles/network_plugin/contiv/tasks/main.yml
  roles/network_plugin/kube-router/tasks/main.yml
  roles/network_plugin/weave/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#4882 fix references to sample files in setup.cfg
  setup.cfg
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, size/S

#4886 fix markdown style
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#4880 multus : use last version
  README.md
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#4879 Allow to specify feature_control in calico cni config
  roles/network_plugin/calico/defaults/main.yml
  roles/network_plugin/calico/templates/cni-calico.conflist.j2
Labels: approved, cncf-cla: yes, lgtm, size/S

#4896 Add holmsten to reviewers (slack - gix)
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4818 Enable kubeadm etcd mode
  cluster.yml
  inventory/sample/group_vars/all/all.yml
  roles/etcd/tasks/main.yml
  roles/kubernetes/kubeadm/defaults/main.yml
  roles/kubernetes/kubeadm/tasks/kubeadm_etcd_node.yml
  roles/kubernetes/kubeadm/tasks/main.yml
  roles/kubernetes/master/defaults/main/etcd.yml
  roles/kubernetes/master/defaults/main/main.yml
  roles/kubernetes/master/tasks/kubeadm-etcd.yml
  roles/kubernetes/master/tasks/kubeadm-secondary-experimental.yml
  roles/kubernetes/master/tasks/main.yml
  roles/kubernetes/master/templates/kubeadm-config.v1beta1.yaml.j2
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
  roles/kubernetes/preinstall/tasks/0040-set_facts.yml
  roles/kubespray-defaults/defaults/main.yaml
  roles/network_plugin/calico/tasks/install.yml
  tests/files/packet_ubuntu-flannel-ha.yml
  upgrade-cluster.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/L

#4904 Allow skip kubeadm image prep but install kubeadm
  roles/download/tasks/main.yml
  roles/download/tasks/prep_kubeadm_images.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4903 Add kube_override_hostname to kubeadm certs.
  roles/kubernetes/master/tasks/kubeadm-setup.yml
  roles/kubernetes/master/templates/kubeadm-controlplane.v1beta1.yaml.j2
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#4898 Upgrade to etcd version 3.3.10 per 1.14 release notes.
  README.md
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4913 Filter undefined SANs for apiserver cert
  roles/kubernetes/master/tasks/kubeadm-setup.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4914 Revert "Filter undefined SANs for apiserver cert"
  roles/kubernetes/master/tasks/kubeadm-setup.yml
Labels: cncf-cla: yes

#4916 Fix empty kube_override_hostname in apiserver_sans
  roles/kubernetes/master/tasks/kubeadm-setup.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4918 Disable redundant CI test cases
  .gitlab-ci/packet.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4928 Remove wasteful extra gather facts step
  cluster.yml
  extra_playbooks/upgrade-only-k8s.yml
  scale.yml
  upgrade-cluster.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#4901 add macvlan cni to kubespray
  .gitlab-ci/packet.yml
  README.md
  docs/macvlan.md
  inventory/sample/group_vars/k8s-cluster/k8s-net-macvlan.yml
  roles/kubernetes/node/templates/kubelet.env.j2
  roles/kubernetes/node/templates/kubelet.env.v1beta1.j2
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
  roles/kubernetes/preinstall/tasks/0050-create_directories.yml
  roles/network_plugin/macvlan/OWNERS
  roles/network_plugin/macvlan/defaults/main.yml
  roles/network_plugin/macvlan/files/ifdown-local
  roles/network_plugin/macvlan/files/ifdown-macvlan
  roles/network_plugin/macvlan/files/ifup-local
  roles/network_plugin/macvlan/files/ifup-macvlan
  roles/network_plugin/macvlan/handlers/main.yml
  roles/network_plugin/macvlan/tasks/main.yml
  roles/network_plugin/macvlan/templates/10-macvlan.conf.j2
  roles/network_plugin/macvlan/templates/99-loopback.conf.j2
  roles/network_plugin/macvlan/templates/centos-network-macvlan.cfg.j2
  roles/network_plugin/macvlan/templates/centos-postdown-macvlan.cfg.j2
  roles/network_plugin/macvlan/templates/centos-postup-macvlan.cfg.j2
  roles/network_plugin/macvlan/templates/centos-routes-macvlan.cfg.j2
  roles/network_plugin/macvlan/templates/coreos-device-macvlan.cfg.j2
  roles/network_plugin/macvlan/templates/coreos-interface-macvlan.cfg.j2
  roles/network_plugin/macvlan/templates/coreos-network-macvlan.cfg.j2
  roles/network_plugin/macvlan/templates/coreos-service-nat_ouside.j2
  roles/network_plugin/macvlan/templates/debian-network-macvlan.cfg.j2
  roles/network_plugin/meta/main.yml
  tests/files/packet_debian9-macvlan-sep.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/L

#4930 kubeadm_discovery_address should not contain proto
  roles/kubernetes/kubeadm/tasks/main.yml
  roles/kubernetes/kubeadm/templates/kubeadm-client.conf.v1alpha1.j2
  roles/kubernetes/kubeadm/templates/kubeadm-client.conf.v1alpha2.j2
  roles/kubernetes/kubeadm/templates/kubeadm-client.conf.v1alpha3.j2
  roles/kubernetes/kubeadm/templates/kubeadm-client.conf.v1beta1.j2
  roles/kubernetes/master/templates/kubeadm-controlplane.v1beta1.yaml.j2
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S

#4909 Repair kube_proxy_exclude_cidrs
  roles/kubernetes/master/defaults/main/kube-proxy.yml
  roles/kubernetes/master/templates/kubeadm-config.v1alpha3.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1beta1.yaml.j2
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#4664 containerd support
  inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml
  roles/container-engine/containerd/defaults/main.yml
  roles/container-engine/containerd/handlers/main.yml
  roles/container-engine/containerd/tasks/crictl.yml
  roles/container-engine/containerd/tasks/main.yml
  roles/container-engine/containerd/templates/config.toml.j2
  roles/container-engine/containerd/templates/crictl.yaml.j2
  roles/container-engine/cri-o/tasks/main.yaml
  roles/container-engine/cri-o/templates/crio.conf.j2
  roles/container-engine/cri-o/vars/clearlinux.yml
  roles/container-engine/cri-o/vars/fedora.yml
  roles/container-engine/cri-o/vars/redhat.yml
  roles/container-engine/cri-o/vars/ubuntu.yml
  roles/container-engine/meta/main.yml
  roles/download/defaults/main.yml
  roles/download/tasks/download_container.yml
  roles/download/tasks/download_prep.yml
  roles/download/tasks/main.yml
  roles/download/tasks/set_docker_image_facts.yml
  roles/download/templates/kubeadm-images.yaml.j2
  roles/kubernetes/kubeadm/templates/kubeadm-client.conf.v1alpha2.j2
  roles/kubernetes/kubeadm/templates/kubeadm-client.conf.v1alpha3.j2
  roles/kubernetes/kubeadm/templates/kubeadm-client.conf.v1beta1.j2
  roles/kubernetes/master/templates/kubeadm-config.v1alpha2.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1alpha3.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1beta1.yaml.j2
  roles/kubernetes/master/templates/kubeadm-controlplane.v1beta1.yaml.j2
  roles/kubernetes/node/tasks/facts.yml
  roles/kubernetes/node/tasks/pre_upgrade.yml
  roles/kubernetes/node/templates/kubelet.env.j2
  roles/kubernetes/node/templates/kubelet.env.v1beta1.j2
  roles/kubespray-defaults/defaults/main.yaml
  roles/network_plugin/calico/rr/tasks/main.yml
  roles/network_plugin/calico/rr/templates/calico-rr-containerd.service.j2
  roles/network_plugin/calico/rr/templates/calico-rr-docker.service.j2
  roles/network_plugin/cilium/templates/cilium-ds.yml.j2
  roles/reset/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XL

#4931 Default to refreshing kubeadm etcd key
  roles/kubernetes/kubeadm/defaults/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS
