Repository kubernetes-sigs/kubespray, pull requests merged in 2019-08, with the labels that each got.

#5027 [contrib/heketi]: path fix and tear down improvements
  contrib/network-storage/heketi/README.md
  contrib/network-storage/heketi/roles/provision/templates/heketi-bootstrap.json.j2
  contrib/network-storage/heketi/roles/provision/templates/heketi-deployment.json.j2
  contrib/network-storage/heketi/roles/tear-down-disks/defaults/main.yml
  contrib/network-storage/heketi/roles/tear-down-disks/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#5029 Fix small typo
  docs/vagrant.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#5039 Always create bash_completion.d folder
  roles/bootstrap-os/tasks/main.yml
  roles/kubernetes/master/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S

#5038 Fix mistakes in downloads docs
  docs/downloads.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/S

#5015 Refactor containerd ubuntu setup and remove redundant tasks
  roles/container-engine/containerd/defaults/main.yml
  roles/container-engine/containerd/tasks/containerd_repo.yml
  roles/container-engine/containerd/tasks/crictl.yml
  roles/container-engine/containerd/tasks/main.yml
  roles/container-engine/containerd/vars/ubuntu-amd64.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/M

#5006 Fix commands for using experimental kubeadm control plane
  roles/kubernetes/kubeadm/tasks/kubeadm_etcd_node.yml
  roles/kubernetes/master/tasks/kubeadm-setup.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S

#5043 Optionally refresh kubeadm token every time
  roles/kubernetes/master/defaults/main/main.yml
  roles/kubernetes/master/tasks/kubeadm-setup.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5014 Upgrade Cilium network plugin to v1.5.5.
  README.md
  roles/download/defaults/main.yml
  roles/network_plugin/cilium/defaults/main.yml
  roles/network_plugin/cilium/tasks/main.yml
  roles/network_plugin/cilium/templates/000-cilium-portmap.conflist.j2
  roles/network_plugin/cilium/templates/cilium-config.yml.j2
  roles/network_plugin/cilium/templates/cilium-cr.yml.j2
  roles/network_plugin/cilium/templates/cilium-crb.yml.j2
  roles/network_plugin/cilium/templates/cilium-deploy.yml.j2
  roles/network_plugin/cilium/templates/cilium-ds.yml.j2
  roles/network_plugin/cilium/templates/cilium-sa.yml.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XL

#5026 [contrib/heketi]: path fix and tear down improvements
  contrib/network-storage/heketi/README.md
  contrib/network-storage/heketi/roles/provision/templates/heketi-bootstrap.json.j2
  contrib/network-storage/heketi/roles/provision/templates/heketi-deployment.json.j2
  contrib/network-storage/heketi/roles/tear-down-disks/defaults/main.yml
  contrib/network-storage/heketi/roles/tear-down-disks/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#5044 Add ability to setup virtual ip for ingress-controller on bare metal
  inventory/sample/group_vars/k8s-cluster/addons.yml
  roles/kubernetes-apps/ingress_controller/ingress_nginx/defaults/main.yml
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/ds-ingress-nginx-controller.yml.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#5050 Ansible version bump for CVE-2019-10156
  requirements.txt
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#5032 Allow etcd member join by checking cluster health only on first etcd
  roles/etcd/tasks/configure.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5009 Refactor remove node to allow removing dead nodes and etcd members
  docs/getting-started.md
  remove-node.yml
  roles/remove-node/post-remove/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/M

#5051 Fix check for removing etcd member
  roles/remove-node/post-remove/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4975 Refactor calico route reflector to run in k8s cluster
  cluster.yml
  docs/calico.md
  inventory/local/hosts.ini
  inventory/sample/inventory.ini
  roles/kubernetes/kubeadm/templates/kubeadm-client.conf.v1alpha3.j2
  roles/kubernetes/kubeadm/templates/kubeadm-client.conf.v1beta1.j2
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
  roles/network_plugin/calico/rr/defaults/main.yml
  roles/network_plugin/calico/rr/handlers/main.yml
  roles/network_plugin/calico/rr/tasks/main.yml
  roles/network_plugin/calico/rr/tasks/pre.yml
  roles/network_plugin/calico/rr/templates/calico-rr-containerd.service.j2
  roles/network_plugin/calico/rr/templates/calico-rr-docker.service.j2
  roles/network_plugin/calico/rr/templates/calico-rr.env.j2
  roles/network_plugin/calico/tasks/install.yml
  tests/cloud_playbooks/roles/packet-ci/templates/inventory.j2
  tests/templates/inventory-aws.j2
  tests/templates/inventory-do.j2
  tests/templates/inventory-gce.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/L

#5048 go to k8s 1.15.2, update nodelocaldns to latest bugfix release
  README.md
  inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml
  roles/download/defaults/main.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#5042 Fix variable for rbd_provisioner_user_secret
  contrib/metallb/README.md
  roles/kubernetes-apps/external_provisioner/rbd_provisioner/defaults/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5041 multus | fix use last version
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#5055 Bump minimum K8S version to 1.14
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#5054 Add missing coredns tag. Fixes #5017
  roles/kubernetes-apps/ansible/tasks/nodelocaldns.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#5071 Always download coredns images with kubeadm
  roles/download/templates/kubeadm-images.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1beta1.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1beta2.yaml.j2
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5073 Allow to configure number of kube-masters
  contrib/inventory_builder/inventory.py
Labels: approved, cncf-cla: yes, lgtm, size/S

#5072 Fix broken containerd pinning on Ubuntu
  roles/container-engine/containerd/templates/apt_preferences.d/debian_containerd.j2
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#5063 move kube-ovn images to dockerhub
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#5057 Set initial kubeadm token if specified in kubeadm init
  roles/kubernetes/master/templates/kubeadm-config.v1beta1.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1beta2.yaml.j2
Labels: approved, cncf-cla: yes, lgtm, size/S

#5066 Ingress nginx
  roles/kubernetes-apps/ingress_controller/ingress_nginx/tasks/main.yml
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/clusterrole-ingress-nginx.yml.j2
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/svc-default-backend.yml.j2
Labels: approved, cncf-cla: yes, lgtm, size/S

#5069 Disable moderator
  .gitlab-ci.yml
Labels: approved, cncf-cla: yes, kind/api-change, lgtm, size/XS

#5076 upgrade helm to 2.14.3 on release-2.11
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5081 Upgrade ingress nginx to 0.25.1
  README.md
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#5075 upgrade Helm to 2.14.3 in master
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4994 modify resource-container default value for kube-proxy
  roles/kubernetes/master/defaults/main/kube-proxy.yml
  roles/kubernetes/master/templates/kubeadm-config.v1beta1.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1beta2.yaml.j2
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#5078 Fix openstack_cacert conditional fail
  roles/kubernetes/node/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#5083 fix word errors in downloads.md
  docs/downloads.md
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#5086 cleanup vars.md typos words
  docs/vars.md
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#5085 add cluster name into filer if specifed in environment variable
  contrib/aws_inventory/kubespray-aws-inventory.py
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#5062 Updated Openstack to terraform 0.12
  .gitlab-ci/terraform.yml
  contrib/terraform/openstack/.gitignore
  contrib/terraform/openstack/README.md
  contrib/terraform/openstack/kubespray.tf
  contrib/terraform/openstack/modules/compute/main.tf
  contrib/terraform/openstack/modules/ips/main.tf
  contrib/terraform/openstack/modules/ips/outputs.tf
  contrib/terraform/openstack/modules/network/main.tf
  contrib/terraform/openstack/sample-inventory/cluster.tfvars
  contrib/terraform/terraform.py
Labels: approved, cncf-cla: yes, lgtm, size/L

#5088 Kube-router annotate.yml: Use group 'k8s-cluster' instead of 'all' (#5087)
  roles/network_plugin/kube-router/tasks/annotate.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#5089 Add support node-volume-attach-limit in the Openstack provider
  contrib/terraform/openstack/README.md
  roles/kubernetes/node/templates/cloud-configs/openstack-cloud-config.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#5091 Upgrade to Kubernetes 1.15.3
  README.md
  inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml
  roles/download/defaults/main.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5092 Allow to configure strict ARP on kube-proxy
  roles/kubernetes/master/defaults/main/kube-proxy.yml
  roles/kubernetes/master/templates/kubeadm-config.v1beta1.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1beta2.yaml.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#5093 terraform/openstack: add network_dns_domain variable
  contrib/terraform/openstack/README.md
  contrib/terraform/openstack/kubespray.tf
  contrib/terraform/openstack/modules/network/main.tf
  contrib/terraform/openstack/modules/network/variables.tf
  contrib/terraform/openstack/variables.tf
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#5094 fix bug: run Copy image to ansible host cache on download_delegate host
  roles/download/tasks/download_container.yml
  roles/download/tasks/download_file.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#5098 Update to Kube v1.14.6
  README.md
  inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml
  roles/download/defaults/main.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#4582 Update CRI-O in CentOS
  README.md
  roles/container-engine/cri-o/defaults/main.yml
  roles/container-engine/cri-o/templates/crio.conf.j2
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/L

#5084 Replace fetch with synchronize due to memory error
  roles/kubernetes/client/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#4629 Added CRI-O support for ubuntu
  roles/container-engine/cri-o/tasks/main.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#5101 Allow calico settings to be modified
  roles/network_plugin/calico/tasks/install.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5108 Fix documentation of extra_args and custom_flags variables
  docs/vars.md
  roles/kubernetes/master/defaults/main/main.yml
Labels: approved, cncf-cla: yes, kind/cleanup, kind/documentation, lgtm, size/S

#5110 print hostnames
  contrib/inventory_builder/inventory.py
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS
