Repository kubernetes-sigs/kubespray, pull requests merged in 2019-10, with the labels that each got.

#5189 Switch to Kubernetes v1.16.0
  .ansible-lint
  .gitlab-ci/packet.yml
  .gitlab-ci/terraform.yml
  README.md
  inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml
  roles/download/defaults/main.yml
  roles/download/tasks/download_file.yml
  roles/download/tasks/sync_file.yml
  roles/kubernetes/client/tasks/main.yml
  roles/kubernetes/kubeadm/tasks/kubeadm_etcd_node.yml
  roles/kubernetes/kubeadm/tasks/main.yml
  roles/kubernetes/master/tasks/kubeadm-secondary-experimental.yml
  roles/kubernetes/master/tasks/kubeadm-setup.yml
  roles/kubernetes/master/tasks/kubeadm-version.yml
  roles/kubernetes/master/templates/kubeadm-config.v1beta1.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1beta2.yaml.j2
  roles/kubernetes/node/tasks/kubelet.yml
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
  roles/kubespray-defaults/defaults/main.yaml
  roles/network_plugin/kube-router/templates/kube-router.yml.j2
  tests/testcases/100_check-k8s-conformance.yml
Labels: approved, cncf-cla: yes, lgtm, size/L

#5230 Apply workaround for NetworkManager and calico
  .ansible-lint
  roles/network_plugin/calico/handlers/main.yml
  roles/network_plugin/calico/tasks/install.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5214 clean up document
  contrib/azurerm/group_vars/all
  docs/azure.md
  roles/download/tasks/check_pull_required.yml
  roles/kubernetes-apps/cloud_controller/oci/tasks/credentials-check.yml
  roles/network_plugin/macvlan/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#5237 Fix selector workaround for helm install
  roles/kubernetes-apps/helm/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5212 Helm init client in a separate task
  roles/kubernetes-apps/helm/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S

#5239 Make it possible to disable access_ip (openstack provider)
  contrib/terraform/openstack/README.md
  contrib/terraform/openstack/kubespray.tf
  contrib/terraform/openstack/modules/compute/main.tf
  contrib/terraform/openstack/modules/compute/variables.tf
  contrib/terraform/openstack/modules/ips/variables.tf
  contrib/terraform/openstack/variables.tf
  contrib/terraform/terraform.py
Labels: approved, cncf-cla: yes, lgtm, size/M

#5240 Reset between kubeadm secondary control plane join attempts
  roles/kubernetes/master/tasks/kubeadm-secondary-experimental.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5243 Enable openstack_cacert to be either file or base64 string
  docs/openstack.md
  roles/kubernetes/node/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5186 Fix issue in remove-node/post-remove task (#5185)
  roles/remove-node/post-remove/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5256 fix wrong path in include install_host.yml in etcd role
  roles/etcd/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#5251 No need to gather facts on localhost
  reset.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5266 Minimum required version of Kubernetes is v1.15.0
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#5269 Update cert-manager to v0.11.0
  README.md
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#5236 add ignore_errors to the kube-proxy deletion task
  roles/kubernetes/kubeadm/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#5233 contrib/heketi: use inventory node ip in topology instead of guessing it
  contrib/network-storage/heketi/roles/provision/templates/heketi-storage.json.j2
  contrib/network-storage/heketi/roles/provision/templates/topology.json.j2
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5197 Fix getting nameserver and search for /etc/resolv.conf with comments
  roles/container-engine/docker/tasks/set_facts_dns.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#5162 update docker-ce to 18.09.7 (#4973) for release 2.10
  roles/container-engine/docker/vars/debian.yml
  roles/container-engine/docker/vars/fedora.yml
  roles/container-engine/docker/vars/redhat.yml
  roles/container-engine/docker/vars/ubuntu-amd64.yml
  roles/container-engine/docker/vars/ubuntu-arm64.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#5187 Update template for dashboard to support v2.x
  roles/kubernetes-apps/ansible/templates/dashboard.yml.j2
Labels: approved, cncf-cla: yes, lgtm, size/M

#5152 Add RotateCertificates to kubelet config
  roles/kubernetes/node/templates/kubelet-config.v1beta1.yaml.j2
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#5235 Add k8s v1.15.4 hashes
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#5264 Clarify process for upgrading more than one version
  docs/upgrades.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/L

#5270 Update nginx image to latest
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#5253 Fix selector for calico-typha deployment
  roles/network_plugin/calico/templates/calico-typha.yml.j2
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5268 Update ingress-nginx to v0.26.1
  README.md
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#5275 Fix typo introduced by PR 5253
  roles/network_plugin/calico/templates/calico-typha.yml.j2
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#5272 Add support for Kubernetes 1.16.2
  README.md
  inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml
  roles/download/defaults/main.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#5250 Add support for restart handlers for control plane on crio/containerd
  roles/kubernetes/master/handlers/main.yml
  roles/kubernetes/preinstall/handlers/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#5263 Add etcd_data_dir variable to the kubeadm config
  roles/kubernetes/master/templates/kubeadm-config.v1beta1.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1beta2.yaml.j2
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5128 add KUBELET_VOLUME_PLUGIN to kubelet.env
  roles/kubernetes/node/templates/kubelet.env.v1beta1.j2
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#5209 ignore gpg files in inventory
  ansible.cfg
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#5111 install python3 instead of python2 for fedora >= 30 fixes 5056, fixes 4802
  roles/kubernetes/preinstall/tasks/0070-system-packages.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S

#5120 Revert Pull Request #5084
  roles/kubernetes/client/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#5177 download container always been on download_delegate host
  roles/download/tasks/check_pull_required.yml
  roles/download/tasks/download_container.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#5279 check on all cluster node - kubelet_max_pods vs kube_network_node_prefix
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#5259 set calico_datastore default value in role kubespray-default
  roles/kubernetes-apps/policy_controller/calico/defaults/main.yml
  roles/kubespray-defaults/defaults/main.yaml
  roles/network_plugin/calico/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#5258 Generate TLS certs for calico typha
  inventory/sample/group_vars/k8s-cluster/k8s-net-calico.yml
  roles/download/defaults/main.yml
  roles/network_plugin/calico/defaults/main.yml
  roles/network_plugin/calico/files/make-ssl-typha.sh
  roles/network_plugin/calico/files/openssl.conf
  roles/network_plugin/calico/tasks/install.yml
  roles/network_plugin/calico/tasks/typha_certs.yml
  roles/network_plugin/calico/templates/calico-config.yml.j2
  roles/network_plugin/calico/templates/calico-node.yml.j2
  roles/network_plugin/calico/templates/calico-typha.yml.j2
  tests/files/gce_centos7-calico-ha.yml
  tests/files/packet_centos7-calico-ha.yml
Labels: approved, cncf-cla: yes, lgtm, size/L

#5294 readme: update url to the Kubernetes documentation page for Kubespray
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#5293 Set cluster DNS in kubeadm config for kubelet dynamic config
  roles/kubernetes/master/templates/kubeadm-config.v1beta2.yaml.j2
Labels: approved, cncf-cla: yes, lgtm, size/S

#5302 Retry cleaning up calico-node container
  roles/network_plugin/calico/handlers/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5298 Terraform dynamic inventory 0.12.12
  .gitlab-ci/terraform.yml
  contrib/terraform/packet/kubespray.tf
  contrib/terraform/packet/output.tf
  contrib/terraform/packet/variables.tf
  contrib/terraform/packet/versions.tf
  contrib/terraform/terraform.py
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/L

#5278 Preparing a 2.11.1 release - kubernetes 1.15.5
  README.md
  inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml
  roles/download/defaults/main.yml
  roles/kubespray-defaults/defaults/main.yaml
  tests/scripts/rebase.sh
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#5304 Raise delay and retry for rotate tokens
  roles/kubernetes-apps/rotate_tokens/tasks/main.yml
  roles/network_plugin/calico/files/make-ssl-typha.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5292 Fix incorrect suggestion to enable old k8s apis
  roles/kubernetes/node/defaults/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5307 Fix typo of docs/dns-stack
  docs/dns-stack.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#5310 Removes repetition.
  docs/_sidebar.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
