Repository kubernetes-sigs/kubespray, pull requests merged in 2019-04, with the labels that each got.

#4401 add 1.14.0 checksum, remove 1.11.* checksums
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#4406 Remove kubedns and dnsmasq. Move dns_late phase after apps
  cluster.yml
  docs/ansible.md
  docs/dns-stack.md
  docs/large-deployments.md
  docs/vars.md
  inventory/sample/group_vars/all/all.yml
  inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml
  roles/container-engine/docker/tasks/set_facts_dns.yml
  roles/dnsmasq/defaults/main.yml
  roles/dnsmasq/tasks/main.yml
  roles/dnsmasq/templates/01-kube-dns.conf.j2
  roles/dnsmasq/templates/dnsmasq-autoscaler.yml.j2
  roles/dnsmasq/templates/dnsmasq-clusterrolebinding.yml.j2
  roles/dnsmasq/templates/dnsmasq-deploy.yml.j2
  roles/dnsmasq/templates/dnsmasq-serviceaccount.yml.j2
  roles/dnsmasq/templates/dnsmasq-svc.yml.j2
  roles/download/defaults/main.yml
  roles/kubernetes-apps/ansible/defaults/main.yml
  roles/kubernetes-apps/ansible/tasks/kubedns.yml
  roles/kubernetes-apps/ansible/tasks/main.yml
  roles/kubernetes-apps/ansible/tasks/nodelocaldns.yml
  roles/kubernetes-apps/ansible/templates/dns-autoscaler.yml.j2
  roles/kubernetes-apps/ansible/templates/kubedns-config.yml.j2
  roles/kubernetes-apps/ansible/templates/kubedns-deploy.yml.j2
  roles/kubernetes-apps/ansible/templates/kubedns-sa.yml.j2
  roles/kubernetes-apps/ansible/templates/kubedns-svc.yml.j2
  roles/kubernetes-apps/rotate_tokens/tasks/main.yml
  roles/kubernetes/node/templates/kubelet.kubeadm.env.j2
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
  roles/kubernetes/preinstall/tasks/0040-set_facts.yml
  roles/kubespray-defaults/defaults/main.yaml
  tests/testcases/010_check-apiserver.yml
  upgrade-cluster.yml
Labels: approved, cncf-cla: yes, lgtm, size/XL

#4408 Speed up old docker package removal
  roles/container-engine/docker/defaults/main.yml
  roles/container-engine/docker/tasks/pre-upgrade.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#4416 Use install_cni init container for cni copy for calico/canal
  roles/network_plugin/calico/defaults/main.yml
  roles/network_plugin/calico/tasks/install.yml
  roles/network_plugin/calico/templates/calico-node.yml.j2
  roles/network_plugin/canal/tasks/main.yml
  roles/network_plugin/canal/templates/canal-node.yaml.j2
Labels: approved, cncf-cla: yes, lgtm, size/M

#4418 Fixed cleanup-docker-orphans.sh to use docker-containerd-shim and con…
  roles/container-engine/docker/files/cleanup-docker-orphans.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4081 enable kubelet client certificate rotation
  docs/vars.md
  roles/kubernetes/node/templates/kubelet.kubeadm.env.j2
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4260 remove our config if docker start failed
  roles/container-engine/docker/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#4268 keep compatibility as it was before
  roles/kubernetes/master/defaults/main/kube-proxy.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4426 jmespath is required when re-running cluster.yml
  requirements.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4425 Update DNS Autoscaler to 1.4.0
  roles/download/defaults/main.yml
  roles/kubernetes-apps/ansible/dns-autoscaler-clusterrole.yml
  roles/kubernetes-apps/ansible/templates/dns-autoscaler.yml.j2
Labels: approved, cncf-cla: yes, lgtm, size/S

#4423 Update nodelocaldns cache settings
  roles/kubernetes-apps/ansible/templates/nodelocaldns-config.yml.j2
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4422 Update CoreDNS to 1.4.0
  README.md
  roles/download/defaults/main.yml
  roles/kubernetes-apps/ansible/templates/coredns-config.yml.j2
  roles/kubernetes-apps/ansible/templates/coredns-deployment.yml.j2
Labels: approved, cncf-cla: yes, lgtm, size/S

#4253 Use docker.io for calico
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#4133 Add CI for contrib/terraform/
  .gitlab-ci.yml
  contrib/terraform/packet/sample-inventory/cluster.tf
Labels: approved, cncf-cla: yes, lgtm, size/M

#4415 add allowVolumeExpansion option
  roles/kubernetes-apps/persistent_volumes/openstack/templates/openstack-storage-class.yml.j2
  roles/kubernetes/master/defaults/main/main.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4430 allow Suse OS family
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4431 Remove bash-completion
  roles/kubernetes/preinstall/defaults/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4428 Tell git to ignore .terraform directory
  .gitignore
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4368 Fix pep8 warnings
  contrib/inventory_builder/inventory.py
  contrib/inventory_builder/requirements.txt
Labels: approved, cncf-cla: yes, lgtm, size/M

#4424 Update premoderator to fix Github API throttle
  scripts/premoderator.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#4445 Upgrade to Helm 2.13.1
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4456 Update pypy3 on CoreOS to 7.0.0
  roles/bootstrap-os/files/bootstrap.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4437 Replace iteritems() to items() in Jinja2 templates
  roles/kubernetes-apps/cloud_controller/oci/templates/controller-manager-config.yml.j2
  roles/kubernetes-apps/external_provisioner/local_volume_provisioner/templates/local-volume-provisioner-cm.yml.j2
  roles/kubernetes-apps/external_provisioner/local_volume_provisioner/templates/local-volume-provisioner-ds.yml.j2
  roles/kubernetes-apps/external_provisioner/local_volume_provisioner/templates/local-volume-provisioner-psp.yml.j2
Labels: approved, cncf-cla: yes, lgtm, size/S

#4444 Upgrade to etcd v3.2.26
  README.md
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4441 Add OWNERS to contrib/terraform
  contrib/terraform/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4458 Update nginx to 1.15. Update manifest and performance optimize
  roles/download/defaults/main.yml
  roles/kubernetes/node/defaults/main.yml
  roles/kubernetes/node/templates/manifests/nginx-proxy.manifest.j2
  roles/kubernetes/node/templates/nginx.conf.j2
Labels: approved, cncf-cla: yes, lgtm, size/M

#4446 Missing ruamel.yaml from requirements.txt
  requirements.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4405 Run terraform fmt and add step to CI
  .gitlab-ci.yml
  contrib/terraform/aws/create-infrastructure.tf
  contrib/terraform/aws/modules/elb/main.tf
  contrib/terraform/aws/modules/elb/outputs.tf
  contrib/terraform/aws/modules/elb/variables.tf
  contrib/terraform/aws/modules/iam/main.tf
  contrib/terraform/aws/modules/iam/outputs.tf
  contrib/terraform/aws/modules/iam/variables.tf
  contrib/terraform/aws/modules/vpc/main.tf
  contrib/terraform/aws/modules/vpc/outputs.tf
  contrib/terraform/aws/modules/vpc/variables.tf
  contrib/terraform/aws/output.tf
  contrib/terraform/aws/variables.tf
  contrib/terraform/packet/kubespray.tf
  contrib/terraform/packet/output.tf
  contrib/terraform/packet/sample-inventory/cluster.tf
Labels: approved, cncf-cla: yes, lgtm, size/L

#4451 [nodelocaldns] expand tolerations on the daemonset
  roles/kubernetes-apps/ansible/templates/nodelocaldns-daemonset.yml.j2
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4460 Remove nodelocaldns iface on reset
  roles/reset/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#4435 robust handling of API server SANs
  roles/kubernetes/master/tasks/kubeadm-setup.yml
  roles/kubernetes/master/templates/kubeadm-config.v1alpha1.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1alpha2.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1alpha3.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1beta1.yaml.j2
Labels: approved, cncf-cla: yes, lgtm, size/M

#4447 Rename inventory/sample/hosts.ini to fix vagrant up
  inventory/sample/inventory.ini
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4442 openSUSE: Use Leap 15.0 instead of 42.3
  Vagrantfile
  docs/opensuse.md
  inventory/sample/group_vars/all/docker.yml
  roles/bootstrap-os/tasks/bootstrap-opensuse.yml
  roles/bootstrap-os/tasks/main.yml
  roles/container-engine/docker/tasks/main.yml
  roles/container-engine/docker/vars/suse.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#4448 Disable download_once in Vagrant to workaround rsync error
  Vagrantfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4464 kubeadmn init: add 'until' to make 'retries' effective
  roles/kubernetes/master/tasks/kubeadm-setup.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4457 Vagrant fix password prompt
  Vagrantfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4462 Add oidc prefixes to kubeadm templates for release-v2.8
  roles/kubernetes/master/templates/kubeadm-config.v1alpha1.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1alpha2.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1alpha3.yaml.j2
Labels: approved, cncf-cla: yes, lgtm, size/S

#4470 Fix CoreDNS upstream servers bogus jinja filters
  roles/kubernetes-apps/ansible/templates/coredns-config.yml.j2
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4468 add default routing to canal and disable bird checks
  roles/network_plugin/canal/templates/canal-node.yaml.j2
  roles/network_plugin/canal/templates/cni-canal.conflist.j2
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4469 Update kube-router to 0.2.5
  README.md
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4291 Don't create secgroup for a bastion host on openstack, if it doesn't exist
  contrib/terraform/openstack/modules/compute/main.tf
Labels: approved, cncf-cla: yes, lgtm, size/M

#4471 Upgrade to Ansible >2.7.6
  README.md
  cluster.yml
  remove-node.yml
  requirements.txt
  reset.yml
  scale.yml
  upgrade-cluster.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#4305 Fix: error converting YAML to JSON: yaml: line 36: mapping values are not allowed in this context
  roles/kubernetes/master/templates/kubeadm-config.v1alpha1.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1alpha2.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1alpha3.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1beta1.yaml.j2
Labels: approved, cncf-cla: yes, lgtm, size/S

#4272 Added tag kube-proxy
  roles/kubernetes/node/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4411 Add Ansible-lint CI step
  .ansible-lint
  .gitlab-ci.yml
  roles/download/tasks/main.yml
  tests/requirements.txt
Labels: approved, cncf-cla: yes, lgtm, size/M

#4475 Add CI for contrib/terraform/openstack
  .gitlab-ci.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#4438 Add terraform validate for contrib/terraform/aws
  .gitlab-ci.yml
  contrib/terraform/aws/sample-inventory/cluster.tf
  contrib/terraform/aws/sample-inventory/group_vars
Labels: approved, cncf-cla: yes, lgtm, size/M

#3920 Update CoreDNS label as specified in the Coredns repository
  roles/kubernetes-apps/ansible/templates/coredns-deployment.yml.j2
  roles/kubernetes-apps/ansible/templates/coredns-svc.yml.j2
Labels: approved, cncf-cla: yes, lgtm, size/S

#4320 Fix for unknown 'kubernetes.io' or 'k8s.io' labels specified with --node-labels
  inventory/sample/group_vars/k8s-cluster/addons.yml
  roles/kubernetes-apps/ansible/templates/coredns-deployment.yml.j2
  roles/kubernetes-apps/ansible/templates/dashboard.yml.j2
  roles/kubernetes-apps/ansible/templates/dns-autoscaler.yml.j2
  roles/kubernetes-apps/cloud_controller/oci/templates/oci-cloud-provider.yml.j2
  roles/kubernetes-apps/ingress_controller/ingress_nginx/defaults/main.yml
  roles/kubernetes-apps/metrics_server/templates/metrics-server-deployment.yaml.j2
  roles/kubernetes-apps/policy_controller/calico/templates/calico-kube-controllers.yml.j2
  roles/kubernetes/master/tasks/kubeadm-setup.yml
  roles/kubernetes/master/templates/kubeadm-config.v1alpha2.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1alpha3.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1beta1.yaml.j2
  roles/kubernetes/node/templates/kubelet.kubeadm.env.j2
  roles/network_plugin/contiv/templates/contiv-api-proxy.yml.j2
  roles/network_plugin/contiv/templates/contiv-etcd-proxy.yml.j2
  roles/network_plugin/contiv/templates/contiv-etcd.yml.j2
  roles/network_plugin/contiv/templates/contiv-netmaster.yml.j2
  roles/network_plugin/multus/templates/multus-daemonset.yml.j2
Labels: approved, cncf-cla: yes, lgtm, size/M

#4322 Added generic CNI network plugin
  docs/cni.md
  inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml
  roles/kubernetes-apps/network_plugin/cni/tasks/main.yml
  roles/kubernetes-apps/network_plugin/meta/main.yml
  roles/kubernetes/node/templates/kubelet.kubeadm.env.j2
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
  roles/network_plugin/cni/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#4478 Release 2.8 robust san handling
  roles/kubernetes/master/tasks/kubeadm-setup.yml
  roles/kubernetes/master/templates/kubeadm-config.v1alpha1.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1alpha2.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1alpha3.yaml.j2
Labels: approved, cncf-cla: yes, lgtm, size/M

#4484 Fix terraform fmt on contrib/terraform/aws
  contrib/terraform/aws/sample-inventory/cluster.tf
Labels: approved, cncf-cla: yes, lgtm, size/S

#4473 Fix ipip: false in calico v3
  roles/network_plugin/calico/defaults/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4465 Fix "Prevent inventory.py from configuring an even number of nodes in…
  contrib/inventory_builder/inventory.py
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4489 Return back bind API server node loadbalancer to 127.0.0.1 for securi…
  roles/kubernetes/node/templates/haproxy.cfg.j2
  roles/kubernetes/node/templates/nginx.conf.j2
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4492 nodelocaldns - Do not force TCP connections to upstream DNS servers
  roles/kubernetes-apps/ansible/templates/nodelocaldns-config.yml.j2
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4494 Upgrade CoreDNS to 1.5.0
  README.md
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4409 Fix syntax of yaml in .gitlab-ci.yml file
  .gitlab-ci.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#4443 Disable cloud-routes for non-cloud plugin
  roles/kubernetes/master/templates/kubeadm-config.v1beta1.yaml.j2
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4461 Enable nodelocaldns by default
  inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml
  roles/kubespray-defaults/defaults/main.yaml
  tests/files/gce_centos7-flannel-addons.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4439 Add CI for Ubuntu 18.04 on Packet
  .gitlab-ci.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#4493 Add several issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/failing-test.md
  .github/ISSUE_TEMPLATE/support.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#4491 Add a PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#4496 ansible-lint: when lines should not include Jinja2 variables
  .ansible-lint
  roles/kubernetes-apps/helm/tasks/gen_helm_tiller_certs.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4395 Fixing mandatory check of docker_version that breaks bastion host
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4317 Use K8s 1.14 and add kubeadm experimental control plane mode
  README.md
  inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml
  roles/download/defaults/main.yml
  roles/kubernetes/client/tasks/main.yml
  roles/kubernetes/kubeadm/tasks/main.yml
  roles/kubernetes/master/defaults/main/kube-proxy.yml
  roles/kubernetes/master/defaults/main/main.yml
  roles/kubernetes/master/tasks/kubeadm-certificate.yml
  roles/kubernetes/master/tasks/kubeadm-kubeconfig.yml
  roles/kubernetes/master/tasks/kubeadm-migrate-certs.yml
  roles/kubernetes/master/tasks/kubeadm-secondary-experimental.yml
  roles/kubernetes/master/tasks/kubeadm-secondary-legacy.yml
  roles/kubernetes/master/tasks/kubeadm-setup.yml
  roles/kubernetes/master/tasks/kubeadm-version.yml
  roles/kubernetes/master/tasks/pre-upgrade.yml
  roles/kubernetes/master/templates/kubeadm-config.v1alpha1.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1alpha2.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1alpha3.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1beta1.yaml.j2
  roles/kubernetes/master/templates/kubeadm-controlplane.v1beta1.yaml.j2
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
  roles/kubespray-defaults/defaults/main.yaml
  roles/network_plugin/calico/defaults/main.yml
  roles/network_plugin/calico/handlers/main.yml
  roles/network_plugin/calico/rr/defaults/main.yml
  roles/network_plugin/calico/rr/tasks/main.yml
  roles/network_plugin/calico/tasks/check.yml
  roles/network_plugin/calico/tasks/install.yml
  roles/network_plugin/calico/tasks/pre.yml
  roles/network_plugin/calico/templates/etcdv2-store.yml.j2
  roles/network_plugin/calico/templates/etcdv3-store.yml.j2
  roles/network_plugin/canal/defaults/main.yml
  roles/network_plugin/canal/tasks/main.yml
  roles/network_plugin/cilium/defaults/main.yml
  roles/network_plugin/cilium/handlers/main.yml
  roles/network_plugin/cilium/tasks/main.yml
  tests/files/gce_centos7-flannel-addons.yml
Labels: approved, cncf-cla: yes, lgtm, size/XL

#4515 Add logo folders
  index.html
  logo/LICENSE
  logo/OWNERS
  logo/logo-clear.png
  logo/logo-clear.svg
  logo/logo-dark.png
  logo/logo-dark.svg
  logo/logo-text-clear.png
  logo/logo-text-clear.svg
  logo/logo-text-dark.png
  logo/logo-text-dark.svg
  logo/logo-text-mixed.png
  logo/logo-text-mixed.svg
  logo/logos.pdf
  logo/usage_guidelines.md
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XL

#4509 Sanitize the cluster_name variable
  .gitlab-ci.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#4524 Switch calicoctl from a container to a binary
  roles/download/defaults/main.yml
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
  roles/network_plugin/calico/tasks/check.yml
  roles/network_plugin/calico/tasks/install.yml
  roles/network_plugin/calico/templates/calicoctl-container.j2
  roles/network_plugin/calico/templates/calicoctl.sh.j2
  roles/network_plugin/canal/tasks/main.yml
  roles/network_plugin/canal/templates/calicoctl-container.j2
  roles/network_plugin/canal/templates/calicoctl.sh.j2
Labels: approved, cncf-cla: yes, lgtm, size/L

#4506 [contrib/terraform/openstack] Add k8s_allowed_remote_ips variable
  .gitlab-ci.yml
  contrib/terraform/openstack/README.md
  contrib/terraform/openstack/kubespray.tf
  contrib/terraform/openstack/modules/compute/main.tf
  contrib/terraform/openstack/modules/compute/variables.tf
  contrib/terraform/openstack/variables.tf
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/M

#4519 Split .gitlab-ci.yml into several files
  .gitlab-ci.yml
  .gitlab-ci/digital-ocean.yml
  .gitlab-ci/gce.yml
  .gitlab-ci/lint.yml
  .gitlab-ci/terraform.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XXL

#4539 Mark "Calico | Set global as_num" as "unchanged"
  roles/network_plugin/calico/tasks/install.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#4537 PHASE 1 - Add Packet-CI playbook and configuration
  tests/Makefile
  tests/cloud_playbooks/create-packet.yml
  tests/cloud_playbooks/delete-packet.yml
  tests/cloud_playbooks/roles/packet-ci/defaults/main.yml
  tests/cloud_playbooks/roles/packet-ci/tasks/create-vms.yml
  tests/cloud_playbooks/roles/packet-ci/tasks/delete-vms.yml
  tests/cloud_playbooks/roles/packet-ci/tasks/main.yml
  tests/cloud_playbooks/roles/packet-ci/templates/inventory.j2
  tests/cloud_playbooks/roles/packet-ci/templates/vm.yml.j2
  tests/requirements.txt
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/L

#3668 add RBD Provisioner Addon
  README.md
  inventory/sample/group_vars/k8s-cluster/addons.yml
  roles/bootstrap-os/tasks/main.yml
  roles/download/defaults/main.yml
  roles/kubernetes-apps/external_provisioner/meta/main.yml
  roles/kubernetes-apps/external_provisioner/rbd_provisioner/README.md
  roles/kubernetes-apps/external_provisioner/rbd_provisioner/defaults/main.yml
  roles/kubernetes-apps/external_provisioner/rbd_provisioner/tasks/main.yml
  roles/kubernetes-apps/external_provisioner/rbd_provisioner/templates/00-namespace.yml.j2
  roles/kubernetes-apps/external_provisioner/rbd_provisioner/templates/clusterrole-rbd-provisioner.yml.j2
  roles/kubernetes-apps/external_provisioner/rbd_provisioner/templates/clusterrolebinding-rbd-provisioner.yml.j2
  roles/kubernetes-apps/external_provisioner/rbd_provisioner/templates/deploy-rbd-provisioner.yml.j2
  roles/kubernetes-apps/external_provisioner/rbd_provisioner/templates/psp-rbd-provisioner.yml.j2
  roles/kubernetes-apps/external_provisioner/rbd_provisioner/templates/role-rbd-provisioner.yml.j2
  roles/kubernetes-apps/external_provisioner/rbd_provisioner/templates/rolebinding-rbd-provisioner.yml.j2
  roles/kubernetes-apps/external_provisioner/rbd_provisioner/templates/sa-rbd-provisioner.yml.j2
  roles/kubernetes-apps/external_provisioner/rbd_provisioner/templates/sc-rbd-provisioner.yml.j2
  roles/kubernetes-apps/external_provisioner/rbd_provisioner/templates/secret-rbd-provisioner.yml.j2
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#4533 [terraform/openstack] Explicitly set egress security groups
  contrib/terraform/openstack/kubespray.tf
  contrib/terraform/openstack/modules/compute/main.tf
  contrib/terraform/openstack/modules/compute/variables.tf
  contrib/terraform/openstack/variables.tf
Labels: approved, cncf-cla: yes, kind/feature, kind/flake, lgtm, size/M

#4553 Revert "Fix for unknown 'kubernetes.io' or 'k8s.io' labels specified …
  inventory/sample/group_vars/k8s-cluster/addons.yml
  roles/kubernetes-apps/ansible/templates/coredns-deployment.yml.j2
  roles/kubernetes-apps/ansible/templates/dashboard.yml.j2
  roles/kubernetes-apps/ansible/templates/dns-autoscaler.yml.j2
  roles/kubernetes-apps/cloud_controller/oci/templates/oci-cloud-provider.yml.j2
  roles/kubernetes-apps/ingress_controller/ingress_nginx/defaults/main.yml
  roles/kubernetes-apps/metrics_server/templates/metrics-server-deployment.yaml.j2
  roles/kubernetes-apps/policy_controller/calico/templates/calico-kube-controllers.yml.j2
  roles/kubernetes/master/tasks/kubeadm-setup.yml
  roles/kubernetes/master/templates/kubeadm-config.v1alpha2.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1alpha3.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1beta1.yaml.j2
  roles/kubernetes/node/templates/kubelet.kubeadm.env.j2
  roles/network_plugin/contiv/templates/contiv-api-proxy.yml.j2
  roles/network_plugin/contiv/templates/contiv-etcd-proxy.yml.j2
  roles/network_plugin/contiv/templates/contiv-etcd.yml.j2
  roles/network_plugin/contiv/templates/contiv-netmaster.yml.j2
  roles/network_plugin/multus/templates/multus-daemonset.yml.j2
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/M

#4538 PHASE 2 - Enable Packet-CI in gitlab and move unit-tests and deploy-part1
  .gitlab-ci.yml
  .gitlab-ci/digital-ocean.yml
  .gitlab-ci/gce.yml
  .gitlab-ci/lint.yml
  .gitlab-ci/packet.yml
  .gitlab-ci/terraform.yml
  tests/files/packet_centos-weave-kubeadm-sep.yml
  tests/files/packet_centos7-calico-ha.yml
  tests/files/packet_centos7-cilium.yml
  tests/files/packet_centos7-flannel-addons.yml
  tests/files/packet_centos7-kube-router.yml
  tests/files/packet_centos7-multus-calico.yml
  tests/files/packet_debian9-calico-upgrade.yml
  tests/files/packet_opensuse-canal.yml
  tests/files/packet_rhel7-canal-sep.yml
  tests/files/packet_rhel7-cilium.yml
  tests/files/packet_rhel7-weave.yml
  tests/files/packet_ubuntu-canal-ha.yml
  tests/files/packet_ubuntu-canal-kubeadm.yml
  tests/files/packet_ubuntu-cilium-sep.yml
  tests/files/packet_ubuntu-contiv-sep.yml
  tests/files/packet_ubuntu-flannel-ha.yml
  tests/files/packet_ubuntu-kube-router-sep.yml
  tests/files/packet_ubuntu-rkt-sep.yml
  tests/files/packet_ubuntu-weave-sep.yml
  tests/files/packet_ubuntu18-flannel-aio.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XL

#4499 ansible-lint: E601 Don’t compare to literal True/False
  .ansible-lint
  roles/download/defaults/main.yml
  roles/kubernetes-apps/ansible/tasks/main.yml
  roles/kubernetes-apps/ansible/tasks/nodelocaldns.yml
  roles/kubernetes-apps/cloud_controller/oci/tasks/credentials-check.yml
  roles/kubernetes-apps/network_plugin/cilium/tasks/main.yml
  roles/kubernetes-apps/network_plugin/kube-router/tasks/main.yml
  roles/kubernetes/node/tasks/main.yml
  roles/kubernetes/node/templates/kubelet.kubeadm.env.j2
  roles/kubernetes/preinstall/tasks/0080-system-configurations.yml
  test-infra/image-builder/roles/kubevirt-images/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#4535 Upgrade to Ansible 2.7.8
  README.md
  cluster.yml
  remove-node.yml
  requirements.txt
  reset.yml
  scale.yml
  upgrade-cluster.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/M

#4548 Add host information for canal readiness probe
  roles/network_plugin/canal/templates/canal-node.yaml.j2
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4561 Fix ansible-lint e601 in create-vms
  tests/cloud_playbooks/roles/packet-ci/tasks/create-vms.yml
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, size/XS

#4521 Fix CI link
  README.md
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#4500 ansible-lint: E403 Package installs should not use latest
  .ansible-lint
  contrib/kvm-setup/roles/kvm-setup/tasks/main.yml
  roles/kubernetes/preinstall/tasks/0120-growpart-azure-centos-7.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#4511 Fix ansible-lint error 103
  .ansible-lint
  tests/cloud_playbooks/create-aws.yml
  tests/cloud_playbooks/delete-aws.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#4559 Enable working Packet CI jobs and delay GCE CI
  .gitlab-ci.yml
  .gitlab-ci/gce.yml
  .gitlab-ci/packet.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/M

#4513 added missing sidebar link to Packet doc
  docs/_sidebar.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4543 Ensure /etc/bash_completion.d/ folder exists
  roles/kubernetes-apps/helm/tasks/main.yml
  roles/kubernetes/master/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S

#4566 Comment loadbalancer_* settings in sample inventory
  inventory/sample/group_vars/all/all.yml
Labels: approved, cncf-cla: yes, kind/bug, size/XS

#4568 Fix ansible-lint for ceph package
  roles/bootstrap-os/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, size/XS

#4542 Fix runc absolute path
  roles/container-engine/cri-o/templates/crio.conf.j2
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#4562 Add shellcheck CI
  .gitlab-ci.yml
  .gitlab-ci/shellcheck.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#4576 YAMLLint everything
  roles/kubernetes-apps/network_plugin/cni/tasks/main.yml
  roles/kubernetes-apps/network_plugin/kube-router/tasks/main.yml
  roles/network_plugin/cni/tasks/main.yml
  tests/files/packet_centos-weave-kubeadm-sep.yml
  tests/files/packet_centos7-calico-ha.yml
  tests/files/packet_centos7-cilium.yml
  tests/files/packet_centos7-flannel-addons.yml
  tests/files/packet_centos7-kube-router.yml
  tests/files/packet_centos7-multus-calico.yml
  tests/files/packet_debian9-calico-upgrade.yml
  tests/files/packet_opensuse-canal.yml
  tests/files/packet_rhel7-canal-sep.yml
  tests/files/packet_rhel7-cilium.yml
  tests/files/packet_rhel7-weave.yml
  tests/files/packet_ubuntu-canal-ha.yml
  tests/files/packet_ubuntu-canal-kubeadm.yml
  tests/files/packet_ubuntu-cilium-sep.yml
  tests/files/packet_ubuntu-contiv-sep.yml
  tests/files/packet_ubuntu-flannel-ha.yml
  tests/files/packet_ubuntu-kube-router-sep.yml
  tests/files/packet_ubuntu-rkt-sep.yml
  tests/files/packet_ubuntu-weave-sep.yml
  tests/files/packet_ubuntu18-flannel-aio.yml
Labels: approved, cncf-cla: yes, kind/bug, kind/failing-test, lgtm, size/S

#4580 Add SHA-256 hashes for calicoctl v3.6.1
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4514 Use K8s 1.14 and add kubeadm experimental control plane mode
  README.md
  inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml
  roles/download/defaults/main.yml
  roles/kubernetes/client/tasks/main.yml
  roles/kubernetes/kubeadm/tasks/main.yml
  roles/kubernetes/master/defaults/main/kube-proxy.yml
  roles/kubernetes/master/defaults/main/main.yml
  roles/kubernetes/master/tasks/kubeadm-certificate.yml
  roles/kubernetes/master/tasks/kubeadm-kubeconfig.yml
  roles/kubernetes/master/tasks/kubeadm-migrate-certs.yml
  roles/kubernetes/master/tasks/kubeadm-secondary-experimental.yml
  roles/kubernetes/master/tasks/kubeadm-secondary-legacy.yml
  roles/kubernetes/master/tasks/kubeadm-setup.yml
  roles/kubernetes/master/tasks/kubeadm-upgrade.yml
  roles/kubernetes/master/tasks/kubeadm-version.yml
  roles/kubernetes/master/tasks/pre-upgrade.yml
  roles/kubernetes/master/templates/kubeadm-config.v1alpha1.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1alpha2.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1alpha3.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1beta1.yaml.j2
  roles/kubernetes/master/templates/kubeadm-controlplane.v1beta1.yaml.j2
  roles/kubernetes/node/templates/kubelet.kubeadm.env.j2
  roles/kubernetes/preinstall/defaults/main.yml
  roles/kubernetes/preinstall/tasks/0050-create_directories.yml
  roles/kubespray-defaults/defaults/main.yaml
  roles/network_plugin/calico/defaults/main.yml
  roles/network_plugin/calico/handlers/main.yml
  roles/network_plugin/calico/rr/defaults/main.yml
  roles/network_plugin/calico/rr/tasks/main.yml
  roles/network_plugin/calico/tasks/install.yml
  roles/network_plugin/calico/tasks/pre.yml
  roles/network_plugin/calico/templates/etcdv2-store.yml.j2
  roles/network_plugin/calico/templates/etcdv3-store.yml.j2
  roles/network_plugin/canal/defaults/main.yml
  roles/network_plugin/canal/tasks/main.yml
  roles/network_plugin/cilium/defaults/main.yml
  roles/network_plugin/cilium/handlers/main.yml
  roles/network_plugin/cilium/tasks/main.yml
  tests/files/gce_centos7-flannel-addons.yml
Labels: approved, cncf-cla: yes, lgtm, size/XL

#4555 Add a testcase to check that pods are running
  .gitlab-ci.yml
  tests/files/packet_ubuntu18-flannel-aio.yml
  tests/testcases/015_check-pods-running.yml
  tests/testcases/030_check-network.yml
Labels: approved, cncf-cla: yes, kind/bug, kind/failing-test, lgtm, size/M

#4584 Packet CI: Increasing the time waiting for IP to be assigned
  tests/cloud_playbooks/roles/packet-ci/tasks/create-vms.yml
Labels: approved, cncf-cla: yes, kind/flake, lgtm, size/XS

#4587 Use yamllint --strict
  .gitlab-ci/lint.yml
  .gitlab-ci/shellcheck.yml
Labels: approved, cncf-cla: yes, kind/cleanup, kind/feature, lgtm

#4208 Cleanup references to Travis CI
  docs/test_cases.md
  scripts/gen_matrix.sh
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/M

#4567 Re-Add docker:dind for Packet CI and fix packet_centos7-calico-ha
  .gitlab-ci.yml
  .gitlab-ci/gce.yml
  .gitlab-ci/packet.yml
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, size/S

#4586 Fix CI for packet_centos7-flannel-addons
  .gitlab-ci/gce.yml
  .gitlab-ci/packet.yml
  tests/files/packet_centos7-flannel-addons.yml
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, size/XS

#4302 [doc] Add documentation about CPU arch compatibility
  docs/arch.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/S

#4350 Install cri-tools on fedora
  roles/container-engine/cri-o/vars/fedora.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4585 Simplify syntax-check CI job
  .gitlab-ci/lint.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/S

#4549 Wait longer for node to join the cluster
  roles/kubernetes/kubeadm/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4581 Inventory builder doc
  README.md
  docs/getting-started.md
Labels: approved, cncf-cla: yes, kind/bug, kind/documentation, lgtm, size/S

#4022 add master_allowed_remote_ips var
  contrib/terraform/openstack/README.md
  contrib/terraform/openstack/kubespray.tf
  contrib/terraform/openstack/modules/compute/main.tf
  contrib/terraform/openstack/modules/compute/variables.tf
  contrib/terraform/openstack/variables.tf
Labels: approved, cncf-cla: yes, lgtm, size/S

#4138 [contrib/terraform] Drop unused dynamic inventory functions
  contrib/terraform/terraform.py
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/L

#4597 Add overcommitment for CPU in Packet CI playbook
  tests/cloud_playbooks/roles/packet-ci/defaults/main.yml
  tests/cloud_playbooks/roles/packet-ci/templates/vm.yml.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#4583 Unmask Docker service in ClearLinux
  roles/bootstrap-os/tasks/bootstrap-clearlinux.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#4531 Fix calico v3.4.0 scale and upgrade
  roles/network_plugin/calico/handlers/main.yml
  roles/network_plugin/calico/tasks/install.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S

#4602 Avoid creating k8s cert dir on non-k8s nodes
  roles/kubernetes/preinstall/tasks/0050-create_directories.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4572 Optimize kube resources creation
  contrib/metallb/roles/provision/tasks/main.yml
  contrib/network-storage/glusterfs/roles/kubernetes-pv/ansible/tasks/main.yaml
  roles/kubernetes-apps/ansible/tasks/dashboard.yml
  roles/kubernetes-apps/ansible/tasks/main.yml
  roles/kubernetes-apps/ansible/tasks/netchecker.yml
  roles/kubernetes-apps/cluster_roles/tasks/main.yml
  roles/kubernetes-apps/container_engine_accelerator/nvidia_gpu/tasks/main.yml
  roles/kubernetes-apps/external_provisioner/cephfs_provisioner/tasks/main.yml
  roles/kubernetes-apps/external_provisioner/local_path_provisioner/tasks/main.yml
  roles/kubernetes-apps/external_provisioner/local_volume_provisioner/tasks/main.yml
  roles/kubernetes-apps/helm/tasks/main.yml
  roles/kubernetes-apps/ingress_controller/cert_manager/tasks/main.yml
  roles/kubernetes-apps/ingress_controller/ingress_nginx/tasks/main.yml
  roles/kubernetes-apps/metrics_server/tasks/main.yml
  roles/kubernetes-apps/network_plugin/calico/tasks/main.yml
  roles/kubernetes-apps/network_plugin/canal/tasks/main.yml
  roles/kubernetes-apps/network_plugin/cilium/tasks/main.yml
  roles/kubernetes-apps/network_plugin/contiv/tasks/main.yml
  roles/kubernetes-apps/network_plugin/flannel/tasks/main.yml
  roles/kubernetes-apps/network_plugin/multus/tasks/main.yml
  roles/kubernetes-apps/policy_controller/calico/tasks/main.yml
  roles/kubernetes-apps/registry/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/L

#4599 Update ansible.md
  docs/ansible.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#4621 Revert "Optimize kube resources creation (#4572)"
  contrib/metallb/roles/provision/tasks/main.yml
  contrib/network-storage/glusterfs/roles/kubernetes-pv/ansible/tasks/main.yaml
  roles/kubernetes-apps/ansible/tasks/dashboard.yml
  roles/kubernetes-apps/ansible/tasks/main.yml
  roles/kubernetes-apps/ansible/tasks/netchecker.yml
  roles/kubernetes-apps/cluster_roles/tasks/main.yml
  roles/kubernetes-apps/container_engine_accelerator/nvidia_gpu/tasks/main.yml
  roles/kubernetes-apps/external_provisioner/cephfs_provisioner/tasks/main.yml
  roles/kubernetes-apps/external_provisioner/local_path_provisioner/tasks/main.yml
  roles/kubernetes-apps/external_provisioner/local_volume_provisioner/tasks/main.yml
  roles/kubernetes-apps/helm/tasks/main.yml
  roles/kubernetes-apps/ingress_controller/cert_manager/tasks/main.yml
  roles/kubernetes-apps/ingress_controller/ingress_nginx/tasks/main.yml
  roles/kubernetes-apps/metrics_server/tasks/main.yml
  roles/kubernetes-apps/network_plugin/calico/tasks/main.yml
  roles/kubernetes-apps/network_plugin/canal/tasks/main.yml
  roles/kubernetes-apps/network_plugin/cilium/tasks/main.yml
  roles/kubernetes-apps/network_plugin/contiv/tasks/main.yml
  roles/kubernetes-apps/network_plugin/flannel/tasks/main.yml
  roles/kubernetes-apps/network_plugin/multus/tasks/main.yml
  roles/kubernetes-apps/policy_controller/calico/tasks/main.yml
  roles/kubernetes-apps/registry/tasks/main.yml
Labels: cncf-cla: yes, kind/bug, size/L

#4617 disable metrics server and fix terraform
  .gitlab-ci/terraform.yml
  contrib/terraform/packet/kubespray.tf
  contrib/terraform/packet/sample-inventory/cluster.tf
  contrib/terraform/packet/variables.tf
  contrib/terraform/terraform.py
  roles/kubernetes-apps/policy_controller/calico/tasks/main.yml
  tests/files/gce_centos7-flannel-addons.yml
  tests/files/packet_centos7-flannel-addons.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#4604 Move inline shell into script files
  .gitlab-ci.yml
  tests/scripts/testcases_cleanup.sh
  tests/scripts/testcases_prepare.sh
  tests/scripts/testcases_run.sh
  tests/testcases/030_check-network.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/L

#4610 Fix control plane setup without a hardcoded key
  roles/kubernetes/master/tasks/kubeadm-secondary-experimental.yml
  roles/kubernetes/master/tasks/kubeadm-setup.yml
  roles/kubernetes/master/templates/kubeadm-config.v1alpha3.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1beta1.yaml.j2
Labels: approved, cncf-cla: yes, lgtm, size/M

#4612 Update probe timeouts, delays etc.
  contrib/network-storage/heketi/roles/provision/templates/glusterfs-daemonset.json.j2
  contrib/network-storage/heketi/roles/provision/templates/heketi-bootstrap.json.j2
  contrib/network-storage/heketi/roles/provision/templates/heketi-deployment.json.j2
  roles/kubernetes-apps/ansible/templates/coredns-deployment.yml.j2
  roles/kubernetes-apps/ansible/templates/dashboard.yml.j2
  roles/kubernetes-apps/ansible/templates/nodelocaldns-daemonset.yml.j2
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/ds-ingress-nginx-controller.yml.j2
  roles/kubernetes-apps/metrics_server/templates/metrics-server-deployment.yaml.j2
  roles/network_plugin/calico/templates/calico-node.yml.j2
  roles/network_plugin/canal/templates/canal-node.yaml.j2
  roles/network_plugin/cilium/templates/cilium-ds.yml.j2
  roles/network_plugin/kube-router/templates/kube-router.yml.j2
  tests/files/gce_centos7-flannel-addons.yml
  tests/files/packet_centos7-flannel-addons.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/M

#4455 Define and implement specs for bootstrap-os
  cluster.yml
  roles/bootstrap-os/README.md
  roles/bootstrap-os/defaults/main.yml
  roles/bootstrap-os/tasks/bootstrap-centos.yml
  roles/bootstrap-os/tasks/bootstrap-clearlinux.yml
  roles/bootstrap-os/tasks/bootstrap-coreos.yml
  roles/bootstrap-os/tasks/bootstrap-debian.yml
  roles/bootstrap-os/tasks/bootstrap-fedora.yml
  roles/bootstrap-os/tasks/bootstrap-opensuse.yml
  roles/bootstrap-os/tasks/bootstrap-ubuntu.yml
  roles/bootstrap-os/tasks/main.yml
  scale.yml
Labels: approved, cncf-cla: yes, lgtm, size/L

#4623 Merge 020_check and 030_check
  tests/scripts/testcases_run.sh
  tests/testcases/020_check-create-pod.yml
  tests/testcases/030_check-network.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/M

#4619 ansible-lint: Fix commands that are also available as module [E303]
  .ansible-lint
  roles/container-engine/docker/handlers/main.yml
  roles/container-engine/docker/tasks/systemd.yml
  roles/etcd/handlers/main.yml
  roles/etcd/tasks/configure.yml
  roles/kubernetes-apps/helm/tasks/gen_helm_tiller_certs.yml
  roles/kubernetes/master/handlers/main.yml
  roles/kubernetes/node/handlers/main.yml
  roles/kubernetes/preinstall/tasks/0070-system-packages.yml
  roles/network_plugin/calico/rr/handlers/main.yml
  roles/network_plugin/cilium/handlers/main.yml
  roles/network_plugin/flannel/handlers/main.yml
  roles/reset/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/M

#4608 ansible-lint: Don't use bare variables [E104]
  .ansible-lint
  roles/etcd/tasks/check_certs.yml
  roles/kubernetes/preinstall/tasks/0090-etchosts.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#4620 Pin Terraform provider versions
  contrib/terraform/openstack/kubespray.tf
  contrib/terraform/packet/kubespray.tf
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#4624 Update Docker defaults to 18.09.5 and drop deprecated
  roles/container-engine/docker/defaults/main.yml
  roles/container-engine/docker/vars/debian.yml
  roles/container-engine/docker/vars/fedora.yml
  roles/container-engine/docker/vars/redhat.yml
  roles/container-engine/docker/vars/ubuntu-amd64.yml
  roles/container-engine/docker/vars/ubuntu-arm64.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#4450 Purge legacy cleanup tasks from older than 1 year
  roles/container-engine/docker/handlers/main.yml
  roles/etcd/handlers/main.yml
  roles/kubernetes-apps/ansible/tasks/cleanup_dns.yml
  roles/kubernetes-apps/ansible/tasks/dashboard.yml
  roles/kubernetes-apps/ansible/tasks/main.yml
  roles/kubernetes-apps/ansible/tasks/netchecker.yml
  roles/kubernetes-apps/ingress_controller/ingress_nginx/tasks/main.yml
  roles/kubernetes/master/handlers/main.yml
  roles/kubernetes/master/tasks/pre-upgrade.yml
  roles/network_plugin/flannel/tasks/main.yml
  roles/network_plugin/flannel/tasks/pre-upgrade.yml
Labels: approved, cncf-cla: yes, lgtm, size/L

#4616 Always rebase on master before running a job
  .gitlab-ci.yml
  .gitlab-ci/shellcheck.yml
  .gitlab-ci/terraform.yml
  tests/scripts/rebase.sh
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, size/S

#4627 Move on_success test to deploy-part2
  .gitlab-ci/packet.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#4615 Test with minimum requirements
  tests/files/packet_ubuntu18-flannel-aio.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#4481 Update to v1.14.1
  README.md
  inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml
  roles/download/defaults/main.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#4476 support azure loadbalancer standard sku (#4150)
  docs/azure.md
  roles/kubernetes/node/defaults/main.yml
  roles/kubernetes/node/tasks/azure-credential-check.yml
  roles/kubernetes/node/templates/azure-cloud-config.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, sig/azure, size/M

#4628 Switch deploy-part1 AIO job to Calico
  .gitlab-ci/packet.yml
  tests/files/packet_ubuntu18-calico-aio.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#4630 Reduce VM size for Packet CI
  tests/cloud_playbooks/roles/packet-ci/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/cleanup, kind/flake, lgtm, size/XS

#4632 Increase ansible-lint speed
  .gitlab-ci/lint.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#4613 remove duble check for run this task just one time
  roles/etcd/tasks/gen_certs_script.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#4218 Fixing Vagrant cluster provisioning
  Vagrantfile
  roles/download/tasks/sync_container.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#4636 Add missing comma to Vagrantfile
  Vagrantfile
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#4634 Clean up check for setting kubeadm certificate key
  roles/kubernetes/master/tasks/kubeadm-setup.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4618 Add an ability to provide oidc cert in base64
  roles/kubernetes/master/defaults/main/main.yml
  roles/kubernetes/master/tasks/kubeadm-setup.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#4643 Fix python syntax in Terraform dynamic inventory
  contrib/terraform/terraform.py
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#4638 Update downloads role to download to correct group
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#4644 Fix typo in test-infra playbook
  test-infra/image-builder/roles/kubevirt-images/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#4645 Fix dynamic inventory parsing in contrib/tf/packet
  .gitlab-ci/terraform.yml
  contrib/terraform/packet/kubespray.tf
  contrib/terraform/packet/sample-inventory/cluster.tf
  contrib/terraform/packet/variables.tf
  contrib/terraform/terraform.py
Labels: approved, cncf-cla: yes, kind/bug, kind/failing-test, lgtm, size/S

#4648 Prepend docker.io for all docker hub images
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#4650 Fix GCE tests with undefined CI_PLATFORM
  .gitlab-ci/gce.yml
Labels: approved, cncf-cla: yes, kind/bug, kind/failing-test, lgtm, size/XS

#4589 Fix issue with etcd arm host installation case
  roles/etcd/tasks/install_host.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#4498 Add support calico kubernetes datastore and typha.
  inventory/sample/group_vars/k8s-cluster/k8s-net-calico.yml
  roles/download/defaults/main.yml
  roles/kubernetes-apps/network_plugin/calico/tasks/main.yml
  roles/kubespray-defaults/defaults/main.yaml
  roles/network_plugin/calico/defaults/main.yml
  roles/network_plugin/calico/tasks/install.yml
  roles/network_plugin/calico/templates/calico-config.yml.j2
  roles/network_plugin/calico/templates/calico-cr.yml.j2
  roles/network_plugin/calico/templates/calico-node.yml.j2
  roles/network_plugin/calico/templates/calico-typha.yml.j2
  roles/network_plugin/calico/templates/cni-calico.conflist.j2
  roles/network_plugin/calico/templates/kdd-crds.yml.j2
Labels: approved, cncf-cla: yes, lgtm, size/L

#4653 Git checkout a specific version for testing upgrades
  .gitlab-ci.yml
  tests/scripts/testcases_run.sh
Labels: approved, cncf-cla: yes, kind/bug, kind/failing-test, lgtm, size/XS

#4651 Fix broken metrics-server deployment not starting
  roles/download/defaults/main.yml
  roles/kubernetes-apps/metrics_server/templates/metrics-server-deployment.yaml.j2
  tests/files/packet_centos7-flannel-addons.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/M

#4660 Make cilium tests pass
  .gitlab-ci/gce.yml
  .gitlab-ci/packet.yml
  tests/files/gce_centos7-cilium.yml
  tests/files/gce_rhel7-cilium.yml
  tests/files/gce_ubuntu-cilium-sep.yml
  tests/files/gce_ubuntu18-cilium-sep.yml
  tests/files/packet_rhel7-cilium.yml
  tests/files/packet_ubuntu18-cilium-sep.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/M

#4661 Remove RHEL from packet deploy
  .gitlab-ci/packet.yml
  tests/files/packet_rhel7-canal-sep.yml
  tests/files/packet_rhel7-weave.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/M
