Repository kubernetes-sigs/kubespray, pull requests merged in 2019-05, with the labels that each got.

#4666 ansible-lint: Don't use the local_action module [E504]
  .ansible-lint
  tests/cloud_playbooks/create-aws.yml
  tests/cloud_playbooks/create-gce.yml
  tests/cloud_playbooks/delete-aws.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/S

#4420 Enable delegating all downloads (binaries, images, kubeadm images)
  docs/downloads.md
  roles/download/defaults/main.yml
  roles/download/tasks/download_container.yml
  roles/download/tasks/download_file.yml
  roles/download/tasks/kubeadm_images.yml
  roles/download/tasks/main.yml
  roles/download/tasks/set_docker_image_facts.yml
  roles/download/tasks/sync_container.yml
  roles/download/tasks/sync_file.yml
  roles/kubernetes/master/tasks/main.yml
  roles/kubernetes/node/tasks/install.yml
Labels: approved, cncf-cla: yes, lgtm, size/L

#4688 Fix ansible-lint 602
  roles/download/tasks/sync_container.yml
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, priority/critical-urgent, size/XS

#4642 Validate Vagrantfile in CI unit-tests
  .gitlab-ci/lint.yml
Labels: approved, cncf-cla: yes, kind/feature, kind/flake, lgtm, size/XS

#4690 Disable CI deploys on master
  .gitlab-ci/gce.yml
  .gitlab-ci/packet.yml
  .gitlab-ci/terraform.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/M

#4219 Apply etcd_extra_vars to etcd-events.env as well.
  roles/etcd/templates/etcd-events.env.j2
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4654 Move terraform CI to .sh scripts
  .gitlab-ci/terraform.yml
  tests/Makefile
  tests/scripts/create-tf.sh
  tests/scripts/delete-tf.sh
  tests/scripts/terraform_install.sh
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/M

#4669 Add support for http(s)_proxy to CoreOS, Fedora and OpenSUSE
  roles/bootstrap-os/README.md
  roles/bootstrap-os/tasks/bootstrap-coreos.yml
  roles/bootstrap-os/tasks/bootstrap-fedora.yml
  roles/bootstrap-os/tasks/bootstrap-opensuse.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/M

#4691 Update ingress nginx 0.24.1.
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4702 Fixing `msg` parameter for `debug` module
  roles/kubernetes/kubeadm/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4708 Removing unnecessary httplib2 install
  roles/kubernetes/preinstall/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#4696 Fix adding output of kubeadm to the admin.conf downloaded to the artifacts directory
  roles/kubernetes/client/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#4713 Add kube anon auth settings to kubeadm config templates
  roles/kubernetes/master/templates/kubeadm-config.v1alpha3.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1beta1.yaml.j2
  tests/testcases/030_check-network.yml
Labels: approved, cncf-cla: yes, kind/api-change, kind/cleanup, lgtm, size/XS

#4719 Minor cleanups of CoreDNS issues and CI job
  docs/dns-stack.md
  inventory/sample/group_vars/k8s-cluster/addons.yml
  roles/kubernetes-apps/ansible/tasks/cleanup_dns.yml
  roles/kubernetes-apps/rotate_tokens/tasks/main.yml
  tests/files/packet_centos7-flannel-addons.yml
Labels: approved, cncf-cla: yes, kind/bug, kind/cleanup, kind/failing-test, lgtm, size/S

#4724 Add Kubelet config, remove deprecated flags and fix minor bugs
  roles/kubernetes/client/tasks/main.yml
  roles/kubernetes/kubeadm/templates/kubeadm-client.conf.v1beta1.j2
  roles/kubernetes/node/tasks/cloud-credentials/azure-credential-check.yml
  roles/kubernetes/node/tasks/cloud-credentials/openstack-credential-check.yml
  roles/kubernetes/node/tasks/cloud-credentials/vsphere-credential-check.yml
  roles/kubernetes/node/tasks/install.yml
  roles/kubernetes/node/tasks/kubelet.yml
  roles/kubernetes/node/tasks/loadbalancer/haproxy.yml
  roles/kubernetes/node/tasks/loadbalancer/nginx-proxy.yml
  roles/kubernetes/node/tasks/main.yml
  roles/kubernetes/node/templates/cloud-configs/aws-cloud-config.j2
  roles/kubernetes/node/templates/cloud-configs/azure-cloud-config.j2
  roles/kubernetes/node/templates/cloud-configs/openstack-cloud-config.j2
  roles/kubernetes/node/templates/cloud-configs/vsphere-cloud-config.j2
  roles/kubernetes/node/templates/kubelet-config.v1beta1.yaml.j2
  roles/kubernetes/node/templates/kubelet.env.j2
  roles/kubernetes/node/templates/kubelet.env.v1beta1.j2
  roles/kubernetes/node/templates/kubelet.service.j2
  roles/kubernetes/node/templates/loadbalancer/haproxy.cfg.j2
  roles/kubernetes/node/templates/loadbalancer/nginx.conf.j2
  roles/kubernetes/node/templates/node-kubeconfig.yaml.j2
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, kind/design, kind/feature, lgtm, size/L

#4720 Update default CentOS version on Azure
  contrib/azurerm/roles/generate-templates/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#4722 Always do OVH CI
  .gitlab-ci/terraform.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#4723 Run TF tests from repo root
  .gitlab-ci/terraform.yml
  tests/scripts/create-tf.sh
  tests/scripts/delete-tf.sh
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/S

#4731 Fixed runc path in runtime for RedHat os family
  roles/container-engine/cri-o/templates/crio.conf.j2
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#4730 Fix "netchecker-server" ClusterRole
  roles/kubernetes-apps/ansible/templates/netchecker-server-clusterrole.yml.j2
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4321 Terraform wait for floating IP instance has been associated
  contrib/terraform/openstack/README.md
  contrib/terraform/openstack/kubespray.tf
  contrib/terraform/openstack/modules/compute/main.tf
  contrib/terraform/openstack/modules/compute/variables.tf
  contrib/terraform/openstack/variables.tf
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/M

#4734 Use common playbook to wait for SSH
  .gitlab-ci/terraform.yml
  tests/cloud_playbooks/create-aws.yml
  tests/cloud_playbooks/create-do.yml
  tests/cloud_playbooks/create-gce.yml
  tests/cloud_playbooks/roles/packet-ci/tasks/create-vms.yml
  tests/cloud_playbooks/wait-for-ssh.yml
  tests/scripts/testcases_run.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#4732 Use standard testcases job for TF CI
  .gitlab-ci/terraform.yml
  tests/files/tf-ovh_ubuntu18-calico.yml
  tests/testcases/010_check-apiserver.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/S

#4735 Only pull images for destined host groups
  roles/download/tasks/set_docker_image_facts.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#4743 Fix Ansible-lint error [E502]
  .ansible-lint
  contrib/azurerm/roles/generate-inventory/tasks/main.yml
  contrib/azurerm/roles/generate-inventory_2/tasks/main.yml
  contrib/azurerm/roles/generate-templates/tasks/main.yml
  contrib/network-storage/heketi/roles/provision/tasks/bootstrap.yml
  contrib/network-storage/heketi/roles/provision/tasks/glusterfs/label.yml
  contrib/network-storage/heketi/roles/provision/tasks/heketi.yml
  contrib/network-storage/heketi/roles/provision/tasks/secret.yml
  roles/bastion-ssh-config/tasks/main.yml
  roles/container-engine/docker/tasks/main.yml
  roles/download/tasks/kubeadm_images.yml
  roles/download/tasks/main.yml
  roles/download/tasks/set_docker_image_facts.yml
  roles/download/tasks/sync_container.yml
  roles/etcd/tasks/gen_certs_script.yml
  roles/etcd/tasks/main.yml
  roles/kubernetes-apps/helm/tasks/gen_helm_tiller_certs.yml
  roles/kubernetes-apps/network_plugin/contiv/tasks/configure.yml
  roles/kubernetes/node/tasks/facts.yml
  roles/kubernetes/preinstall/tasks/0040-set_facts.yml
  roles/network_plugin/contiv/tasks/main.yml
  roles/upgrade/pre-upgrade/tasks/main.yml
  scripts/collect-info.yaml
  tests/cloud_playbooks/create-do.yml
  tests/cloud_playbooks/create-gce.yml
  tests/cloud_playbooks/delete-gce.yml
  tests/cloud_playbooks/upload-logs-gcs.yml
  tests/testcases/015_check-pods-running.yml
  tests/testcases/030_check-network.yml
  tests/testcases/040_check-network-adv.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/L

#4775 Add Load Balancer IP to API servers SANs
  roles/kubernetes/master/tasks/kubeadm-setup.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#4753 Fix invalid YAML formatting within addons.yml
  inventory/sample/group_vars/k8s-cluster/addons.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#4752 Change default for kubelet_flexvolumes_plugins_dir
  roles/kubernetes/node/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/api-change, kind/cleanup, lgtm, size/XS

#4764 var node_labels as string
  docs/vars.md
  roles/kubernetes/node/templates/kubelet.env.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#4782 upgrade to 1.14.2
  README.md
  inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml
  roles/download/defaults/main.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#4783 updated pinning to prevent breaking changes
  requirements.txt
  tests/requirements.txt
Labels: approved, cncf-cla: yes, lgtm, size/S

#4744 Ignore 2 ansible-lint rules (E204, E701) on purpose.
  .ansible-lint
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/S

#4779 Add ignore_assert_errors to "kube-master, ...
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#4785 Error in nginx when starting registry-proxy
  roles/kubernetes-apps/registry/templates/registry-proxy-psp.yml.j2
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S

#4756 cordon all deleted nodes before drain
  roles/remove-node/pre-remove/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#4385 Added pod psp in Rancher Local Path Provisioner
  roles/kubernetes-apps/external_provisioner/local_path_provisioner/tasks/main.yml
  roles/kubernetes-apps/external_provisioner/local_path_provisioner/templates/local-path-storage-clusterrolebinding.yml.j2
  roles/kubernetes-apps/external_provisioner/local_path_provisioner/templates/local-path-storage-cm.yml.j2
  roles/kubernetes-apps/external_provisioner/local_path_provisioner/templates/local-path-storage-cr.yml.j2
  roles/kubernetes-apps/external_provisioner/local_path_provisioner/templates/local-path-storage-deployment.yml.j2
  roles/kubernetes-apps/external_provisioner/local_path_provisioner/templates/local-path-storage-ns.yml.j2
  roles/kubernetes-apps/external_provisioner/local_path_provisioner/templates/local-path-storage-psp-cr.yml.j2
  roles/kubernetes-apps/external_provisioner/local_path_provisioner/templates/local-path-storage-psp-rb.yml.j2
  roles/kubernetes-apps/external_provisioner/local_path_provisioner/templates/local-path-storage-psp.yml.j2
  roles/kubernetes-apps/external_provisioner/local_path_provisioner/templates/local-path-storage-sa.yml.j2
  roles/kubernetes-apps/external_provisioner/local_path_provisioner/templates/local-path-storage-sc.yml.j2
  roles/kubernetes-apps/external_provisioner/local_path_provisioner/templates/local-path-storage.yaml.j2
Labels: approved, cncf-cla: yes, lgtm, size/L

#4789 Fix certificate-key param for kubeadm init
  roles/kubernetes/master/tasks/kubeadm-setup.yml
Labels: approved, cncf-cla: yes, kind/bug, kind/cleanup, lgtm, size/XS

#4795 Fix group_vars/openstack.yml comment styling
  inventory/sample/group_vars/all/openstack.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#4798 kubeadm join path fixed for RH / CentOS linux
  roles/kubernetes/kubeadm/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#4614 K8s conformance
  tests/files/tf-ovh_ubuntu18-calico.yml
  tests/scripts/testcases_run.sh
  tests/testcases/100_check-k8s-conformance.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/M

#4807 Change CentOS CRI-O repo from developer repo to public one
  roles/container-engine/cri-o/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#4763 Add tf-ovh_coreos CI job
  .gitlab-ci/terraform.yml
  roles/kubernetes/kubeadm/tasks/main.yml
  tests/files/tf-ovh_coreos-calico.yml
  tests/scripts/testcases_run.sh
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/M

#4811 Update roadmap
  docs/roadmap.md
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/S

#4814 Add missing extraArgs to kubeadm-config
  roles/kubernetes/master/templates/kubeadm-config.v1alpha3.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1beta1.yaml.j2
Labels: approved, cncf-cla: yes, kind/bug, kind/cleanup, lgtm, size/S

#4817 Add ready plugin for CoreDNS
  roles/kubernetes-apps/ansible/templates/coredns-config.yml.j2
  roles/kubernetes-apps/ansible/templates/coredns-deployment.yml.j2
Labels: approved, cncf-cla: yes, kind/cleanup, kind/design, lgtm, size/XS

#4034 README: Make usage section clearer
  README.md
Labels: approved, cncf-cla: yes, lgtm, lifecycle/stale, size/XS
