Repository kubernetes-sigs/kubespray, pull requests merged in 2019-07, with the labels that each got.

#4938 Add nginx stub metrics if health check enabled
  roles/kubernetes/node/templates/loadbalancer/nginx.conf.j2
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4905 Use K8s 1.15
  README.md
  inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml
  roles/download/defaults/main.yml
  roles/download/templates/kubeadm-images.yaml.j2
  roles/kubernetes-apps/cluster_roles/tasks/main.yml
  roles/kubernetes/kubeadm/tasks/main.yml
  roles/kubernetes/master/defaults/main/main.yml
  roles/kubernetes/master/tasks/kubeadm-secondary-experimental.yml
  roles/kubernetes/master/tasks/kubeadm-setup.yml
  roles/kubernetes/master/tasks/kubeadm-version.yml
  roles/kubernetes/master/templates/kubeadm-config.v1alpha2.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1alpha3.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1beta2.yaml.j2
  roles/kubernetes/master/templates/kubeadm-controlplane.v1beta2.yaml.j2
  roles/kubernetes/node/defaults/main.yml
  roles/kubernetes/node/tasks/kubelet.yml
  roles/kubernetes/node/templates/kubelet.env.j2
  roles/kubernetes/node/templates/kubelet.env.v1beta1.j2
  roles/kubespray-defaults/defaults/main.yaml
  tests/testcases/100_check-k8s-conformance.yml
Labels: approved, cncf-cla: yes, lgtm, size/XL

#4933 Adding "-F /dev/null" to load null SSH config file.
  roles/bastion-ssh-config/templates/ssh-bastion.conf
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4910 Additional uppercase proxy env variables
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#4946 Use kubespray-defaults in remove-node role
  remove-node.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#4922 fix for calico with kdd datastore
  roles/network_plugin/calico/tasks/check.yml
  roles/network_plugin/calico/tasks/install.yml
  roles/network_plugin/calico/templates/calico-node.yml.j2
  roles/network_plugin/calico/templates/calicoctl.etcd.sh.j2
  roles/network_plugin/calico/templates/calicoctl.kdd.sh.j2
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/M

#4925 bump rpm based docker versions to docker-ce-18.06.3.ce-3
  roles/container-engine/docker/vars/fedora.yml
  roles/container-engine/docker/vars/redhat.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#4940 Fix order of names in /etc/hosts
  roles/kubernetes/preinstall/tasks/0090-etchosts.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#4934 Add support for Docker plugins
  docs/vars.md
  roles/container-engine/docker/tasks/docker_plugin.yml
  roles/container-engine/docker/tasks/main.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#4902 nodelocaldns: allow to set health port
  inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml
  roles/kubernetes-apps/ansible/templates/nodelocaldns-config.yml.j2
  roles/kubernetes-apps/ansible/templates/nodelocaldns-daemonset.yml.j2
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#4952 Fixup deploy of kubeadm etcd for Kubernetes v1.15.0
  roles/kubernetes/kubeadm/defaults/main.yml
  roles/kubernetes/kubeadm/tasks/main.yml
  roles/kubernetes/kubeadm/templates/kubeadm-client.conf.v1beta1.j2
  roles/kubernetes/master/tasks/kubeadm-setup.yml
  roles/kubernetes/master/tasks/kubeadm-upgrade.yml
  roles/kubernetes/master/templates/kubeadm-config.v1beta1.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1beta2.yaml.j2
  roles/kubernetes/preinstall/tasks/0070-system-packages.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#4957 Default kubeadm_images to empty dict instead of set_fact
  roles/download/defaults/main.yml
  roles/download/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#4953 Add calico 3.7.3 support
  roles/download/defaults/main.yml
  roles/kubernetes-apps/policy_controller/calico/defaults/main.yml
  roles/kubernetes-apps/policy_controller/calico/templates/calico-kube-controllers.yml.j2
  roles/kubernetes-apps/policy_controller/calico/templates/calico-kube-cr.yml.j2
  roles/kubernetes-apps/policy_controller/meta/main.yml
  roles/network_plugin/calico/templates/calico-cr.yml.j2
  roles/network_plugin/calico/templates/calico-node.yml.j2
  roles/network_plugin/calico/templates/calico-typha.yml.j2
  roles/network_plugin/calico/templates/cni-calico.conflist.j2
  roles/network_plugin/calico/templates/kdd-crds.yml.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/L

#4936 docfix: azure.md azure cli parameter update
  docs/azure.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#4951 Enable containerd to deploy vanilla containerd package
  roles/container-engine/containerd/defaults/main.yml
  roles/container-engine/containerd/handlers/main.yml
  roles/container-engine/containerd/tasks/containerd_repo.yml
  roles/container-engine/containerd/tasks/crictl.yml
  roles/container-engine/containerd/tasks/main.yml
  roles/container-engine/containerd/templates/apt_preferences.d/debian_containerd.j2
  roles/container-engine/containerd/templates/config.toml.j2
  roles/container-engine/containerd/templates/rh_containerd.repo.j2
  roles/container-engine/containerd/vars/redhat.yml
  roles/container-engine/containerd/vars/suse.yml
  roles/container-engine/containerd/vars/ubuntu-amd64.yml
  roles/container-engine/meta/main.yml
  roles/download/tasks/check_pull_required.yml
  roles/download/tasks/download_container.yml
  roles/download/tasks/main.yml
  roles/download/tasks/prep_download.yml
  roles/download/templates/kubeadm-images.yaml.j2
  roles/kubernetes-apps/helm/tasks/install_host.yml
  roles/kubernetes/client/tasks/main.yml
  roles/kubernetes/master/templates/kubeadm-config.v1beta2.yaml.j2
  roles/kubernetes/master/templates/kubeadm-controlplane.v1beta2.yaml.j2
  tests/files/gce_centos7-flannel-addons.yml
  tests/files/packet_centos7-flannel-addons.yml
  tests/files/packet_opensuse-canal.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/L

#4964 Generate certificate key before kubeadm control plane config
  roles/kubernetes/master/tasks/kubeadm-secondary-experimental.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#3655 Add support for Oracle Linux
  .gitlab-ci/gce.yml
  .gitlab-ci/packet.yml
  README.md
  Vagrantfile
  roles/bootstrap-os/tasks/bootstrap-oracle.yml
  roles/bootstrap-os/tasks/main.yml
  roles/container-engine/cri-o/tasks/main.yaml
  roles/container-engine/docker/tasks/main.yml
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
  roles/kubernetes/preinstall/tasks/main.yml
  test-infra/image-builder/roles/kubevirt-images/defaults/main.yml
  tests/cloud_playbooks/roles/packet-ci/defaults/main.yml
  tests/files/gce_oracle-canal.yml
  tests/files/packet_oracle-7-canal.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#4959 Add checksums for k8s 1.14.4
  Dockerfile
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4965 Use crictl to get images info
  roles/download/tasks/download_prep.yml
  roles/download/tasks/prep_download.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/M

#4966 Update supported calico version in README.md
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#4973 Update docker-ce to 18.09.7
  roles/container-engine/docker/vars/debian.yml
  roles/container-engine/docker/vars/fedora.yml
  roles/container-engine/docker/vars/redhat.yml
  roles/container-engine/docker/vars/ubuntu-amd64.yml
  roles/container-engine/docker/vars/ubuntu-arm64.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#4971 fix parsing refresh of kubeadm cert key
  roles/kubernetes/master/tasks/kubeadm-secondary-experimental.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4969 Update Weave CNI to 2.5.2
  README.md
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#4970 Update CoreDNS to 1.5.2
  README.md
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#4908 Ansible 2.8.x note
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#4892 azure loadbalancer vars generation
  contrib/azurerm/roles/generate-inventory_2/tasks/main.yml
  contrib/azurerm/roles/generate-inventory_2/templates/loadbalancer_vars.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#4956 Enable nodes to run calicoctl for calico kdd mode
  roles/kubernetes-apps/network_plugin/calico/tasks/main.yml
  roles/network_plugin/calico/tasks/install.yml
  roles/network_plugin/calico/tasks/main.yml
  roles/network_plugin/calico/templates/calicoctl.kdd.sh.j2
Labels: approved, cncf-cla: yes, lgtm, size/L

#4977 prep_kubeadm_images: parse repo and tag (#4976)
  roles/download/tasks/prep_kubeadm_images.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#4974 remove support for calico v2.x
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
  roles/network_plugin/calico/rr/tasks/main.yml
  roles/network_plugin/calico/tasks/install.yml
  roles/network_plugin/calico/tasks/pre.yml
  roles/network_plugin/calico/templates/calico-node.yml.j2
  roles/network_plugin/canal/templates/canal-node.yaml.j2
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, needs-ci-auth, size/L

#4978 Let Premoderator script add labels
  scripts/premoderator.sh
Labels: approved, cncf-cla: yes, kind/api-change, lgtm, size/M

#4704 Add k8s_external plugin to CoreDNS configuration
  docs/vars.md
  inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml
  roles/kubernetes-apps/ansible/templates/coredns-config.yml.j2
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#4981 Remove code related to kube version < 1.14
  roles/download/tasks/main.yml
  roles/kubernetes-apps/ansible/templates/dashboard.yml.j2
  roles/kubernetes-apps/ansible/templates/dns-autoscaler.yml.j2
  roles/kubernetes-apps/ansible/templates/netchecker-agent-ds.yml.j2
  roles/kubernetes-apps/ansible/templates/netchecker-agent-hostnet-ds.yml.j2
  roles/kubernetes-apps/ansible/templates/netchecker-server-deployment.yml.j2
  roles/kubernetes-apps/ansible/templates/nodelocaldns-daemonset.yml.j2
  roles/kubernetes-apps/cluster_roles/tasks/main.yml
  roles/kubernetes-apps/cluster_roles/templates/psp.yml.j2
  roles/kubernetes-apps/external_provisioner/cephfs_provisioner/templates/deploy-cephfs-provisioner.yml.j2
  roles/kubernetes-apps/external_provisioner/local_volume_provisioner/templates/local-volume-provisioner-ds.yml.j2
  roles/kubernetes-apps/external_provisioner/rbd_provisioner/templates/deploy-rbd-provisioner.yml.j2
  roles/kubernetes-apps/helm/tasks/main.yml
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/deploy-cert-manager.yml.j2
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/ds-ingress-nginx-controller.yml.j2
  roles/kubernetes-apps/metrics_server/templates/metrics-server-deployment.yaml.j2
  roles/kubernetes-apps/policy_controller/calico/templates/calico-kube-controllers.yml.j2
  roles/kubernetes-apps/registry/templates/registry-proxy-ds.yml.j2
  roles/kubernetes-apps/registry/templates/registry-rs.yml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1beta1.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1beta2.yaml.j2
  roles/kubernetes/node/templates/cloud-configs/aws-cloud-config.j2
  roles/kubernetes/node/templates/cloud-configs/vsphere-cloud-config.j2
  roles/kubernetes/node/templates/manifests/haproxy.manifest.j2
  roles/kubernetes/node/templates/manifests/nginx-proxy.manifest.j2
  roles/network_plugin/cilium/templates/cilium-ds.yml.j2
  roles/network_plugin/contiv/templates/contiv-api-proxy.yml.j2
  roles/network_plugin/contiv/templates/contiv-cleanup.yml.j2
  roles/network_plugin/contiv/templates/contiv-etcd-proxy.yml.j2
  roles/network_plugin/contiv/templates/contiv-etcd.yml.j2
  roles/network_plugin/contiv/templates/contiv-netmaster.yml.j2
  roles/network_plugin/contiv/templates/contiv-netplugin.yml.j2
  roles/network_plugin/contiv/templates/contiv-ovs.yml.j2
  roles/network_plugin/flannel/templates/cni-flannel.yml.j2
  roles/network_plugin/kube-router/templates/kube-router.yml.j2
  roles/network_plugin/weave/templates/weave-net.yml.j2
Labels: approved, cncf-cla: yes, lgtm, size/L

#4972 Check all apt config files for configured proxies
  roles/bootstrap-os/tasks/bootstrap-debian.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#4311 use the locally deployed kubectl binary within the kubectl.sh helper …
  roles/kubernetes/client/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4983 Upgrade local volume provisioner to v2.3.2
  inventory/sample/group_vars/k8s-cluster/addons.yml
  roles/download/defaults/main.yml
  roles/kubernetes-apps/external_provisioner/local_volume_provisioner/README.md
  roles/kubernetes-apps/external_provisioner/local_volume_provisioner/defaults/main.yml
  roles/kubernetes-apps/external_provisioner/local_volume_provisioner/tasks/main.yml
  roles/kubernetes-apps/external_provisioner/local_volume_provisioner/templates/local-volume-provisioner-clusterrole.yml.j2
  roles/kubernetes-apps/external_provisioner/local_volume_provisioner/templates/local-volume-provisioner-clusterrolebinding.yml.j2
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/M

#4985 Fix calico handler for containerd
  roles/network_plugin/calico/handlers/main.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S

#4987 [backport] kubeadm join path fixed for RH linux
  roles/kubernetes/kubeadm/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#4988 [backport] Fix certificate-key param for kubeadm init (#4789)
  roles/kubernetes/master/tasks/kubeadm-setup.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#4991 Fixup etcdctl download for etcd kubeadm mode
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4912 configure docker_options directly with template
  roles/container-engine/docker/templates/docker-options.conf.j2
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, kind/design, lgtm, size/M

#4984 Remove unused handlers from Flannel CNI
  roles/network_plugin/flannel/handlers/main.yml
Labels: approved, cncf-cla: yes, kind/bug, kind/cleanup, lgtm, size/M

#4989 update to kubernetes 1.15.1
  README.md
  inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml
  roles/download/defaults/main.yml
  roles/kubespray-defaults/defaults/main.yaml
  tests/testcases/015_check-pods-running.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#4990 add ansible_hostname and ansible_fqdn to apiserver_sans
  roles/kubernetes/master/tasks/kubeadm-setup.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4992 Restart canal after scale or upgrade. Just like PR#4531, but for canal
  roles/network_plugin/canal/handlers/main.yml
  roles/network_plugin/canal/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5003 Update calico-typha deployment to address v3.7.x changes
  roles/network_plugin/calico/templates/calico-typha.yml.j2
Labels: approved, cncf-cla: yes, lgtm, size/S

#5002 fix broken ubuntu containerd engine
  roles/container-engine/containerd/tasks/main.yml
  roles/container-engine/containerd/vars/ubuntu-amd64.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#4999 move flexvolume plugin directory creation to preinstall
  inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml
  roles/kubernetes/node/defaults/main.yml
  roles/kubernetes/node/templates/kubelet.service.j2
  roles/kubernetes/preinstall/defaults/main.yml
  roles/kubernetes/preinstall/tasks/0040-set_facts.yml
  roles/kubernetes/preinstall/tasks/0050-create_directories.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/S

#5000 Additional files and dirs to remove when running reset
  roles/reset/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#5016 Update critools to v1.15.0
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5021 Update CoreDNS to 1.6.0
  README.md
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#5023 fix broken link in documentation
  roles/kubernetes-apps/registry/README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#5020 add Kube-OVN cni to kubespray
  .gitlab-ci/packet.yml
  README.md
  docs/kube-ovn.md
  roles/download/defaults/main.yml
  roles/kubernetes-apps/network_plugin/kube-ovn/tasks/main.yml
  roles/kubernetes-apps/network_plugin/meta/main.yml
  roles/kubernetes/node/templates/kubelet.env.v1beta1.j2
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
  roles/kubernetes/preinstall/tasks/0050-create_directories.yml
  roles/network_plugin/kube-ovn/OWNERS
  roles/network_plugin/kube-ovn/defaults/main.yml
  roles/network_plugin/kube-ovn/tasks/main.yml
  roles/network_plugin/kube-ovn/templates/cni-kube-ovn-crd.yml.j2
  roles/network_plugin/kube-ovn/templates/cni-kube-ovn.yml.j2
  roles/network_plugin/kube-ovn/templates/cni-ovn.yml.j2
  roles/network_plugin/meta/main.yml
  tests/files/packet_centos7-kube-ovn.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XL

#5004 Add packet_ubuntu18-flannel-containerd
  .gitlab-ci/packet.yml
  tests/files/packet_ubuntu18-flannel-containerd.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/M

#5007 Add an option to reserve resources for OS system daemons
  inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml
  roles/kubernetes/node/templates/kubelet-config.v1beta1.yaml.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#5012 Add CoreDNS kubernetes endpoint_pod_names option
  docs/vars.md
  inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml
  roles/kubernetes-apps/ansible/templates/coredns-config.yml.j2
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S
