Repository kubernetes-sigs/kubespray, pull requests merged in 2019-02, with the labels that each got.

#4161 Fixing an issue when trying to install docker-ce-18.09 on rhel7 nodes
  roles/container-engine/docker/defaults/main.yml
  roles/container-engine/docker/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#4153 fix(vagrant): sets ansible.inventory_path to file not dir
  Vagrantfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4054 Add Setting Multi into group_vars
  inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4149 Add timeout to Get current version of calico cluster version
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
  roles/network_plugin/calico/tasks/check.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4145 fix kubeadm-setup when enable access_ip
  roles/kubernetes/master/tasks/kubeadm-setup.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3904 Install the latest filesystem creation packages
  roles/kubernetes/preinstall/defaults/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4173 [Calico] Define FELIX_KUBENODEPORTRANGES when kube-proxy in ipvs mode
  roles/network_plugin/calico/templates/calico-node.yml.j2
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4157 Refactor collect-info.yaml playbook
  scripts/collect-info.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#4164 Fix newline issue of priorityClassName when enable ingress_nginx_tolerations
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/ds-ingress-nginx-controller.yml.j2
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4182 add to inventory.py script ability to indicate ip ranges
  contrib/inventory_builder/inventory.py
  contrib/inventory_builder/tests/test_inventory.py
Labels: cncf-cla: yes, lgtm, size/M

#4192 update k8s to 1.13.3
  README.md
  inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml
  roles/download/defaults/main.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#4185 Fix kube_hostname_override inconsistencies
  inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml
  roles/kubernetes/kubeadm/defaults/main.yml
  roles/kubernetes/kubeadm/templates/kubeadm-client.conf.v1alpha2.j2
  roles/kubernetes/kubeadm/templates/kubeadm-client.conf.v1alpha3.j2
  roles/kubernetes/kubeadm/templates/kubeadm-client.conf.v1beta1.j2
  roles/kubernetes/master/templates/kubeadm-config.v1alpha3.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1beta1.yaml.j2
  roles/kubespray-defaults/defaults/main.yaml
  roles/win_nodes/kubernetes_patch/files/hostnameOverride-patch.json
  roles/win_nodes/kubernetes_patch/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#4190 Update flannel version to v0.11.0 (#4183)
  README.md
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4193 Publish docs with docsify
  .nojekyll
  docs/_sidebar.md
  index.html
Labels: approved, cncf-cla: yes, lgtm, size/M

#4195 [contrib/metallb] Fix MetaLB library
  contrib/metallb/library
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4198 [docs] Update docs/roadmap.md
  docs/roadmap.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#3900 Tell Git to ignore the inventory/mycluster directory
  .gitignore
Labels: approved, cncf-cla: yes, lgtm, lifecycle/stale, size/S

#4176 Add checksums for arm64 images for hyperkube, kubeadm and cni_binary
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/L

#3974 Remove Ubuntu Bionic specific vars file - breaks multi-arch
  roles/container-engine/docker/vars/ubuntu-bionic.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#4203 fix error with delete host in inventory.py script
  contrib/inventory_builder/inventory.py
Labels: cncf-cla: yes, lgtm, size/XS

#4186 OCI Cloud Provider Update
  inventory/sample/group_vars/all/oci.yml
  roles/kubernetes-apps/cloud_controller/oci/defaults/main.yml
  roles/kubernetes-apps/cloud_controller/oci/tasks/credentials-check.yml
  roles/kubernetes-apps/cloud_controller/oci/tasks/main.yml
  roles/kubernetes-apps/cloud_controller/oci/templates/cloud-provider.yml.j2
  roles/kubernetes-apps/cloud_controller/oci/templates/controller-manager-config.yml.j2
  roles/kubernetes-apps/cloud_controller/oci/templates/oci-cloud-provider.yml.j2
  roles/kubernetes-apps/cluster_roles/defaults/main.yml
  roles/kubernetes-apps/cluster_roles/files/oci-rbac.yml
  roles/kubernetes-apps/cluster_roles/tasks/oci.yml
Labels: approved, cncf-cla: yes, lgtm, size/L

#4213 Adding centos 7 extras repo if it is missing
  roles/bootstrap-os/defaults/main.yml
  roles/bootstrap-os/tasks/bootstrap-centos.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#3949 kubespray: fix missing ca-certificate path in apiserver
  roles/kubernetes/master/templates/kubeadm-config.v1alpha1.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1alpha2.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1alpha3.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1beta1.yaml.j2
Labels: approved, cncf-cla: yes, lgtm, size/M

#4045 bootstrap: rework role
  roles/bootstrap-os/tasks/bootstrap-centos.yml
  roles/bootstrap-os/tasks/bootstrap-clearlinux.yml
  roles/bootstrap-os/tasks/bootstrap-coreos.yml
  roles/bootstrap-os/tasks/bootstrap-debian.yml
  roles/bootstrap-os/tasks/bootstrap-fedora.yml
  roles/bootstrap-os/tasks/bootstrap-opensuse.yml
  roles/bootstrap-os/tasks/bootstrap-ubuntu.yml
  roles/bootstrap-os/tasks/main.yml
  roles/bootstrap-os/tasks/setup-pipelining.yml
Labels: approved, cncf-cla: yes, lgtm, size/L

#4135 [contrib/terraform/openstack] Update the admin cert paths
  contrib/terraform/openstack/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#4188 check kube_pods_subnet and kube_service_addresses to valid ip network range
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4191 change permission /opt/cni/bin after unarchive
  roles/network_plugin/calico/tasks/install.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#4202 Add an option for helm init --wait
  roles/kubernetes-apps/helm/defaults/main.yml
  roles/kubernetes-apps/helm/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4210 Fix the file path for all.yml and k8s-cluster.yml
  contrib/terraform/openstack/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4206 Improve kubeadm join tasks
  roles/kubernetes/kubeadm/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#4225 Repository proxy fix
  roles/bootstrap-os/tasks/bootstrap-centos.yml
  roles/container-engine/docker/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm

#4223 [SECURITY] Docker patches for CVE-2019-5736
  roles/container-engine/docker/vars/debian.yml
  roles/container-engine/docker/vars/fedora.yml
  roles/container-engine/docker/vars/redhat.yml
  roles/container-engine/docker/vars/ubuntu-amd64.yml
  roles/container-engine/docker/vars/ubuntu-arm64.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#4063 Explicitely set etcd endpoint in kubeadm-images.yaml
  roles/download/templates/kubeadm-images.yaml.j2
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4235 Fix calico when kube_override_hostname is set
  roles/network_plugin/calico/defaults/main.yml
  roles/network_plugin/calico/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4234 backport cve-2019-5736 to release-2.8
  roles/container-engine/docker/vars/debian.yml
  roles/container-engine/docker/vars/fedora.yml
  roles/container-engine/docker/vars/redhat.yml
  roles/container-engine/docker/vars/ubuntu-amd64.yml
  roles/container-engine/docker/vars/ubuntu-arm64.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#4216 use swapon -s
  roles/kubernetes/preinstall/tasks/0010-swapoff.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4229 Allow customizing container image path used in NVIDIA GPU addon.
  inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml
  roles/kubernetes-apps/container_engine_accelerator/nvidia_gpu/defaults/main.yml
  roles/kubernetes-apps/container_engine_accelerator/nvidia_gpu/templates/k8s-device-plugin-nvidia-daemonset.yml.j2
  roles/kubernetes-apps/container_engine_accelerator/nvidia_gpu/templates/nvidia-driver-install-daemonset.yml.j2
  roles/kubernetes-apps/container_engine_accelerator/nvidia_gpu/vars/centos-7.yml
  roles/kubernetes-apps/container_engine_accelerator/nvidia_gpu/vars/ubuntu-16.yml
  roles/kubernetes-apps/container_engine_accelerator/nvidia_gpu/vars/ubuntu-18.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#4209 Use git tag when checking out for test upgrade
  .gitlab-ci.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4236 Fix typo with docker-ce package versions
  roles/container-engine/docker/vars/debian.yml
  roles/container-engine/docker/vars/ubuntu-amd64.yml
  roles/container-engine/docker/vars/ubuntu-arm64.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4246 Docker 18.09 apt repo name fix (again)
  roles/container-engine/docker/vars/debian.yml
  roles/container-engine/docker/vars/ubuntu-amd64.yml
  roles/container-engine/docker/vars/ubuntu-arm64.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#4247 Add image tag in "pause" container of nvidia driver installer.
  roles/kubernetes-apps/container_engine_accelerator/nvidia_gpu/templates/nvidia-driver-install-daemonset.yml.j2
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4242 Run 'terraform fmt' in contrib/terraform/openstack
  contrib/terraform/openstack/modules/compute/main.tf
  contrib/terraform/openstack/modules/network/outputs.tf
  contrib/terraform/openstack/sample-inventory/cluster.tf
  contrib/terraform/openstack/variables.tf
Labels: approved, cncf-cla: yes, lgtm, size/L

#4184 Updated OWNERS file pointing to docs
  OWNERS
  test-infra/image-builder/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4267 backport cve-2019-5736 for Ubuntu Bionic to release-2.8
  roles/container-engine/docker/vars/ubuntu-bionic.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4243 Fix typo in task description
  roles/container-engine/docker/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4255 Adding ability to maintain existing Encryption Secrets at Rest.
  roles/kubernetes/master/defaults/main/main.yml
  roles/kubernetes/master/tasks/encrypt-at-rest.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#4027 Add update server field in kube-proxy kubeconfig
  inventory/sample/group_vars/all/all.yml
  roles/kubernetes/kubeadm/tasks/main.yml
Labels: approved, cncf-cla: yes, size/M

#4276 fix node join error because of etc-kubernetes-manifests not empty
  roles/kubernetes/kubeadm/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4263 fix wrong indent in kubeadm-config.v1beta1.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1beta1.yaml.j2
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4265 Add support for --enable-skip-login in Dashboard
  roles/kubernetes-apps/ansible/defaults/main.yml
  roles/kubernetes-apps/ansible/templates/dashboard.yml.j2
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4230 fix(vagrant): sets video RAM to 8 MB, avoids large default (256)
  Vagrantfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4231 feat(vagrant/virtualbox): adds parameter to resize vbox disks
  Vagrantfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4281 Add CNCF CLA to the contributing document
  CONTRIBUTING.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4168 Add flexvolume plugin dir to kubeadm kubelet
  roles/kubernetes/node/templates/kubelet.kubeadm.env.j2
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4296 Upgrade to latest version of ubuntu-nvidia-driver-installer.
  inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml
  roles/kubernetes-apps/container_engine_accelerator/nvidia_gpu/defaults/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4279 Retry applying podsecurity policies
  roles/kubernetes-apps/cluster_roles/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4180 Move kube_proxy_remove out of set_facts and set default
  roles/kubernetes/kubeadm/defaults/main.yml
  roles/kubernetes/node/defaults/main.yml
  roles/kubernetes/preinstall/tasks/0040-set_facts.yml
  roles/kubespray-defaults/defaults/main.yaml
  roles/win_nodes/kubernetes_patch/defaults/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#4284 Make container storage repository configurable
  roles/container-engine/docker-storage/defaults/main.yml
  roles/container-engine/docker-storage/files/install_container_storage_setup.sh
  roles/container-engine/docker-storage/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#4290 Add master toleration flag in dashboard deployment
  roles/kubernetes-apps/ansible/defaults/main.yml
  roles/kubernetes-apps/ansible/templates/dashboard.yml.j2
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4287 Disable become for localhost
  cluster.yml
  remove-node.yml
  reset.yml
  scale.yml
  upgrade-cluster.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4282 terraform: correct the spelling of Betacloud
  contrib/terraform/openstack/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4278 Speed up tasks
  cluster.yml
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#4275 Add labels to vsphere cloud config
  docs/vsphere.md
  roles/kubernetes/node/templates/vsphere-cloud-config.j2
Labels: approved, cncf-cla: yes, lgtm, size/S

#4233 added hardware requirements in README.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4248 weave: Upgrade to 2.5.1
  README.md
  roles/download/defaults/main.yml
  roles/network_plugin/weave/templates/weave-net.yml.j2
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4227 30MiB for gpu-device-plugin
  roles/kubernetes-apps/container_engine_accelerator/nvidia_gpu/defaults/main.yml
  roles/kubernetes-apps/container_engine_accelerator/nvidia_gpu/templates/k8s-device-plugin-nvidia-daemonset.yml.j2
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4194 [contrib/metallb] Update MetalLB to v0.7.3
  contrib/metallb/roles/provision/defaults/main.yml
  contrib/metallb/roles/provision/templates/metallb.yml.j2
Labels: approved, cncf-cla: yes, lgtm, size/M

#4160 Packet docs
  README.md
  docs/packet.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#4189 Add changed_when: false
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
  roles/network_plugin/calico/tasks/check.yml
  roles/network_plugin/calico/tasks/install.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4204 Add more links to the docs
  docs/_sidebar.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#4280 terraform: use openstackclient instead of novaclient
  contrib/terraform/openstack/README.md
  contrib/terraform/openstack/variables.tf
  inventory/sample/group_vars/all/all.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#4240 [doc] Add link to Kubespray.io
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4273 kube module: add recursive option
  library/kube.py
Labels: approved, cncf-cla: yes, lgtm, size/S

#4232 feat(external-provisioner): adds support for local-path-provisioner
  Vagrantfile
  inventory/sample/group_vars/k8s-cluster/addons.yml
  roles/download/defaults/main.yml
  roles/kubernetes-apps/external_provisioner/local_path_provisioner/defaults/main.yml
  roles/kubernetes-apps/external_provisioner/local_path_provisioner/tasks/main.yml
  roles/kubernetes-apps/external_provisioner/local_path_provisioner/templates/local-path-storage.yaml.j2
  roles/kubernetes-apps/external_provisioner/meta/main.yml
  tests/files/gce_centos7-flannel-addons.yml
Labels: approved, cncf-cla: yes, lgtm, size/L

#4250 remove kube bridge on reset
  roles/network_plugin/kube-router/tasks/reset.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#4309 Set default value for local_path_provisioner_enabled in role
  roles/kubernetes-apps/external_provisioner/local_path_provisioner/defaults/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4308 Add 1.12.6, sort arm64 descending
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/L

#4303 rewrite inventory script to create inventory file in YAML format
  contrib/inventory_builder/inventory.py
  contrib/inventory_builder/requirements.txt
  contrib/inventory_builder/tests/test_inventory.py
Labels: cncf-cla: yes, lgtm, size/L
