Repository kubernetes-sigs/kubespray, pull requests merged in 2019-12, with the labels that each got.

#5398 Allow inventory_builder to add nodes with hostname
  contrib/inventory_builder/inventory.py
  contrib/inventory_builder/tests/test_inventory.py
Labels: approved, cncf-cla: yes, lgtm, size/S

#5391 Tidy up coredns_server var and set proper priority in systemd-resolved
  roles/kubernetes/preinstall/tasks/0040-set_facts.yml
  roles/kubernetes/preinstall/templates/resolved.conf.j2
Labels: approved, cncf-cla: yes, lgtm, size/S

#5403 Allow customizing kubelet healthz port and bind addr
  roles/kubernetes/node/defaults/main.yml
  roles/kubernetes/node/templates/kubelet-config.v1beta1.yaml.j2
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5370 Fix OpenSUSE support
  test-infra/image-builder/roles/kubevirt-images/defaults/main.yml
  tests/files/packet_opensuse-canal.yml
  tests/scripts/testcases_run.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#5267 Update to TF v0.12.12
  .gitlab-ci/terraform.yml
  contrib/terraform/aws/create-infrastructure.tf
  contrib/terraform/aws/modules/elb/main.tf
  contrib/terraform/aws/sample-inventory/cluster.tfvars
  contrib/terraform/aws/terraform.tfvars
  contrib/terraform/packet/README.md
  contrib/terraform/packet/sample-inventory/cluster.tfvars
  docs/packet.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#5380 Add markdown CI
  .gitlab-ci/lint.yml
  .markdownlint.yaml
  README.md
  docs/ansible.md
  docs/arch.md
  docs/atomic.md
  docs/aws.md
  docs/azure.md
  docs/calico.md
  docs/cinder-csi.md
  docs/cloud.md
  docs/cni.md
  docs/comparisons.md
  docs/contiv.md
  docs/coreos.md
  docs/cri-o.md
  docs/debian.md
  docs/dns-stack.md
  docs/downloads.md
  docs/flannel.md
  docs/getting-started.md
  docs/ha-mode.md
  docs/integration.md
  docs/kube-ovn.md
  docs/kube-router.md
  docs/kubernetes-reliability.md
  docs/large-deployments.md
  docs/macvlan.md
  docs/multus.md
  docs/netcheck.md
  docs/opensuse.md
  docs/packet.md
  docs/proxy.md
  docs/recover-control-plane.md
  docs/roadmap.md
  docs/test_cases.md
  docs/upgrades.md
  docs/vagrant.md
  docs/vars.md
  docs/vsphere.md
  docs/weave.md
Labels: approved, cncf-cla: yes, kind/cleanup, kind/feature, lgtm, size/XXL

#5406 update oidc to contain quotes
  roles/kubernetes/master/templates/kubeadm-config.v1beta2.yaml.j2
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S

#5362 Fix Python code style for inventory_builder
  .gitlab-ci/lint.yml
  contrib/inventory_builder/inventory.py
  contrib/inventory_builder/tests/test_inventory.py
  contrib/inventory_builder/tox.ini
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/M

#5407 Add OIDC to CI
  tests/files/packet_centos7-flannel-addons.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5408 Add support for Debian 10
  .gitlab-ci/packet.yml
  test-infra/image-builder/roles/kubevirt-images/defaults/main.yml
  tests/cloud_playbooks/roles/packet-ci/defaults/main.yml
  tests/files/packet_debian10-containerd.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#5410 Add CI for Amazon Linux 2
  .gitlab-ci/packet.yml
  tests/cloud_playbooks/roles/packet-ci/defaults/main.yml
  tests/files/packet_amazon-linux-2-aio.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5405 Add toleration for calico-typha on master
  roles/network_plugin/calico/templates/calico-typha.yml.j2
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5361 Update to Ansible 2.9.1
  README.md
  contrib/vault/roles/vault/tasks/bootstrap/ca_trust.yml
  roles/container-engine/docker/tasks/main.yml
  roles/container-engine/docker/tasks/systemd.yml
  roles/download/tasks/download_container.yml
  roles/download/tasks/download_file.yml
  roles/download/tasks/prep_download.yml
  roles/download/tasks/sync_container.yml
  roles/download/tasks/sync_file.yml
  roles/etcd/meta/main.yml
  roles/etcd/tasks/upd_ca_trust.yml
  roles/kubernetes-apps/cloud_controller/oci/tasks/credentials-check.yml
  roles/kubernetes-apps/helm/tasks/main.yml
  roles/kubernetes/master/tasks/kubeadm-setup.yml
  roles/kubernetes/preinstall/handlers/main.yml
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
  roles/kubernetes/preinstall/tasks/0040-set_facts.yml
  roles/kubernetes/preinstall/tasks/0060-resolvconf.yml
  roles/kubernetes/preinstall/tasks/0070-system-packages.yml
  roles/kubernetes/preinstall/tasks/0080-system-configurations.yml
  roles/kubernetes/preinstall/tasks/main.yml
  roles/network_plugin/macvlan/handlers/main.yml
  roles/network_plugin/macvlan/tasks/main.yml
  roles/reset/tasks/main.yml
  tests/testcases/015_check-pods-running.yml
  tests/testcases/030_check-network.yml
  tests/testcases/040_check-network-adv.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/L

#5412 Support Openstack servergroups
  contrib/terraform/openstack/README.md
  contrib/terraform/openstack/kubespray.tf
  contrib/terraform/openstack/modules/compute/main.tf
  contrib/terraform/openstack/modules/compute/variables.tf
  contrib/terraform/openstack/variables.tf
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/L

#5213 Fixes for CentOS 8
  roles/bootstrap-os/tasks/bootstrap-centos.yml
  roles/container-engine/containerd/templates/rh_containerd.repo.j2
  roles/container-engine/docker/templates/rh_docker.repo.j2
  roles/kubernetes/preinstall/vars/centos.yml
  roles/kubernetes/preinstall/vars/redhat.yml
  roles/reset/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S

#5257 set node label via kubectl label command
  cluster.yml
  roles/kubernetes/node-label/tasks/main.yml
  roles/kubernetes/node/templates/kubelet.env.v1beta1.j2
  scale.yml
  upgrade-cluster.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/M

#5314 Set kube_image_repo use {{ gcr_image_repo }}
  inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#5396 Add default value for `bin_dir` in recover control plane
  roles/recover_control_plane/master/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#5423 Add checksums for v1.17.0
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#5342 Add k8s 1.15.6 hashes
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#5424 Fix TF inventory script
  contrib/terraform/terraform.py
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#5418 Remove Digital Ocean CI
  .gitlab-ci.yml
  .gitlab-ci/digital-ocean.yml
  tests/files/do_ubuntu-canal-ha.yml
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, size/M

#5419 Update the release process doc
  RELEASE.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/S

#5363 Use kubespray/kubespray:v2.11.0 for CI
  .gitlab-ci.yml
  .gitlab-ci/lint.yml
  .gitlab-ci/packet.yml
  .gitlab-ci/terraform.yml
  Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/S

#5428 Ensure 0644 mode for ca.crt on nodes
  roles/kubernetes/kubeadm/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5427 Re introduce CI for upgrades
  .gitlab-ci/packet.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/M

#5433 Add wait for kubectl get ds after upgrades
  roles/win_nodes/kubernetes_patch/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-blocker, size/XS

#5435 Update aws tf
  contrib/terraform/aws/README.md
  contrib/terraform/aws/create-infrastructure.tf
  contrib/terraform/aws/modules/elb/main.tf
  contrib/terraform/aws/modules/vpc/outputs.tf
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S

#5441 Add Helm 3.x support
  docs/vars.md
  roles/download/defaults/main.yml
  roles/kubernetes-apps/helm/tasks/main.yml
  tests/files/packet_debian10-containerd.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#5447 Bump nodelocaldns version to 1.15.8
  roles/download/defaults/main.yml
  roles/kubernetes-apps/ansible/templates/nodelocaldns-daemonset.yml.j2
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#5448 Update CI to use v2.12.0 image and update release process
  .gitlab-ci.yml
  RELEASE.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5444 cri-o: redhat.yml - remove package cri-tools
  roles/container-engine/cri-o/vars/redhat.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#5452 fix typo
  inventory/sample/group_vars/all/oci.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5416 Add kube-router configuration to enable metrics exposure
  inventory/sample/group_vars/k8s-cluster/k8s-net-kube-router.yml
  roles/network_plugin/kube-router/defaults/main.yml
  roles/network_plugin/kube-router/templates/kube-router.yml.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/M

#5453 Update CNI plugins to v0.8.3
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#5461 [docs] Add CI matrix and script
  .gitlab-ci/packet.yml
  docs/_sidebar.md
  docs/ci.md
  tests/files/packet_centos7-weave-kubeadm-sep.yml
  tests/files/packet_oracle7-canal.yml
  tests/files/packet_ubuntu16-canal-ha.yml
  tests/files/packet_ubuntu16-canal-kubeadm.yml
  tests/files/packet_ubuntu16-contiv-sep.yml
  tests/files/packet_ubuntu16-flannel-ha.yml
  tests/files/packet_ubuntu16-kube-router-sep.yml
  tests/files/packet_ubuntu16-weave-sep.yml
  tests/scripts/md-table/main.py
  tests/scripts/md-table/requirements.txt
  tests/scripts/md-table/table.md.j2
  tests/scripts/md-table/test.sh
  tests/scripts/md-table/tmp.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/L

#5459 Remove GCE tests files
  .gitlab-ci.yml
  .gitlab-ci/gce.yml
  tests/files/gce_centos-weave-kubeadm-sep.yml
  tests/files/gce_centos7-calico-ha.yml
  tests/files/gce_centos7-flannel-addons.yml
  tests/files/gce_centos7-kube-router.yml
  tests/files/gce_centos7-multus-calico.yml
  tests/files/gce_coreos-alpha-weave-ha.yml
  tests/files/gce_coreos-calico-aio.yml
  tests/files/gce_coreos-canal.yml
  tests/files/gce_coreos-cilium.yml
  tests/files/gce_coreos-kube-router.yml
  tests/files/gce_debian9-calico-upgrade.yml
  tests/files/gce_opensuse-canal.yml
  tests/files/gce_oracle-canal.yml
  tests/files/gce_rhel7-canal-sep.yml
  tests/files/gce_rhel7-weave.yml
  tests/files/gce_ubuntu-canal-ha.yml
  tests/files/gce_ubuntu-canal-kubeadm.yml
  tests/files/gce_ubuntu-contiv-sep.yml
  tests/files/gce_ubuntu-flannel-ha.yml
  tests/files/gce_ubuntu-kube-router-sep.yml
  tests/files/gce_ubuntu-weave-sep.yml
  tests/files/gce_ubuntu18-cilium-sep.yml
  tests/files/gce_ubuntu18-flannel-aio.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XL

#5386 Remove inline shell in YAML for vagrant-validate
  .gitlab-ci/lint.yml
  tests/scripts/vagrant-validate.sh
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/S

#5421 Bump yamllint and ansible-lint versions
  tests/requirements.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5470 Add script for generating binary hashes
  scripts/download_hash.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#5476 Update the url in .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5426 Ubuntu CRI-O
  roles/container-engine/cri-o/tasks/crictl.yml
  roles/container-engine/cri-o/tasks/main.yaml
  roles/container-engine/cri-o/templates/crictl.yaml.j2
  roles/container-engine/cri-o/templates/crio.conf.j2
  roles/container-engine/cri-o/vars/ubuntu.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/M

#5483 A fix of install instructions
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5481 Fix invalid variable in host inventory script
  contrib/terraform/terraform.py
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS
