Repository kubernetes-sigs/kubespray, pull requests merged in 2020-10, with the labels that each got.

#6744 [2.14] Set ansible_python_interpreter to python3 on debian
  roles/bootstrap-os/tasks/bootstrap-debian.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#6774 Add `plugins/mitogen` to `.gitignore`
  .gitignore
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/XS

#6784 Update cilium with minor fix for CVE
  README.md
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#6783 Add optional arguments for external cloud controller manager DaemonSet
  roles/kubernetes-apps/external_cloud_controller/openstack/defaults/main.yml
  roles/kubernetes-apps/external_cloud_controller/openstack/templates/external-openstack-cloud-controller-manager-ds.yml.j2
  roles/kubernetes-apps/external_cloud_controller/vsphere/defaults/main.yml
  roles/kubernetes-apps/external_cloud_controller/vsphere/templates/external-vsphere-cloud-controller-manager-ds.yml.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/S

#6781 harden reset to work in more cases
  roles/reset/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#6793 Update kube-router to 1.1.0
  README.md
  roles/download/defaults/main.yml
  roles/network_plugin/kube-router/templates/kube-router.yml.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#6792 Update triage/support label references to kind/support
  .github/ISSUE_TEMPLATE/support.md
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#6796 Add oomichi to reviewers
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#6773 Use v2.14.1 as base image for CI
  .gitlab-ci.yml
Labels: approved, cncf-cla: yes, kind/api-change, lgtm, size/XS

#6786 Update nginx ingress controller to 0.40.1
  README.md
  roles/download/defaults/main.yml
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/ds-ingress-nginx-controller.yml.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#6785 Added comment to clarify supported Kubernetes versions in download role
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/XS

#6745 Fix cinder & external_openstack cacert deployment
  roles/kubernetes-apps/csi_driver/cinder/tasks/cinder-write-cacert.yml
  roles/kubernetes-apps/csi_driver/cinder/tasks/main.yml
  roles/kubernetes-apps/external_cloud_controller/openstack/tasks/main.yml
  roles/kubernetes-apps/external_cloud_controller/openstack/tasks/openstack-write-cacert.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/M

#6776 Fix AWS EBS CSI Driver.
  roles/kubernetes-apps/csi_driver/aws_ebs/templates/aws-ebs-csi-controllerservice-rbac.yml.j2
  roles/kubernetes-apps/csi_driver/aws_ebs/templates/aws-ebs-csi-controllerservice.yml.j2
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/S

#6798 Scale cluster playbook failed when etcd installed by kubeadm
  roles/etcd/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#6753 Ensure crio service state
  roles/container-engine/cri-o/tasks/main.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#6520 Fix issue 6294 - "All pods simultaneously restart during worker scaling"
  docs/proxy.md
  docs/vars.md
  inventory/sample/group_vars/all/all.yml
  roles/kubespray-defaults/tasks/no_proxy.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/M

#6801 Update bunch of dependencies
  README.md
  roles/bootstrap-os/files/bootstrap.sh
  roles/download/defaults/main.yml
  test-infra/vagrant-docker/Dockerfile
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#6800 Chmod kubeconfig to avoid group-readable
  roles/kubernetes/client/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#6804 Disable dashboard by default
  roles/kubernetes-apps/ansible/defaults/main.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, kind/api-change, lgtm, ok-to-test, size/XS

#6803 Fix handlers naming issue for Kubeadm | kubelet
  roles/kubernetes/kubeadm/handlers/main.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#6810 Fix line-spacing in no_proxy.yml
  roles/kubespray-defaults/tasks/no_proxy.yml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#6755 allow pre-existing floating IPs to be specified with k8s_master_fips
  contrib/terraform/openstack/README.md
  contrib/terraform/openstack/kubespray.tf
  contrib/terraform/openstack/modules/ips/main.tf
  contrib/terraform/openstack/modules/ips/outputs.tf
  contrib/terraform/openstack/modules/ips/variables.tf
  contrib/terraform/openstack/variables.tf
Labels: approved, cncf-cla: yes, kind/bug, kind/feature, lgtm, ok-to-test, size/S

#6815 cleanup kubelet_deployment_type
  docs/cri-o.md
  docs/vars.md
  inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml
  tests/files/packet_centos7-crio.yml
  tests/files/packet_ubuntu18-crio.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/S

#6403 Added option to force apiserver and respective client certificate to …
  inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml
  roles/kubernetes/master/defaults/main/main.yml
  roles/kubernetes/master/tasks/kubeadm-setup.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/XS

#6812 Make reset work for crio
  roles/reset/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/S

#6813 fix: add tags for set facts nodelocaldns
  roles/kubernetes-apps/ansible/tasks/nodelocaldns.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#6816 Modify imagepullpolicy
  roles/kubernetes-apps/ingress_controller/ambassador/templates/deploy-ambassador.yml.j2
  roles/kubernetes-apps/metallb/templates/metallb.yml.j2
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6814 change owner to root for bin_dir directory
  roles/kubernetes/preinstall/tasks/0050-create_directories.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S

#6758 bump crio version to 1.19
  README.md
  docs/cri-o.md
  roles/container-engine/cri-o/defaults/main.yml
  roles/container-engine/cri-o/tasks/crio_repo.yml
  roles/container-engine/cri-o/vars/debian.yml
  roles/container-engine/cri-o/vars/fedora.yml
  roles/container-engine/cri-o/vars/ubuntu.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/M

#6811 Disable audio device mapping in Vagrant for VirtualBox
  Vagrantfile
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/XS

#6826 Upgrade Flannel to 0.13.0
  README.md
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#6829 Use existing variable for tiller service account name
  roles/kubernetes-apps/helm/templates/tiller-clusterrolebinding.yml.j2
  roles/kubernetes-apps/helm/templates/tiller-sa.yml.j2
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6837 Fix proxy and module_hotfixes
  roles/container-engine/containerd/templates/rh_containerd.repo.j2
  roles/container-engine/docker/templates/rh_docker.repo.j2
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#6828 Adding option to disable globally applying a proxy to etc/yum.conf
  inventory/sample/group_vars/all/all.yml
  roles/bootstrap-os/defaults/main.yml
  roles/bootstrap-os/tasks/bootstrap-centos.yml
  roles/bootstrap-os/tasks/bootstrap-debian.yml
  roles/bootstrap-os/tasks/bootstrap-fedora.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/S

#6841 Update hashes and set default version to 1.19.3
  Dockerfile
  README.md
  inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml
  roles/download/defaults/main.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/M

#6842 [2.14] Update hashes and set default to 1.18.10
  README.md
  inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml
  roles/download/defaults/main.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/M

#6832 [2.14] Fix cinder & external_openstack cacert deployment
  roles/kubernetes-apps/csi_driver/cinder/tasks/cinder-write-cacert.yml
  roles/kubernetes-apps/csi_driver/cinder/tasks/main.yml
  roles/kubernetes-apps/external_cloud_controller/openstack/tasks/main.yml
  roles/kubernetes-apps/external_cloud_controller/openstack/tasks/openstack-write-cacert.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/M

#6817 [2.14] Fix unintended SIGPIPE
  roles/etcd/tasks/configure.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#6848 Add tag for test-infra images and docker logout
  test-infra/image-builder/roles/kubevirt-images/defaults/main.yml
  test-infra/image-builder/roles/kubevirt-images/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#6797 allow non existing etcd group
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
  roles/kubernetes/preinstall/tasks/0090-etchosts.yml
  roles/kubespray-defaults/defaults/main.yaml
  roles/kubespray-defaults/tasks/no_proxy.yml
  roles/network_plugin/calico/templates/calico-node.yml.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/S

#6822 fix scaling in kubeadm etcd mode
  roles/kubernetes/kubeadm/defaults/main.yml
  roles/kubernetes/kubeadm/tasks/kubeadm_etcd_node.yml
  scale.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/M

#6851 Set feature gates in kube-proxy ConfigMap
  roles/kubernetes/master/templates/kubeadm-config.v1beta2.yaml.j2
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#6852 Update k8s-dns-node-cache to 1.15.16
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#6830 Add Kata Containers support to CRI-O runtime
  roles/container-engine/cri-o/defaults/main.yml
  roles/container-engine/cri-o/tasks/main.yaml
  roles/container-engine/cri-o/templates/crio.conf.j2
  roles/container-engine/cri-o/vars/debian.yml
  roles/container-engine/cri-o/vars/ubuntu.yml
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/M

#6836 Fixes 6621 etcd backup directory is consuming much rootfs disk space
  roles/etcd/defaults/main.yml
  roles/etcd/handlers/backup.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/XS

#6853 Install cri-o with package version
  roles/container-engine/cri-o/vars/centos-7.yml
  roles/container-engine/cri-o/vars/centos-8.yml
  roles/container-engine/cri-o/vars/ubuntu.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/S

#6860 fixed bug in etcd retention where backups are not sorted by date
  roles/etcd/handlers/backup.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#6855 update version of ingress-nginx controller in docs.
  roles/kubernetes-apps/ingress_controller/ingress_nginx/README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/M

#6856 Register missing outputs in role "remove-node/pre-remove"
  roles/remove-node/pre-remove/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#6854 Notes About Server In admin.conf
  contrib/terraform/aws/README.md
  docs/getting-started.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/M

#6825 Handle dns_mode set to 'none' in generate nameservers task
  roles/kubernetes/preinstall/tasks/0040-set_facts.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#6871 Minor update Calico and Cilium
  README.md
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#6868 Fix missing spaces in section heading.
  docs/comparisons.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6867 Update helm stable repo
  roles/kubernetes-apps/helm/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS
