Repository kubernetes-sigs/kubespray, pull requests merged in 2020-08, with the labels that each got.

#6477 [2.12] Update hashes and set default version to 1.16.13
  README.md
  inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml
  roles/download/defaults/main.yml
  roles/kubernetes/master/handlers/main.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/M

#6394 Moved docker_dns_options to defaults so it can be overridden
  docs/dns-stack.md
  roles/container-engine/docker/tasks/set_facts_dns.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/M

#6475 [2.13] Fix test if openstack_cacert is a base64 string (#6421)
  roles/kubernetes/node/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#6474 Fix download calico policy condition
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#6396 Add option to configure IPVS timeouts in kube-proxy configration
  roles/kubernetes/master/defaults/main/kube-proxy.yml
  roles/kubernetes/master/templates/kubeadm-config.v1beta2.yaml.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/S

#6432 crio: align template crio.conf with upstream
  roles/container-engine/cri-o/defaults/main.yml
  roles/container-engine/cri-o/templates/crio.conf.j2
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#6470 fix src for audit webhook config yaml
  roles/kubernetes/master/templates/apiserver-audit-webhook-config.yaml.j2
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#6479 Update kube-router to 1.0.1 and kube-ovn to 1.3.0
  README.md
  roles/download/defaults/main.yml
  roles/network_plugin/kube-ovn/templates/cni-kube-ovn.yml.j2
  roles/network_plugin/kube-ovn/templates/cni-ovn.yml.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#6478 Remove workaround for kubeadm upgrade
  roles/kubernetes/master/tasks/kubeadm-upgrade.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#6371 [v2.12] fix test if openstack_cacert is a base64 string
  roles/kubernetes/node/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#6492 [2.13] Update base image to v2.12.9
  .gitlab-ci.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6468 Upgrade Ansible molecule to version 3
  roles/bootstrap-os/molecule/default/converge.yml
  roles/bootstrap-os/molecule/default/molecule.yml
  roles/container-engine/containerd/molecule/default/converge.yml
  roles/container-engine/containerd/molecule/default/molecule.yml
  roles/container-engine/cri-o/molecule/default/converge.yml
  roles/container-engine/cri-o/molecule/default/molecule.yml
  roles/container-engine/docker/molecule/default/converge.yml
  roles/container-engine/docker/molecule/default/molecule.yml
  tests/requirements.txt
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/M

#6385 Create a PodDisruptionBudget for the Cinder CSI controller plugin
  roles/kubernetes-apps/csi_driver/cinder/tasks/main.yml
  roles/kubernetes-apps/csi_driver/cinder/templates/cinder-csi-poddisruptionbudget.yml.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/S

#6476 Remove hvac dependency
  requirements.txt
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#6480 Fix Flexvolume mount in Openstack Controller
  roles/kubernetes-apps/external_cloud_controller/openstack/templates/external-openstack-cloud-controller-manager-ds.yml.j2
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#6494 Update base image to v2.13.3
  .gitlab-ci.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6497 Quoted type constraints are deprecated
  contrib/terraform/openstack/modules/compute/variables.tf
  contrib/terraform/openstack/modules/network/variables.tf
  contrib/terraform/openstack/variables.tf
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/M

#6154 bootstrap-os for remove-node
  remove-node.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#6383 Option for MetalLB to talk BGP
  inventory/sample/group_vars/k8s-cluster/addons.yml
  roles/kubernetes-apps/metallb/README.md
  roles/kubernetes-apps/metallb/tasks/main.yml
  roles/kubernetes-apps/metallb/templates/metallb-config.yml.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/M

#6499 Correct sample inventory to pass yamllint
  inventory/sample/group_vars/all/all.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/XS

#6496 Fix E306 in scripts/
  scripts/collect-info.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#6472 Allows tls verify skip on webhook auth url
  roles/kubernetes/master/defaults/main/main.yml
  roles/kubernetes/master/templates/webhook-token-auth-config.yaml.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/XS

#6500 Fix E306 in roles/kubernetes
  roles/kubernetes/kubeadm/tasks/main.yml
  roles/kubernetes/master/tasks/kubeadm-setup.yml
  roles/kubernetes/master/tasks/pre-upgrade.yml
  roles/kubernetes/node/tasks/pre_upgrade.yml
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
  roles/kubernetes/tokens/tasks/gen_tokens.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/M

#6495 Fix E306 in tests/
  tests/cloud_playbooks/roles/packet-ci/tasks/create-vms.yml
  tests/testcases/040_check-network-adv.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#6473 Fix cilium strict kube proxy replacement in HA
  docs/cilium.md
  roles/kubespray-defaults/defaults/main.yaml
  roles/network_plugin/cilium/templates/cilium-deploy.yml.j2
  roles/network_plugin/cilium/templates/cilium-ds.yml.j2
  tests/files/packet_debian10-cilium-svc-proxy.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/M

#6503 Minor Ambassador docs updates
  docs/ambassador.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/XS

#6490 Add tlsMinVersion and tlsCipherSuites in kubelet configuration
  roles/kubernetes/node/defaults/main.yml
  roles/kubernetes/node/templates/kubelet-config.v1beta1.yaml.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/M

#6513 Improve Cilium metrics support
  roles/network_plugin/cilium/defaults/main.yml
  roles/network_plugin/cilium/templates/cilium-deploy.yml.j2
  roles/network_plugin/cilium/templates/cilium-ds.yml.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/S

#6514 FIx Cilium deploy additionally with etcd kubeadm
  roles/kubernetes/kubeadm/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#6518 Fixed Kubespray container-engine/docker role to populate docker.service
  roles/container-engine/docker/tasks/systemd.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#6519 Add new cilium options for native routing
  roles/network_plugin/cilium/defaults/main.yml
  roles/network_plugin/cilium/templates/cilium-config.yml.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/S

#6522 Remove unused variables - force_etcd3/kube_front_proxy_ca
  roles/kubernetes/master/defaults/main/main.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#6524 add master_volume_type TF variable to support volume type on Openstack
  contrib/terraform/openstack/kubespray.tf
  contrib/terraform/openstack/modules/compute/main.tf
  contrib/terraform/openstack/modules/compute/variables.tf
  contrib/terraform/openstack/variables.tf
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#6526 Fix apiVersion for audit policy
  roles/kubernetes/master/templates/apiserver-audit-policy.yaml.j2
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6529 Allow hosts with hyphen in name
  contrib/inventory_builder/inventory.py
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#6536 Update sonobuoy dependency
  tests/testcases/100_check-k8s-conformance.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#6546 Edited pre-upgrade task to uncordon a node failing to drain
  roles/upgrade/pre-upgrade/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/M

#6549 Fix cert-manager E305 ansible-lint error
  roles/kubernetes-apps/ingress_controller/cert_manager/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#6482 fix scale playbook
  roles/kubernetes/kubeadm/handlers/main.yml
  scale.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/S

#6501 Update weave to 2.7.0 + minor update to Cilium
  README.md
  roles/download/defaults/main.yml
  roles/network_plugin/weave/templates/weave-net.yml.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#6538 Update coredns to 1.7.0
  README.md
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/XS

#6397 Add docs about CI setup
  docs/_sidebar.md
  docs/ci-setup.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/S

#6557 Fix setting node label if kube_override_hostname is defined
  roles/kubernetes/node-label/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#6544 Add docs for 'setting up your first cluster'
  README.md
  docs/getting-started.md
  docs/setting-up-your-first-cluster.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/XL

#6532 Update k8s hashes and set default version to 1.18.8
  README.md
  inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml
  roles/download/defaults/main.yml
  roles/kubernetes/preinstall/defaults/main.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/M

#6555 Updated pypy download url in bootstrap script
  roles/bootstrap-os/files/bootstrap.sh
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#6556 kind/bug: Update extras_rh_repo_base_url
  roles/container-engine/containerd/defaults/main.yml
  roles/container-engine/docker/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#6562 Bump Openstack cloud controller image verison to 1.18.2
  roles/kubernetes-apps/external_cloud_controller/openstack/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#6442 make pre-remove node draining a failable task
  roles/remove-node/pre-remove/defaults/main.yml
  roles/remove-node/pre-remove/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6493 Add timeout to Get current version of calico cluster version, again
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
  roles/network_plugin/calico/tasks/check.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#6502 Allow webhook authorization
  inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml
  roles/kubernetes/master/defaults/main/main.yml
  roles/kubernetes/master/tasks/main.yml
  roles/kubernetes/master/templates/kubeadm-config.v1beta2.yaml.j2
  roles/kubernetes/master/templates/webhook-authorization-config.yaml.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/M

#6573 Rollback coredns, should not have been updated before 1.19
  README.md
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#6531 update the ovn4nfv-k8s-plugin image version to v1.1.0
  README.md
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/XS

#6574 Improve metallb template for bgp peers
  roles/kubernetes-apps/metallb/defaults/main.yml
  roles/kubernetes-apps/metallb/templates/metallb-config.yml.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/XS

#6575 Add cilium hubble server in config
  roles/network_plugin/cilium/defaults/main.yml
  roles/network_plugin/cilium/templates/cilium-config.yml.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/S

#6581 Fix Ansible Lint warnings (No such file or directory)
  contrib/network-storage/heketi/roles/tear-down/tasks/main.yml
  roles/kubernetes-apps/ansible/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, ok-to-test, size/S

#6508 Deviceroutesourceaddress
  inventory/sample/group_vars/k8s-cluster/k8s-net-calico.yml
  roles/network_plugin/calico/templates/calico-node.yml.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/S

#6547 [Openstack] Make it possible to open additional ports on masters
  contrib/terraform/openstack/kubespray.tf
  contrib/terraform/openstack/modules/compute/main.tf
  contrib/terraform/openstack/modules/compute/variables.tf
  contrib/terraform/openstack/variables.tf
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#6570 Update bunch of dependencies with minor fixes
  README.md
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#6579 Remove ethtool workaround, issue is now fixed
  tests/testcases/040_check-network-adv.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#6587 etcd should not fail when adding an already existing member
  roles/etcd/tasks/join_etcd_member.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#6568 cri-o: add variable to configure unsecure pull
  roles/container-engine/cri-o/defaults/main.yml
  roles/container-engine/cri-o/templates/crio.conf.j2
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#6593 Add Kubernetes 1.19 hashes
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#6571 Update nginx ingress to 0.34.1
  README.md
  roles/download/defaults/main.yml
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/clusterrolebinding-ingress-nginx.yml.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#6517 Fix E306 in other roles
  roles/container-engine/docker/tasks/set_facts_dns.yml
  roles/container-engine/docker/tasks/systemd.yml
  roles/download/tasks/prep_kubeadm_images.yml
  roles/kubernetes-apps/helm/tasks/gen_helm_tiller_certs.yml
  roles/kubernetes-apps/helm/tasks/main.yml
  roles/reset/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/M

#6576 Remove support for CoreOS Container Linux (EOL)
  README.md
  Vagrantfile
  contrib/terraform/aws/README.md
  contrib/terraform/aws/variables.tf
  contrib/terraform/openstack/README.md
  contrib/terraform/packet/README.md
  contrib/terraform/terraform.py
  contrib/vault/roles/vault/tasks/bootstrap/ca_trust.yml
  docs/_sidebar.md
  docs/flatcar.md
  docs/vagrant.md
  roles/bootstrap-os/README.md
  roles/bootstrap-os/defaults/main.yml
  roles/bootstrap-os/tasks/bootstrap-flatcar.yml
  roles/bootstrap-os/tasks/main.yml
  roles/container-engine/docker/handlers/main.yml
  roles/container-engine/docker/tasks/main.yml
  roles/container-engine/docker/tasks/systemd.yml
  roles/download/defaults/main.yml
  roles/download/tasks/prep_download.yml
  roles/etcd/meta/main.yml
  roles/etcd/tasks/upd_ca_trust.yml
  roles/kubernetes-apps/external_provisioner/local_volume_provisioner/README.md
  roles/kubernetes-apps/helm/tasks/install_host.yml
  roles/kubernetes-apps/helm/tasks/main.yml
  roles/kubernetes/node/tasks/install.yml
  roles/kubernetes/preinstall/defaults/main.yml
  roles/kubernetes/preinstall/handlers/main.yml
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
  roles/kubernetes/preinstall/tasks/0040-set_facts.yml
  roles/kubernetes/preinstall/tasks/0060-resolvconf.yml
  roles/kubernetes/preinstall/tasks/0070-system-packages.yml
  roles/kubernetes/preinstall/tasks/0080-system-configurations.yml
  roles/kubernetes/preinstall/tasks/main.yml
  roles/kubespray-defaults/defaults/main.yaml
  roles/network_plugin/macvlan/handlers/main.yml
  roles/network_plugin/macvlan/tasks/main.yml
  roles/reset/tasks/main.yml
  tests/cloud_playbooks/create-do.yml
  tests/scripts/testcases_run.sh
  tests/testcases/015_check-nodes-ready.yml
  tests/testcases/020_check-pods-running.yml
  tests/testcases/030_check-network.yml
  tests/testcases/040_check-network-adv.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, needs-ok-to-test, size/L

#6515 Fix E306 in roles/etcd
  roles/etcd/tasks/configure.yml
  roles/etcd/tasks/gen_certs_script.yml
  roles/etcd/tasks/join_etcd-events_member.yml
  roles/etcd/tasks/join_etcd_member.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/M

#6599 Update nginx ingress to 0.35.0
  README.md
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#6409 Fix Ansible-lint E303
  roles/kubernetes/preinstall/handlers/main.yml
  roles/kubernetes/preinstall/tasks/0040-set_facts.yml
  roles/network_plugin/calico/tasks/install.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/S

#6534 Add support for openstack application credentials
  inventory/sample/group_vars/all/openstack.yml
  roles/kubernetes-apps/external_cloud_controller/openstack/tasks/openstack-credential-check.yml
  roles/kubernetes-apps/external_cloud_controller/openstack/templates/external-openstack-cloud-config.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/M

#6563 Docker: Set Cgroup driver by default to systemd
  inventory/sample/group_vars/all/docker.yml
  roles/container-engine/docker/defaults/main.yml
  roles/container-engine/docker/templates/docker-options.conf.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, needs-ok-to-test, size/S

#6592 Update cni plugins with minor fix
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS
