Repository kubernetes-sigs/kubespray, pull requests merged in 2020-01, with the labels that each got.

#5469 Fix invalid count index
  contrib/terraform/openstack/modules/compute/main.tf
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#5479 Clean kubectl cache after upgrade on first master
  roles/kubernetes/master/tasks/kubeadm-upgrade.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5506 Set pipefail in case tar fails
  roles/etcd/tasks/gen_certs_script.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#5502 update ingress_nginx install guide
  roles/kubernetes-apps/ingress_controller/ingress_nginx/README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/L

#5478 kube-proxy need conntrack
  roles/kubernetes/preinstall/defaults/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5514 Calico: update to 3.11.1, allow to configure calico_iptables_backend
  README.md
  inventory/sample/group_vars/k8s-cluster/k8s-net-calico.yml
  roles/download/defaults/main.yml
  roles/network_plugin/calico/defaults/main.yml
  roles/network_plugin/calico/templates/calico-cr.yml.j2
  roles/network_plugin/calico/templates/calico-crb.yml.j2
  roles/network_plugin/calico/templates/calico-node.yml.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/M

#5518 Upgrade to Kubernetes 1.15.7
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#5527 Raise typha max connections to 300
  inventory/sample/group_vars/k8s-cluster/k8s-net-calico.yml
  roles/network_plugin/calico/defaults/main.yml
  roles/network_plugin/calico/templates/calico-typha.yml.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#5528 Remove downloading deprecated calico-rr image
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5524 Ensure we always fixup kube-proxy kubeconfig
  roles/kubernetes/kubeadm/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#5450 Update api-versions to cleanup depreciated ones
  roles/kubernetes-apps/cluster_roles/files/k8s-cluster-critical-pc.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5548 Remove dockerproject org
  roles/container-engine/containerd/templates/rh_docker.repo.j2
  roles/container-engine/docker/defaults/main.yml
  roles/container-engine/docker/tasks/main.yml
  roles/container-engine/docker/vars/debian.yml
  roles/container-engine/docker/vars/redhat.yml
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, size/S

#5540 Fix temp filename for debian-10 image
  test-infra/image-builder/roles/kubevirt-images/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#5488 Rebase on 2.12
  tests/scripts/rebase.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5557 #5373 "ruamel.yaml.composer.ComposerError"
  contrib/inventory_builder/inventory.py
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5560 tag role kubernetes/node-label in playbooks
  cluster.yml
  scale.yml
  upgrade-cluster.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#5564 Update to hashes and default version (1.15.9 / 1.16.6 / 1.17.2)
  README.md
  inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml
  roles/download/defaults/main.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/M

#5581 Fix hashes... kubernetes 1.17.2
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#5482 Fix invalid variable in host inventory script
  contrib/terraform/terraform.py
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#5569 Remove stale legacy yum docker repo /etc/yum.repos.d/docker.repo
  roles/container-engine/docker/tasks/pre-upgrade.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#5583 Add proxy support to containerd, improves no_proxy
  roles/container-engine/containerd/tasks/main.yml
  roles/container-engine/containerd/templates/http-proxy.conf.j2
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S

#5568 Fix typo in Multus plugin
  roles/kubernetes-apps/network_plugin/multus/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#5589 Add CentOS 8 image for testing
  Vagrantfile
  test-infra/image-builder/roles/kubevirt-images/defaults/main.yml
  tests/cloud_playbooks/roles/packet-ci/defaults/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS
