Repository kubernetes-sigs/kubespray, pull requests merged in 2020-11, with the labels that each got.

#6862 Sets cgroup v1 in Fedora +31
  roles/container-engine/cri-o/tasks/main.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/S

#6880 Allow the eventRecordQPS setting to be set.
  roles/kubernetes/node/templates/kubelet-config.v1beta1.yaml.j2
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/XS

#6882 crio: avoid extra restart after install and upgrade
  roles/container-engine/cri-o/tasks/main.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#6857 install etcdctl to host when etcd deployment type is kubeadm
  docs/cri-o.md
  roles/etcdctl/tasks/main.yml
  roles/etcdctl/templates/etcdctl.sh.j2
  roles/kubernetes/master/tasks/kubeadm-etcd.yml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#6865 [Openstack] Add security groups not managed by terraform
  contrib/terraform/openstack/kubespray.tf
  contrib/terraform/openstack/modules/compute/main.tf
  contrib/terraform/openstack/modules/compute/variables.tf
  contrib/terraform/openstack/variables.tf
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/M

#6881 Update BGPPeer CRD to match v3.16 of Calico
  roles/network_plugin/calico/templates/kdd-crds.yml.j2
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/M

#6887 [Openstack] Make sure router port is created before attaching floating IPs
  contrib/terraform/openstack/kubespray.tf
  contrib/terraform/openstack/modules/ips/main.tf
  contrib/terraform/openstack/modules/ips/variables.tf
  contrib/terraform/openstack/variables.tf
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/S

#6897 Fix hash of pypy3.6-v7.3.2-linux64 archive.
  roles/bootstrap-os/files/bootstrap.sh
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#6886 calico: avoid POD restart during initial deploy
  roles/network_plugin/calico/handlers/main.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/XS

#6888 add warning about current state of heketi
  contrib/network-storage/heketi/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6823 Update kubevirt Centos7 from 1809 to 2003
  test-infra/image-builder/roles/kubevirt-images/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/XS

#6910 fix flake8 errors in Kubespray CI - tox-inventory-builder
  contrib/inventory_builder/tests/test_inventory.py
  roles/container-engine/cri-o/tasks/crio_repo.yml
  roles/download/defaults/main.yml
  roles/kubernetes/preinstall/defaults/main.yml
  roles/kubernetes/preinstall/tasks/0070-system-packages.yml
  tests/files/tf-ovh_ubuntu18-calico.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/M

#6923 Some typos in docs
  docs/azure-csi.md
  docs/azure.md
  docs/calico.md
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/XS

#6944 bump calico version to 3.16.5
  README.md
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6572 Add RHEL support subscription registration
  Vagrantfile
  docs/centos8.md
  docs/offline-environment.md
  docs/rhel.md
  inventory/sample/group_vars/all/all.yml
  roles/bootstrap-os/handlers/main.yml
  roles/bootstrap-os/tasks/bootstrap-redhat.yml
  roles/bootstrap-os/tasks/main.yml
  roles/container-engine/containerd/defaults/main.yml
  roles/container-engine/containerd/tasks/containerd_repo.yml
  roles/container-engine/docker/defaults/main.yml
  roles/container-engine/docker/tasks/main.yml
  roles/container-engine/docker/vars/redhat.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/L

#6928 Added support for calico serviceExternalIPs
  docs/calico.md
  inventory/sample/group_vars/k8s-cluster/k8s-net-calico.yml
  roles/network_plugin/calico/defaults/main.yml
  roles/network_plugin/calico/tasks/install.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/S

#6916 Bump nodelocaldns to 1.16.0
  docs/centos8.md
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/XS

#6933 Allow configuring container log limits for Kubelet
  roles/kubernetes/node/defaults/main.yml
  roles/kubernetes/node/templates/kubelet-config.v1beta1.yaml.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/XS

#6955 Switch some image from dockerhub to k8s.gcr (also increase pkg retries)
  inventory/sample/group_vars/k8s-cluster/addons.yml
  roles/download/defaults/main.yml
  tests/files/packet_centos8-calico.yml
  tests/files/tf-ovh_ubuntu18-calico.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#6610 Update kube-ovn to 1.5.2
  README.md
  roles/download/defaults/main.yml
  roles/network_plugin/kube-ovn/templates/cni-kube-ovn.yml.j2
  roles/network_plugin/kube-ovn/templates/cni-ovn.yml.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/M

#6890 fix: added boto3 as dependency required by kubespray-aws-inventory.py
  contrib/aws_inventory/requirements.txt
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6957 add Google proxy-mirror-cache for docker hub to CI tests
  tests/scripts/testcases_run.sh
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, size/S

#6953 Fix warning of "Enable ip forwarding"
  roles/kubernetes/preinstall/tasks/0080-system-configurations.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#6961 Fix crictl paths and some of docker paths
  roles/etcdctl/tasks/main.yml
  roles/kubernetes/master/handlers/main.yml
  roles/kubernetes/node/tasks/pre_upgrade.yml
  roles/kubernetes/preinstall/handlers/main.yml
  roles/network_plugin/kube-router/handlers/main.yml
  roles/reset/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/M

#6960 Fix yaml syntax error when use multilines in dns_etchosts
  roles/kubernetes-apps/ansible/templates/coredns-config.yml.j2
  roles/kubernetes-apps/ansible/templates/nodelocaldns-config.yml.j2
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#6927 Allow configuring CRI-O for use in offline environments
  roles/container-engine/cri-o/defaults/main.yml
  roles/container-engine/cri-o/tasks/main.yaml
  roles/container-engine/cri-o/templates/crio.conf.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/S

#6930 Disable CRI-O restart by Multus
  roles/network_plugin/multus/templates/multus-daemonset.yml.j2
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#6894 Remove executable bit from some files
  roles/etcd/templates/etcd.j2
  roles/etcd/templates/make-ssl-etcd.sh.j2
  roles/kubernetes-apps/network_plugin/cilium/tasks/main.yml
  roles/kubespray-defaults/tasks/no_proxy.yml
  roles/network_plugin/cilium/defaults/main.yml
  roles/network_plugin/cilium/tasks/main.yml
  roles/network_plugin/cilium/templates/cilium-crb.yml.j2
  roles/network_plugin/cilium/templates/cilium-ds.yml.j2
  roles/network_plugin/cilium/templates/cilium-sa.yml.j2
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/XS

#6962 containerd docker hub registry mirror support
  .gitlab-ci.yml
  docs/containerd.md
  inventory/sample/group_vars/all/containerd.yml
  roles/container-engine/containerd/templates/config.toml.j2
  tests/common/_docker_hub_registry_mirror.yml
  tests/scripts/testcases_run.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#6964 Remove contiv related files
  .gitlab-ci/packet.yml
  README.md
  docs/_sidebar.md
  docs/ci.md
  docs/contiv.md
  inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml
  inventory/sample/group_vars/k8s-cluster/k8s-net-contiv.yml
  roles/download/defaults/main.yml
  roles/kubernetes-apps/network_plugin/contiv/tasks/configure.yml
  roles/kubernetes-apps/network_plugin/contiv/tasks/main.yml
  roles/kubernetes-apps/network_plugin/meta/main.yml
  roles/kubernetes/node/templates/kubelet.env.v1beta1.j2
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
  roles/kubernetes/preinstall/tasks/0050-create_directories.yml
  roles/kubespray-defaults/defaults/main.yaml
  roles/network_plugin/contiv/defaults/main.yml
  roles/network_plugin/contiv/files/contiv-cleanup.sh
  roles/network_plugin/contiv/handlers/main.yml
  roles/network_plugin/contiv/meta/main.yml
  roles/network_plugin/contiv/tasks/main.yml
  roles/network_plugin/contiv/tasks/pre-reset.yml
  roles/network_plugin/contiv/tasks/reset.yml
  roles/network_plugin/contiv/templates/contiv-api-proxy.yml.j2
  roles/network_plugin/contiv/templates/contiv-cleanup.yml.j2
  roles/network_plugin/contiv/templates/contiv-config.yml.j2
  roles/network_plugin/contiv/templates/contiv-etcd-proxy.yml.j2
  roles/network_plugin/contiv/templates/contiv-etcd.yml.j2
  roles/network_plugin/contiv/templates/contiv-netmaster-clusterrole.yml.j2
  roles/network_plugin/contiv/templates/contiv-netmaster-clusterrolebinding.yml.j2
  roles/network_plugin/contiv/templates/contiv-netmaster-serviceaccount.yml.j2
  roles/network_plugin/contiv/templates/contiv-netmaster.yml.j2
  roles/network_plugin/contiv/templates/contiv-netplugin-clusterrole.yml.j2
  roles/network_plugin/contiv/templates/contiv-netplugin-clusterrolebinding.yml.j2
  roles/network_plugin/contiv/templates/contiv-netplugin-serviceaccount.yml.j2
  roles/network_plugin/contiv/templates/contiv-netplugin.yml.j2
  roles/network_plugin/contiv/templates/contiv-ovs.yml.j2
  roles/network_plugin/contiv/templates/generate-certificate.sh.j2
  roles/network_plugin/meta/main.yml
  roles/reset/tasks/main.yml
  tests/files/packet_ubuntu16-contiv-sep.yml
  tests/scripts/md-table/main.py
  tests/testcases/040_check-network-adv.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XXL

#6937 Upgrade Jetstack Cert-Manager v1.0.4
  roles/download/defaults/main.yml
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/clusterrole-cert-manager.yml.j2
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/clusterrolebinding-cert-manager.yml.j2
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/crd-certificate.yml.j2
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/crd-challenge.yml.j2
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/crd-clusterissuer.yml.j2
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/crd-issuer.yml.j2
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/crd-order.yml.j2
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/deploy-cert-manager.yml.j2
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/role-cert-manager.yml.j2
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/rolebinding-cert-manager.yml.j2
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/sa-cert-manager.yml.j2
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/svc-cert-manager.yml.j2
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/webhook-cert-manager.yml.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XXL

#6940 Add test for Fedora CoreOS before creating Docker service file
  roles/container-engine/docker/tasks/systemd.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#6907 fix ansible password authentication
  README.md
  roles/container-engine/containerd/tasks/crictl.yml
  roles/container-engine/cri-o/tasks/crictl.yml
  roles/download/tasks/prep_kubeadm_images.yml
  roles/kubernetes/master/tasks/main.yml
  roles/kubernetes/node/tasks/install.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/M
