Repository kubernetes-sigs/kubespray, pull requests merged in 2020-07, with the labels that each got.

#6339 Add additional metadata configuration options to external Openstack CCM (kubernetes-sigs#6338)
  docs/openstack.md
  inventory/sample/group_vars/all/openstack.yml
  roles/kubernetes-apps/external_cloud_controller/openstack/templates/external-openstack-cloud-config.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/S

#6327 Explicitly set ETCDCTL_API and use ETCDCTL_ENDPOINTS
  roles/etcd/handlers/backup.yml
  roles/etcd/tasks/configure.yml
  roles/etcd/tasks/join_etcd-events_member.yml
  roles/etcd/tasks/join_etcd_member.yml
  roles/recover_control_plane/etcd/tasks/main.yml
  roles/remove-node/remove-etcd-node/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/M

#6276 Patch Calico V3.14.0 roles, missing CR and CRD for calico_kube_controller
  roles/kubernetes-apps/policy_controller/calico/templates/calico-kube-cr.yml.j2
  roles/network_plugin/calico/templates/kdd-crds.yml.j2
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/M

#6329 Cilium: overwrite auto-detected MTU of underlying network
  roles/network_plugin/cilium/defaults/main.yml
  roles/network_plugin/cilium/templates/cilium-ds.yml.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/XS

#6350 Update MetalLB README.md
  roles/kubernetes-apps/metallb/README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/S

#6364 Fix azure-cloud-config.j2 JSON syntax
  roles/kubernetes/node/templates/cloud-configs/azure-cloud-config.j2
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#6363 Fix can't remove etcd node
  roles/remove-node/post-remove/tasks/main.yml
  roles/remove-node/remove-etcd-node/tasks/main.yml
  roles/reset/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/S

#6365 Enable OVH CI
  .gitlab-ci/terraform.yml
  tests/files/tf-ovh_ubuntu18-calico.yml
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, size/M

#6346 [2.13] Fix no_proxy generation tasks
  roles/kubespray-defaults/tasks/no_proxy.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#6312 Local volume provisioner role workaround for mitogen
  roles/kubernetes-apps/external_provisioner/local_volume_provisioner/tasks/basedirs.yml
  roles/kubernetes-apps/external_provisioner/local_volume_provisioner/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/S

#6374 crio: harden downloads with retry
  roles/container-engine/cri-o/tasks/crio_repo.yml
  roles/container-engine/cri-o/tasks/main.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6345 allow kubeadm to upgrade etcd
  roles/kubernetes/master/tasks/kubeadm-upgrade.yml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6337 Add Fedora CoreOS kubevirt image for tests
  test-infra/image-builder/roles/kubevirt-images/defaults/main.yml
  test-infra/image-builder/roles/kubevirt-images/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#6382 Add readiness probe to dns-autoscaler
  roles/kubernetes-apps/ansible/templates/dns-autoscaler.yml.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/XS

#6376 Update cilium minimum kernel preinstall check
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/XS

#6358 Remove deprecated flag for Cinder CSI controllerplugin
  roles/kubernetes-apps/csi_driver/cinder/templates/cinder-csi-controllerplugin-rbac.yml.j2
  roles/kubernetes-apps/csi_driver/cinder/templates/cinder-csi-controllerplugin.yml.j2
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#5554 Fix kube-proxy post deployment removal
  .gitlab-ci/packet.yml
  roles/kubernetes/kubeadm/defaults/main.yml
  roles/kubernetes/kubeadm/tasks/main.yml
  roles/kubernetes/node/defaults/main.yml
  roles/win_nodes/kubernetes_patch/defaults/main.yml
  tests/files/packet_ubuntu16-kube-router-svc-proxy.yml
Labels: approved, cncf-cla: yes, kind/bug, kind/feature, lgtm, ok-to-test, size/S

#6300 Fixed fedora modular repos activation for fcos
  roles/container-engine/cri-o/tasks/crio_repo.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/S

#6347 Respect kube_override_hostname during removal/upgrade
  roles/remove-node/post-remove/tasks/main.yml
  roles/remove-node/pre-remove/tasks/main.yml
  roles/upgrade/post-upgrade/tasks/main.yml
  roles/upgrade/pre-upgrade/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/S

#6393 Add oomichi to reviwers of MetalLB addon
  roles/kubernetes-apps/metallb/OWNERS
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#6359 add calico-node selinux
  roles/network_plugin/calico/templates/calico-node.yml.j2
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#6349 Remove allow-release-candidate-upgrades already include in experimental-upgrades flag
  roles/kubernetes/master/tasks/kubeadm-upgrade.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#6412 Always enable GitLab CI artifacts for cluster-dump
  .gitlab-ci.yml
  .gitlab-ci/terraform.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#6418 Cleanup old build-cephfs-provisioner.yml playbook
  extra_playbooks/build-cephfs-provisioner.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/M

#6373 Add a way to deploy cilium alongside another CNI
  roles/download/defaults/main.yml
  roles/kubernetes-apps/network_plugin/meta/main.yml
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
  roles/network_plugin/cilium/defaults/main.yml
  roles/network_plugin/meta/main.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/S

#6317 add audit webhook support
  roles/kubernetes/master/defaults/main/main.yml
  roles/kubernetes/master/tasks/kubeadm-setup.yml
  roles/kubernetes/master/templates/apiserver-webhook-config.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1beta2.yaml.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/M

#5998 Make all etcd commands use ETCDCTL_API 3
  README.md
  roles/download/defaults/main.yml
  roles/etcd/handlers/backup.yml
  roles/etcd/tasks/configure.yml
  roles/etcd/tasks/join_etcd-events_member.yml
  roles/etcd/tasks/join_etcd_member.yml
  roles/etcd/templates/etcd-events.env.j2
  roles/etcd/templates/etcd.env.j2
  roles/network_plugin/canal/tasks/main.yml
  roles/recover_control_plane/etcd/tasks/main.yml
  roles/recover_control_plane/etcd/tasks/recover_lost_quorum.yml
  roles/remove-node/post-remove/tasks/main.yml
  roles/remove-node/remove-etcd-node/tasks/main.yml
  scripts/collect-info.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, priority/important-soon, release-blocker, size/L

#6413 Replace Openstack with OpenStack in docs
  contrib/terraform/openstack/README.md
  docs/roadmap.md
Labels: approved, cncf-cla: yes, kind/cleanup, kind/documentation, lgtm, size/XS

#6408 change /etc/ssl/etcd to etcd_config_dir param
  roles/etcd/defaults/main.yml
  roles/kubespray-defaults/defaults/main.yaml
  roles/reset/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/XS

#6419 Update the calico_veth_mtu setting to affect IP-in-IP users
  roles/network_plugin/calico/templates/calico-node.yml.j2
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6429 Typo fix: Modprode -> Modprobe
  roles/kubernetes/node/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/XS

#6438 Minor update to Cilium and Calico
  README.md
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#6428 Remove dbus-tools from coreos bootstrap install
  roles/bootstrap-os/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#6433 Felix configuration via extraenvs of calico node
  docs/calico.md
  roles/network_plugin/calico/templates/calico-node.yml.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/S

#6437 Newer version of Local Path Provisioner in samples
  inventory/sample/group_vars/k8s-cluster/addons.yml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6431 Fix Issue 6430: add proxy_env definition to remove_node.yml
  remove-node.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/S

#6439 Update docker package to 19.03.12
  roles/container-engine/docker/vars/debian.yml
  roles/container-engine/docker/vars/fedora.yml
  roles/container-engine/docker/vars/redhat.yml
  roles/container-engine/docker/vars/ubuntu-amd64.yml
  roles/container-engine/docker/vars/ubuntu-arm64.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/M

#6434 Update Cinder CSI manifests to K/1.18
  roles/kubernetes-apps/csi_driver/cinder/templates/cinder-csi-controllerplugin-rbac.yml.j2
  roles/kubernetes-apps/csi_driver/cinder/templates/cinder-csi-controllerplugin.yml.j2
  roles/kubernetes-apps/csi_driver/cinder/templates/cinder-csi-driver.yml.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/S

#6448 Fix remove etcd broken with etcdctl_api 3
  roles/remove-node/remove-etcd-node/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#6444 Update multus version & crio conf
  README.md
  roles/download/defaults/main.yml
  roles/network_plugin/multus/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#6446 Move healthz check to secure ports
  roles/kubernetes/master/handlers/main.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#6455 Update README.md
  README.md
  docs/openstack.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/M

#6417 Adding ansible-lint E404 justification
  roles/container-engine/containerd/tasks/crictl.yml
  roles/container-engine/cri-o/tasks/crictl.yml
  roles/network_plugin/contiv/tasks/pre-reset.yml
  tests/cloud_playbooks/create-aws.yml
  tests/cloud_playbooks/create-do.yml
  tests/cloud_playbooks/create-gce.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/S

#6459 Fix ansible-lint E305
  roles/container-engine/containerd/tasks/main.yml
  roles/container-engine/cri-o/tasks/crictl.yml
  roles/container-engine/docker/tasks/main.yml
  roles/download/tasks/check_pull_required.yml
  roles/download/tasks/download_container.yml
  roles/download/tasks/prep_download.yml
  roles/kubernetes-apps/network_plugin/calico/tasks/main.yml
  roles/kubernetes/kubeadm/tasks/main.yml
  roles/kubernetes/node/tasks/main.yml
  roles/kubernetes/preinstall/tasks/0040-set_facts.yml
  roles/kubernetes/preinstall/tasks/0070-system-packages.yml
  roles/kubernetes/tokens/tasks/gen_tokens.yml
  roles/network_plugin/kube-ovn/tasks/main.yml
  roles/recover_control_plane/etcd/tasks/main.yml
  roles/recover_control_plane/etcd/tasks/recover_lost_quorum.yml
  roles/recover_control_plane/master/tasks/main.yml
  roles/remove-node/remove-etcd-node/tasks/main.yml
  roles/reset/tasks/main.yml
  tests/cloud_playbooks/roles/packet-ci/tasks/delete-vms.yml
  tests/testcases/030_check-network.yml
  tests/testcases/040_check-network-adv.yml
  tests/testcases/roles/cluster-dump/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/L

#6462 Fix shellcheck url
  .gitlab-ci/shellcheck.yml
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, ok-to-test, size/XS

#6463 [2.13] fix shellcheck url
  .gitlab-ci/shellcheck.yml
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, ok-to-test, size/XS

#6465 Fix ansible-lint E301 for commands fetching data
  roles/network_plugin/calico/rr/tasks/main.yml
  roles/network_plugin/calico/tasks/reset.yml
  roles/network_plugin/macvlan/tasks/main.yml
  tests/cloud_playbooks/roles/packet-ci/tasks/create-vms.yml
  tests/cloud_playbooks/upload-logs-gcs.yml
  tests/testcases/015_check-nodes-ready.yml
  tests/testcases/020_check-pods-running.yml
  tests/testcases/030_check-network.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/M

#6464 [2.12] Fix shellcheck url
  .gitlab-ci/shellcheck.yml
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, ok-to-test, size/XS

#6457 [2.13] Move healthz check to secure ports (#6446)
  roles/kubernetes/master/handlers/main.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#6378 Documentation for Ingress
  README.md
  docs/_sidebar.md
  docs/ambassador.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/M

#6405 Upgrade to kubernetes 1.18.6
  README.md
  inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml
  roles/download/defaults/main.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/M

#6435 [2.13] Update hashes and set default version to 1.17.9
  README.md
  inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml
  roles/download/defaults/main.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#6469 azure csi typo
  roles/kubernetes-apps/persistent_volumes/azuredisk-csi/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6467 Replaced a broken link
  roles/kubernetes-apps/ingress_controller/ingress_nginx/README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/XS

#6334 Adding kube-proxy-replacement support in cilium
  .gitlab-ci/packet.yml
  docs/ci.md
  roles/kubespray-defaults/defaults/main.yaml
  roles/network_plugin/cilium/defaults/main.yml
  roles/network_plugin/cilium/templates/cilium-config.yml.j2
  tests/files/packet_debian10-cilium-svc-proxy.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/M

#6421 Fix test if openstack_cacert is a base64 string
  roles/kubernetes/node/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#6426 Move fedora30 jobs to fedora32
  .gitignore
  .gitlab-ci/packet.yml
  README.md
  Vagrantfile
  docs/ci.md
  roles/container-engine/containerd-common/vars/fedora.yml
  roles/container-engine/containerd/defaults/main.yml
  roles/container-engine/docker/defaults/main.yml
  roles/container-engine/docker/vars/fedora.yml
  test-infra/image-builder/roles/kubevirt-images/defaults/main.yml
  tests/cloud_playbooks/roles/packet-ci/defaults/main.yml
  tests/files/packet_fedora32-kube-ovn-containerd.yml
  tests/files/packet_fedora32-weave.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/M

#6381 adding ovn4nfv-k8s-plugin in kubespray
  .gitlab-ci/packet.yml
  README.md
  docs/ci.md
  docs/ovn4nfv.md
  roles/download/defaults/main.yml
  roles/kubernetes-apps/network_plugin/meta/main.yml
  roles/kubernetes-apps/network_plugin/ovn4nfv/tasks/main.yml
  roles/kubernetes/node/templates/kubelet.env.v1beta1.j2
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
  roles/kubernetes/preinstall/tasks/0050-create_directories.yml
  roles/network_plugin/meta/main.yml
  roles/network_plugin/ovn4nfv/defaults/main.yml
  roles/network_plugin/ovn4nfv/tasks/main.yml
  roles/network_plugin/ovn4nfv/templates/ovn-daemonset.yml.j2
  roles/network_plugin/ovn4nfv/templates/ovn4nfv-k8s-plugin.yml.j2
  tests/files/packet_ubuntu18-ovn4nfv.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/XXL
