Repository kubernetes-sigs/kubespray, pull requests merged in 2020-02, with the labels that each got.

#5584 Add LuckySB as an approver
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5590 Update nginx image to latest
  README.md
  roles/download/defaults/main.yml
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/ds-ingress-nginx-controller.yml.j2
  roles/kubernetes-apps/registry/README.md
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#5566 fix duplicates when scheduler_extra_volumes defined
  roles/kubernetes/master/templates/kubeadm-config.v1beta1.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1beta2.yaml.j2
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#5597 Update the url in .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5414 fully clean docker_options from sample inventory
  inventory/sample/group_vars/all/docker.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#5477 Bind docker.service to containerd.service
  roles/container-engine/docker/templates/docker.service.j2
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#5587 Fix etcd deployment type variable location
  docs/cri-o.md
  inventory/sample/group_vars/etcd.yml
  inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S

#5606 Remove last rkt references
  roles/kubernetes/node/tasks/facts.yml
  roles/kubernetes/node/tasks/pre_upgrade.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/S

#5596 force rotate control plane certifcate on master node when upgrade
  roles/kubernetes/master/tasks/kubeadm-upgrade.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#5415 improve documentation about user account and connecting to API
  docs/getting-started.md
  docs/vars.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/S

#5500 Fix recover-control-plane to work with etcd 3.3.x and add CI
  .gitlab-ci.yml
  .gitlab-ci/packet.yml
  docs/recover-control-plane.md
  recover-control-plane.yml
  roles/etcd/defaults/main.yml
  roles/etcd/tasks/configure.yml
  roles/etcd/tasks/install_docker.yml
  roles/etcd/tasks/join_etcd-events_member.yml
  roles/etcd/tasks/join_etcd_member.yml
  roles/recover_control_plane/etcd/tasks/main.yml
  roles/recover_control_plane/etcd/tasks/prepare.yml
  roles/recover_control_plane/etcd/tasks/recover_lost_quorum.yml
  roles/recover_control_plane/master/tasks/main.yml
  roles/recover_control_plane/pre-recover/defaults/main.yml
  roles/recover_control_plane/pre-recover/tasks/main.yml
  tests/cloud_playbooks/roles/packet-ci/tasks/main.yml
  tests/cloud_playbooks/roles/packet-ci/templates/inventory.j2
  tests/files/packet_ubuntu18-calico-ha-recover-noquorum.yml
  tests/files/packet_ubuntu18-calico-ha-recover.yml
  tests/scripts/testcases_run.sh
  tests/templates/inventory-aws.j2
  tests/templates/inventory-do.j2
  tests/templates/inventory-gce.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/L

#5529 Fix default value of kube_api_server_endpoint
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#5579 Upgrade to Kubernetes 1.16.6 [2.12 branch]
  README.md
  inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml
  roles/download/defaults/main.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/M

#5571 Files to archive can be passed directly when gathering etcd and tiller certs
  roles/etcd/tasks/gen_certs_script.yml
  roles/kubernetes-apps/helm/tasks/gen_helm_tiller_certs.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#5627 Upgrade to Kubernetes 1.16.7 [2.12 branch]
  README.md
  inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml
  roles/download/defaults/main.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#5585 Update bug-report.md w/ adding version of Python question
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#5503 Set helm 3.0 as default
  docs/vars.md
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note-action-required, size/XS

#5612 added reference to calico_ip_auto_method in sample inventory group vars
  inventory/sample/group_vars/k8s-cluster/k8s-net-calico.yml
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#5617 Securing http link to https link
  RELEASE.md
  docs/ansible.md
  docs/contiv.md
  docs/dns-stack.md
  docs/integration.md
  docs/large-deployments.md
  docs/vars.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#5608 Remove old features gates
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/S

#5629 Upgrade cri-tools (crictl) to 1.17.0
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#5623 kubelet_config_extra_args and kubelet_node_config_extra_args
  docs/vars.md
  roles/kubernetes/node/defaults/main.yml
  roles/kubernetes/node/templates/kubelet-config.v1beta1.yaml.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/M

#5463 Use 'private_dns' as hostname in inventory file
  contrib/terraform/aws/create-infrastructure.tf
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#5614 updated links in the PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/XS

#5609 [docs] Update docs to match actuall required settings to perform an unsafe u…
  docs/upgrades.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#5523 update Calico CNI description
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#5492 Fix Cinder CSI bugs
  roles/kubernetes-apps/csi_driver/cinder/defaults/main.yml
  roles/kubernetes-apps/csi_driver/cinder/tasks/cinder-credential-check.yml
  roles/kubernetes-apps/csi_driver/cinder/templates/cinder-csi-cloud-config.j2
  roles/kubernetes-apps/csi_driver/cinder/templates/cinder-csi-controllerplugin.yml.j2
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/M

#5334 Added in code to allow control over pull policy for local path provis…
  roles/kubernetes-apps/csi_driver/cinder/templates/cinder-csi-controllerplugin.yml.j2
  roles/kubernetes-apps/external_provisioner/local_path_provisioner/templates/local-path-storage-deployment.yml.j2
  roles/network_plugin/contiv/templates/contiv-etcd.yml.j2
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5624 Ability to define plugins.cri.containerd params
  docs/vars.md
  roles/container-engine/containerd/defaults/main.yml
  roles/container-engine/containerd/templates/config.toml.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#5561 Fix some minor issues with the Cinder CSI plugin
  roles/download/defaults/main.yml
  roles/kubernetes-apps/csi_driver/cinder/templates/cinder-csi-controllerplugin.yml.j2
  roles/kubernetes-apps/csi_driver/cinder/templates/cinder-csi-driver.yml.j2
  roles/kubernetes-apps/csi_driver/cinder/templates/cinder-csi-nodeplugin.yml.j2
  roles/kubernetes-apps/persistent_volumes/cinder-csi/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/L

#5640 remove legacy docker repo in kubernetes/preinstall before install pkg
  roles/kubernetes/preinstall/tasks/0070-system-packages.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#5636 Fixing and issue where if the pids in the orphan list no longer exist…
  roles/container-engine/docker/files/cleanup-docker-orphans.sh
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#5525 Fix to Vagrant config.rb apply correctly
  Vagrantfile
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/M

#5607 Add flatcar
  contrib/vault/roles/vault/tasks/bootstrap/ca_trust.yml
  roles/bootstrap-os/tasks/bootstrap-coreos.yml
  roles/bootstrap-os/tasks/main.yml
  roles/container-engine/docker/handlers/main.yml
  roles/container-engine/docker/tasks/main.yml
  roles/container-engine/docker/tasks/systemd.yml
  roles/download/defaults/main.yml
  roles/download/tasks/download_container.yml
  roles/download/tasks/download_file.yml
  roles/download/tasks/prep_download.yml
  roles/download/tasks/sync_container.yml
  roles/download/tasks/sync_file.yml
  roles/etcd/meta/main.yml
  roles/etcd/tasks/upd_ca_trust.yml
  roles/kubernetes-apps/external_provisioner/local_volume_provisioner/README.md
  roles/kubernetes-apps/helm/tasks/install_host.yml
  roles/kubernetes-apps/helm/tasks/main.yml
  roles/kubernetes/node/tasks/install.yml
  roles/kubernetes/preinstall/handlers/main.yml
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
  roles/kubernetes/preinstall/tasks/0040-set_facts.yml
  roles/kubernetes/preinstall/tasks/0060-resolvconf.yml
  roles/kubernetes/preinstall/tasks/0070-system-packages.yml
  roles/kubernetes/preinstall/tasks/0080-system-configurations.yml
  roles/kubernetes/preinstall/tasks/main.yml
  roles/kubespray-defaults/defaults/main.yaml
  roles/network_plugin/macvlan/handlers/main.yml
  roles/network_plugin/macvlan/tasks/main.yml
  roles/reset/tasks/main.yml
  tests/testcases/015_check-pods-running.yml
  tests/testcases/030_check-network.yml
  tests/testcases/040_check-network-adv.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/L

#5633 Cache facts for 2 hours
  ansible.cfg
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#5616 Fix a typo in integration.md
  docs/integration.md
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#5634 helm default version 3.1.0
  roles/download/defaults/main.yml
  tests/files/packet_debian10-containerd.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/XS

#5413 add az_list_node variable to specify different AZs for kubelets
  contrib/terraform/openstack/kubespray.tf
  contrib/terraform/openstack/modules/compute/main.tf
  contrib/terraform/openstack/modules/compute/variables.tf
  contrib/terraform/openstack/variables.tf
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#5491 External OpenStack Cloud Controller Manager implementation
  cluster.yml
  inventory/sample/group_vars/all/all.yml
  inventory/sample/group_vars/all/openstack.yml
  roles/kubernetes-apps/external_cloud_controller/meta/main.yml
  roles/kubernetes-apps/external_cloud_controller/openstack/defaults/main.yml
  roles/kubernetes-apps/external_cloud_controller/openstack/tasks/main.yml
  roles/kubernetes-apps/external_cloud_controller/openstack/tasks/openstack-credential-check.yml
  roles/kubernetes-apps/external_cloud_controller/openstack/templates/external-openstack-cloud-config-secret.yml.j2
  roles/kubernetes-apps/external_cloud_controller/openstack/templates/external-openstack-cloud-config.j2
  roles/kubernetes-apps/external_cloud_controller/openstack/templates/external-openstack-cloud-controller-manager-ds.yml.j2
  roles/kubernetes-apps/external_cloud_controller/openstack/templates/external-openstack-cloud-controller-manager-role-bindings.yml.j2
  roles/kubernetes-apps/external_cloud_controller/openstack/templates/external-openstack-cloud-controller-manager-roles.yml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1beta1.yaml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1beta2.yaml.j2
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/L

#5658 Make calico iptables lock timeout configurable
  roles/network_plugin/calico/defaults/main.yml
  roles/network_plugin/calico/templates/calico-node.yml.j2
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5620 Do not display skipped hosts/tasks.
  ansible.cfg
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#5651 remove unused var 'kube_apiserver_admission_control' (#5648)
  roles/kubernetes/master/defaults/main/main.yml
  roles/kubernetes/master/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/S

#5659 Add stable repo on all masters with helm 3.x.x
  roles/kubernetes-apps/helm/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#5632 Ignore assertion comparison for kube_network_node_prefix when using calico
  docs/vars.md
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5558 [2.12] Ensure we always fixup kube-proxy kubeconfig
  roles/kubernetes/kubeadm/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#5664 Enhance ha document
  docs/ha-mode.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#5669 @ #5008 | Local path provisioner boolean annotation is rendered incorrectly and not applied
  roles/kubernetes-apps/external_provisioner/local_path_provisioner/templates/local-path-storage-sc.yml.j2
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#5662 Remove dockerproject_.+_repo_.+ variables
  roles/container-engine/containerd/templates/rh_containerd.repo.j2
  roles/container-engine/containerd/templates/rh_docker.repo.j2
  roles/container-engine/docker/defaults/main.yml
  roles/container-engine/docker/tasks/main.yml
  roles/container-engine/docker/vars/debian.yml
  roles/container-engine/docker/vars/ubuntu-amd64.yml
  roles/container-engine/docker/vars/ubuntu-arm64.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/M

#5673 [Openstack] Convert volume resources into dynamic blocks
  contrib/terraform/openstack/modules/compute/main.tf
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XL

#5655 Require a complete inventory with all variables in the bugreport
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#5672 add mangle table in the iptable flush task
  roles/reset/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/flake, lgtm, size/XS

#5678 Modifying Ansible filter 'failed' according to Ansible 2.5 porting guide
  roles/download/tasks/download_container.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#5618 docs: fix some typos
  docs/comparisons.md
  docs/kubernetes-reliability.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5667 Implement topology support for Cinder CSI
  roles/kubernetes-apps/csi_driver/cinder/templates/cinder-csi-controllerplugin.yml.j2
  roles/kubernetes-apps/persistent_volumes/cinder-csi/templates/cinder-csi-storage-class.yml.j2
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S

#5661 Add additional configuration options to external Openstack CCM
  inventory/sample/group_vars/all/openstack.yml
  roles/kubernetes-apps/external_cloud_controller/openstack/templates/external-openstack-cloud-config.j2
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/S

#5601 Upgrade container-engine after draining
  roles/kubernetes/master/tasks/kubeadm-upgrade.yml
  upgrade-cluster.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S

#5695 fix upgrade procedure
  roles/kubernetes/preinstall/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS
