Repository kubernetes-sigs/kubespray, pull requests merged in 2021-05, with the labels that each got.

#7464 Add krew support
  inventory/sample/group_vars/k8s_cluster/addons.yml
  roles/download/defaults/main.yml
  roles/kubernetes-apps/krew/defaults/main.yml
  roles/kubernetes-apps/krew/tasks/krew.yml
  roles/kubernetes-apps/krew/tasks/main.yml
  roles/kubernetes-apps/krew/templates/krew.j2
  roles/kubernetes-apps/krew/templates/krew.yml.j2
  roles/kubernetes-apps/meta/main.yml
  roles/kubespray-defaults/defaults/main.yaml
  roles/reset/tasks/main.yml
  tests/files/packet_centos7-flannel-containerd-addons-ha.yml
  tests/files/packet_debian10-containerd.yml
  tests/files/packet_ubuntu18-flannel-containerd-ha-once.yml
  tests/files/packet_ubuntu18-flannel-containerd-ha.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/L

#7480 Add suport of Vsphere CSI driver 2.X versions
  docs/vsphere-csi.md
  inventory/sample/group_vars/all/vsphere.yml
  roles/kubernetes-apps/csi_driver/vsphere/defaults/main.yml
  roles/kubernetes-apps/csi_driver/vsphere/tasks/main.yml
  roles/kubernetes-apps/csi_driver/vsphere/templates/vsphere-csi-controller-deployment.yml.j2
  roles/kubernetes-apps/csi_driver/vsphere/templates/vsphere-csi-controller-rbac.yml.j2
  roles/kubernetes-apps/csi_driver/vsphere/templates/vsphere-csi-node.yml.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/L

#7572 Add external_openstack_enable_ingress_hostname option for external-openstack-cloud-controller-manager
  roles/kubernetes-apps/external_cloud_controller/openstack/templates/external-openstack-cloud-config.j2
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/XS

#7587 Scale down workflow fails when ipvsadm utility not found on node
  roles/reset/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7592 bump calico 3.18 to v3.18.3
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/XS

#7598 Cleanup duplicate task in etcd role
  roles/etcd/tasks/gen_certs_script.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/S

#7597 Fix reset cluster task failed
  roles/reset/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#7591 allow overriding calico peers names and avoid ipv6 naming issues
  roles/network_plugin/calico/tasks/install.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/XS

#7586 Enable calico CNI kubeconfig token monitor
  roles/network_plugin/calico/templates/calico-node.yml.j2
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#7593 Support Calico advertisement of MetalLB LoadBalancer IPs
  README.md
  docs/metallb.md
  inventory/sample/group_vars/k8s_cluster/addons.yml
  inventory/sample/group_vars/k8s_cluster/k8s-net-calico.yml
  roles/kubernetes-apps/metallb/README.md
  roles/kubernetes-apps/metallb/defaults/main.yml
  roles/kubernetes-apps/metallb/templates/metallb.yml.j2
  roles/network_plugin/calico/defaults/main.yml
  roles/network_plugin/calico/tasks/install.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/L

#7607 fixed MarkupSafe version to 1.1.1
  requirements.txt
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#7578 Replace map in Terraform scripts with tomap (#7576)
  contrib/terraform/aws/create-infrastructure.tf
  contrib/terraform/aws/modules/elb/main.tf
  contrib/terraform/aws/modules/vpc/main.tf
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/M

#7608 update README about supported OSes
  README.md
  docs/amazonlinux.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/S

#7615 remove experimental note about CentOS 8 and derivatives
  README.md
  docs/centos8.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/S

#7617 Update nerdctl version to 0.8.1
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7600 add support for using ansible 2.10.x for deploying kubespray
  README.md
  ansible_version.yml
  roles/kubernetes-apps/ansible/tasks/coredns.yml
  roles/kubernetes-apps/ansible/templates/coredns-clusterrole.yml.j2
  roles/kubernetes-apps/ansible/templates/coredns-clusterrolebinding.yml.j2
  roles/kubernetes-apps/ansible/templates/coredns-sa.yml.j2
  roles/kubernetes-apps/ansible/templates/dns-autoscaler-clusterrole.yml.j2
  roles/kubernetes-apps/ansible/templates/dns-autoscaler-clusterrolebinding.yml.j2
  roles/kubernetes-apps/ansible/templates/dns-autoscaler-sa.yml.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/M

#7612 Fix pull_by_digest variable type to boolean instead of str
  roles/download/tasks/set_container_facts.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#7606 Fix cloud_resolver type from str to list (issue #7605)
  roles/kubernetes/preinstall/tasks/0040-set_facts.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/S

#7431 Add contrib playbook to disable service firewall
  contrib/os-services/os-services.yml
  contrib/os-services/roles/prepare/defaults/main.yml
  contrib/os-services/roles/prepare/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#7619 Fix missing broken_etcd filter in recover control plane task
  roles/recover_control_plane/etcd/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#7623 add note on download_localhost
  docs/downloads.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/XS

#7622 Override the default value of containerd's root, state, and oom_score
  inventory/sample/group_vars/all/containerd.yml
  roles/container-engine/containerd/defaults/main.yml
  roles/container-engine/containerd/templates/config.toml.j2
  tests/files/packet_centos7-flannel-containerd-addons-ha.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/S

#7626 Remove warning about Docker-only support
  docs/downloads.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/XS

#7640 Minor spelling edits
  docs/proxy.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/XS

#7639 Fix Oracle yum disabled repository file after EPEL install
  roles/bootstrap-os/tasks/bootstrap-centos.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S

#7613 Add nodeSelector for other services and node labels before CNI setup
  cluster.yml
  roles/kubernetes-apps/ansible/defaults/main.yml
  roles/kubernetes-apps/ansible/templates/coredns-deployment.yml.j2
  roles/kubernetes-apps/ansible/templates/dns-autoscaler.yml.j2
  roles/kubernetes-apps/ansible/templates/nodelocaldns-daemonset.yml.j2
  roles/kubernetes-apps/policy_controller/calico/defaults/main.yml
  roles/kubernetes-apps/policy_controller/calico/templates/calico-kube-controllers.yml.j2
  roles/network_plugin/calico/defaults/main.yml
  roles/network_plugin/calico/templates/calico-node.yml.j2
  scale.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/S

#7630 Calico: add support for v3.19.1
  roles/download/defaults/main.yml
  roles/kubernetes-apps/policy_controller/calico/templates/calico-kube-controllers.yml.j2
  roles/network_plugin/calico/tasks/install.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/M

#7603 store openstack external cloud controller ca.cert in a k8s secret instead of the host filesystem
  roles/kubernetes-apps/external_cloud_controller/openstack/tasks/main.yml
  roles/kubernetes-apps/external_cloud_controller/openstack/tasks/openstack-write-cacert.yml
  roles/kubernetes-apps/external_cloud_controller/openstack/templates/external-openstack-cloud-config-secret.yml.j2
  roles/kubernetes-apps/external_cloud_controller/openstack/templates/external-openstack-cloud-controller-manager-ds.yml.j2
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/M

#7648 Calico: upgrade 3.18 to 3.18.4
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/S

#7649 Fix docs/nodes.md numbering typo
  docs/nodes.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7647 Update KUBE_VERSION in gitlab-ci following release
  .gitlab-ci.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#7653 Packet renamed
  README.md
  contrib/terraform/packet/README.md
  contrib/terraform/packet/kubespray.tf
  contrib/terraform/packet/sample-inventory/cluster.tfvars
  contrib/terraform/packet/variables.tf
  docs/_sidebar.md
  docs/equinix-metal.md
  docs/roadmap.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/M

#7645 Add retries to 'Set label for route reflector' task
  roles/network_plugin/calico/rr/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#7646 Added possibility to specify vSphere credentials via env variables
  docs/vsphere-csi.md
  docs/vsphere.md
  inventory/sample/group_vars/all/vsphere.yml
  roles/kubernetes-apps/external_cloud_controller/vsphere/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/M

#7655 Update crun 0.19 checksum
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#7657 Add Fedora 33 image and CI, remove Fedora 31 (EOL) + update docker packages
  .gitlab-ci/packet.yml
  README.md
  Vagrantfile
  docs/ci.md
  roles/container-engine/docker/vars/debian.yml
  roles/container-engine/docker/vars/fedora.yml
  roles/container-engine/docker/vars/redhat.yml
  roles/container-engine/docker/vars/ubuntu.yml
  roles/kubernetes/node/vars/fedora-34.yml
  test-infra/image-builder/roles/kubevirt-images/defaults/main.yml
  tests/cloud_playbooks/roles/packet-ci/defaults/main.yml
  tests/files/packet_fedora34-kube-ovn-containerd.yml
  tests/files/packet_fedora34-weave.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/M

#7664 Fix spelling mistakes
  roles/kubernetes-apps/external_provisioner/local_volume_provisioner/README.md
  roles/kubernetes-apps/ingress_controller/ambassador/README.md
  roles/kubernetes-apps/ingress_controller/cert_manager/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS
