Repository kubernetes-sigs/kubespray, pull requests merged in 2021-03, with the labels that each got.

#7328 Update default exoscale master with more RAM
  contrib/terraform/exoscale/default.tfvars
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/XS

#7327 Move centos7-crio CI job to centos8
  .gitlab-ci/packet.yml
  docs/ci.md
  tests/files/packet_centos8-calico.yml
  tests/files/packet_centos8-crio.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#7313 fix: the filename </etc/vault> is Duplicate in the reset role.
  roles/reset/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7324 Fixed: checking the correct value of use_localhost_as_kubeapi_loadbalancer
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/XS

#7326 Fix recover-control-plane undefined 'proxy_disable_env' variable
  recover-control-plane.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#7316 Update dashboard_enabled on sample
  inventory/sample/group_vars/k8s-cluster/addons.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#7300 add option to use calico with azure when using calico in vxlan
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/XS

#7336 fix master node taint removal bug
  roles/kubernetes/control-plane/tasks/kubeadm-setup.yml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7315 Add kube-ipvs0/nodelocaldns to NetworkManager unmanaged-devices
  roles/kubernetes/preinstall/handlers/main.yml
  roles/kubernetes/preinstall/tasks/0062-networkmanager-unmanaged-devices.yml
  roles/kubernetes/preinstall/tasks/0063-networkmanager-dns.yml
  roles/kubernetes/preinstall/tasks/main.yml
  roles/network_plugin/calico/handlers/main.yml
  roles/network_plugin/calico/tasks/install.yml
  roles/reset/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/M

#7338 Stop using kubeadm to update server in kubeconfigs
  roles/kubernetes/control-plane/tasks/kubeadm-fix-apiserver.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/M

#7339 kubeadm-config.v1beta2.yaml.j2: etcd log level arg
  roles/kubernetes/control-plane/templates/kubeadm-config.v1beta2.yaml.j2
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#7343 Add privileged_without_host_devices support
  roles/container-engine/containerd/defaults/main.yml
  roles/container-engine/containerd/templates/config.toml.j2
  roles/container-engine/cri-o/templates/crio.conf.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#7334 Add nodeselector and tolerations for metallb
  inventory/sample/group_vars/k8s-cluster/addons.yml
  roles/kubernetes-apps/metallb/defaults/main.yml
  roles/kubernetes-apps/metallb/templates/metallb.yml.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/M

#7357 ansible and jinja2 updates
  requirements.txt
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/XS

#7347 Fixup kubelet.conf to point to kubelet-client-current.pem
  roles/kubernetes/control-plane/tasks/kubelet-fix-client-cert-rotation.yml
  roles/kubernetes/control-plane/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S

#7265 Disable gather_facts for correctly work via bastion
  scale.yml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7348 Check for dummy kernel module
  roles/kubernetes/preinstall/tasks/0080-system-configurations.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/XS

#7364 Update crun binary version
  roles/container-engine/crun/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#7367 Fix dynamic inventory link
  docs/getting-started.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/XS

#7360 Terraform support for UpCloud
  .gitlab-ci/terraform.yml
  contrib/terraform/upcloud/README.md
  contrib/terraform/upcloud/cluster-settings.tfvars
  contrib/terraform/upcloud/main.tf
  contrib/terraform/upcloud/modules/kubernetes-cluster/main.tf
  contrib/terraform/upcloud/modules/kubernetes-cluster/output.tf
  contrib/terraform/upcloud/modules/kubernetes-cluster/variables.tf
  contrib/terraform/upcloud/modules/kubernetes-cluster/versions.tf
  contrib/terraform/upcloud/output.tf
  contrib/terraform/upcloud/sample-inventory/cluster.tfvars
  contrib/terraform/upcloud/sample-inventory/group_vars
  contrib/terraform/upcloud/templates/inventory.tpl
  contrib/terraform/upcloud/variables.tf
  contrib/terraform/upcloud/versions.tf
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#7361 Update upgrades.md
  docs/upgrades.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/S

#7376 Add most_recent = true while retrieving the latest image
  contrib/terraform/openstack/modules/compute/main.tf
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#7375 Fixup one more missing kubespray-defaults
  scale.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#7331 Upgrade openSUSE Leap to 15.2
  README.md
  Vagrantfile
  docs/opensuse.md
  test-infra/image-builder/roles/kubevirt-images/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/S

#7383 correct a wrong word
  docs/kata-containers.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7382 Add etcd max snapshot and wals
  roles/etcd/defaults/main.yml
  roles/etcd/templates/etcd.env.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/S

#7380 Change default OCCM internal and public networks variables to empty lists
  docs/openstack.md
  inventory/sample/group_vars/all/openstack.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/S

#7372 Download Calico KDD CRDs
  docs/offline-environment.md
  inventory/sample/group_vars/k8s-cluster/offline.yml
  roles/download/defaults/main.yml
  roles/download/tasks/extract_file.yml
  roles/network_plugin/calico/tasks/install.yml
  roles/network_plugin/calico/templates/kdd-crds.yml.j2
Labels: approved, cncf-cla: yes, kind/design, lgtm, size/XXL

#7353 Added experimental cri-o support for Amazon Linux 2
  roles/container-engine/cri-o/tasks/crio_repo.yml
  roles/container-engine/cri-o/vars/amazon.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/M

#7386 Fix calico crds missing 3.16.9
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#7370 Download crun using download_file.yml
  roles/container-engine/crun/defaults/main.yml
  roles/container-engine/crun/tasks/main.yml
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#7358 Auto renew control plane certificates
  inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml
  roles/kubernetes/control-plane/defaults/main/main.yml
  roles/kubernetes/control-plane/tasks/kubeadm-setup.yml
  roles/kubernetes/control-plane/tasks/main.yml
  roles/kubernetes/control-plane/templates/k8s-certs-renew.service.j2
  roles/kubernetes/control-plane/templates/k8s-certs-renew.sh.j2
  roles/kubernetes/control-plane/templates/k8s-certs-renew.timer.j2
  roles/reset/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/M

#7393 download kata bin useing download_file
  roles/container-engine/kata-containers/defaults/main.yml
  roles/container-engine/kata-containers/tasks/main.yml
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#7384 Fix cinder cert permissions
  roles/kubernetes-apps/external_cloud_controller/openstack/templates/external-openstack-cloud-controller-manager-ds.yml.j2
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#7397 MetalLB: bump to v0.9.6
  inventory/sample/group_vars/k8s-cluster/addons.yml
  roles/kubernetes-apps/metallb/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/XS

#7342 Add support for cilium ipsec
  roles/network_plugin/cilium/defaults/main.yml
  roles/network_plugin/cilium/tasks/check.yml
  roles/network_plugin/cilium/tasks/install.yml
  roles/network_plugin/cilium/tasks/main.yml
  roles/network_plugin/cilium/templates/cilium-config.yml.j2
  roles/network_plugin/cilium/templates/cilium-ds.yml.j2
  roles/network_plugin/cilium/templates/cilium-secret.yml.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/L

#7401 fix: correct hardcoded macvlan template, use var macvlan_interface.
  roles/network_plugin/macvlan/templates/centos-network-macvlan.cfg.j2
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#7402 Set Kube-router version to 1.2.0
  README.md
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#7400 Remove vault
  README.md
  contrib/terraform/openstack/modules/compute/main.tf
  contrib/vault/groups_vars/vault.yaml
  contrib/vault/requirements.txt
  contrib/vault/roles/etcd/vault/tasks/gen_certs_vault.yml
  contrib/vault/roles/etcd/vault/tasks/sync_etcd_master_certs.yml
  contrib/vault/roles/etcd/vault/tasks/sync_etcd_node_certs.yml
  contrib/vault/roles/kubernetes/vault-secrets/tasks/gen_certs_vault.yml
  contrib/vault/roles/kubernetes/vault-secrets/tasks/sync_kube_master_certs.yml
  contrib/vault/roles/kubernetes/vault-secrets/tasks/sync_kube_node_certs.yml
  contrib/vault/roles/vault/defaults/main.yml
  contrib/vault/roles/vault/handlers/main.yml
  contrib/vault/roles/vault/meta/main.yml
  contrib/vault/roles/vault/tasks/bootstrap/ca_trust.yml
  contrib/vault/roles/vault/tasks/bootstrap/create_mounts.yml
  contrib/vault/roles/vault/tasks/bootstrap/create_roles.yml
  contrib/vault/roles/vault/tasks/bootstrap/gen_vault_certs.yml
  contrib/vault/roles/vault/tasks/bootstrap/main.yml
  contrib/vault/roles/vault/tasks/bootstrap/start_vault_temp.yml
  contrib/vault/roles/vault/tasks/bootstrap/sync_etcd_certs.yml
  contrib/vault/roles/vault/tasks/bootstrap/sync_secrets.yml
  contrib/vault/roles/vault/tasks/bootstrap/sync_vault_certs.yml
  contrib/vault/roles/vault/tasks/cluster/binary.yml
  contrib/vault/roles/vault/tasks/cluster/configure.yml
  contrib/vault/roles/vault/tasks/cluster/create_mounts.yml
  contrib/vault/roles/vault/tasks/cluster/create_roles.yml
  contrib/vault/roles/vault/tasks/cluster/init.yml
  contrib/vault/roles/vault/tasks/cluster/main.yml
  contrib/vault/roles/vault/tasks/cluster/systemd.yml
  contrib/vault/roles/vault/tasks/cluster/unseal.yml
  contrib/vault/roles/vault/tasks/main.yml
  contrib/vault/roles/vault/tasks/shared/auth_backend.yml
  contrib/vault/roles/vault/tasks/shared/cert_auth_mount.yml
  contrib/vault/roles/vault/tasks/shared/check_etcd.yml
  contrib/vault/roles/vault/tasks/shared/check_vault.yml
  contrib/vault/roles/vault/tasks/shared/config_ca.yml
  contrib/vault/roles/vault/tasks/shared/create_mount.yml
  contrib/vault/roles/vault/tasks/shared/create_role.yml
  contrib/vault/roles/vault/tasks/shared/find_leader.yml
  contrib/vault/roles/vault/tasks/shared/gen_ca.yml
  contrib/vault/roles/vault/tasks/shared/gen_userpass.yml
  contrib/vault/roles/vault/tasks/shared/issue_cert.yml
  contrib/vault/roles/vault/tasks/shared/pki_mount.yml
  contrib/vault/roles/vault/tasks/shared/sync.yml
  contrib/vault/roles/vault/tasks/shared/sync_auth_certs.yml
  contrib/vault/roles/vault/tasks/shared/sync_file.yml
  contrib/vault/roles/vault/templates/docker.service.j2
  contrib/vault/roles/vault/templates/host.service.j2
  contrib/vault/roles/vault/templates/http-proxy.conf.j2
  contrib/vault/vault.md
  docs/upgrades.md
  inventory/sample/group_vars/all/all.yml
  roles/etcd/defaults/main.yml
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
  roles/reset/tasks/main.yml
  tests/cloud_playbooks/roles/packet-ci/templates/inventory.j2
  tests/templates/inventory-aws.j2
  tests/templates/inventory-do.j2
  tests/templates/inventory-gce.j2
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XXL

#7404 Add cryptography installation
  requirements.txt
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#7396 Allow connecting to bastion via non-standard SSH port
  roles/bastion-ssh-config/tasks/main.yml
  roles/bastion-ssh-config/templates/ssh-bastion.conf
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#6919 Improve ARM 64 support
  roles/kubernetes/control-plane/templates/kubeadm-config.v1beta2.yaml.j2
Labels: approved, cncf-cla: yes, kind/bug, lgtm, lifecycle/stale, ok-to-test, size/XS

#7410 Fix k8s-certs-renew for k8s <= 1.19
  roles/kubernetes/control-plane/templates/k8s-certs-renew.sh.j2
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#7405 Fix remove-node by removing jq usage
  roles/remove-node/pre-remove/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S

#7408 Remove obsolete DNSSEC config management in bootstrap-debian.yml
  roles/bootstrap-os/tasks/bootstrap-debian.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/S

#7414 cilium not needed this handlers
  roles/network_plugin/cilium/handlers/main.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/S

#7416 Update cilium-operator clusterrole
  roles/network_plugin/cilium/templates/cilium-cr.yml.j2
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7419 add support for custom bird calico port
  roles/network_plugin/calico/defaults/main.yml
  roles/network_plugin/calico/tasks/install.yml
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#7412 Remove left over nodes_to_drain
  roles/remove-node/pre-remove/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#7422 Update k8s-certs-renew.sh.j2
  roles/kubernetes/control-plane/templates/k8s-certs-renew.sh.j2
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS
