Repository kubernetes-sigs/kubespray, pull requests merged in 2021-11, with the labels that each got.

#8144 Ensure addon-resizer 1.8.11 only effective at arch amd64.
  roles/kubernetes-apps/metrics_server/defaults/main.yml
  roles/kubernetes-apps/metrics_server/tasks/main.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#8148 fix(doc): update typo
  docs/setting-up-your-first-cluster.md
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/documentation

#8142 [2.17] Update kubernetes version to 1.21.6
  README.md
  inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
  roles/download/defaults/main.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved, kind/feature

#8153 Fix-CI: python was upgraded in CI to 3.10 and pathlib is now included
  tests/scripts/md-table/requirements.txt
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved

#8157 fix calico crds hashes for 3.20.2
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/feature

#8118 heketi: fix deployment logic that was broken by the ansible 3.4 upgrade
  contrib/network-storage/heketi/roles/provision/tasks/secret.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#8147 Mitogen: deprecate the use of mitogen and remove coverage from CI
  .gitlab-ci/packet.yml
  .gitlab-ci/terraform.yml
  Makefile
  ansible.cfg
  docs/ansible.md
  docs/mitogen.md
  tests/scripts/testcases_run.sh
Labels: cncf-cla: yes, size/M, lgtm, approved, kind/cleanup

#8107 Fix containerd install for fcos
  roles/container-engine/containerd/tasks/main.yml
  roles/container-engine/runc/defaults/main.yml
  roles/container-engine/runc/tasks/main.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/container-managers

#8123 Fix Kubelet and Containerd when using cgroupfs
  docs/vars.md
  roles/container-engine/containerd/defaults/main.yml
  roles/container-engine/containerd/tasks/facts.yml
  roles/container-engine/containerd/tasks/main.yml
  roles/container-engine/containerd/templates/config.toml.j2
  roles/kubernetes/node/defaults/main.yml
  roles/kubernetes/node/tasks/facts.yml
  roles/kubernetes/node/templates/kubelet-config.v1beta1.yaml.j2
Labels: cncf-cla: yes, size/M, lgtm, approved, kind/container-managers

#8135 cert-manager: add trusted internal ca when configured
  docs/cert_manager.md
  inventory/sample/group_vars/k8s_cluster/addons.yml
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/cert-manager.yml.j2
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/feature

#8162 Bump crun version 1.2 to 1.3
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature, release-note-none

#7895 Added ArgoCD kubernetes-app
  inventory/sample/group_vars/k8s_cluster/addons.yml
  roles/kubernetes-apps/argocd/defaults/main.yml
  roles/kubernetes-apps/argocd/tasks/main.yml
  roles/kubernetes-apps/argocd/templates/argocd-namespace.yml.j2
  roles/kubernetes-apps/meta/main.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: cncf-cla: yes, size/L, lgtm, ok-to-test, approved, kind/feature

#8164 Fix cloud_provider check
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved

#8160 Replace path_join to support Ansible 2.9
  roles/reset/tasks/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note

#8167 Add vxlanEnabled spec in FelixConfiguration
  roles/network_plugin/calico/tasks/install.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/network

#8101 Limit kubectl delete node to k8s nodes
  roles/remove-node/post-remove/tasks/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note

#8168 krew: update to v0.4.2
  roles/download/defaults/main.yml
  roles/kubernetes-apps/krew/tasks/krew.yml
  roles/kubernetes-apps/krew/templates/krew.yml.j2
  roles/kubespray-defaults/defaults/main.yaml
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/feature

#8130 Docker: replace the use of containerd_version with docker_containerd_version
  docs/upgrades.md
  docs/vars.md
  roles/container-engine/docker/vars/debian-stretch.yml
  roles/container-engine/docker/vars/debian.yml
  roles/container-engine/docker/vars/fedora.yml
  roles/container-engine/docker/vars/redhat.yml
  roles/container-engine/docker/vars/ubuntu-16.yml
  roles/container-engine/docker/vars/ubuntu.yml
  roles/download/defaults/main.yml
  roles/kubespray-defaults/defaults/main.yaml
  tests/files/packet_debian9-calico-upgrade-once.yml
  tests/files/packet_debian9-calico-upgrade.yml
  tests/files/packet_debian9-macvlan.yml
  tests/files/packet_ubuntu16-canal-kubeadm-ha.yml
  tests/files/packet_ubuntu16-canal-sep.yml
  tests/files/packet_ubuntu16-flannel-ha.yml
  tests/files/packet_ubuntu16-kube-router-sep.yml
  tests/files/packet_ubuntu16-kube-router-svc-proxy.yml
  tests/files/packet_ubuntu16-weave-sep.yml
Labels: cncf-cla: yes, size/M, lgtm, approved, kind/container-managers

#8171 Add krew auto completion
  roles/kubernetes-apps/krew/tasks/krew.yml
  roles/reset/tasks/main.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, release-note

#8129 containerd: upgrade versions 1.4.11 and 1.5.7 and make 1.4.11 the default
  roles/download/defaults/main.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/feature

#8068 Kata-Containers: Fix kata-containers runtime
  roles/container-engine/kata-containers/molecule/default/converge.yml
  roles/container-engine/kata-containers/molecule/default/files/10-mynet.conf
  roles/container-engine/kata-containers/molecule/default/files/container.json
  roles/container-engine/kata-containers/molecule/default/files/sandbox.json
  roles/container-engine/kata-containers/molecule/default/prepare.yml
  roles/container-engine/kata-containers/molecule/default/tests/test_default.py
  roles/container-engine/kata-containers/tasks/main.yml
  roles/container-engine/kata-containers/templates/configuration-qemu.toml.j2
  roles/download/defaults/main.yml
  roles/reset/tasks/main.yml
Labels: kind/bug, cncf-cla: yes, size/L, lgtm, ok-to-test, approved

#8172 Exercise multiple ansible versions in CI
  .gitlab-ci.yml
  .gitlab-ci/packet.yml
  ansible_version.yml
  requirements-2.10.txt
  requirements-2.11.txt
  requirements-2.9.txt
  requirements-2.9.yml
  requirements.txt
  tests/files/packet_ubuntu20-calico-aio-ansible-2_11.yml
  tests/files/packet_ubuntu20-calico-aio-ansible-2_9.yml
  tests/requirements-2.10.txt
  tests/requirements-2.11.txt
  tests/requirements-2.9.txt
  tests/requirements.txt
  tests/scripts/testcases_prepare.sh
  tests/scripts/testcases_run.sh
Labels: cncf-cla: yes, size/L, lgtm, approved, kind/feature

#8137 Added tolerations for cinder-csi-nodeplugin DaemonSet
  roles/kubernetes-apps/csi_driver/cinder/defaults/main.yml
  roles/kubernetes-apps/csi_driver/cinder/templates/cinder-csi-nodeplugin.yml.j2
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#8178 Fixes various issues in vSphere Terraform code
  contrib/terraform/vsphere/README.md
  contrib/terraform/vsphere/default.tfvars
  contrib/terraform/vsphere/main.tf
  contrib/terraform/vsphere/modules/kubernetes-cluster/main.tf
  contrib/terraform/vsphere/modules/kubernetes-cluster/output.tf
  contrib/terraform/vsphere/modules/kubernetes-cluster/templates/cloud-init.tmpl
  contrib/terraform/vsphere/modules/kubernetes-cluster/variables.tf
  contrib/terraform/vsphere/output.tf
  contrib/terraform/vsphere/variables.tf
Labels: cncf-cla: yes, size/L, lgtm, ok-to-test, approved, kind/cleanup

#8185 Fix krew auto completion command not found at lower version
  roles/kubernetes-apps/krew/tasks/krew.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#8184 calico add support for container ip forwarding setting
  roles/network_plugin/calico/defaults/main.yml
  roles/network_plugin/calico/templates/cni-calico.conflist.j2
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/network

#8190 change krew uri to krew_download_url
  roles/kubernetes-apps/krew/templates/krew.yml.j2
Labels: cncf-cla: yes, size/S, lgtm, approved, kind/cleanup

#8158 Remove extra parameter kube_proxy_remove
  docs/calico.md
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
  roles/kubespray-defaults/defaults/main.yaml
  tests/files/packet_centos8-calico-ha-ebpf.yml
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/documentation, kind/cleanup

#8192 Python: bring back python 2.7 support for ansible 2.9 in supported EL distributions
  requirements-2.9.txt
  tests/requirements-2.9.txt
Labels: cncf-cla: yes, size/S, lgtm, approved, kind/feature

#8196 Remove helm duplicate check task
  roles/kubernetes-apps/helm/tasks/main.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved

#8193 Allow setting 'auto-assign' property to 'false' for default IP pool (Metallb addon)
  inventory/sample/group_vars/k8s_cluster/addons.yml
  roles/kubernetes-apps/metallb/defaults/main.yml
  roles/kubernetes-apps/metallb/templates/metallb-config.yml.j2
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/applications

#8179 Add possibility of automation creation of Load Balancers on Google Compute Engine
  docs/gcp-lb.md
  roles/kubernetes/control-plane/templates/kubeadm-config.v1beta2.yaml.j2
  roles/kubernetes/node/tasks/main.yml
  roles/kubernetes/node/templates/cloud-configs/gce-cloud-config.j2
  roles/kubernetes/node/templates/kubelet.env.v1beta1.j2
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/feature

#8203 Allow to scrape etcd metrics using a service
  docs/etcd.md
  roles/etcd/defaults/main.yml
  roles/kubernetes-apps/ansible/defaults/main.yml
  roles/kubernetes-apps/ansible/tasks/etcd_metrics.yml
  roles/kubernetes-apps/ansible/tasks/main.yml
  roles/kubernetes-apps/ansible/templates/etcd_metrics-endpoints.yml.j2
  roles/kubernetes-apps/ansible/templates/etcd_metrics-service.yml.j2
  roles/kubespray-defaults/defaults/main.yaml
Labels: cncf-cla: yes, size/L, lgtm, ok-to-test, approved, kind/feature

#8205 Fix fedora reset
  .gitlab-ci/packet.yml
  roles/reset/tasks/main.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved

#8208 Fix wrong baseurl for centos extra repo for Oracle Linux
  roles/bootstrap-os/tasks/bootstrap-centos.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#8210 [2.17] Fix-CI: python was upgraded in CI to 3.10
  requirements.txt
  tests/scripts/md-table/requirements.txt
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/failing-test

#8181 [2.17] Fix kubespray flatcar ansible_os_family and ansible_distribution
  roles/bootstrap-os/tasks/main.yml
  roles/container-engine/containerd/tasks/main.yml
  roles/container-engine/docker/handlers/main.yml
  roles/container-engine/docker/tasks/main.yml
  roles/container-engine/docker/tasks/systemd.yml
  roles/download/defaults/main.yml
  roles/download/tasks/prep_download.yml
  roles/etcd/meta/main.yml
  roles/etcd/tasks/upd_ca_trust.yml
  roles/kubernetes/node/tasks/install.yml
  roles/kubernetes/preinstall/handlers/main.yml
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
  roles/kubernetes/preinstall/tasks/0040-set_facts.yml
  roles/kubernetes/preinstall/tasks/0060-resolvconf.yml
  roles/kubernetes/preinstall/tasks/0070-system-packages.yml
  roles/kubernetes/preinstall/tasks/0080-system-configurations.yml
  roles/kubernetes/preinstall/tasks/main.yml
  roles/kubespray-defaults/defaults/main.yaml
  roles/network_plugin/macvlan/handlers/main.yml
  roles/network_plugin/macvlan/tasks/main.yml
  roles/reset/tasks/main.yml
  tests/testcases/015_check-nodes-ready.yml
  tests/testcases/020_check-pods-running.yml
  tests/testcases/030_check-network.yml
  tests/testcases/040_check-network-adv.yml
Labels: kind/bug, cncf-cla: yes, size/M, lgtm, ok-to-test, approved

#8214 Use Pre-existing Floating IP for Bastion
  contrib/terraform/openstack/README.md
  contrib/terraform/openstack/kubespray.tf
  contrib/terraform/openstack/modules/ips/main.tf
  contrib/terraform/openstack/modules/ips/outputs.tf
  contrib/terraform/openstack/modules/ips/variables.tf
  contrib/terraform/openstack/variables.tf
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/feature

#8206 Fix typo in Containerd configuration
  roles/container-engine/containerd/defaults/main.yml
  roles/container-engine/containerd/tasks/facts.yml
  roles/container-engine/containerd/tasks/main.yml
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, approved

#8215 Fix debian 9 check for apt cache update
  roles/bootstrap-os/tasks/bootstrap-debian.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved

#8209 CI: use images from quay.io to prevent being throttled by docker hub
  roles/container-engine/docker/molecule/default/tests/test_default.py
  roles/container-engine/gvisor/molecule/default/files/container.json
  roles/container-engine/gvisor/molecule/default/tests/test_default.py
  roles/container-engine/kata-containers/molecule/default/files/container.json
  roles/container-engine/kata-containers/molecule/default/tests/test_default.py
  tests/common/_docker_hub_registry_mirror.yml
Labels: cncf-cla: yes, size/S, lgtm, approved, kind/failing-test

#7823 docs: remove basic auth reference in getting-started
  docs/getting-started.md
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/documentation

#8202 Enable experimental modules when rpm-ostree version >= 2021.9
  roles/container-engine/cri-o/tasks/crio_repo.yml
  roles/container-engine/cri-o/tasks/main.yaml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/container-managers

#8198 Update registry template
  docs/kubernetes-apps/registry.md
  roles/kubernetes-apps/registry/defaults/main.yml
  roles/kubernetes-apps/registry/templates/registry-pvc.yml.j2
  roles/kubernetes-apps/registry/templates/registry-rs.yml.j2
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/feature

#8046 Add option to set different server group policy for etcd, node, and master server
  contrib/terraform/openstack/README.md
  contrib/terraform/openstack/kubespray.tf
  contrib/terraform/openstack/modules/compute/main.tf
  contrib/terraform/openstack/modules/compute/variables.tf
  contrib/terraform/openstack/variables.tf
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/applications

#8224 DeprecationWarning occurs when indentfirst=None is specified in coredns-config.yml.j2
  roles/kubernetes-apps/ansible/templates/coredns-config.yml.j2
  roles/kubernetes-apps/ansible/templates/nodelocaldns-config.yml.j2
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/cert-manager.yml.j2
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#8227 Reduce calico bird route removal time to improving Kubernetes node removal performance
  roles/network_plugin/calico/tasks/reset.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/feature

#8231 add Gather facts to remove-node.yml
  remove-node.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#8238 Update calico versions
  README.md
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/S, lgtm, approved, kind/feature, release-note-none

#8240 [2.17] Add vxlanEnabled spec in FelixConfiguration
  roles/network_plugin/calico/tasks/install.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#8219 OEL7: Fix CentOS7 Extras for OEL7
  .gitlab-ci/vagrant.yml
  roles/bootstrap-os/tasks/bootstrap-centos.yml
  tests/scripts/molecule_logs.sh
  tests/scripts/molecule_run.sh
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, approved

#8243 Various documentation updates
  CONTRIBUTING.md
  docs/ci-setup.md
  docs/kata-containers.md
  docs/roadmap.md
  docs/vars.md
Labels: cncf-cla: yes, size/M, lgtm, approved, kind/documentation

#8245 containerd: properly pull images with containerd specific tools
  roles/download/tasks/prep_download.yml
  roles/download/tasks/set_container_facts.yml
Labels: cncf-cla: yes, size/S, lgtm, approved, kind/container-managers

#8241 Add capability to use swap, requires Kube 1.22
  .gitlab-ci/packet.yml
  docs/ci.md
  roles/kubernetes/node/templates/kubelet-config.v1beta1.yaml.j2
  roles/kubernetes/preinstall/tasks/0010-swapoff.yml
  tests/files/packet_fedora35-calico-swap-selinux.yml
Labels: cncf-cla: yes, size/M, lgtm, approved, kind/feature

#8254 offline install using containerd runtime
  inventory/sample/group_vars/all/offline.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/documentation

#8255 Update docker to 20.10.11 with containerd 1.4.12
  roles/container-engine/docker/vars/amazon.yml
  roles/container-engine/docker/vars/debian.yml
  roles/container-engine/docker/vars/fedora.yml
  roles/container-engine/docker/vars/redhat.yml
  roles/container-engine/docker/vars/ubuntu.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: cncf-cla: yes, size/M, lgtm, approved, kind/feature

#8256 Add option for boot volume type for k8s node
  contrib/terraform/openstack/README.md
  contrib/terraform/openstack/kubespray.tf
  contrib/terraform/openstack/modules/compute/main.tf
  contrib/terraform/openstack/modules/compute/variables.tf
  contrib/terraform/openstack/variables.tf
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/feature

#8246 Drop support for Fedora 33 (eol)
  .gitlab-ci/packet.yml
  README.md
  Vagrantfile
  docs/ci.md
  roles/bootstrap-os/tasks/main.yml
  roles/container-engine/cri-o/molecule/default/molecule.yml
  test-infra/image-builder/roles/kubevirt-images/defaults/main.yml
  tests/cloud_playbooks/roles/packet-ci/defaults/main.yml
  tests/files/packet_fedora33-calico.yml
  tests/files/packet_fedora35-docker-calico.yml
Labels: cncf-cla: yes, size/M, lgtm, approved, kind/cleanup
