Repository kubernetes-sigs/kubespray, pull requests merged in 2021-01, with the labels that each got.

#6969 calico: check if inventory settings match cluster settings
  roles/network_plugin/calico/tasks/check.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/S

#7074 Remove libseccomp install tasks
  roles/container-engine/containerd/tasks/main.yml
  roles/container-engine/cri-o/tasks/main.yaml
  roles/container-engine/docker/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/S

#7093 Add repo name for Fedora
  roles/container-engine/containerd/vars/fedora.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#7094 Improve reset
  roles/reset/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/M

#7098 Allow containerd root and state path to be configured
  roles/container-engine/containerd/defaults/main.yml
  roles/container-engine/containerd/templates/config.toml.j2
  tests/files/packet_centos7-flannel-containerd-addons-ha.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#7078 Valuating conditional (need_https_proxy.rc != 0) fail if http_proxy set and skip_http_proxy_on_os_packages is true
  inventory/sample/group_vars/all/all.yml
  roles/bootstrap-os/tasks/bootstrap-debian.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#7024 Add manage-offline-container-images.sh
  contrib/offline/README.md
  contrib/offline/docker-daemon.json
  contrib/offline/manage-offline-container-images.sh
  contrib/offline/registries.conf
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/L

#7107 Remove last 1.19.5 references
  Dockerfile
  inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#7106 Add docker 20.10 to available packages
  roles/container-engine/docker/vars/debian.yml
  roles/container-engine/docker/vars/fedora.yml
  roles/container-engine/docker/vars/redhat.yml
  roles/container-engine/docker/vars/ubuntu-amd64.yml
  roles/container-engine/docker/vars/ubuntu-arm64.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#7108 Fix mardownlint failures of offline
  contrib/offline/README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#7109 Ignore all .git* for mardownlint
  .gitlab-ci/lint.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#7102 Proxy small fixes
  docs/proxy.md
  roles/bootstrap-os/tasks/bootstrap-centos.yml
  roles/bootstrap-os/tasks/bootstrap-fedora.yml
  roles/bootstrap-os/tasks/bootstrap-redhat.yml
  roles/kubespray-defaults/tasks/no_proxy.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/M

#7114 Restore ability to set pod eviction timer
  docs/kubernetes-reliability.md
  docs/large-deployments.md
  roles/kubernetes/master/defaults/main/main.yml
  roles/kubernetes/master/templates/kubeadm-config.v1beta2.yaml.j2
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/M

#7117 Update sample to 3 master node
  inventory/sample/inventory.ini
Labels: approved, cncf-cla: yes, kind/flake, lgtm, size/XS

#7121 calico: fix warnings
  roles/network_plugin/calico/tasks/install.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/S

#7125 Typo fix: kuberntes -> kubernetes
  docs/getting-started.md
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/XS

#7128 Service is in unknown state fix
  requirements.txt
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#7020 Add ping_access_ip to control ping test
  inventory/sample/group_vars/all/all.yml
  roles/kubernetes/preinstall/defaults/main.yml
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/XS

#7126 Update containerd documentation with etcd change
  docs/containerd.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7095 Rework proxy support
  cluster.yml
  remove-node.yml
  reset.yml
  roles/bootstrap-os/tasks/bootstrap-centos.yml
  roles/bootstrap-os/tasks/bootstrap-coreos.yml
  roles/bootstrap-os/tasks/bootstrap-debian.yml
  roles/bootstrap-os/tasks/bootstrap-fedora.yml
  roles/bootstrap-os/tasks/bootstrap-flatcar.yml
  roles/bootstrap-os/tasks/main.yml
  roles/container-engine/containerd/tasks/containerd_repo.yml
  roles/container-engine/crun/tasks/main.yml
  roles/container-engine/docker/tasks/main.yml
  roles/download/tasks/download_file.yml
  roles/kubespray-defaults/tasks/main.yaml
  scale.yml
  upgrade-cluster.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/L

#7130 Require 2.9.0 <= Ansible version < 2.10.0
  README.md
  ansible_version.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/S

#7120 Remove unnecessary failed_when
  roles/download/tasks/check_pull_required.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#7132 update docs main menu with CRI section
  docs/_sidebar.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/XS

#7127 Fix and document environment variable KUBE_MASTERS
  contrib/inventory_builder/inventory.py
Labels: approved, cncf-cla: yes, kind/api-change, kind/bug, kind/documentation, lgtm, ok-to-test, size/XS

#7144 change nginx default HTTPS protocol from "SSLv2" to "TLSv1.2 TLSv1.3"
  inventory/sample/group_vars/k8s-cluster/addons.yml
Labels: approved, cncf-cla: yes, kind/flake, lgtm, size/XS

#7145 Remove unnecessary condition check when updating server field in kube-proxy kubeconfig
  roles/kubernetes/kubeadm/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#7138 change nodeSelector label from deprecated beta.kubernetes.io
  roles/kubernetes-apps/metallb/templates/metallb.yml.j2
  roles/network_plugin/ovn4nfv/templates/ovn-daemonset.yml.j2
  roles/network_plugin/ovn4nfv/templates/ovn4nfv-k8s-plugin.yml.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#7149 preinstall: check etcd_deployment_type
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/XS

#7150 Update hashes and set default version to 1.19.7
  Dockerfile
  README.md
  inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml
  roles/download/defaults/main.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/M

#7134 test-infra: update CentOS images
  test-infra/image-builder/roles/kubevirt-images/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, needs-ok-to-test, size/S

#7152 preinstall: fixup etcd_deployment_type check
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/S

#7160 Update kube_version_min_required and cleanup hashes for release
  README.md
  roles/download/defaults/main.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/L

#7164 Fix typo
  docs/setting-up-your-first-cluster.md
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/XS

#7165 Use Kubespray v2.15.0 as base image for CI
  .gitlab-ci.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7171 Add hashes and update default K8S version to 1.20.2
  Dockerfile
  README.md
  inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml
  roles/download/defaults/main.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/M

#7151 Remove ignore_errors from drain tasks and enable retires
  roles/remove-node/pre-remove/defaults/main.yml
  roles/remove-node/pre-remove/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/M

#7166 Adding other masters sequentially, not in parallel
  roles/kubernetes/master/tasks/kubeadm-secondary.yml
Labels: approved, cncf-cla: yes, kind/bug, kind/feature, lgtm, size/XS

#7168 Add prompt to upgrade node or delay before upgrade
  docs/upgrades.md
  roles/upgrade/pre-upgrade/defaults/main.yml
  roles/upgrade/pre-upgrade/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#7172 Decrease docker dependency
  roles/download/defaults/main.yml
  roles/download/tasks/check_pull_required.yml
  roles/download/tasks/prep_download.yml
  roles/download/tasks/set_container_facts.yml
  roles/kubernetes/node/tasks/install.yml
  roles/network_plugin/calico/handlers/main.yml
  roles/network_plugin/kube-router/handlers/main.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/M

#7187 Update bunch of dependencies
  README.md
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#7188 Update metrics-server to 0.4.1
  roles/download/defaults/main.yml
  roles/kubernetes-apps/metrics_server/templates/metrics-server-deployment.yaml.j2
  roles/kubernetes-apps/metrics_server/templates/metrics-server-service.yaml.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#7175 Fix Calico image tags support multiarch on quay.io.
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7181 Update Weave to 2.8.0
  README.md
  roles/download/defaults/main.yml
  roles/network_plugin/weave/templates/weave-net.yml.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/M

#7192 Cleanup old checks for k8s 1.18
  roles/kubernetes-apps/metallb/templates/metallb.yml.j2
  roles/network_plugin/ovn4nfv/templates/ovn-daemonset.yml.j2
  roles/network_plugin/ovn4nfv/templates/ovn4nfv-k8s-plugin.yml.j2
  roles/win_nodes/kubernetes_patch/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/S

#7182 Promote node.k8s.io API groups from v1beta1 to v1
  roles/kubernetes-apps/container_runtimes/crun/files/runtimeclass-crun.yml
  roles/kubernetes-apps/container_runtimes/kata_containers/templates/runtimeclass-kata-qemu.yml.j2
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS, tide/merge-method-rebase

#7193 Check kube-apiserver up on all masters before upgrade
  roles/kubernetes/master/tasks/kubeadm-upgrade.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#7119 [2.13] Backport CI fix
  .gitlab-ci.yml
  .gitlab-ci/packet.yml
  .gitlab-ci/shellcheck.yml
  contrib/inventory_builder/tests/test_inventory.py
  docs/containerd.md
  inventory/sample/group_vars/all/containerd.yml
  inventory/sample/group_vars/k8s-cluster/addons.yml
  roles/container-engine/containerd/templates/config.toml.j2
  roles/container-engine/cri-o/molecule/default/molecule.yml
  roles/container-engine/cri-o/tasks/crio_repo.yml
  roles/download/defaults/main.yml
  roles/kubernetes/preinstall/defaults/main.yml
  roles/kubernetes/preinstall/tasks/0070-system-packages.yml
  tests/common/_docker_hub_registry_mirror.yml
  tests/files/packet_centos8-calico.yml
  tests/scripts/testcases_run.sh
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, ok-to-test, size/L

#7183 Change node-role.kubernetes.io from master to control-plane
  inventory/sample/group_vars/k8s-cluster/addons.yml
  roles/kubernetes-apps/ansible/templates/coredns-deployment.yml.j2
  roles/kubernetes-apps/ansible/templates/dashboard.yml.j2
  roles/kubernetes-apps/ansible/templates/dns-autoscaler.yml.j2
  roles/kubernetes-apps/cloud_controller/oci/templates/oci-cloud-provider.yml.j2
  roles/kubernetes-apps/csi_driver/azuredisk/templates/azure-csi-azuredisk-controller.yml.j2
  roles/kubernetes-apps/csi_driver/vsphere/templates/vsphere-csi-controller-ss.yml.j2
  roles/kubernetes-apps/external_cloud_controller/openstack/templates/external-openstack-cloud-controller-manager-ds.yml.j2
  roles/kubernetes-apps/external_cloud_controller/vsphere/templates/external-vsphere-cloud-controller-manager-ds.yml.j2
  roles/kubernetes-apps/ingress_controller/ambassador/templates/cr-ambassador-installation.yml.j2
  roles/kubernetes-apps/metallb/templates/metallb.yml.j2
  roles/kubernetes-apps/metrics_server/templates/metrics-server-deployment.yaml.j2
  roles/kubernetes-apps/policy_controller/calico/templates/calico-kube-controllers.yml.j2
  roles/kubernetes/master/tasks/kubeadm-setup.yml
  roles/network_plugin/calico/templates/calico-typha.yml.j2
  roles/network_plugin/ovn4nfv/templates/ovn4nfv-k8s-plugin.yml.j2
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/M

#7201 Add cleanup of openstack network ports in CI
  scripts/openstack-cleanup/main.py
Labels: approved, cncf-cla: yes, kind/failing-test, kind/flake, lgtm, size/XS

#7202 preinstall: etcd group might not exists
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#7195 Calico: fixup check when ipipMode / vxlanMode is not present
  roles/network_plugin/calico/tasks/check.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#7204 Add missing 'ingress-controller' tag to alb
  roles/kubernetes-apps/ingress_controller/meta/main.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#7141 Added terraform support for Exoscale
  contrib/terraform/exoscale/README.md
  contrib/terraform/exoscale/default.tfvars
  contrib/terraform/exoscale/main.tf
  contrib/terraform/exoscale/modules/kubernetes-cluster/main.tf
  contrib/terraform/exoscale/modules/kubernetes-cluster/output.tf
  contrib/terraform/exoscale/modules/kubernetes-cluster/templates/cloud-init.tmpl
  contrib/terraform/exoscale/modules/kubernetes-cluster/variables.tf
  contrib/terraform/exoscale/modules/kubernetes-cluster/versions.tf
  contrib/terraform/exoscale/output.tf
  contrib/terraform/exoscale/templates/inventory.tpl
  contrib/terraform/exoscale/variables.tf
  contrib/terraform/exoscale/versions.tf
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/XL

#7131 Add download bin tasks
  roles/etcd/tasks/install_host.yml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#7203 containerd,docker: stop installing extras repo on CentOS/RHEL
  docs/offline-environment.md
  inventory/sample/group_vars/k8s-cluster/offline.yml
  roles/bootstrap-os/tasks/bootstrap-redhat.yml
  roles/container-engine/containerd/defaults/main.yml
  roles/container-engine/containerd/tasks/containerd_repo.yml
  roles/container-engine/docker/defaults/main.yml
  roles/container-engine/docker/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/M

#7169 calico: fix NetworkManager check
  roles/network_plugin/calico/tasks/install.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#7209 [2.14] Backport: 6758, 6853 and 7003 to fix CRI-O pkg
  docs/cri-o.md
  roles/container-engine/cri-o/defaults/main.yml
  roles/container-engine/cri-o/tasks/crio_repo.yml
  roles/container-engine/cri-o/vars/centos-7.yml
  roles/container-engine/cri-o/vars/centos-8.yml
  roles/container-engine/cri-o/vars/debian.yml
  roles/container-engine/cri-o/vars/fedora.yml
  roles/container-engine/cri-o/vars/ubuntu.yml
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, ok-to-test, size/M

#7217 [2.15] Backport: Check kube-apiserver up on all masters before upgrade
  roles/kubernetes/master/tasks/kubeadm-upgrade.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#7208 Update azure cloud config
  docs/azure.md
  inventory/sample/group_vars/all/azure.yml
  roles/kubernetes/node/templates/cloud-configs/azure-cloud-config.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/S

#7215 Update nginx, minor weave and misc CI tools (vagrant/terraform)
  .gitlab-ci/lint.yml
  .gitlab-ci/terraform.yml
  README.md
  docs/packet.md
  roles/download/defaults/main.yml
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/clusterrole-ingress-nginx.yml.j2
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/role-ingress-nginx.yml.j2
  test-infra/vagrant-docker/Dockerfile
  tests/testcases/100_check-k8s-conformance.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/M

#7206 Add retries to drain during upgrade. Allow leaving nodes cordoned aft…
  roles/upgrade/pre-upgrade/defaults/main.yml
  roles/upgrade/pre-upgrade/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/S

#7214 Fix unintended SIGPIPEs.
  roles/etcd/tasks/configure.yml
  roles/etcd/tasks/join_etcd-events_member.yml
  roles/etcd/tasks/join_etcd_member.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#7220 [2.14] Update azure cloud config
  docs/azure.md
  inventory/sample/group_vars/all/azure.yml
  roles/kubernetes/node/templates/cloud-configs/azure-cloud-config.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/S

#7221 [2.15] Update azure cloud config
  docs/azure.md
  inventory/sample/group_vars/all/azure.yml
  roles/kubernetes/node/templates/cloud-configs/azure-cloud-config.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/S

#7207 [2.14] update hashes for 1.18 and 1.19 for kubespray-2.14
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/M

#7227 FIX: Bastion undefined variable
  inventory/sample/inventory.ini
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#7197 [2.14] Backport: Check kube-apiserver up on all masters before upgrade
  roles/kubernetes/master/tasks/kubeadm-upgrade.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#7228 Fix bootstrap-os on Oracle Linux in an offline environment
  roles/bootstrap-os/tasks/bootstrap-centos.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/XS
