Repository kubernetes-sigs/kubespray, pull requests merged in 2021-08, with the labels that each got.

#7729 Remove environment variable in remove-node play
  remove-node.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#7854 Update crun binary version
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/feature

#7842 addons/cert_manager: fix kubernetes-sigs#7085 by adding retries..until
  roles/kubernetes-apps/ingress_controller/cert_manager/tasks/main.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#7848 Add suport of Vsphere CSI driver 2.2.X versions
  docs/vsphere-csi.md
  roles/kubernetes-apps/csi_driver/vsphere/defaults/main.yml
  roles/kubernetes-apps/csi_driver/vsphere/tasks/main.yml
  roles/kubernetes-apps/csi_driver/vsphere/templates/vsphere-csi-controller-deployment.yml.j2
  roles/kubernetes-apps/csi_driver/vsphere/templates/vsphere-csi-node-rbac.yaml.j2
  roles/kubernetes-apps/csi_driver/vsphere/templates/vsphere-csi-node.yml.j2
Labels: cncf-cla: yes, size/L, lgtm, ok-to-test, approved, kind/feature

#7858 fix parameters for module replace in 0060-resolvconf
  roles/kubernetes/preinstall/tasks/0060-resolvconf.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#7855 Calico: add v3.20.0 hashes
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#7864 Update metrics-server to 0.5.0
  inventory/sample/group_vars/k8s_cluster/addons.yml
  roles/download/defaults/main.yml
  roles/kubernetes-apps/metrics_server/defaults/main.yml
  roles/kubernetes-apps/metrics_server/templates/metrics-server-deployment.yaml.j2
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/feature

#7859 Cleanup python scripts removing unused imports
  scripts/gitlab-branch-cleanup/main.py
  scripts/openstack-cleanup/main.py
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/cleanup

#7871 Update cilium to 1.9.9
  README.md
  docs/cilium.md
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#7860 Improve python system exit calls
  contrib/inventory_builder/inventory.py
  scripts/download_hash.py
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#7888 debian: Fix test failed after bullseye release
  roles/bootstrap-os/tasks/bootstrap-debian.yml
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, ok-to-test, approved

#7877 docs/cert_manager.md: Update docs for K8s v1.22
  docs/cert_manager.md
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/documentation

#7873 Calico: use --allow-version-mismatch in calicoctl.sh to allow upgrades
  roles/network_plugin/calico/templates/calicoctl.etcd.sh.j2
  roles/network_plugin/calico/templates/calicoctl.kdd.sh.j2
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#7880 Update Azure.md with Links and Azure Style Guide
  docs/azure.md
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/documentation

#7868 feat(containerd): auth support
  inventory/sample/group_vars/all/containerd.yml
  roles/container-engine/containerd/defaults/main.yml
  roles/container-engine/containerd/templates/config.toml.j2
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/feature

#7902 Update nodes.md
  docs/nodes.md
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#7901 add cilium_operator_api_serve_addr to cilium operator config
  roles/network_plugin/cilium/defaults/main.yml
  roles/network_plugin/cilium/templates/cilium-config.yml.j2
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved

#7850 addons/cert_manager: retries until webhook pods has been created
  roles/kubernetes-apps/ingress_controller/cert_manager/tasks/main.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#7867 Calico: replace version 3.19.1 with 3.19.2 and set default
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/feature

#7918 Update docker to 20.10.8
  roles/container-engine/docker/vars/debian.yml
  roles/container-engine/docker/vars/fedora.yml
  roles/container-engine/docker/vars/redhat.yml
  roles/container-engine/docker/vars/ubuntu.yml
Labels: cncf-cla: yes, size/M, lgtm, approved, kind/feature

#7921 Fix Fedora nightly jobs (mitogen issue) and centos8 CI instability
  .gitlab-ci/packet.yml
  tests/cloud_playbooks/roles/packet-ci/templates/vm.yml.j2
  tests/files/packet_centos8-calico.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved

#7853 kubernetes/preinstall: Add Debian 11 (bullseye) support
  roles/kubernetes/preinstall/vars/debian-11.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#7892 During pre-upgrade add a flag to always cordon
  roles/upgrade/pre-upgrade/defaults/main.yml
  roles/upgrade/pre-upgrade/tasks/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#7926 Fix Calico's FelixConfiguration when "IP in IP" is disabled
  roles/network_plugin/calico/tasks/install.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#7924 Calico: replace hashes for latest 3.17 and 3.18 to the .5 minor versions
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/feature

#7919 Add Debian 11 image and CI
  .gitlab-ci/packet.yml
  README.md
  docs/ci.md
  test-infra/image-builder/roles/kubevirt-images/defaults/main.yml
  tests/cloud_playbooks/roles/packet-ci/defaults/main.yml
  tests/files/packet_debian11-calico.yml
Labels: cncf-cla: yes, size/S, lgtm, approved, kind/feature
