Repository kubernetes-sigs/kubespray, pull requests merged in 2021-12, with the labels that each got.

#8244 Clean kubeadm-config cm from removed etcd nodes endPoints
  roles/remove-node/remove-etcd-node/tasks/main.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved

#8250 Calico: add dependencies for 3.21.x
  roles/kubernetes-apps/policy_controller/calico/templates/calico-kube-cr.yml.j2
  roles/network_plugin/calico/templates/calico-cr.yml.j2
  roles/network_plugin/calico/templates/calico-node.yml.j2
Labels: kind/bug, cncf-cla: yes, size/M, lgtm, approved

#8252 Set ingress-nginx default terminationGracePeriodSeconds to 5 min
  inventory/sample/group_vars/k8s_cluster/addons.yml
  roles/kubernetes-apps/ingress_controller/ingress_nginx/defaults/main.yml
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/ds-ingress-nginx-controller.yml.j2
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#8258 Move cri-o default package to 1.22
  .gitlab-ci/packet.yml
  README.md
  docs/ci.md
  roles/container-engine/cri-o/defaults/main.yml
  roles/container-engine/cri-o/molecule/default/molecule.yml
  roles/container-engine/cri-o/vars/amazon.yml
  roles/container-engine/cri-o/vars/centos-7.yml
  roles/container-engine/cri-o/vars/centos-8.yml
  roles/container-engine/cri-o/vars/debian.yml
  roles/container-engine/cri-o/vars/fedora.yml
  roles/container-engine/cri-o/vars/ubuntu.yml
  tests/files/packet_fedora35-crio.yml
Labels: cncf-cla: yes, size/M, lgtm, approved, kind/feature

#8261 containerd: add support for suse distributions
  roles/container-engine/containerd/molecule/default/molecule.yml
  roles/container-engine/containerd/tasks/main.yml
Labels: cncf-cla: yes, size/S, lgtm, approved, kind/feature

#8257 Move opensuse CI to docker and fix ubuntu16 containerd version for docker
  .gitlab-ci/packet.yml
  docs/ci.md
  tests/files/packet_opensuse-docker-cilium.yml
  tests/files/packet_ubuntu16-docker-weave-sep.yml
Labels: cncf-cla: yes, size/S, lgtm, approved, kind/failing-test

#8264 CI: upgrade vagrant to 2.2.19
  .gitlab-ci/lint.yml
  test-infra/vagrant-docker/Dockerfile
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/failing-test

#8253 Update etcd-servers for apiserver
  roles/kubernetes/control-plane/tasks/kubeadm-fix-apiserver.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved

#8266 Fix calico crd archive checksums for v3.20.3
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/flake

#8267 [2.17] CI: upgrade vagrant to 2.2.19 (#8264)
  .gitlab-ci/lint.yml
  test-infra/vagrant-docker/Dockerfile
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/failing-test

#8265 Remove ovn4nfv support
  .gitlab-ci/packet.yml
  README.md
  docs/_sidebar.md
  docs/ansible.md
  docs/ci.md
  docs/ovn4nfv.md
  roles/download/defaults/main.yml
  roles/kubernetes-apps/network_plugin/meta/main.yml
  roles/kubernetes-apps/network_plugin/ovn4nfv/tasks/main.yml
  roles/kubernetes/node/templates/kubelet.env.v1beta1.j2
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
  roles/kubernetes/preinstall/tasks/0050-create_directories.yml
  roles/network_plugin/meta/main.yml
  roles/network_plugin/ovn4nfv/defaults/main.yml
  roles/network_plugin/ovn4nfv/tasks/main.yml
  roles/network_plugin/ovn4nfv/templates/ovn-daemonset.yml.j2
  roles/network_plugin/ovn4nfv/templates/ovn4nfv-k8s-plugin.yml.j2
  tests/files/packet_ubuntu18-ovn4nfv.yml
Labels: cncf-cla: yes, size/XXL, lgtm, approved, kind/cleanup

#8239 containerd: add hashes for 1.5.8 and 1.4.12 and make 1.5.8 the new default
  README.md
  roles/bootstrap-os/tasks/bootstrap-opensuse.yml
  roles/container-engine/containerd/meta/main.yml
  roles/container-engine/containerd/molecule/default/prepare.yml
  roles/container-engine/containerd/molecule/default/tests/test_default.py
  roles/download/defaults/main.yml
  roles/download/tasks/main.yml
  roles/download/tasks/prep_download.yml
  roles/download/tasks/set_container_facts.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: cncf-cla: yes, size/L, lgtm, approved, kind/feature

#8269 Calico: remove duplicate values
  roles/network_plugin/calico/templates/calico-node.yml.j2
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved

#7731 Prefer nodelocaldns as dns server over coredns when defined
  roles/kubernetes/preinstall/tasks/0040-set_facts.yml
  roles/kubernetes/preinstall/templates/resolved.conf.j2
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#8270 Fix k8scsi/csi-resizer repo
  roles/kubernetes-apps/csi_driver/vsphere/templates/vsphere-csi-controller-deployment.yml.j2
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved

#8262 Fix if bind-address is not set to 0.0.0.0
  docs/ha-mode.md
  roles/kubernetes/control-plane/defaults/main/main.yml
  roles/kubernetes/node/tasks/main.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, ok-to-test, approved

#7989 Improve control plane scale flow (#13)
  roles/kubernetes/control-plane/tasks/define-first-kube-control.yml
  roles/kubernetes/control-plane/tasks/kubeadm-secondary.yml
  roles/kubernetes/control-plane/tasks/kubeadm-setup.yml
  roles/kubernetes/control-plane/tasks/kubeadm-upgrade.yml
  roles/kubernetes/control-plane/tasks/main.yml
  roles/kubernetes/kubeadm/tasks/main.yml
  roles/kubespray-defaults/defaults/main.yaml
  roles/network_plugin/calico/templates/kubernetes-services-endpoint.yml.j2
Labels: kind/bug, cncf-cla: yes, size/M, lgtm, ok-to-test, approved

#8263 change dns upstream condition for coredns
  roles/kubernetes-apps/ansible/templates/coredns-config.yml.j2
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#8273 download calico_flexvol image by default
  roles/download/defaults/main.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved

#8272 Update loadbalancers versions
  roles/download/defaults/main.yml
  roles/kubernetes/node/tasks/loadbalancer/haproxy.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#8237 Use cgroupsv2 where available (fedora)
  roles/container-engine/containerd/tasks/main.yml
  roles/container-engine/cri-o/tasks/main.yaml
  roles/container-engine/docker/tasks/main.yml
Labels: cncf-cla: yes, size/M, lgtm, approved, kind/feature

#8232 Change etcd-events listen port to avoid conflicts
  roles/etcd/handlers/main.yml
  roles/etcd/templates/etcd-events.env.j2
  roles/kubespray-defaults/defaults/main.yaml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#8274 runc: upgrade to v1.0.3
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/feature

#8275 Calico: upgrade 3.21.x to 3.21.2
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/feature

#8276 Kata-Containers: add 2.3.0
  roles/download/defaults/main.yml
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/container-managers

#8229 Registry add TLS and authentication support
  roles/kubernetes-apps/registry/defaults/main.yml
  roles/kubernetes-apps/registry/tasks/main.yml
  roles/kubernetes-apps/registry/templates/registry-cm.yml.j2
  roles/kubernetes-apps/registry/templates/registry-rs.yml.j2
  roles/kubernetes-apps/registry/templates/registry-secrets.yml.j2
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/feature

#8284 Add oomichi to approvers
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/cleanup

#8287 Revert "Clean kubeadm-config cm from removed etcd nodes endPoints"
  roles/remove-node/remove-etcd-node/tasks/main.yml
Labels: cncf-cla: yes, size/S, lgtm, approved

#8247 containerd: change default resolvconf_mode to host_resolvconf
  .gitlab-ci/packet.yml
  inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
  roles/adduser/molecule/default/molecule.yml
  roles/bastion-ssh-config/molecule/default/molecule.yml
  roles/bootstrap-os/molecule/default/molecule.yml
  roles/container-engine/containerd/molecule/default/molecule.yml
  roles/container-engine/cri-o/molecule/default/molecule.yml
  roles/container-engine/docker/molecule/default/molecule.yml
  roles/container-engine/gvisor/molecule/default/molecule.yml
  roles/container-engine/kata-containers/molecule/default/molecule.yml
  roles/kubernetes/preinstall/handlers/main.yml
  roles/kubernetes/preinstall/tasks/0040-set_facts.yml
  roles/kubernetes/preinstall/tasks/0060-resolvconf.yml
  roles/kubernetes/preinstall/tasks/0100-dhclient-hooks.yml
  roles/kubespray-defaults/defaults/main.yaml
  tests/files/packet_centos7-docker-weave-upgrade-ha.yml
  tests/files/packet_centos8-docker.yml
  tests/files/packet_debian10-docker.yml
  tests/files/packet_debian11-docker.yml
  tests/files/packet_fedora34-docker-weave.yml
  tests/files/packet_ubuntu16-docker-weave-sep.yml
  tests/files/packet_ubuntu18-docker.yml
  tests/files/packet_ubuntu20-docker.yml
Labels: cncf-cla: yes, size/M, lgtm, approved, kind/container-managers

#8296 Update Cinder CSI to v1.22
  roles/download/defaults/main.yml
  roles/kubernetes-apps/csi_driver/aws_ebs/templates/aws-ebs-csi-controllerservice.yml.j2
  roles/kubernetes-apps/csi_driver/cinder/templates/cinder-csi-controllerplugin-rbac.yml.j2
  roles/kubernetes-apps/csi_driver/cinder/templates/cinder-csi-controllerplugin.yml.j2
  roles/kubernetes-apps/csi_driver/cinder/templates/cinder-csi-nodeplugin.yml.j2
Labels: kind/bug, cncf-cla: yes, size/L, lgtm, ok-to-test, approved

#8295 vSphere-CSI: update to 2.4.0
  inventory/sample/group_vars/all/vsphere.yml
  roles/kubernetes-apps/csi_driver/vsphere/defaults/main.yml
  roles/kubernetes-apps/csi_driver/vsphere/tasks/main.yml
  roles/kubernetes-apps/csi_driver/vsphere/templates/vsphere-csi-controller-config.yml.j2
  roles/kubernetes-apps/csi_driver/vsphere/templates/vsphere-csi-controller-deployment.yml.j2
  roles/kubernetes-apps/csi_driver/vsphere/templates/vsphere-csi-controller-rbac.yml.j2
  roles/kubernetes-apps/csi_driver/vsphere/templates/vsphere-csi-controller-service.yml.j2
  roles/kubernetes-apps/csi_driver/vsphere/templates/vsphere-csi-controller-ss.yml.j2
  roles/kubernetes-apps/csi_driver/vsphere/templates/vsphere-csi-driver.yml.j2
  roles/kubernetes-apps/csi_driver/vsphere/templates/vsphere-csi-node-rbac.yml.j2
  roles/kubernetes-apps/csi_driver/vsphere/templates/vsphere-csi-node.yml.j2
Labels: cncf-cla: yes, size/L, lgtm, approved, kind/applications

#8298 containerd insecure registry support
  inventory/sample/group_vars/all/containerd.yml
  roles/container-engine/containerd/templates/config.toml.j2
  roles/kubespray-defaults/defaults/main.yaml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved

#8301 sample containerd: containerd_runtimes is removed
  inventory/sample/group_vars/all/containerd.yml
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, ok-to-test, approved

#8299 Fix external lb error
  roles/kubernetes/preinstall/defaults/main.yml
  roles/kubernetes/preinstall/tasks/0090-etchosts.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#8286 CI: fix test name debian10-aio was a 2 instance default
  .gitlab-ci/packet.yml
  tests/files/packet_debian10-calico.yml
  tests/files/packet_ubuntu18-aio-docker.yml
  tests/files/packet_ubuntu20-aio-docker.yml
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, approved

#8291 registry: service add clusterIP, nodePort, loadBalancer support
  roles/kubernetes-apps/registry/defaults/main.yml
  roles/kubernetes-apps/registry/tasks/main.yml
  roles/kubernetes-apps/registry/templates/registry-svc.yml.j2
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/feature

#8310 clean files for kube-ovn
  roles/reset/tasks/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/cleanup

#8314 Fix bad indentation in cert-manager when trusted internal ca is defined
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/cert-manager.yml.j2
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#8315 Upgrade to nerdctl 0.15.0 and some fixes
  roles/download/defaults/main.yml
  roles/download/tasks/download_container.yml
  roles/download/tasks/prep_download.yml
Labels: cncf-cla: yes, size/S, lgtm, approved, kind/feature, release-note-none

#8306 add support for Calico BGPPeer sourceAddress
  docs/calico_peer_example/new-york.yml
  docs/calico_peer_example/paris.yml
  roles/network_plugin/calico/tasks/install.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/network

#8268 Add support for CRI-O user namespaces
  docs/cri-o.md
  roles/container-engine/cri-o/defaults/main.yml
  roles/container-engine/cri-o/tasks/main.yaml
  roles/container-engine/cri-o/templates/crio.conf.j2
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/container-managers

#8322 Delete "kubeadm alpha certs" code
  roles/kubernetes/control-plane/templates/k8s-certs-renew.sh.j2
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/cleanup

#8323 Support deploying kubernetes 1.23
  roles/container-engine/cri-o/defaults/main.yml
  roles/container-engine/cri-o/vars/fedora.yml
  roles/download/defaults/main.yml
  roles/kubernetes/control-plane/tasks/main.yml
  roles/kubernetes/control-plane/templates/kubescheduler-config.yaml.j2
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, approved

#8311 registry: add ingress support
  roles/kubernetes-apps/registry/defaults/main.yml
  roles/kubernetes-apps/registry/tasks/main.yml
  roles/kubernetes-apps/registry/templates/registry-ing.yml.j2
Labels: cncf-cla: yes, size/M, lgtm, approved, kind/feature

#8327 Remove registry-proxy
  roles/download/defaults/main.yml
  roles/kubernetes-apps/registry/tasks/main.yml
  roles/kubernetes-apps/registry/templates/registry-proxy-cr.yml.j2
  roles/kubernetes-apps/registry/templates/registry-proxy-crb.yml.j2
  roles/kubernetes-apps/registry/templates/registry-proxy-ds.yml.j2
  roles/kubernetes-apps/registry/templates/registry-proxy-psp.yml.j2
  roles/kubernetes-apps/registry/templates/registry-proxy-sa.yml.j2
Labels: cncf-cla: yes, size/L, lgtm, approved, kind/cleanup

#8309 Glusterfs daemonset readiness and liveness params. #8307
  contrib/network-storage/heketi/inventory.yml.sample
  contrib/network-storage/heketi/roles/provision/templates/glusterfs-daemonset.json.j2
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/feature

#8321 calico_pool_blocksize must be cast as well in assertion when defined
  roles/network_plugin/calico/tasks/check.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#8331 [cni-plugins] upgrade to stable 1.0.1
  roles/download/defaults/main.yml
  roles/network_plugin/flannel/tasks/main.yml
Labels: cncf-cla: yes, size/M, lgtm, approved, kind/feature
