Repository kubernetes-sigs/kubespray, pull requests merged in 2021-04, with the labels that each got.

#7418 Add cilium_ipam_mode variable
  roles/network_plugin/cilium/defaults/main.yml
  roles/network_plugin/cilium/templates/cilium-config.yml.j2
  roles/network_plugin/cilium/templates/cilium-deploy.yml.j2
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#7427 Update kata-containers to 1.12.1
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#7421 allow local provisioner 'useNodeNameOnly' option to be configured
  roles/kubernetes-apps/external_provisioner/local_volume_provisioner/defaults/main.yml
  roles/kubernetes-apps/external_provisioner/local_volume_provisioner/templates/local-volume-provisioner-cm.yml.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/XS

#7398 Set containerd version to 1.4.4
  README.md
  docs/containerd.md
  docs/upgrades.md
  docs/vars.md
  inventory/sample/group_vars/all/containerd.yml
  inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml
  roles/container-engine/containerd-common/defaults/main.yml
  roles/container-engine/containerd-common/vars/debian-stretch.yml
  roles/container-engine/containerd-common/vars/debian.yml
  roles/container-engine/containerd-common/vars/fedora.yml
  roles/container-engine/containerd-common/vars/redhat.yml
  roles/container-engine/containerd-common/vars/ubuntu.yml
  roles/container-engine/containerd/defaults/main.yml
  roles/container-engine/containerd/templates/config.toml.j2
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
  roles/kubespray-defaults/defaults/main.yaml
  roles/kubespray-defaults/vars/main.yml
  tests/common/_docker_hub_registry_mirror.yml
  tests/files/packet_centos7-flannel-containerd-addons-ha.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/L

#7429 Remove old note related to offline installation
  docs/offline-environment.md
Labels: approved, cncf-cla: yes, kind/cleanup, kind/documentation, lgtm, size/XS

#7426 reset roles need flush iptables raw
  roles/reset/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#7433 Crun v0.19 support
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7436 fix typo
  contrib/terraform/openstack/README.md
  docs/setting-up-your-first-cluster.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7437 remove local lb privileged
  roles/kubernetes/node/templates/manifests/haproxy.manifest.j2
  roles/kubernetes/node/templates/manifests/nginx-proxy.manifest.j2
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7439 Remove calico-rr from local inventory hosts file
  inventory/local/hosts.ini
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/XS

#7441 Fix CI template for etcd recover jobs (kube-master rename)
  tests/cloud_playbooks/roles/packet-ci/templates/inventory.j2
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#7442 Replace deprecated 'with_dict' with 'loop'
  roles/download/tasks/main.yml
  roles/kubernetes/preinstall/tasks/0090-etchosts.yml
  test-infra/image-builder/roles/kubevirt-images/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/flake, lgtm, size/S

#7434 Add documentation for audit webhook variables
  docs/vars.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7351 Add KubeSchedulerConfiguration for k8s 1.19 and up
  roles/kubernetes/control-plane/defaults/main/kube-scheduler.yml
  roles/kubernetes/control-plane/defaults/main/main.yml
  roles/kubernetes/control-plane/tasks/main.yml
  roles/kubernetes/control-plane/templates/kubeadm-config.v1beta2.yaml.j2
  roles/kubernetes/control-plane/templates/kubescheduler-config.v1beta1.yaml.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/M

#7413 Update cilium_ipsec_enabled check
  roles/network_plugin/cilium/tasks/install.yml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7449 fix scale
  scale.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#7454 Backport remove local lb privileged to release-2.15
  roles/kubernetes/node/templates/manifests/haproxy.manifest.j2
  roles/kubernetes/node/templates/manifests/nginx-proxy.manifest.j2
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/XS

#7459 Fix issue with 'latest' in containerd version
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
  tests/files/packet_fedora32-kube-ovn-containerd.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#7462 Move cilium kvstore settings to configmap
  roles/network_plugin/cilium/templates/cilium-config.yml.j2
  roles/network_plugin/cilium/templates/cilium-deploy.yml.j2
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/XS

#7444 Add condition for audit_webhook_mode batch
  roles/kubernetes/control-plane/templates/kubeadm-config.v1beta2.yaml.j2
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#7466 Use v2.15.1 as base image for CI
  .gitlab-ci.yml
  README.md
Labels: approved, cncf-cla: yes, kind/api-change, lgtm, size/XS

#7472 add CI test for auto_renew_certificates
  roles/kubernetes/control-plane/templates/k8s-certs-renew.sh.j2
  roles/kubernetes/control-plane/templates/k8s-certs-renew.timer.j2
  tests/files/packet_centos7-calico-ha-once-localhost.yml
  tests/files/packet_centos7-calico-ha.yml
  tests/files/packet_centos8-crio.yml
  tests/files/packet_debian10-containerd.yml
  tests/files/packet_debian9-macvlan.yml
  tests/files/packet_fedora33-calico.yml
  tests/files/packet_opensuse-canal.yml
  tests/files/packet_oracle7-canal-ha.yml
  tests/files/packet_ubuntu16-weave-sep.yml
  tests/files/packet_ubuntu18-cilium-sep.yml
  tests/files/packet_ubuntu20-calico-aio.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S

#7470 Remove dead code from kubeadm-etcd
  roles/kubernetes/control-plane/tasks/kubeadm-etcd.yml
Labels: approved, cncf-cla: yes, kind/flake, lgtm, size/S

#7478 Update hashes with 1.21.0
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#7482 format helm roles output
  roles/kubernetes-apps/helm/tasks/main.yml
  roles/kubernetes-apps/metallb/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#7461 Add containerd_extra_args
  roles/container-engine/containerd/defaults/main.yml
  roles/container-engine/containerd/tasks/main.yml
  roles/container-engine/containerd/templates/config.toml.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/XS

#7447 kubeadm_feature_gates
  docs/vars.md
  roles/kubernetes/control-plane/templates/kubeadm-config.v1beta2.yaml.j2
  roles/kubernetes/preinstall/tasks/0040-set_facts.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/S

#7463 Regenerate apiserver.crt on all control-plane nodes
  roles/kubernetes/control-plane/tasks/kubeadm-setup.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S

#7489 Fix typo
  docs/setting-up-your-first-cluster.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, needs-ok-to-test, size/XS

#7477 Update Terraform/Vagrant + increase tf_ovh retries
  .gitlab-ci.yml
  .gitlab-ci/lint.yml
  .gitlab-ci/terraform.yml
  docs/packet.md
  test-infra/vagrant-docker/Dockerfile
  tests/files/tf-ovh_ubuntu18-calico.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/M

#7490 Add auto_renew_certificates_systemd_calendar
  inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml
  roles/kubernetes/control-plane/defaults/main/main.yml
  roles/kubernetes/control-plane/templates/k8s-certs-renew.timer.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#7486 Check if python netaddr and recent enough jinja are installed
  ansible_version.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#7493 fix offline mode
  docs/offline-environment.md
  inventory/sample/group_vars/all/offline.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S

#7492 Add missing proxy environment in crio_repo.yml
  roles/container-engine/cri-o/tasks/crio_repo.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#7498 Fix sample inventory (offline template)
  inventory/sample/group_vars/all/offline.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#7502 Remove some bash completion file when reset cluster
  roles/reset/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/bug, kind/cleanup, lgtm, needs-ok-to-test, size/XS

#7499 Update some docker defaults
  inventory/sample/group_vars/all/docker.yml
  roles/container-engine/docker/defaults/main.yml
  roles/container-engine/docker/tasks/set_facts_dns.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, kind/flake, lgtm, size/S

#7510 Add bash-completion package
  roles/kubernetes/preinstall/defaults/main.yml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7337 exoscale: Rework EIP access from workers
  contrib/terraform/exoscale/modules/kubernetes-cluster/templates/cloud-init.tmpl
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/S

#7520 Refactor cilium_ipsec_enabled check
  roles/network_plugin/cilium/tasks/install.yml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7534 Cleanup hashes and 1.18 hooks
  roles/download/defaults/main.yml
  roles/kubernetes/control-plane/tasks/main.yml
  roles/kubernetes/control-plane/templates/kubeadm-config.v1beta2.yaml.j2
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/L

#7530 Fixes issue #7528 - allow configuring CALICO_STARTUP_LOGLEVEL
  roles/network_plugin/calico/defaults/main.yml
  roles/network_plugin/calico/templates/calico-node.yml.j2
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7527 Fix OpenId Connect example prefixes
  inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml
  roles/kubernetes/control-plane/defaults/main/main.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/XS

#7506 Fix keepcache values of yum_repository
  roles/container-engine/cri-o/tasks/crio_repo.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#7507 add enablerepo: amzn2extra-docker for docker install on aws 2
  roles/container-engine/docker/vars/amazon.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#7535 Fix OpenStack StyleGuide rule H216 (On by default in latest version)
  contrib/inventory_builder/tests/test_inventory.py
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#7524 Add Calico v3.17.3 and v3.18.1
  roles/download/defaults/main.yml
  roles/network_plugin/calico/tasks/install.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/S

#7525 add support for configuring cri-o pids_limit
  docs/cri-o.md
  roles/container-engine/cri-o/defaults/main.yml
  roles/container-engine/cri-o/templates/crio.conf.j2
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/S

#7516 Ambassador can watch multiple namespaces
  inventory/sample/group_vars/k8s-cluster/addons.yml
  roles/kubernetes-apps/ingress_controller/ambassador/README.md
  roles/kubernetes-apps/ingress_controller/ambassador/defaults/main.yml
  roles/kubernetes-apps/ingress_controller/ambassador/templates/deploy-ambassador.yml.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/S

#7522 Add ingress controller ingress-class var
  inventory/sample/group_vars/k8s-cluster/addons.yml
  roles/kubernetes-apps/ingress_controller/ingress_nginx/defaults/main.yml
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/ds-ingress-nginx-controller.yml.j2
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/role-ingress-nginx.yml.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#7537 update calico default version in README.md
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/XS

#7538 Initial AlmaLinux support
  docs/centos8.md
  docs/offline-environment.md
  inventory/sample/group_vars/all/offline.yml
  requirements.txt
  roles/bootstrap-os/README.md
  roles/bootstrap-os/defaults/main.yml
  roles/bootstrap-os/tasks/main.yml
  roles/container-engine/containerd/tasks/containerd_repo.yml
  roles/container-engine/containerd/tasks/main.yml
  roles/container-engine/docker/tasks/main.yml
  roles/container-engine/docker/tasks/pre-upgrade.yml
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
  roles/kubernetes/preinstall/tasks/0070-system-packages.yml
  roles/kubernetes/preinstall/tasks/main.yml
  roles/network_plugin/macvlan/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/M

#7540 Update cni-plugins and kubernetes version in README.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7545 Drop calico 3.15
  roles/download/defaults/main.yml
  roles/network_plugin/calico/tasks/install.yml
  roles/network_plugin/calico/templates/calico-node.yml.j2
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/XS

#7543 Bump calico versions
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/XS

#7500 Add nerdctl cli tool for containerd user
  roles/container-engine/nerdctl/handlers/main.yml
  roles/container-engine/nerdctl/tasks/main.yml
  roles/download/defaults/main.yml
  roles/download/tasks/main.yml
  roles/kubespray-defaults/defaults/main.yaml
  roles/reset/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/M

#7550 Fix some docs.ansible.com url typo
  contrib/network-storage/glusterfs/roles/glusterfs/README.md
  docs/ansible.md
  docs/large-deployments.md
  docs/vars.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7551 Fix Opensuse not working with ansible_distribution
  roles/kubernetes-apps/ingress_controller/ambassador/templates/deploy-ambassador.yml.j2
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#7541 Fix cri-o support for Oracle and AlmaLinux
  roles/container-engine/cri-o/tasks/crio_repo.yml
  roles/container-engine/cri-o/vars/almalinux-8.yml
  roles/container-engine/cri-o/vars/oraclelinux-8.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/S

#7544 Add cri-o 1.20/1.21
  roles/container-engine/cri-o/vars/amazon.yml
  roles/container-engine/cri-o/vars/centos-7.yml
  roles/container-engine/cri-o/vars/centos-8.yml
  roles/container-engine/cri-o/vars/debian.yml
  roles/container-engine/cri-o/vars/fedora.yml
  roles/container-engine/cri-o/vars/ubuntu.yml
  roles/download/tasks/download_container.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/M

#7548 Fix calico-kube-controller becomes Error
  roles/network_plugin/calico/tasks/install.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#7556 Update Dockerfile for reduce image size
  Dockerfile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#7557 Do not fail recover-control-plane.yml playbook when broken etcd node is not reachable
  roles/recover_control_plane/etcd/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, ok-to-test, size/XS

#7558 Modify the calico datastore commented config info
  inventory/sample/group_vars/k8s-cluster/k8s-net-calico.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7563 Calico new versions v3.17.4 and v3.18.2
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/S

#7564 Fix calico-kube-controller becomes Error for canal
  roles/network_plugin/canal/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#7562 crio: add supported versions 1.20 and 1.21 and align default with k8s version
  README.md
  roles/container-engine/cri-o/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/S

#7567 add default empty value for etc_hosts_localhosts_dict_target
  roles/kubernetes/preinstall/tasks/0090-etchosts.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#7571 Fix busybox for tests to reduce dockerhub calls
  README.md
  roles/download/defaults/main.yml
  tests/testcases/030_check-network.yml
Labels: approved, cncf-cla: yes, kind/flake, lgtm, size/S

#7560 Add image_arch in flannel image tag
  roles/download/defaults/main.yml
  roles/network_plugin/flannel/templates/cni-flannel.yml.j2
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#7575 Fixes issue #7573 - Made Calico permissions compatible with v3.18.x
  roles/kubernetes-apps/policy_controller/calico/templates/calico-kube-cr.yml.j2
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7570 change kubeadm coredns addon images name to `coredns/coredns`
  roles/download/defaults/main.yml
  roles/download/templates/kubeadm-images.yaml.j2
  roles/kubernetes/control-plane/templates/kubeadm-config.v1beta2.yaml.j2
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/S

#7566 Fix issue with api token wait check not working
  tests/testcases/030_check-network.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#7521 Upgrade cilium role
  README.md
  docs/cilium.md
  roles/download/defaults/main.yml
  roles/kubernetes-apps/network_plugin/meta/main.yml
  roles/network_plugin/cilium/defaults/main.yml
  roles/network_plugin/cilium/tasks/apply.yml
  roles/network_plugin/cilium/tasks/install.yml
  roles/network_plugin/cilium/tasks/main.yml
  roles/network_plugin/cilium/tasks/reset.yml
  roles/network_plugin/cilium/templates/cilium-config.yml.j2
  roles/network_plugin/cilium/templates/cilium-cr.yml.j2
  roles/network_plugin/cilium/templates/cilium-crb.yml.j2
  roles/network_plugin/cilium/templates/cilium-ds.yml.j2
  roles/network_plugin/cilium/templates/hubble-config.yml.j2
  roles/network_plugin/cilium/templates/hubble-cr.yml.j2
  roles/network_plugin/cilium/templates/hubble-crb.yml.j2
  roles/network_plugin/cilium/templates/hubble-cronjob.yml.j2
  roles/network_plugin/cilium/templates/hubble-deploy.yml.j2
  roles/network_plugin/cilium/templates/hubble-job.yml.j2
  roles/network_plugin/cilium/templates/hubble-sa.yml.j2
  roles/network_plugin/cilium/templates/hubble-service.yml.j2
Labels: approved, cncf-cla: yes, kind/design, kind/feature, lgtm, ok-to-test, size/XL
