Repository kubernetes-sigs/kubespray, pull requests merged in 2021-06, with the labels that each got.

#7665 Fix typo
  docs/integration.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7624 Add cinder_csi_ignore_volume_az
  docs/openstack.md
  roles/kubernetes-apps/csi_driver/cinder/templates/cinder-csi-cloud-config.j2
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/S

#7660 Docs improvements
  docs/_sidebar.md
  docs/bootstrap-os.md
  docs/cert_manager.md
  docs/ingress_controller/alb_ingress_controller.md
  docs/ingress_controller/ambassador.md
  docs/ingress_controller/ingress_nginx.md
  docs/ingress_controller/metallb.md
  docs/kubernetes-apps/cephfs_provisioner.md
  docs/kubernetes-apps/local_volume_provisioner.md
  docs/kubernetes-apps/rbd_provisioner.md
  docs/kubernetes-apps/registry.md
  roles/kubernetes-apps/ingress_controller/ambassador/README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/L

#7659 make Terraform inventory script robust against VMs in Error state
  contrib/terraform/terraform.py
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#7674 update containerd to version 1.4.6
  README.md
  roles/container-engine/containerd-common/vars/amazon.yml
  roles/container-engine/containerd-common/vars/debian.yml
  roles/container-engine/containerd-common/vars/fedora.yml
  roles/container-engine/containerd-common/vars/redhat.yml
  roles/container-engine/containerd-common/vars/ubuntu.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#7621 Replace yum module with package module
  contrib/kvm-setup/roles/kvm-setup/tasks/main.yml
  contrib/network-storage/glusterfs/roles/glusterfs/client/tasks/setup-RedHat.yml
  contrib/network-storage/glusterfs/roles/glusterfs/server/tasks/main.yml
  contrib/network-storage/glusterfs/roles/glusterfs/server/tasks/setup-RedHat.yml
  contrib/network-storage/heketi/roles/prepare/tasks/main.yml
  contrib/network-storage/heketi/roles/tear-down-disks/tasks/main.yml
  roles/container-engine/docker-storage/tasks/main.yml
  roles/container-engine/docker/tasks/pre-upgrade.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/S

#7618 Calico enable support for eBPF
  docs/calico.md
  roles/download/defaults/main.yml
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
  roles/network_plugin/calico/defaults/main.yml
  roles/network_plugin/calico/tasks/install.yml
  roles/network_plugin/calico/templates/calico-cr.yml.j2
  roles/network_plugin/calico/templates/calico-node.yml.j2
  roles/network_plugin/calico/templates/calico-typha.yml.j2
  roles/network_plugin/calico/templates/cni-calico.conflist.j2
  roles/network_plugin/calico/templates/kubernetes-services-endpoint.yml.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/L

#7610 Improve scale flow and documentation
  docs/nodes.md
  remove-node.yml
  roles/remove-node/remove-etcd-node/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/M

#7679 make sure serviceaccounts/token is only in the metadata stage
  roles/kubernetes/control-plane/templates/apiserver-audit-policy.yaml.j2
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/XS

#7677 readme invalid k8s_cluster.yml, the create file k8s-cluster.yml
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7656 Remove old groups from test inventory
  tests/cloud_playbooks/roles/packet-ci/templates/inventory.j2
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/M

#7685 Updage docker packages to 20.10.7
  roles/container-engine/docker/vars/debian.yml
  roles/container-engine/docker/vars/fedora.yml
  roles/container-engine/docker/vars/redhat.yml
  roles/container-engine/docker/vars/ubuntu.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/M

#7684 Update the version of local_volume_provisioner
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#7699 Drop "Server" from crio repo URL
  roles/container-engine/cri-o/tasks/crio_repo.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#7703 fix local-path-provisioner helper image repo
  roles/kubernetes-apps/external_provisioner/local_path_provisioner/templates/local-path-storage-cm.yml.j2
  roles/kubernetes-apps/external_provisioner/local_path_provisioner/templates/local-path-storage-deployment.yml.j2
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#7686 Update kube-ovn to 1.7.0
  README.md
  roles/download/defaults/main.yml
  roles/network_plugin/kube-ovn/defaults/main.yml
  roles/network_plugin/kube-ovn/templates/cni-kube-ovn-crd.yml.j2
  roles/network_plugin/kube-ovn/templates/cni-kube-ovn.yml.j2
  roles/network_plugin/kube-ovn/templates/cni-ovn.yml.j2
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/L

#7701 Disable conmon location override for Redhat and Fedora
  roles/container-engine/cri-o/vars/fedora.yml
  roles/container-engine/cri-o/vars/redhat.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#7715 Ubuntu 21.04 changed packagename python-apt in python3-apt
  roles/kubernetes/preinstall/vars/ubuntu-21.04.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/XS

#7702 fix image pull url for coredns v1.8.0
  roles/download/defaults/main.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#7661 gVisor: initial support for gVisor container runtime
  docs/_sidebar.md
  docs/gvisor.md
  roles/container-engine/containerd-common/defaults/main.yml
  roles/container-engine/containerd/templates/config.toml.j2
  roles/container-engine/docker/defaults/main.yml
  roles/container-engine/gvisor/molecule/default/converge.yml
  roles/container-engine/gvisor/molecule/default/files/10-mynet.conf
  roles/container-engine/gvisor/molecule/default/files/container.json
  roles/container-engine/gvisor/molecule/default/files/sandbox.json
  roles/container-engine/gvisor/molecule/default/molecule.yml
  roles/container-engine/gvisor/molecule/default/prepare.yml
  roles/container-engine/gvisor/molecule/default/tests/test_default.py
  roles/container-engine/gvisor/tasks/main.yml
  roles/container-engine/meta/main.yml
  roles/download/defaults/main.yml
  roles/kubernetes-apps/container_runtimes/gvisor/tasks/main.yaml
  roles/kubernetes-apps/container_runtimes/gvisor/templates/runtimeclass-gvisor.yml.j2
  roles/kubernetes-apps/container_runtimes/meta/main.yml
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/L

#7722 Clean up residual files
  roles/reset/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/XS

#7723 Fix deployment without openstack cacert
  roles/kubernetes-apps/external_cloud_controller/openstack/tasks/main.yml
  roles/kubernetes-apps/external_cloud_controller/openstack/templates/external-openstack-cloud-config-secret.yml.j2
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#7724 Update kubernetes-reliability.md
  docs/kubernetes-reliability.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7643 Openstack cwd
  contrib/terraform/openstack/kubespray.tf
  contrib/terraform/openstack/modules/compute/main.tf
  contrib/terraform/openstack/modules/compute/variables.tf
  contrib/terraform/openstack/variables.tf
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/S

#7737 Clean up residual files about modules-load.d
  roles/reset/tasks/main.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/XS

#7736 fix broken link in doc
  docs/metallb.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/XS

#7744 Clean up extra spaces
  contrib/network-storage/glusterfs/inventory.example
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/XS

#7727 [KS-0] - added forgotten bracket in README.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7638 Calico wireguard
  .gitlab-ci/packet.yml
  docs/calico.md
  inventory/sample/group_vars/k8s_cluster/k8s-net-calico.yml
  roles/bootstrap-os/tasks/bootstrap-amazon.yml
  roles/bootstrap-os/tasks/main.yml
  roles/network_plugin/calico/defaults/main.yml
  roles/network_plugin/calico/tasks/install.yml
  roles/network_plugin/calico/tasks/main.yml
  roles/network_plugin/calico/tasks/pre.yml
  roles/network_plugin/calico/tasks/repos.yml
  roles/network_plugin/calico/vars/amazon.yml
  roles/network_plugin/calico/vars/debian.yml
  roles/network_plugin/calico/vars/fedora.yml
  roles/network_plugin/calico/vars/opensuse.yml
  roles/network_plugin/calico/vars/redhat.yml
  tests/files/packet_ubuntu20-calico-ha-wireguard.yml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/L

#7746 Enable Graceful Node Shutdown for Kubernetes >= 1.21.0
  inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
  roles/kubernetes/node/templates/kubelet-config.v1beta1.yaml.j2
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/S

#7749 Calico Docs: clarify the algorithm to calculate calico_veth_mtu
  docs/calico.md
  inventory/sample/group_vars/k8s_cluster/k8s-net-calico.yml
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/S

#7752 Extra spaces of macvlan
  roles/network_plugin/macvlan/files/ifdown-macvlan
  roles/network_plugin/macvlan/files/ifup-macvlan
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/S

#7748 nodelocaldns: allow binding metrics address to host IP
  inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
  roles/kubernetes-apps/ansible/templates/nodelocaldns-config.yml.j2
  roles/kubernetes-apps/ansible/templates/nodelocaldns-daemonset.yml.j2
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/S

#7764 added destination filename to cp command
  roles/etcdctl/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7754 add python requirement ruamel.yaml.clib==0.2.2 to keep python 2.7
  requirements.txt
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS
