Repository kubernetes-sigs/kubespray, pull requests merged in 2021-09, with the labels that each got.

#7925 MetalLB: update to v0.10.2
  inventory/sample/group_vars/k8s_cluster/addons.yml
  roles/kubernetes-apps/metallb/defaults/main.yml
  roles/kubernetes-apps/metallb/tasks/main.yml
  roles/kubernetes-apps/metallb/templates/metallb.yml.j2
Labels: cncf-cla: yes, size/L, lgtm, ok-to-test, approved, kind/feature

#7928 Fix CI script for Terraform >0.15
  .gitlab-ci/terraform.yml
  tests/scripts/create-tf.sh
  tests/scripts/delete-tf.sh
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved

#7923 Replace cluster_name by dns_domain
  roles/kubernetes-apps/registry/templates/registry-proxy-ds.yml.j2
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#7931 MetalLB: keep nodeSelector in one place
  roles/kubernetes-apps/metallb/defaults/main.yml
  roles/kubernetes-apps/metallb/templates/metallb.yml.j2
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/cleanup

#7837 cri-o registry auth support
  inventory/sample/group_vars/all/cri-o.yml
  roles/container-engine/cri-o/defaults/main.yml
  roles/container-engine/cri-o/tasks/main.yaml
  roles/container-engine/cri-o/templates/config.json.j2
  roles/container-engine/cri-o/templates/crio.conf.j2
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/feature

#7933 Update Ansible tags in documentation
  docs/ansible.md
Labels: cncf-cla: yes, size/L, lgtm, approved, kind/documentation

#7943 Update CSI snaphotter and make it independent
  inventory/sample/group_vars/k8s_cluster/addons.yml
  roles/download/defaults/main.yml
  roles/kubernetes-apps/csi_driver/csi_crd/templates/volumesnapshotclasses.yml.j2
  roles/kubernetes-apps/csi_driver/csi_crd/templates/volumesnapshotcontents.yml.j2
  roles/kubernetes-apps/csi_driver/csi_crd/templates/volumesnapshots.yml.j2
  roles/kubernetes-apps/meta/main.yml
  roles/kubernetes-apps/snapshots/meta/main.yml
  roles/kubernetes-apps/snapshots/snapshot-controller/templates/snapshot-controller.yml.j2
  roles/kubespray-defaults/defaults/main.yaml
Labels: cncf-cla: yes, size/XXL, lgtm, ok-to-test, approved, kind/feature

#7936 crictl: add hashes for 1.22
  roles/download/defaults/main.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#7940 Update containerd to 1.4.9
  roles/container-engine/containerd-common/vars/debian.yml
  roles/container-engine/containerd-common/vars/fedora.yml
  roles/container-engine/containerd-common/vars/redhat.yml
  roles/container-engine/containerd-common/vars/ubuntu.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/feature

#7942 nginx-ingress: bump to 1.0.0 to support kube 1.22
  roles/download/defaults/main.yml
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/clusterrole-ingress-nginx.yml.j2
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/role-ingress-nginx.yml.j2
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#7938 Feature DynamicKubeletConfig is deprecated in 1.22 and will not move to GA
  inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
  roles/kubernetes/node/tasks/kubelet.yml
  roles/kubernetes/node/templates/kubelet.env.v1beta1.j2
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
  tests/files/packet_oracle7-canal-ha.yml
  tests/files/packet_ubuntu16-canal-kubeadm-ha.yml
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, ok-to-test, approved

#7944 Calico: Add kube_service_addresses_ipv6 to serviceClusterIPs
  roles/network_plugin/calico/tasks/install.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#7947 Replace incorrect {% end %} tags with {% endif %} in csi_crd templates
  roles/kubernetes-apps/csi_driver/csi_crd/templates/volumesnapshotclasses.yml.j2
  roles/kubernetes-apps/csi_driver/csi_crd/templates/volumesnapshotcontents.yml.j2
  roles/kubernetes-apps/csi_driver/csi_crd/templates/volumesnapshots.yml.j2
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, ok-to-test, approved

#7949 Remove invalid spec - deployment.spec.serviceName
  roles/kubernetes-apps/snapshots/snapshot-controller/templates/snapshot-controller.yml.j2
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#7950 Fix README for containerd/calico/nginx and cert_manager
  README.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/documentation

#7957 Update snapshot-controller repository and image versions
  roles/download/defaults/main.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#7952 Update cilium and kube-ovn minor versions
  README.md
  roles/download/defaults/main.yml
  roles/network_plugin/kube-ovn/templates/cni-kube-ovn-crd.yml.j2
Labels: cncf-cla: yes, size/S, lgtm, approved, kind/feature, tide/merge-method-rebase

#7955 Bugfix/cinder csi cloud config template
  roles/kubernetes-apps/csi_driver/cinder/templates/cinder-csi-cloud-config.j2
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, ok-to-test, approved

#7959 Fix missing file mode (risky-file-permissions)
  roles/bootstrap-os/tasks/bootstrap-centos.yml
  roles/container-engine/cri-o/tasks/main.yaml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/cleanup

#7583 Fix: adding new ips with inventory builder (#7577)
  contrib/inventory_builder/inventory.py
  contrib/inventory_builder/tests/test_inventory.py
Labels: kind/bug, cncf-cla: yes, size/L, lgtm, ok-to-test, approved

#7779 Updated UpCloud terraform script to use private network and dynamic additional disks
  contrib/terraform/upcloud/README.md
  contrib/terraform/upcloud/cluster-settings.tfvars
  contrib/terraform/upcloud/main.tf
  contrib/terraform/upcloud/modules/kubernetes-cluster/main.tf
  contrib/terraform/upcloud/modules/kubernetes-cluster/output.tf
  contrib/terraform/upcloud/modules/kubernetes-cluster/variables.tf
  contrib/terraform/upcloud/sample-inventory/cluster.tfvars
  contrib/terraform/upcloud/variables.tf
Labels: cncf-cla: yes, size/L, lgtm, ok-to-test, approved, kind/feature

#7785 add node-based upgrade
  docs/upgrades.md
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/documentation

#7964 Fix iptables missing on Debian 11 if APT::Install-Recommends=0
  roles/kubernetes/preinstall/vars/debian-11.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#7966 Modify connection_strings_etcd to only return etcd nodes
  contrib/terraform/aws/create-infrastructure.tf
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/documentation

#7971 remove kube_proxy_conntrack_max var
  roles/kubernetes/control-plane/defaults/main/kube-proxy.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/cleanup

#7972 Fix ubuntu16/centos8 CI jobs
  roles/container-engine/containerd-common/vars/ubuntu-16.yml
  roles/container-engine/docker/vars/ubuntu-16.yml
  tests/files/packet_centos8-kube-ovn.yml
  tests/files/packet_ubuntu16-canal-kubeadm-ha.yml
  tests/files/packet_ubuntu16-canal-sep.yml
  tests/files/packet_ubuntu16-flannel-ha.yml
  tests/files/packet_ubuntu16-kube-router-sep.yml
  tests/files/packet_ubuntu16-kube-router-svc-proxy.yml
  tests/files/packet_ubuntu16-weave-sep.yml
Labels: cncf-cla: yes, size/M, lgtm, approved

#7976 Add option to kubeadm upgrade command to control certificates renewal during control plane upgrade
  roles/kubernetes/control-plane/defaults/main/main.yml
  roles/kubernetes/control-plane/tasks/kubeadm-upgrade.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#7977 Fix default version
  roles/kubespray-defaults/defaults/main.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#7981 Calico: increase calico node probe timeouts and allow tunning
  docs/calico.md
  inventory/sample/group_vars/k8s_cluster/k8s-net-calico.yml
  roles/network_plugin/calico/templates/calico-node.yml.j2
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/network

#7939 Calico: make calico_min_version check relevant
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
  roles/kubespray-defaults/vars/main.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/feature

#7984 Calico: update versions 3.20.1, 3.19.3
  README.md
  roles/download/defaults/main.yml
  roles/network_plugin/calico/tasks/install.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/feature

#7992 Fix k8s-certs-renew cp path
  roles/kubernetes/control-plane/templates/k8s-certs-renew.sh.j2
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#7993 Remove comparison of kubelet_shutdown_grace_period and kubelet_shutdown_grace_period_critical_pods
  inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note

#8000 Fix Cilium operator metrics activation
  roles/network_plugin/cilium/templates/cilium-config.yml.j2
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#7998 Remove k8s hooks for versions prior to 1.20
  roles/kubernetes-apps/ansible/templates/coredns-deployment.yml.j2
  roles/kubernetes-apps/ansible/templates/dns-autoscaler.yml.j2
  roles/kubernetes-apps/cloud_controller/oci/templates/oci-cloud-provider.yml.j2
  roles/kubernetes-apps/container_runtimes/crun/templates/runtimeclass-crun.yml
  roles/kubernetes-apps/container_runtimes/gvisor/templates/runtimeclass-gvisor.yml.j2
  roles/kubernetes-apps/container_runtimes/kata_containers/templates/runtimeclass-kata-qemu.yml.j2
  roles/kubernetes-apps/csi_driver/csi_crd/templates/volumesnapshotclasses.yml.j2
  roles/kubernetes-apps/csi_driver/csi_crd/templates/volumesnapshotcontents.yml.j2
  roles/kubernetes-apps/csi_driver/csi_crd/templates/volumesnapshots.yml.j2
  roles/kubernetes-apps/csi_driver/vsphere/templates/vsphere-csi-controller-deployment.yml.j2
  roles/kubernetes-apps/csi_driver/vsphere/templates/vsphere-csi-controller-ss.yml.j2
  roles/kubernetes-apps/external_cloud_controller/openstack/templates/external-openstack-cloud-controller-manager-ds.yml.j2
  roles/kubernetes-apps/external_cloud_controller/vsphere/templates/external-vsphere-cloud-controller-manager-ds.yml.j2
  roles/kubernetes-apps/metrics_server/templates/metrics-server-deployment.yaml.j2
Labels: cncf-cla: yes, size/M, lgtm, approved, kind/cleanup

#8001 etcd: enable v2 api only if needed
  roles/etcd/templates/etcd.env.j2
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/cleanup

#8005 Issue 8004: Fix typha prometheus
  roles/network_plugin/calico/templates/calico-typha.yml.j2
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/network

#7996 Use kube_config_dir for kubeconfig
  roles/kubernetes/control-plane/tasks/kubeadm-setup.yml
  roles/kubernetes/control-plane/tasks/kubeadm-upgrade.yml
  roles/remove-node/pre-remove/tasks/main.yml
  roles/upgrade/post-upgrade/tasks/main.yml
  roles/upgrade/pre-upgrade/tasks/main.yml
Labels: cncf-cla: yes, size/S, lgtm, approved, release-note

#8008 Revert "etcd: enable v2 api only if needed"
  roles/etcd/templates/etcd.env.j2
Labels: cncf-cla: yes, size/XS, lgtm, approved

#8007 kube-router 1.3.0 -> 1.3.1
  README.md
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#7995 Add definition check of disable_service_firewall
  contrib/os-services/roles/prepare/tasks/main.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved

#8011 Fix containerd failed to start if apparmor is not installed
  roles/kubernetes/preinstall/vars/debian-11.yml
  roles/kubernetes/preinstall/vars/debian.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#7710 CI: Add Calico eBPF in HA mode test
  .gitlab-ci/packet.yml
  docs/calico.md
  inventory/sample/group_vars/k8s_cluster/k8s-net-calico.yml
  tests/files/packet_centos8-calico-ha-ebpf.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/feature

#8021 Check if Openstack application credentials are empty
  roles/kubernetes-apps/external_cloud_controller/openstack/templates/external-openstack-cloud-config.j2
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/applications

#8006 Move ovn4nfv crd from v1beta1 to v1
  roles/network_plugin/ovn4nfv/templates/ovn4nfv-k8s-plugin.yml.j2
Labels: cncf-cla: yes, size/L, lgtm, approved, kind/network

#8017 Kata-Containers: update versions 2.2.0 (default) and 2.1.1
  roles/container-engine/kata-containers/templates/configuration-qemu.toml.j2
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/container-managers

#8014 Remove allowPrivilegeEscalation from metrics-server
  roles/kubernetes-apps/metrics_server/templates/metrics-server-deployment.yaml.j2
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved

#8012 Add proxy for subscription-manager
  roles/bootstrap-os/tasks/bootstrap-redhat.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved

#8019 Add 'stable' and 'edge' keys in docker_cli_versioned_pkg dict
  roles/container-engine/docker/vars/debian-stretch.yml
  roles/container-engine/docker/vars/debian.yml
  roles/container-engine/docker/vars/fedora.yml
  roles/container-engine/docker/vars/redhat.yml
  roles/container-engine/docker/vars/ubuntu-16.yml
  roles/container-engine/docker/vars/ubuntu.yml
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, approved

#7717 check if 'plugins' key exists in calico_cni_config object
  roles/network_plugin/calico/tasks/pre.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#8025 [2.17] Remove allowPrivilegeEscalation from metrics-server (#8014)
  roles/kubernetes-apps/metrics_server/templates/metrics-server-deployment.yaml.j2
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved

#8024 Determine root filesistem device and partition before running growpart
  roles/kubernetes/preinstall/tasks/0120-growpart-azure-centos-7.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/feature

#8018 Add metrics_server_resizer option
  inventory/sample/group_vars/k8s_cluster/addons.yml
  roles/kubernetes-apps/metrics_server/defaults/main.yml
  roles/kubernetes-apps/metrics_server/templates/metrics-server-deployment.yaml.j2
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/feature

#8013 Update weave template to match source for 2.8.1
  roles/network_plugin/weave/templates/weave-net.yml.j2
Labels: kind/bug, cncf-cla: yes, size/M, lgtm, ok-to-test, approved

#7692 Fix invalid documentation links
  docs/ansible.md
  docs/calico.md
  docs/large-deployments.md
  docs/vars.md
  docs/vsphere.md
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/documentation

#8031 [2.17] Add metrics_server_resizer option (#8018)
  inventory/sample/group_vars/k8s_cluster/addons.yml
  roles/kubernetes-apps/metrics_server/defaults/main.yml
  roles/kubernetes-apps/metrics_server/templates/metrics-server-deployment.yaml.j2
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved

#8032 [2.17] Fix k8s-certs-renew cp path (#7992)
  roles/kubernetes/control-plane/templates/k8s-certs-renew.sh.j2
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved

#8033 [2.17] Fix cilium operator metrics activation (#8000)
  roles/network_plugin/cilium/templates/cilium-config.yml.j2
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved

#8016 In CentOS 8.x Docker install Step: remove podman when existing
  roles/container-engine/docker/defaults/main.yml
  roles/container-engine/docker/tasks/pre-upgrade.yml
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, ok-to-test, approved

#8034 Upgrade ruamel.yaml.clib to work with Python 3.10
  requirements.txt
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#8035 [2.17] Issue 8004: Fix typha prometheus (#8005)
  roles/network_plugin/calico/templates/calico-typha.yml.j2
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, approved

#8015 gVisor: bump release to 20210921 version
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/container-managers

#8036 Ensure apparmor is installed (Ubuntu)
  roles/kubernetes/preinstall/vars/ubuntu.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#8037 [2.17] Use kube_config_dir for kubeconfig (#7996)
  roles/kubernetes/control-plane/tasks/kubeadm-setup.yml
  roles/kubernetes/control-plane/tasks/kubeadm-upgrade.yml
  roles/remove-node/pre-remove/tasks/main.yml
  roles/upgrade/post-upgrade/tasks/main.yml
  roles/upgrade/pre-upgrade/tasks/main.yml
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, approved

#8040 [2.17] check if 'plugins' key exists in calico_cni_config object (#7717)
  roles/network_plugin/calico/tasks/pre.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved

#8039 [2.17] Add proxy for subscription-manager (#8012)
  roles/bootstrap-os/tasks/bootstrap-redhat.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved
