Repository kubernetes-sigs/kubespray, pull requests merged in 2022-02, with the labels that each got.

#8488 Allow overriding CoreDNS default zone cache block
  docs/dns-stack.md
  roles/kubernetes-apps/ansible/defaults/main.yml
  roles/kubernetes-apps/ansible/templates/coredns-config.yml.j2
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/feature

#8489 [helm] upgrade to 3.8.0
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/S, lgtm, approved, kind/feature, release-note-none

#8494 [misc] add cristicalin to approvers list
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/flake

#8395 Use sysctl_file_path variable for all sysctl_file locations
  contrib/kvm-setup/roles/kvm-setup/tasks/sysctl.yml
  inventory/sample/group_vars/all/all.yml
  roles/kubernetes/preinstall/tasks/0080-system-configurations.yml
  roles/kubespray-defaults/defaults/main.yaml
  roles/reset/tasks/main.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, release-note

#8497 terraform/gcp: Do not create unused subnetworks and Upgrade to latest google provider
  contrib/terraform/gcp/main.tf
  contrib/terraform/gcp/modules/kubernetes-cluster/main.tf
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved

#8490 [ingress-nginx] upgrade to 1.1.1
  README.md
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/feature, release-note-none

#8484 [nerdctl] upgrade to 0.16.0
  roles/container-engine/nerdctl/tasks/main.yml
  roles/container-engine/nerdctl/templates/nerdctl.toml.j2
  roles/download/defaults/main.yml
  roles/reset/tasks/main.yml
Labels: cncf-cla: yes, size/M, lgtm, approved, kind/feature, release-note-none

#8477 Amend documentation for docker to containerd migration
  docs/upgrades/migrate_docker2containerd.md
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved

#8500 Fix kubelet_kubelet_cgroups_cgroupfs
  roles/kubernetes/node/defaults/main.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#8455 [terraform][openstack] allow disabling port_security at port level
  contrib/terraform/openstack/README.md
  contrib/terraform/openstack/kubespray.tf
  contrib/terraform/openstack/modules/compute/main.tf
  contrib/terraform/openstack/modules/compute/variables.tf
Labels: kind/bug, cncf-cla: yes, size/L, lgtm, approved, release-note

#8491 feat: update cert-manager to 1.7.0
  roles/download/defaults/main.yml
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/cert-manager.crds.yml.j2
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/cert-manager.yml.j2
Labels: cncf-cla: yes, size/XXL, lgtm, ok-to-test, approved

#8505 Added ppc64le support
  roles/download/defaults/main.yml
  scripts/download_hash.py
  scripts/download_hash.sh
Labels: cncf-cla: yes, size/L, lgtm, ok-to-test, approved, kind/feature

#8496 CRI-O: fix unqualified-search registries
  docs/cri-o.md
  roles/container-engine/cri-o/templates/unqualified.conf.j2
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#8504 Add bastion support to remove-node.yml
  remove-node.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#8508 Fixed mitogen.yml
  contrib/mitogen/mitogen.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#8514 [2.18] CI: Replace CentOS 8 with AlmaLinux 8
  .gitlab-ci/packet.yml
  Vagrantfile
  docs/ci.md
  roles/bootstrap-os/molecule/default/molecule.yml
  roles/container-engine/containerd/molecule/default/molecule.yml
  roles/container-engine/cri-o/molecule/default/molecule.yml
  roles/container-engine/docker/molecule/default/molecule.yml
  roles/container-engine/gvisor/molecule/default/molecule.yml
  test-infra/image-builder/roles/kubevirt-images/defaults/main.yml
  tests/cloud_playbooks/roles/packet-ci/defaults/main.yml
  tests/files/packet_almalinux8-calico-ha-ebpf.yml
  tests/files/packet_almalinux8-calico-nodelocaldns-secondary.yml
  tests/files/packet_almalinux8-calico.yml
  tests/files/packet_almalinux8-crio.yml
  tests/files/packet_almalinux8-docker.yml
  tests/files/packet_almalinux8-kube-ovn.yml
Labels: cncf-cla: yes, size/M, lgtm, approved, kind/feature, kind/failing-test

#8519 Change Cilium setting identity_allocation_mode to cilium_identity_allocation_mode
  inventory/sample/group_vars/k8s_cluster/k8s-net-cilium.yml
  roles/network_plugin/cilium/defaults/main.yml
  roles/network_plugin/cilium/tasks/check.yml
  roles/network_plugin/cilium/tasks/install.yml
  roles/network_plugin/cilium/templates/cilium-config.yml.j2
  roles/network_plugin/cilium/templates/cilium-deploy.yml.j2
  roles/network_plugin/cilium/templates/cilium-ds.yml.j2
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/cleanup

#8523 docs: Update offline-environment.md for containerd (#8520)
  docs/offline-environment.md
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#8513 [2.18] Move containerd_version to defaults/main.yml (#8379)
  contrib/offline/generate_list.sh
  roles/download/defaults/main.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved

#8538 feat(offline): Improve generate_list.sh using ansible (#8537)
  contrib/offline/README.md
  contrib/offline/generate_list.sh
  contrib/offline/generate_list.yml
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/feature

#8474 implement download mirrors support
  roles/download/defaults/main.yml
  roles/download/tasks/download_file.yml
Labels: cncf-cla: yes, size/M, lgtm, approved, kind/feature

#8541 add support for Calico IP6_AUTODETECTION_METHOD
  inventory/sample/group_vars/k8s_cluster/k8s-net-calico.yml
  roles/network_plugin/calico/defaults/main.yml
  roles/network_plugin/calico/templates/calico-node.yml.j2
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/feature

#8524 terraform/gcp: Allow to change extra disk types
  contrib/terraform/gcp/README.md
  contrib/terraform/gcp/main.tf
  contrib/terraform/gcp/modules/kubernetes-cluster/main.tf
  contrib/terraform/gcp/modules/kubernetes-cluster/variables.tf
  contrib/terraform/gcp/variables.tf
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved

#8542 add ip6 host vars to support Dual Stack node InternalIP
  docs/vars.md
  roles/kubernetes/node/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#8534 Allow to specify a source address for metallb peerings, and target on…
  roles/kubernetes-apps/metallb/templates/metallb-config.yml.j2
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/applications

#8544 [calico] upgrade release checksums
  README.md
  roles/download/defaults/main.yml
  roles/network_plugin/calico/tasks/install.yml
Labels: cncf-cla: yes, size/M, lgtm, approved, kind/feature

#8530 Allow pausing after upgrade but before uncordon
  docs/upgrades.md
  roles/upgrade/post-upgrade/defaults/main.yml
  roles/upgrade/post-upgrade/tasks/main.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/feature

#8539 [nerdctl] upgrade to 0.16.1
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/S, lgtm, approved, kind/feature

#8550 Fix etcd_events not getting upgraded in upgrade-cluster.yml
  upgrade-cluster.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#8554 Fix print_hostnames of inventory.py
  contrib/inventory_builder/inventory.py
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved

#8521 Configure Etcd container_manager explicitly
  inventory/sample/group_vars/etcd.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#8564 Fix amazon docker version
  roles/container-engine/docker/vars/amazon.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/flake

#8565 fix: kube-dns service deletion
  roles/kubernetes-apps/ansible/tasks/cleanup_dns.yml
  roles/kubernetes-apps/ansible/templates/coredns-svc.yml.j2
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, ok-to-test, approved

#8566 chore: remove addon-resizer
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, release-note

#8568 improve validation conditions for MetalLB BGP Peers
  roles/kubernetes-apps/metallb/tasks/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/cleanup

#8570 Prevent removing etcd member when running in check mode
  roles/remove-node/remove-etcd-node/tasks/main.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#8569 Cleanup crictl configuration file
  roles/reset/tasks/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/cleanup

#8573 Check all places with `check_mode: no` for side effects
  roles/etcd/tasks/gen_certs_script.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/cleanup, needs-ok-to-test

#8574 Encrypting Secret Data at Rest
  docs/encrypting-secret-data-at-rest.md
  inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
  roles/kubernetes/control-plane/defaults/main/main.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/feature

#8576 Fixup remaining etcd_kubeadm_enabled variables
  roles/network_plugin/canal/tasks/main.yml
  roles/remove-node/remove-etcd-node/tasks/main.yml
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, approved

#8545 [CI] add ara to collect CI job logs
  ansible.cfg
  tests/requirements-2.10.txt
  tests/requirements-2.11.txt
  tests/requirements-2.9.txt
  tests/scripts/testcases_cleanup.sh
  tests/scripts/testcases_run.sh
Labels: cncf-cla: yes, size/S, lgtm, approved, kind/feature

#8572 fix(coredns): make sure to keep coredns repository namespace
  roles/download/templates/kubeadm-images.yaml.j2
  roles/kubernetes/control-plane/templates/kubeadm-config.v1beta2.yaml.j2
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#8578 [Terraform-AWS] Replace CLB with NLB for kube-apiserver domain
  contrib/terraform/aws/create-infrastructure.tf
  contrib/terraform/aws/modules/elb/main.tf
  contrib/terraform/aws/modules/elb/outputs.tf
  contrib/terraform/aws/modules/nlb/main.tf
  contrib/terraform/aws/modules/nlb/outputs.tf
  contrib/terraform/aws/modules/nlb/variables.tf
  contrib/terraform/aws/output.tf
  contrib/terraform/aws/sample-inventory/cluster.tfvars
  contrib/terraform/aws/templates/inventory.tpl
  contrib/terraform/aws/terraform.tfvars
  contrib/terraform/aws/terraform.tfvars.example
  contrib/terraform/aws/variables.tf
Labels: cncf-cla: yes, size/L, lgtm, ok-to-test, approved, release-note

#8575 Fix host DNS settings being edited too soon, and not working with NetworkManager
  cluster.yml
  roles/kubernetes/preinstall/defaults/main.yml
  roles/kubernetes/preinstall/handlers/main.yml
  roles/kubernetes/preinstall/tasks/0040-set_facts.yml
  roles/kubernetes/preinstall/tasks/0060-resolvconf.yml
  roles/kubernetes/preinstall/tasks/0062-networkmanager-unmanaged-devices.yml
  roles/kubernetes/preinstall/tasks/0063-networkmanager-dns.yml
  roles/kubernetes/preinstall/tasks/main.yml
  scale.yml
  upgrade-cluster.yml
Labels: kind/bug, cncf-cla: yes, size/M, lgtm, ok-to-test, approved

#8580 Fix typo / error regarding etcd and k8s_cluster groups
  docs/ansible.md
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/documentation

#8439 feat: check & uninstall container engine if needed
  roles/container-engine/containerd/tasks/reset.yml
  roles/container-engine/cri-o/tasks/crio_repo.yml
  roles/container-engine/cri-o/tasks/reset.yml
  roles/container-engine/docker/tasks/reset.yml
  roles/container-engine/meta/main.yml
  roles/container-engine/validate-container-engine/tasks/main.yml
Labels: kind/bug, cncf-cla: yes, size/L, lgtm, ok-to-test, approved
