Repository kubernetes-sigs/kubespray, pull requests merged in 2022-08, with the labels that each got.

#9136 Update Kube-router version to 1.5.1
  README.md
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/feature

#9078 Add kylin OS support
  README.md
  docs/_sidebar.md
  docs/kylinlinux.md
  roles/bootstrap-os/tasks/main.yml
  roles/container-engine/containerd/tasks/main.yml
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/feature

#9133 Update to latest registry version
  README.md
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9132 Update to latest local path provisioner version
  README.md
  inventory/sample/group_vars/k8s_cluster/addons.yml
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9144 Add docker support for kylin distributions
  docs/kylinlinux.md
  roles/container-engine/docker/tasks/main.yml
  roles/container-engine/docker/vars/kylin.yml
  roles/kubernetes/preinstall/tasks/0040-set_facts.yml
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/feature

#9146 Argument jsonpath must be single-quoted in "See if node is schedulable" task
  roles/upgrade/pre-upgrade/tasks/main.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9147 Move old etcd backup removal after etcd restart
  roles/etcd/handlers/backup.yml
  roles/etcd/handlers/backup_cleanup.yml
  roles/etcd/handlers/main.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/feature

#9149 add kube-vip in README
  README.md
Labels: cncf-cla: yes, size/XS, lgtm, approved

#9155 Add kube-vip check to check_readme_versions.sh
  tests/scripts/check_readme_versions.sh
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/cleanup

#9156 [ingress-nginx] Fix ingress-nginx RBAC rules when deployed classless
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/role-ingress-nginx.yml.j2
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved

#9175 [CI] fix molecule tests on opensuse by upgrading to 15.4
  Vagrantfile
  roles/bootstrap-os/tasks/bootstrap-opensuse.yml
  roles/container-engine/containerd/molecule/default/molecule.yml
Labels: cncf-cla: yes, size/S, lgtm, approved, kind/failing-test

#9180 Upgrade nerdctl from 0.20.0 to 0.22.2
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved

#9125 fix: remove condition for user creation
  roles/adduser/tasks/main.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9185 Update dashboard to v2.6.1
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#9181 [containerd] upgrade to 1.6.8 , add hashes
  README.md
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/S, lgtm, approved, kind/feature

#9184 add tar in common required package
  roles/kubernetes/preinstall/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9164 Add unsafe_show_logs switch
  inventory/sample/group_vars/all/all.yml
  roles/bootstrap-os/defaults/main.yml
  roles/bootstrap-os/tasks/bootstrap-redhat.yml
  roles/download/defaults/main.yml
  roles/download/tasks/download_file.yml
  roles/download/tasks/prep_download.yml
  roles/etcd/defaults/main.yml
  roles/etcd/tasks/gen_certs_script.yml
  roles/kubernetes-apps/csi_driver/vsphere/defaults/main.yml
  roles/kubernetes-apps/csi_driver/vsphere/tasks/main.yml
  tests/common/_kubespray_test_settings.yml
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/feature

#9134 [calico] calico rr supports multiple groups
  docs/calico.md
  roles/network_plugin/calico/rr/tasks/update-node.yml
  roles/network_plugin/calico/tasks/install.yml
  roles/network_plugin/calico/tasks/peer_with_calico_rr.yml
  roles/network_plugin/calico/tasks/peer_with_router.yml
Labels: cncf-cla: yes, size/L, lgtm, approved, kind/feature

#9153 Fix CSI drivers issues on Azure
  roles/kubernetes-apps/csi_driver/azuredisk/tasks/main.yml
  roles/kubernetes-apps/csi_driver/azuredisk/templates/azure-csi-azuredisk-controller.yml.j2
  roles/kubernetes-apps/csi_driver/azuredisk/templates/azure-csi-azuredisk-node.yml.j2
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved

#9159 Subnet setup order fix & Number of master nodes syntax fix
  contrib/terraform/openstack/kubespray.tf
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9160 Disable DNSStubListener for Flatcar Linux
  roles/kubernetes/preinstall/templates/resolved.conf.j2
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9165 docs(kube-vip): fix broken links
  docs/kube-vip.md
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/documentation

#9178 add list/watch nodes rules to cilium-operator clusterrole
  roles/network_plugin/cilium/templates/cilium-operator/cr.yml.j2
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/network

#9017 Add the option to enable default Pod Security Configuration
  docs/hardening.md
  roles/kubernetes/control-plane/defaults/main/main.yml
  roles/kubernetes/control-plane/templates/podsecurity.yaml.j2
  roles/kubernetes/control-plane/vars/main.yaml
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/feature

#9166 Add 'avoid-buggy-ips' support of MetalLB
  docs/metallb.md
  inventory/sample/group_vars/k8s_cluster/addons.yml
  roles/kubernetes-apps/metallb/defaults/main.yml
  roles/kubernetes-apps/metallb/templates/metallb-config.yml.j2
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/feature

#9191 [kubernetes] Add hashes for 1.24.4, 1.22.13, 1.23.10 and make v1.24.4 default
  README.md
  inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
  roles/download/defaults/main.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: cncf-cla: yes, size/M, lgtm, approved, kind/feature

#9176 9035: Make Cilium rolling-restart delay/timeout configurable
  docs/cilium.md
  roles/network_plugin/cilium/defaults/main.yml
  roles/network_plugin/cilium/tasks/apply.yml
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/network

#9207 Fix containerd (<1.7) configuration for insecure registries
  roles/container-engine/containerd/templates/config.toml.j2
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9203 fix one bug in docs/nodes
  docs/nodes.md
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9172 typos fixed in `kubespray/docs/vars.md`
  docs/vars.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/documentation

#9204 optimize the format of evictionHard in kubelet-config.yaml template
  roles/kubernetes/node/templates/kubelet-config.v1beta1.yaml.j2
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9210 do not run etcd role in scale.yml playbook when etcd installed by kub…
  scale.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved

#9205 cri-dockerd: add restart of docker.service
  roles/container-engine/cri-dockerd/handlers/main.yml
  roles/container-engine/cri-dockerd/tasks/main.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9158 add pre-commit hook to facilitate local testing
  .gitignore
  .markdownlint.yaml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  contrib/network-storage/glusterfs/roles/glusterfs/README.md
  contrib/terraform/aws/README.md
  contrib/terraform/exoscale/README.md
  contrib/terraform/vsphere/README.md
  docs/azure-csi.md
  docs/azure.md
  docs/bootstrap-os.md
  docs/calico.md
  docs/debian.md
  docs/fcos.md
  docs/gcp-lb.md
  docs/integration.md
  docs/kubernetes-apps/registry.md
  docs/setting-up-your-first-cluster.md
  docs/vagrant.md
  docs/vars.md
Labels: cncf-cla: yes, size/L, lgtm, approved, kind/feature

#9216 backport 2.19 - do not run etcd role in scale.yml playbook when etcd installed by kub…
  scale.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#9229 [CI] remove opensuse Leap from molecule test blocking CI
  roles/container-engine/containerd/molecule/default/molecule.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/failing-test

#9228 Fixes for calico_datastore: etcd
  roles/network_plugin/calico/tasks/install.yml
  roles/network_plugin/calico/templates/calico-cr.yml.j2
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9223 kube-vip shoud fail if kube_proxy_strict_arp is false in arp mod
  docs/kube-vip.md
  inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
  roles/kubernetes/control-plane/defaults/main/kube-proxy.yml
  roles/kubernetes/node/tasks/loadbalancer/kube-vip.yml
Labels: cncf-cla: yes, size/S, lgtm, approved, release-note

#9230 [runc] update to v1.1.4
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature, release-note-none

#9220 Fix some typo
  docs/ansible.md
  docs/calico.md
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/documentation, release-note-none

#9218 Fix kube_ovn_hw_offload value
  roles/network_plugin/kube-ovn/templates/cni-ovn.yml.j2
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved

#9232 Fix cloud_init files for different distros
  tests/cloud_playbooks/roles/packet-ci/defaults/main.yml
Labels: cncf-cla: yes, size/S, lgtm, approved, kind/flake

#9217 Fix abort because calicoctl.sh is not a full path
  roles/network_plugin/calico/tasks/check.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9234 Fixes for calico etcd mode (2.19 backport)
  roles/network_plugin/calico/tasks/install.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved

#9194 feat: add kubelet systemd service hardening option
  docs/hardening.md
  docs/img/kubelet-hardening.png
  docs/vars.md
  roles/kubernetes/node/defaults/main.yml
  roles/kubernetes/node/templates/kubelet.service.j2
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved

#9227 add retries for creating calico ipamconfig resources
  roles/network_plugin/calico/tasks/install.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9235 Update security contacts file
  SECURITY_CONTACTS
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/flake

#9240 [2.18] disable auth webhook default
  roles/kubespray-defaults/defaults/main.yaml
Labels: kind/bug, cncf-cla: yes, size/XS

#9239 [2.19] disable auth webhook default
  docs/hardening.md
  roles/kubespray-defaults/defaults/main.yaml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved

#9238 disable kubelet_authorization_mode_webhook by default
  docs/hardening.md
  roles/kubespray-defaults/defaults/main.yaml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved
