Repository kubernetes-sigs/kubespray, pull requests merged in 2022-10, with the labels that each got.

#9351 Support customize the additional sysctl variables
  roles/kubernetes/preinstall/tasks/0080-system-configurations.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/feature

#9357 feat: add a parameter to disable host nameservers
  inventory/sample/group_vars/all/all.yml
  roles/kubernetes/preinstall/tasks/0040-set_facts.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#9331 Add possibility to skip adding load balancer name in the hosts file
  roles/kubernetes/preinstall/defaults/main.yml
  roles/kubernetes/preinstall/tasks/0090-etchosts.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#9352 Promote Kubean Link in Docs
  README.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, release-note-none

#9355 Fix default value for kubelet_secure_addresses
  roles/kubernetes/node/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#9326 Features/support kubeadm patches v1beta3
  inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
  inventory/sample/patches/kube-controller-manager+merge.yaml
  inventory/sample/patches/kube-scheduler+merge.yaml
  roles/kubernetes/control-plane/defaults/main/main.yml
  roles/kubernetes/control-plane/tasks/kubeadm-setup.yml
  roles/kubernetes/control-plane/templates/kubeadm-config.v1beta3.yaml.j2
  roles/kubernetes/control-plane/templates/kubeadm-controlplane.v1beta3.yaml.j2
  roles/kubernetes/kubeadm/defaults/main.yml
  roles/kubernetes/kubeadm/tasks/main.yml
  roles/kubernetes/kubeadm/templates/kubeadm-client.conf.v1beta3.j2
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/feature

#9360 Use hostname override in post-remove role, just as pre-remove role does
  roles/remove-node/post-remove/tasks/main.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9361 Add check_typo job
  .gitlab-ci/lint.yml
  docs/ansible.md
  docs/centos.md
  docs/vars.md
  roles/container-engine/containerd-common/defaults/main.yml
  roles/container-engine/kata-containers/templates/configuration-qemu.toml.j2
  roles/kubernetes/preinstall/templates/chrony.conf.j2
  roles/kubernetes/preinstall/templates/ntp.conf.j2
  tests/scripts/check_typo.sh
Labels: cncf-cla: yes, size/M, lgtm, approved, kind/cleanup

#9362 fix(cinder-csi-nodeplugin): Remove the pods-cloud-data volume
  roles/kubernetes-apps/csi_driver/cinder/templates/cinder-csi-nodeplugin.yml.j2
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/applications

#9316 Download coredns image to all hosts in k8s_cluster
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#9369 Update api version, deprecated in 1.25
  roles/kubernetes-apps/csi_driver/cinder/templates/cinder-csi-poddisruptionbudget.yml.j2
  roles/network_plugin/calico/templates/calico-typha.yml.j2
  roles/network_plugin/cilium/templates/hubble/cronjob.yml.j2
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#9358 Fix: install calico-kube-controller on kdd
  roles/kubernetes-apps/policy_controller/meta/main.yml
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, ok-to-test, approved

#9378 Change dns upstream condition for nodelocaldns
  roles/kubernetes-apps/ansible/tasks/nodelocaldns.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#9384 Add note for containerd oom_score
  roles/container-engine/containerd/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/cleanup

#9376 Added download configuration for cilium hubble images
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/M, lgtm, approved, kind/feature

#9387 Fix YAML format in hardening.md
  docs/hardening.md
Labels: cncf-cla: yes, size/S, lgtm, approved, kind/documentation, kind/cleanup

#9343 fix helm install with password authentication
  roles/kubernetes-apps/helm/tasks/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#9388 Update calico.md to metion the ChecksumOffloadBroken=true
  docs/calico.md
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9248 Avoid MetalLB speaker image download when MetalLB speaker is disabled
  inventory/sample/group_vars/k8s_cluster/addons.yml
  roles/download/defaults/main.yml
  roles/kubernetes-apps/metallb/defaults/main.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9370 Fix ensure ping package error in fedora CoreOS & Flatcar
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved

#9365 Remove PodSecurityPolicy in flannel (required for the kubernetes 1.25)
  roles/network_plugin/flannel/templates/cni-flannel-rbac.yml.j2
  roles/network_plugin/flannel/templates/cni-flannel.yml.j2
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/network

#9372 don't define kubeadm_patches by default
  roles/kubernetes/control-plane/defaults/main/main.yml
  roles/kubernetes/kubeadm/defaults/main.yml
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, approved

#9390 Use agnhost instead of busybox for network test
  tests/testcases/030_check-network.yml
Labels: cncf-cla: yes, size/M, lgtm, approved, kind/cleanup

#9395 Remove PodSecurityPolicies in Calico for kubernetes 1.25
  roles/network_plugin/calico/templates/calico-apiserver.yml.j2
Labels: cncf-cla: yes, size/M, lgtm, approved

#9397 [kubernetes] Add hashes for 1.25.3, 1.24.7, 1.23.13 and make v1.24.7 default
  README.md
  inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
  roles/download/defaults/main.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: cncf-cla: yes, size/M, lgtm, approved, kind/feature

#9398 Update securityContext of netchecker
  roles/kubernetes-apps/ansible/templates/netchecker-server-deployment.yml.j2
Labels: cncf-cla: yes, size/S, lgtm, approved, kind/cleanup

#9401 fix(defaults): wrong cri_socket path for containerd
  roles/kubespray-defaults/defaults/main.yaml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9396 [Docs] support the download mirror for China
  README.md
  docs/mirror.md
Labels: cncf-cla: yes, size/M, lgtm, approved

#9403 [ingress-nginx] upgrade to 1.4.0
  README.md
  roles/download/defaults/main.yml
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/clusterrole-ingress-nginx.yml.j2
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/role-ingress-nginx.yml.j2
Labels: cncf-cla: yes, size/S, lgtm, approved

#9359 Add packet_ubuntu20-calico-aio-hardening
  .gitlab-ci/packet.yml
  tests/files/packet_ubuntu20-calico-aio-hardening.yml
  tests/scripts/testcases_run.sh
Labels: kind/bug, cncf-cla: yes, size/L, lgtm, approved, kind/flake

#9374 use cri-o from upstream instead of kubic/OBS
  roles/container-engine/cri-o/defaults/main.yml
  roles/container-engine/cri-o/meta/main.yml
  roles/container-engine/cri-o/molecule/default/files/10-mynet.conf
  roles/container-engine/cri-o/molecule/default/files/container.json
  roles/container-engine/cri-o/molecule/default/files/sandbox.json
  roles/container-engine/cri-o/molecule/default/molecule.yml
  roles/container-engine/cri-o/molecule/default/prepare.yml
  roles/container-engine/cri-o/molecule/default/tests/test_default.py
  roles/container-engine/cri-o/tasks/cleanup.yaml
  roles/container-engine/cri-o/tasks/crio_repo.yml
  roles/container-engine/cri-o/tasks/main.yaml
  roles/container-engine/cri-o/tasks/setup-amazon.yaml
  roles/container-engine/cri-o/vars/almalinux-8.yml
  roles/container-engine/cri-o/vars/amazon.yml
  roles/container-engine/cri-o/vars/centos-7.yml
  roles/container-engine/cri-o/vars/centos-8.yml
  roles/container-engine/cri-o/vars/clearlinux.yml
  roles/container-engine/cri-o/vars/debian.yml
  roles/container-engine/cri-o/vars/fedora-36.yml
  roles/container-engine/cri-o/vars/fedora.yml
  roles/container-engine/cri-o/vars/oraclelinux-8.yml
  roles/container-engine/cri-o/vars/redhat.yml
  roles/container-engine/cri-o/vars/rocky-8.yml
  roles/container-engine/cri-o/vars/ubuntu.yml
  roles/container-engine/skopeo/tasks/main.yml
  roles/download/defaults/main.yml
  roles/download/tasks/set_container_facts.yml
  roles/kubernetes/node/tasks/facts.yml
  roles/kubernetes/preinstall/tasks/0070-system-packages.yml
  roles/kubernetes/preinstall/vars/fedora.yml
Labels: cncf-cla: yes, size/XL, lgtm, approved, kind/container-managers

#9405 [Ingress_nginx] Add var for control initialDelaySeconds
  roles/kubernetes-apps/ingress_controller/ingress_nginx/defaults/main.yml
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/ds-ingress-nginx-controller.yml.j2
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#9364 [kubernetes] Make kubernetes v1.25 default
  README.md
  inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9410 Update docker version to 20.10.20
  roles/container-engine/docker/vars/debian.yml
  roles/container-engine/docker/vars/fedora.yml
  roles/container-engine/docker/vars/redhat-7.yml
  roles/container-engine/docker/vars/redhat.yml
  roles/container-engine/docker/vars/ubuntu.yml
Labels: cncf-cla: yes, size/M, lgtm, approved, kind/container-managers

#9413 Update kubelet checksum
  roles/download/defaults/main.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9416 Fix iputils install failure in Kylin OS
  roles/bootstrap-os/tasks/main.yml
  roles/kubernetes/preinstall/tasks/0040-set_facts.yml
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, approved

#9414 Minor changes on Kube VIP configuration parameters
  roles/kubernetes/node/defaults/main.yml
  roles/kubernetes/node/templates/manifests/kube-vip.manifest.j2
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/network

#9421 etcd arch can support arm64 and amd64
  docs/offline-environment.md
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9420 as argocd 2.4.15 is releasesd , update the version
  README.md
  inventory/sample/group_vars/k8s_cluster/addons.yml
  roles/kubernetes-apps/argocd/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9417 [2.19] Ensure ostree variable has been defined
  roles/container-engine/runc/tasks/main.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9419 [etcd] add 3.5.5 hashes, make it default for k8s 1.25
  README.md
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#9424 [nerdctl] upgrade to version 1.0.0
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/S, lgtm, approved, kind/feature

#9425 Update kubernetes dashboard to 2.7.0 (k8s 1.25 support)
  roles/download/defaults/main.yml
  roles/kubernetes-apps/ansible/templates/dashboard.yml.j2
Labels: cncf-cla: yes, size/S, lgtm, approved, kind/feature

#9427 [containerd] upgrade to 1.6.9
  README.md
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#9407 Fix inconsistent handling of admission plugin list
  docs/hardening.md
  roles/kubernetes/control-plane/tasks/kubeadm-setup.yml
  roles/kubernetes/control-plane/templates/admission-controls.yaml.j2
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
  tests/files/packet_ubuntu20-calico-aio-hardening.yml
Labels: kind/bug, cncf-cla: yes, size/M, lgtm, ok-to-test, approved

#9437 Update kube-vip to v0.5.5
  README.md
  roles/download/defaults/main.yml
  roles/kubernetes/node/defaults/main.yml
  roles/kubernetes/node/templates/manifests/kube-vip.manifest.j2
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9426 Upgrade ruamel.yaml.clib to work with Python 3.11
  requirements-2.11.txt
  requirements-2.12.txt
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9442 Remove PodSecurityPolicies in Metallb for kubernetes 1.25
  roles/kubernetes-apps/metallb/templates/metallb.yml.j2
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/feature

#9441 Add switch cilium_enable_bandwidth_manager
  docs/cilium.md
  roles/network_plugin/cilium/defaults/main.yml
  roles/network_plugin/cilium/templates/cilium/config.yml.j2
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/feature

#9436 When using cilium CNI, install Cilium CLI
  roles/download/defaults/main.yml
  roles/network_plugin/cilium/tasks/install.yml
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved

#9432 Add UOS linux support
  README.md
  docs/_sidebar.md
  docs/uoslinux.md
  roles/bootstrap-os/tasks/main.yml
  roles/container-engine/containerd/tasks/main.yml
  roles/container-engine/docker/tasks/main.yml
  roles/container-engine/docker/vars/uniontech.yml
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/feature

#9448 Removed PodSecurityPolicy from ingress-nginx
  roles/kubernetes-apps/ingress_controller/ingress_nginx/tasks/main.yml
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/psp-ingress-nginx.yml.j2
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/cleanup

#9438 Allow setting the DirectRouting option on flannel VXLAN
  inventory/sample/group_vars/k8s_cluster/k8s-net-flannel.yml
  roles/network_plugin/flannel/defaults/main.yml
  roles/network_plugin/flannel/templates/cni-flannel.yml.j2
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature
