Repository kubernetes-sigs/kubespray, pull requests merged in 2022-06, with the labels that each got.

#8903 Add 1.24 mappings for etcd and snapshot_controller
  roles/download/defaults/main.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#8872 Revert "Set exact user for Kubelet services"
  roles/kubernetes/node/templates/kubelet.service.j2
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/cleanup

#8884 Update RELEASE.md
  RELEASE.md
Labels: cncf-cla: yes, size/M, lgtm, approved, kind/documentation

#8904 [ingress-nginx] upgrade to 1.2.1
  README.md
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/feature, release-note-none

#8922 Update KUBESPRAY_VERSION
  .gitlab-ci.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/cleanup

#8906 Update dashboard to 2.6.0 (k8s 1.24 support)
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/feature

#8895 feat: Support reserve ephemeral-storage
  .gitignore
  inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
  roles/kubernetes/node/defaults/main.yml
  roles/kubernetes/node/templates/kubelet-config.v1beta1.yaml.j2
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/feature

#8909 [feat] Upgrade metrics server to v0.6.1
  roles/download/defaults/main.yml
  roles/kubernetes-apps/metrics_server/templates/resource-reader.yaml.j2
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#8928 Kube-router version 1.4.0 -> 1.5.0
  README.md
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/feature

#8918 Use blocks for macvlan tasks for each distribution
  roles/network_plugin/macvlan/tasks/main.yml
Labels: cncf-cla: yes, size/M, lgtm, approved, kind/cleanup

#8926 Fix: set fallback value of kubelet ip6 (#8858)
  roles/kubernetes/node/defaults/main.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#8934 update kubespray image tag in readme to v2.19.0
  README.md
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/documentation

#8933 fix wrong template rendering on cilium_ip_masq_agent_enable variable
  roles/network_plugin/cilium/templates/cilium/ds.yml.j2
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#8937 Update RELEASE.md
  RELEASE.md
Labels: cncf-cla: yes, size/S, lgtm, approved, kind/documentation

#8939 [2.19] fix wrong template rendering on cilium_ip_masq_agent_enable variable (#8933)
  roles/network_plugin/cilium/templates/cilium/ds.yml.j2
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#8921 Allow disabling calico CNI logs with calico_cni_log_file_path
  docs/calico.md
  roles/network_plugin/calico/defaults/main.yml
  roles/network_plugin/calico/templates/cni-calico.conflist.j2
  roles/network_plugin/canal/defaults/main.yml
  roles/network_plugin/canal/templates/cni-canal.conflist.j2
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/network

#8943 update etcd download url in offline.yml
  inventory/sample/group_vars/all/offline.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note

#8942 [2.19] Fix: set fallback value of kubelet ip6 (#8858) (#8926)
  roles/kubernetes/node/defaults/main.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#8925 Drop Ansible support for v2.9 and v2.10
  .gitlab-ci.yml
  README.md
  ansible.cfg
  ansible_version.yml
  docs/ansible.md
  requirements-2.10.txt
  requirements-2.9.txt
  requirements-2.9.yml
  roles/download/tasks/download_container.yml
  roles/download/tasks/download_file.yml
  tests/cloud_playbooks/roles/packet-ci/templates/inventory.j2
  tests/cloud_playbooks/wait-for-ssh.yml
  tests/requirements-2.10.txt
  tests/requirements-2.9.txt
Labels: cncf-cla: yes, size/M, lgtm, approved, kind/cleanup

#8759 Replace callback_whitelist with callbacks_enabled
  ansible.cfg
  roles/adduser/molecule/default/molecule.yml
  roles/bastion-ssh-config/molecule/default/molecule.yml
  roles/bootstrap-os/molecule/default/molecule.yml
  roles/container-engine/containerd/molecule/default/molecule.yml
  roles/container-engine/cri-dockerd/molecule/default/molecule.yml
  roles/container-engine/cri-o/molecule/default/molecule.yml
  roles/container-engine/docker/molecule/default/molecule.yml
  roles/container-engine/gvisor/molecule/default/molecule.yml
  roles/container-engine/kata-containers/molecule/default/molecule.yml
  roles/container-engine/youki/molecule/default/molecule.yml
  tests/ansible.cfg
Labels: cncf-cla: yes, size/S, lgtm, approved, kind/cleanup

#8944 [vsphere-csi] fix support for vsphere 6.7U3
  inventory/sample/group_vars/all/vsphere.yml
  roles/kubernetes-apps/csi_driver/vsphere/templates/vsphere-csi-controller-config.yml.j2
  roles/kubernetes-apps/csi_driver/vsphere/templates/vsphere-csi-controller-deployment.yml.j2
  roles/kubernetes-apps/csi_driver/vsphere/templates/vsphere-csi-controller-rbac.yml.j2
  roles/kubernetes-apps/csi_driver/vsphere/templates/vsphere-csi-node.yml.j2
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, ok-to-test, approved

#8951 Fix CI broken by drop spport for ansible 2.9 and 2.10
  .gitlab-ci/packet.yml
  tests/files/packet_ubuntu20-calico-aio-ansible-2_10.yml
  tests/files/packet_ubuntu20-calico-aio-ansible-2_9.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved

#8949 fix a typo in the "matallb_auto_assign" variable name
  inventory/sample/group_vars/k8s_cluster/addons.yml
  roles/kubernetes-apps/metallb/defaults/main.yml
  roles/kubernetes-apps/metallb/tasks/main.yml
  roles/kubernetes-apps/metallb/templates/metallb-config.yml.j2
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/cleanup

#8972 [2.19] use latest calicoctl repo first
  roles/download/defaults/main.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved

#8966 Several fixes for docker reset tasks
  roles/container-engine/docker/tasks/reset.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#8970 Remove unneeded socat wrapper installation for Flatcar
  roles/download/defaults/main.yml
  roles/kubernetes/node/tasks/install.yml
Labels: kind/bug, cncf-cla: yes, size/M, lgtm, ok-to-test, approved

#8959 Add arm64 Flatcar OS's pypy bootstrapping support
  roles/bootstrap-os/files/bootstrap.sh
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/feature

#8957 Fix regex for replacing http_proxy host in RedHat Subscription Manager
  roles/bootstrap-os/tasks/bootstrap-redhat.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#8855 Expose calico-typha metrics port when metrics are enabled
  roles/network_plugin/calico/templates/calico-typha.yml.j2
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/network

#8976 [cert-manager] Upgrade to v1.8.1
  README.md
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/feature

#8975 Update Dockerfile base image
  Dockerfile
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#8958 Add CI for Ubuntu 22.04
  .gitlab-ci/packet.yml
  docs/ci.md
  test-infra/image-builder/roles/kubevirt-images/defaults/main.yml
  tests/cloud_playbooks/roles/packet-ci/defaults/main.yml
  tests/files/packet_ubuntu22-aio-docker.yml
  tests/files/packet_ubuntu22-calico-aio.yml
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/feature

#8978 Remove forgotten 1.21 references
  README.md
  roles/container-engine/cri-o/defaults/main.yml
  roles/container-engine/cri-o/vars/amazon.yml
  roles/container-engine/cri-o/vars/centos-7.yml
  roles/container-engine/cri-o/vars/centos-8.yml
  roles/container-engine/cri-o/vars/debian.yml
  roles/container-engine/cri-o/vars/fedora.yml
  roles/container-engine/cri-o/vars/ubuntu.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved, kind/flake

#8988 Fix broken link in readme
  README.md
Labels: cncf-cla: yes, size/XS, ok-to-test, approved

#8987 Suggest calico_iptables_backend: "NFT" In Centos8
  docs/centos.md
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/documentation, release-note-none

#8952 feat: make kubernetes owner parametrized
  docs/hardening.md
  inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
  roles/adduser/defaults/main.yml
  roles/adduser/tasks/main.yml
  roles/container-engine/cri-dockerd/molecule/default/prepare.yml
  roles/container-engine/kata-containers/molecule/default/prepare.yml
  roles/download/defaults/main.yml
  roles/etcd/defaults/main.yml
  roles/etcd/tasks/gen_certs_script.yml
  roles/kubernetes/control-plane/defaults/main/etcd.yml
  roles/kubernetes/control-plane/tasks/kubeadm-etcd.yml
  roles/kubernetes/preinstall/defaults/main.yml
  roles/kubernetes/preinstall/tasks/0050-create_directories.yml
  roles/kubespray-defaults/defaults/main.yaml
  roles/network_plugin/canal/tasks/main.yml
  roles/network_plugin/cni/tasks/main.yml
  roles/network_plugin/kube-router/tasks/main.yml
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/feature

#8946 Add assertion for IPv4 check in verify settings
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9002 Fix kubectl download for v1.23.8 amd64
  roles/download/defaults/main.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, sig/apps

#8956 add manage offline files script
  .gitignore
  contrib/offline/README.md
  contrib/offline/manage-offline-files.sh
  contrib/offline/nginx.conf
  inventory/sample/group_vars/all/offline.yml
Labels: cncf-cla: yes, size/L, lgtm, ok-to-test, approved, kind/feature

#8979 Fixed concatenate str & int in auto_renew_certificates_systemd_calendar var
  roles/kubernetes/control-plane/defaults/main/main.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved

#8999 [2.19] Add missing configuration for extra tolerations
  roles/kubernetes-apps/ansible/defaults/main.yml
  roles/kubernetes-apps/ansible/templates/coredns-deployment.yml.j2
  roles/kubernetes-apps/ansible/templates/dns-autoscaler.yml.j2
  roles/kubernetes-apps/policy_controller/calico/templates/calico-kube-controllers.yml.j2
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/feature

#9024 bump pause container to 3.6
  roles/container-engine/cri-dockerd/templates/cri-dockerd.service.j2
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/feature

#9022 [runc] update versions for 1.1.x and drop 1.0.x
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/S, lgtm, approved, kind/feature, tide/merge-method-rebase

#8974 Apply calico bgp peer definition task to all nodes
  roles/network_plugin/calico/tasks/install.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9029 [cert-manager] Upgrade to v1.8.2
  README.md
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#9026 let containerd_default_runtime be undefined by default
  docs/vars.md
  roles/container-engine/containerd/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/cleanup

#9031 Add support for the updated (startup|liveness|readiness)Probe.Port numbers in Cilium
  roles/network_plugin/cilium/templates/cilium/ds.yml.j2
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/feature

#9016 Fix the issue of the miss the etcd user when etcd_deployment_type: kubeadm
  roles/kubernetes/control-plane/meta/main.yml
  roles/kubernetes/control-plane/tasks/kubeadm-etcd.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9033 add ingress nginx webhook
  inventory/sample/group_vars/k8s_cluster/addons.yml
  roles/download/defaults/main.yml
  roles/kubernetes-apps/ingress_controller/ingress_nginx/defaults/main.yml
  roles/kubernetes-apps/ingress_controller/ingress_nginx/tasks/main.yml
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/admission-webhook-configuration.yml.j2
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/admission-webhook-job.yml.j2
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/clusterrole-admission-webhook.yml.j2
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/clusterrole-ingress-nginx.yml.j2
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/clusterrolebinding-admission-webhook.yml.j2
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/ds-ingress-nginx-controller.yml.j2
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/role-admission-webhook.ym.j2
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/role-admission-webhook.yml.j2
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/rolebinding-admission-webhook.yml.j2
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/sa-admission-webhook.yml.j2
  tests/files/packet_centos7-flannel-addons-ha.yml
  tests/files/packet_ubuntu18-flannel-ha.yml
Labels: cncf-cla: yes, size/L, lgtm, approved, kind/feature

#9027 Add Feature for NTP management.
  README.md
  docs/_sidebar.md
  docs/ntp.md
  inventory/sample/group_vars/all/all.yml
  roles/kubernetes/preinstall/defaults/main.yml
  roles/kubernetes/preinstall/handlers/main.yml
  roles/kubernetes/preinstall/tasks/0081-ntp-configurations.yml
  roles/kubernetes/preinstall/tasks/main.yml
  roles/kubernetes/preinstall/templates/chrony.conf.j2
  roles/kubernetes/preinstall/templates/ntp.conf.j2
  tests/files/packet_almalinux8-calico.yml
Labels: cncf-cla: yes, size/L, lgtm, ok-to-test, approved

#9042 Add component version check for README.md
  .gitlab-ci/lint.yml
  README.md
  tests/scripts/check_readme_versions.sh
Labels: cncf-cla: yes, size/M, lgtm, approved, kind/cleanup

#9032 add calico-kube-controllers missing verbs
  roles/kubernetes-apps/policy_controller/calico/templates/calico-kube-cr.yml.j2
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, ok-to-test, approved

#9043 [krew] update krew to 0.4.3
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/S, lgtm, approved

#9044 [docs] update supported components
  README.md
Labels: cncf-cla: yes, size/S, lgtm, approved
