Repository kubernetes-sigs/kubespray, pull requests merged in 2022-03, with the labels that each got.

#8592 Revert documentation regression
  docs/large-deployments.md
  inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/documentation

#8555 [containerd] Upgrade containerd to 1.6.0 and re-enable arm64 architecture with default options
  README.md
  roles/download/defaults/main.yml
  roles/reset/tasks/main.yml
Labels: cncf-cla: yes, size/S, lgtm, approved, kind/feature

#8590 terraform/gcp: Add ingress_whitelist
  contrib/terraform/gcp/README.md
  contrib/terraform/gcp/main.tf
  contrib/terraform/gcp/modules/kubernetes-cluster/main.tf
  contrib/terraform/gcp/modules/kubernetes-cluster/output.tf
  contrib/terraform/gcp/modules/kubernetes-cluster/variables.tf
  contrib/terraform/gcp/tfvars.json
  contrib/terraform/gcp/variables.tf
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/feature

#8593 MetalLB: update to v0.12.1
  inventory/sample/group_vars/k8s_cluster/addons.yml
  roles/kubernetes-apps/metallb/defaults/main.yml
  roles/kubernetes-apps/metallb/templates/metallb.yml.j2
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#8597 [containerd]: upgrade versions to fix CVE-2022-23648
  README.md
  roles/download/defaults/main.yml
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, approved

#8598 [crun] upgrade to 1.4.3
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/S, lgtm, approved, kind/feature

#8605 [2.18] Update quay.io/kubespray/vagrant for fixing molecule_tests
  .gitlab-ci/vagrant.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/failing-test

#8588 etcd: add etcd v3.5.1 for kubernetes 1.22+
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note

#8594 Fix cri-o packages install for Rocky 8
  roles/container-engine/cri-o/vars/rocky-8.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#8606 [2.18] feat(offline): Improve generate_list.sh using ansible
  contrib/offline/README.md
  contrib/offline/generate_list.sh
  contrib/offline/generate_list.yml
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/feature

#8608 Update ansible-lint to 5.4.0 (#8607)
  roles/kubernetes/kubeadm/tasks/main.yml
  roles/reset/tasks/main.yml
  roles/upgrade/pre-upgrade/tasks/main.yml
  tests/requirements-2.10.txt
  tests/requirements-2.11.txt
  tests/requirements-2.9.txt
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/feature

#8589 Clarify confirmation prompt during node upgrade
  roles/upgrade/pre-upgrade/tasks/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#8596 add IPv6 listen directive to nginx if enable_dual_stack_networks
  roles/kubernetes/node/templates/loadbalancer/nginx.conf.j2
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/cleanup

#8599 [cri-o] add cri-0 1.23.x
  roles/container-engine/cri-o/defaults/main.yml
  roles/container-engine/cri-o/vars/amazon.yml
  roles/container-engine/cri-o/vars/centos-7.yml
  roles/container-engine/cri-o/vars/centos-8.yml
  roles/container-engine/cri-o/vars/debian.yml
  roles/container-engine/cri-o/vars/ubuntu.yml
Labels: cncf-cla: yes, size/S, lgtm, approved, kind/feature

#8612 [calico] add 3.22.1
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/S, lgtm, approved, kind/feature

#8581 feat(calico): add configurable ipam strictaffinity
  roles/network_plugin/calico/defaults/main.yml
  roles/network_plugin/calico/tasks/install.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/feature

#8601 [2.18] nerdctl insecure registry config
  roles/download/defaults/main.yml
  roles/download/tasks/prep_download.yml
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/feature

#8602 [2.18] Update containerd_insecure_registries to match containerd_registries
  inventory/sample/group_vars/all/containerd.yml
  roles/container-engine/containerd/templates/config.toml.j2
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/feature

#8618 Add epoch to docker-ce and docker-ce-cli packages to ensure docker up…
  roles/container-engine/docker/tasks/main.yml
  roles/container-engine/docker/vars/redhat-7.yml
  roles/container-engine/docker/vars/redhat.yml
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/container-managers

#8556 Restart etcd if the etcd version changes
  roles/etcd/tasks/install_docker.yml
  roles/etcd/tasks/install_host.yml
  roles/etcd/tasks/main.yml
Labels: kind/bug, cncf-cla: yes, size/M, lgtm, ok-to-test, approved

#8591 fix typo and duplicated declaration of ingressclasses
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/clusterrole-ingress-nginx.yml.j2
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#8558 Add unit test for print_hostnames of inventory.py
  contrib/inventory_builder/tests/test_inventory.py
Labels: cncf-cla: yes, size/S, lgtm, approved, kind/cleanup

#8561 [systemd-resolved] Fix DNS configuration according to docs/dns-stack.…
  reset.yml
  roles/kubernetes/preinstall/templates/resolved.conf.j2
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#8347 Helm-apps role for installing helm charts
  roles/helm-apps/README.md
  roles/helm-apps/meta/argument_specs.yml
  roles/helm-apps/tasks/main.yml
  roles/helm-apps/vars/main.yml
Labels: cncf-cla: yes, size/L, lgtm, ok-to-test, approved, kind/feature, kind/design

#8624 [containerd] avoid cleanup of /usr/bin on ostree distributions
  roles/container-engine/containerd/tasks/main.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved

#8623 [docker] add support for cri-dockerd as a replacement for dockershim
  .gitignore
  docs/_sidebar.md
  docs/docker.md
  inventory/sample/group_vars/all/docker.yml
  roles/container-engine/cri-dockerd/handlers/main.yml
  roles/container-engine/cri-dockerd/meta/main.yml
  roles/container-engine/cri-dockerd/molecule/default/converge.yml
  roles/container-engine/cri-dockerd/molecule/default/files/10-mynet.conf
  roles/container-engine/cri-dockerd/molecule/default/files/container.json
  roles/container-engine/cri-dockerd/molecule/default/files/sandbox.json
  roles/container-engine/cri-dockerd/molecule/default/molecule.yml
  roles/container-engine/cri-dockerd/molecule/default/prepare.yml
  roles/container-engine/cri-dockerd/molecule/default/tests/test_default.py
  roles/container-engine/cri-dockerd/tasks/main.yml
  roles/container-engine/cri-dockerd/templates/cri-dockerd.service.j2
  roles/container-engine/cri-dockerd/templates/cri-dockerd.socket.j2
  roles/container-engine/meta/main.yml
  roles/download/defaults/main.yml
  roles/kubernetes/node/templates/kubelet.env.v1beta1.j2
  roles/kubespray-defaults/defaults/main.yaml
  roles/reset/tasks/main.yml
  tests/files/packet_almalinux8-docker.yml
  tests/files/packet_ubuntu20-aio-docker.yml
Labels: cncf-cla: yes, size/L, lgtm, approved, kind/feature

#8625 Calico: Fix Wireguard support for CentOS Stream 9/RHEL 9 Beta
  roles/network_plugin/calico/tasks/repos.yml
  roles/network_plugin/calico/vars/centos-9.yml
  roles/network_plugin/calico/vars/redhat-9.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/network

#8626 do not remove package in validate container engine role when FCOS
  roles/container-engine/validate-container-engine/tasks/main.yml
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, approved

#8434 [calico] don't enable ipip encapsulation by default and use vxlan in CI
  .gitlab-ci/packet.yml
  .gitlab-ci/vagrant.yml
  Vagrantfile
  docs/calico.md
  docs/setting-up-your-first-cluster.md
  docs/vars.md
  inventory/sample/group_vars/k8s_cluster/k8s-net-calico.yml
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
  roles/network_plugin/calico/defaults/main.yml
  roles/network_plugin/calico/tasks/check.yml
  roles/network_plugin/calico/tasks/install.yml
  roles/network_plugin/calico/templates/calico-config.yml.j2
  roles/network_plugin/calico/templates/calico-node.yml.j2
  roles/network_plugin/kube-router/templates/kube-router.yml.j2
  tests/Makefile
  tests/files/packet_debian10-calico-upgrade-once.yml
  tests/files/packet_debian10-calico-upgrade.yml
  tests/files/vagrant_centos7-kube-router.rb
  tests/files/vagrant_centos7-kube-router.yml
  tests/files/vagrant_fedora35-kube-router.rb
  tests/files/vagrant_fedora35-kube-router.yml
  tests/files/vagrant_ubuntu16-kube-router-sep.rb
  tests/files/vagrant_ubuntu16-kube-router-sep.yml
  tests/files/vagrant_ubuntu16-kube-router-svc-proxy.rb
  tests/files/vagrant_ubuntu16-kube-router-svc-proxy.yml
  tests/testcases/040_check-network-adv.yml
Labels: kind/bug, cncf-cla: yes, size/L, lgtm, approved, kind/failing-test

#8629 Updated openstack cloud controller version to v1.22.0
  roles/kubernetes-apps/external_cloud_controller/openstack/defaults/main.yml
  roles/kubernetes-apps/external_cloud_controller/openstack/templates/external-openstack-cloud-controller-manager-role-bindings.yml.j2
  roles/kubernetes-apps/external_cloud_controller/openstack/templates/external-openstack-cloud-controller-manager-roles.yml.j2
Labels: cncf-cla: yes, size/L, lgtm, ok-to-test, approved, kind/applications

#8631 [container image] use focal (ubuntu 20.04) base image for our docker builds
  Dockerfile
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/feature

#8633 [backport-2.18][container image] use focal (ubuntu 20.04) base image for our docker builds
  Dockerfile
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/feature

#8634 Fix the condition of drain on pre-remove task
  roles/container-engine/validate-container-engine/tasks/main.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved

#8638 Fixed cluster roles for openstack cloud controller
  roles/kubernetes-apps/external_cloud_controller/openstack/templates/external-openstack-cloud-controller-manager-roles.yml.j2
Labels: kind/bug, cncf-cla: yes, size/M, lgtm, ok-to-test, approved

#8635 [sysctl] set fs.may_detach_mounts=1 even when CRIs don't set it themselves
  roles/kubernetes/preinstall/tasks/0080-system-configurations.yml
Labels: cncf-cla: yes, size/S, lgtm, approved, kind/feature

#8642 [backport-2.18][sysctl] set fs.may_detach_mounts=1 even when CRIs don't set it themselves
  roles/kubernetes/preinstall/tasks/0080-system-configurations.yml
Labels: cncf-cla: yes, size/S, lgtm, approved, kind/feature

#8639 Vagrantfile: add var to set ansible verbosity level
  Vagrantfile
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#8650 fix vagrant parameter
  Vagrantfile
Labels: cncf-cla: yes, size/XS, lgtm, approved

#8648 Update cert-manager to v1.7.2
  roles/download/defaults/main.yml
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/cert-manager.crds.yml.j2
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/feature

#8651 [etcd] add 0 hash for arm v3.5.2 to prevent deployment failures
  roles/download/defaults/main.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved

#8512 [ansible] add support for ansible 5 (ansible-core 2.12)
  .gitlab-ci/packet.yml
  README.md
  ansible_version.yml
  requirements-2.12.txt
  tests/files/packet_ubuntu20-calico-aio-ansible-2_12.yml
  tests/requirements-2.12.txt
Labels: cncf-cla: yes, size/M, lgtm, approved, kind/feature

#8646 terrform/openstack: Fix templating of ansible_ssh_common_args in no_floating.yml if used as TF module
  contrib/terraform/openstack/modules/compute/ansible_bastion_template.txt
  contrib/terraform/openstack/modules/compute/main.tf
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, ok-to-test, approved

#8658 Run 0100-dhclient-hooks if dhcpclient is enabled
  roles/kubernetes/preinstall/tasks/0100-dhclient-hooks.yml
  roles/kubernetes/preinstall/tasks/0110-dhclient-hooks-undo.yml
  roles/kubernetes/preinstall/tasks/main.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved

#8660 [ansible] make ansible 5.x the new default version
  .gitlab-ci/lint.yml
  .gitlab-ci/packet.yml
  .gitlab-ci/vagrant.yml
  docs/ansible.md
  requirements.txt
  tests/files/packet_ubuntu20-calico-aio-ansible-2_12.yml
  tests/requirements.txt
Labels: cncf-cla: yes, size/S, lgtm, approved, kind/feature

#8665 Add missing 2.10 ansible test
  tests/files/packet_ubuntu20-calico-aio-ansible-2_10.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/failing-test

#8663 Update vagrant.md
  docs/vagrant.md
Labels: cncf-cla: yes, size/M, lgtm, approved, kind/documentation

#8656 fix disk controller type in Vagrantfile
  Vagrantfile
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved
