Repository kubernetes-sigs/kubespray, pull requests merged in 2022-09, with the labels that each got.

#9247 add yankay to reviewers
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/flake

#9241 Update kubespray version to v2.19.1
  .gitlab-ci.yml
  README.md
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/documentation

#9249 Add featureDetectOverride configration of calico
  roles/network_plugin/calico/defaults/main.yml
  roles/network_plugin/calico/tasks/install.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#9245 Add Support for Rewrite Plugin to CoreDNS/NodelocalDNS
  docs/dns-stack.md
  inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
  roles/kubernetes-apps/ansible/templates/coredns-config.yml.j2
  roles/kubernetes-apps/ansible/templates/nodelocaldns-config.yml.j2
Labels: cncf-cla: yes, size/S, lgtm, approved, kind/feature, needs-ok-to-test

#9212 Add Rocky Linux 9 Support
  .gitlab-ci/packet.yml
  README.md
  docs/centos.md
  docs/ci.md
  test-infra/image-builder/roles/kubevirt-images/defaults/main.yml
  tests/cloud_playbooks/roles/packet-ci/defaults/main.yml
  tests/files/packet_rockylinux9-calico.yml
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved

#9254 Fix typos in calico comments
  inventory/sample/group_vars/k8s_cluster/k8s-net-calico.yml
  roles/network_plugin/calico/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/documentation

#9253 [2.19] Update kubespray version to v2.19.1 (#9241)
  README.md
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/documentation

#9244 Ignore deleting worker nodes that are not in cluster
  roles/remove-node/post-remove/tasks/main.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9256 add retries for restart of kube-apiserver
  roles/kubernetes/preinstall/handlers/main.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9258 Remove useless file
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/role-admission-webhook.ym.j2
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved

#9259 Remove cri_dockerd_enabled configuration
  tests/files/packet_ubuntu22-aio-docker.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/cleanup

#9264 [ingress-nginx] upgrade to 1.3.1
  README.md
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#9173 [etcd] Sometimes, we do not need to run etcd role on all nodes.
  cluster.yml
  roles/etcd/defaults/main.yml
  roles/etcd/tasks/check_certs.yml
  roles/etcd/tasks/gen_certs_script.yml
  roles/etcd/tasks/gen_nodes_certs_script.yml
  roles/etcd/tasks/main.yml
  scale.yml
  upgrade-cluster.yml
Labels: cncf-cla: yes, size/L, lgtm, approved, kind/feature

#9266 fix number node name can't be added
  roles/kubernetes/kubeadm/templates/kubeadm-client.conf.v1beta3.j2
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9211 add optional parameter extra_groups for k8s_nodes in openstack terraform
  contrib/terraform/openstack/README.md
  contrib/terraform/openstack/modules/compute/main.tf
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#9255 Remove mutual exclusivity in calico: NAT and router mode
  docs/calico.md
  roles/network_plugin/calico/tasks/install.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/network

#9271 Upgrade ingress nginx webhook to 1.3.0
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9269 Add LimitMEMLOCK parameter configuration in containerd.service
  roles/container-engine/containerd/defaults/main.yml
  roles/container-engine/containerd/templates/containerd.service.j2
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/feature

#9274 Update offline.yml
  inventory/sample/group_vars/all/offline.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9263 Add timezone support
  docs/ntp.md
  roles/kubernetes/preinstall/defaults/main.yml
  roles/kubernetes/preinstall/tasks/0081-ntp-configurations.yml
  tests/files/packet_almalinux8-calico.yml
Labels: cncf-cla: yes, size/S, lgtm, approved

#9276 Fix typos in docs
  docs/metallb.md
  docs/ntp.md
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/documentation

#9278 Add variable for the vsphere-csi namespace
  docs/vsphere-csi.md
  roles/kubernetes-apps/csi_driver/vsphere/defaults/main.yml
  roles/kubernetes-apps/csi_driver/vsphere/tasks/main.yml
  roles/kubernetes-apps/csi_driver/vsphere/templates/vsphere-csi-controller-config.yml.j2
  roles/kubernetes-apps/csi_driver/vsphere/templates/vsphere-csi-controller-deployment.yml.j2
  roles/kubernetes-apps/csi_driver/vsphere/templates/vsphere-csi-controller-rbac.yml.j2
  roles/kubernetes-apps/csi_driver/vsphere/templates/vsphere-csi-controller-service.yml.j2
  roles/kubernetes-apps/csi_driver/vsphere/templates/vsphere-csi-namespace.yml.j2
  roles/kubernetes-apps/csi_driver/vsphere/templates/vsphere-csi-node-rbac.yml.j2
  roles/kubernetes-apps/csi_driver/vsphere/templates/vsphere-csi-node.yml.j2
Labels: kind/bug, cncf-cla: yes, size/M, lgtm, ok-to-test, approved

#9286 [kubernetes] Add hashes for 1.24.5, 1.22.14, 1.23.11 and make v1.24.5 default
  README.md
  inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
  roles/download/defaults/main.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: cncf-cla: yes, size/M, lgtm, approved, kind/feature

#9225 Cilium 1.12 Upgrade
  README.md
  docs/cilium.md
  inventory/sample/group_vars/k8s_cluster/k8s-net-cilium.yml
  roles/download/defaults/main.yml
  roles/network_plugin/cilium/defaults/main.yml
  roles/network_plugin/cilium/tasks/check.yml
  roles/network_plugin/cilium/templates/cilium-operator/cr.yml.j2
  roles/network_plugin/cilium/templates/cilium-operator/deploy.yml.j2
  roles/network_plugin/cilium/templates/cilium/config.yml.j2
  roles/network_plugin/cilium/templates/cilium/cr.yml.j2
  roles/network_plugin/cilium/templates/cilium/crb.yml.j2
  roles/network_plugin/cilium/templates/cilium/ds.yml.j2
Labels: cncf-cla: yes, size/XL, lgtm, approved, kind/network

#9288 Adds support for multiple architectures to yq
  roles/kubernetes-apps/argocd/tasks/main.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved, needs-ok-to-test

#9285 fix duplicate field in ingress-nginx template
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/ds-ingress-nginx-controller.yml.j2
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/cleanup

#9297 [argocd] update argocd to v2.4.12
  README.md
  inventory/sample/group_vars/k8s_cluster/addons.yml
  roles/kubernetes-apps/argocd/defaults/main.yml
  roles/kubernetes-apps/argocd/tasks/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#9295 [cert-manager] Upgrade to v1.9.1
  README.md
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#9293 vSphere-csi: add nodeAffinity to daemonset
  roles/kubernetes-apps/csi_driver/vsphere/defaults/main.yml
  roles/kubernetes-apps/csi_driver/vsphere/templates/vsphere-csi-node.yml.j2
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#9287 Calico: add wireguard support for Rocky Linux 9
  roles/network_plugin/calico/vars/rocky-9.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9298 [helm] upgrade to 3.9.4
  README.md
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved

#9301 Remove duplication in containerd template
  roles/container-engine/containerd/templates/config.toml.j2
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/cleanup

#9296 [flannel] update to v1.19.2 & make it default
  README.md
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/feature

#9284 Ensure the ping package
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, ok-to-test, approved

#9307 add max_concurrent in coredns to fix memory leak issue
  roles/kubernetes-apps/ansible/templates/coredns-config.yml.j2
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved

#9314 Changed createhome to create_home
  roles/adduser/defaults/main.yml
  roles/adduser/tasks/main.yml
  roles/adduser/vars/coreos.yml
  roles/adduser/vars/debian.yml
  roles/adduser/vars/redhat.yml
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, approved

#9270 feat: allows users to have more control on DNS
  docs/dns-stack.md
  docs/vars.md
  inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
  roles/kubernetes/preinstall/tasks/0040-set_facts.yml
  roles/kubernetes/preinstall/tasks/0060-resolvconf.yml
  roles/kubernetes/preinstall/tasks/0063-networkmanager-dns.yml
  roles/kubernetes/preinstall/templates/dhclient_dnsupdate.sh.j2
  roles/kubernetes/preinstall/templates/dhclient_dnsupdate_rh.sh.j2
  roles/kubernetes/preinstall/templates/resolved.conf.j2
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/feature

#9302 Allow configuring base_runtime_spec per containerd runtime and supply a default runtime spec
  docs/containerd.md
  roles/container-engine/containerd/defaults/main.yml
  roles/container-engine/containerd/files/cri-base.json
  roles/container-engine/containerd/tasks/main.yml
  roles/container-engine/containerd/templates/config.toml.j2
Labels: cncf-cla: yes, size/L, lgtm, ok-to-test, approved, kind/feature

#9304 support removing options in resolvconf with tab separator
  roles/kubernetes/preinstall/tasks/0060-resolvconf.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9312 Move back vsphere csi to kube-system ns
  docs/vsphere-csi.md
  roles/kubernetes-apps/csi_driver/vsphere/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/flake

#9313 add liupeng0518 to approvers list
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/flake

#9320 doc(openstack.md): Move Additional step to own section
  docs/openstack.md
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/documentation

#9321 Ensure ostree variable has been defined
  roles/container-engine/runc/tasks/main.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9322 Hotfix containerd restart
  roles/container-engine/containerd/handlers/reset.yml
  roles/container-engine/validate-container-engine/tasks/main.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9317 upcloud csi driver: bump version to v0.3.3
  inventory/sample/group_vars/all/upcloud.yml
  roles/kubernetes-apps/csi_driver/upcloud/defaults/main.yml
  roles/kubernetes-apps/csi_driver/upcloud/tasks/main.yml
  roles/kubernetes-apps/csi_driver/upcloud/templates/upcloud-csi-controller.yml.j2
  roles/kubernetes-apps/csi_driver/upcloud/templates/upcloud-csi-node.yml.j2
  roles/kubernetes-apps/csi_driver/upcloud/templates/upcloud-csi-setup.yml.j2
  roles/kubernetes-apps/persistent_volumes/upcloud-csi/defaults/main.yml
  roles/kubernetes-apps/persistent_volumes/upcloud-csi/templates/upcloud-csi-storage-class.yml.j2
Labels: cncf-cla: yes, size/L, lgtm, ok-to-test, approved, kind/feature

#9282 preinstall: Add nodelocaldns to supersede_nameserver if enabled
  roles/kubernetes/preinstall/tasks/0040-set_facts.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9327 Fix typos in calico
  docs/calico.md
  roles/network_plugin/calico/rr/tasks/update-node.yml
  roles/network_plugin/calico/tasks/peer_with_calico_rr.yml
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, ok-to-test, approved

#9333 Update kubespray version following release
  .gitlab-ci.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/flake

#9332 cloud-provider-openstack: upgrade 1.22.0 to 1.23.4
  roles/kubernetes-apps/external_cloud_controller/openstack/defaults/main.yml
  roles/kubernetes-apps/external_cloud_controller/openstack/templates/external-openstack-cloud-config.j2
  roles/kubespray-defaults/defaults/main.yaml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/applications

#9323 [2.18] preinstall: Add nodelocaldns to supersede_nameserver if enabled
  roles/kubernetes/preinstall/tasks/0040-set_facts.yml
Labels: cncf-cla: yes, size/XS, needs-ok-to-test

#9324 [2.19] preinstall: Add nodelocaldns to supersede_nameserver if enabled
  roles/kubernetes/preinstall/tasks/0040-set_facts.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9337 update pause image version
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#9340 Fix: The Hubble certificate is faulty because the cluster name is har…
  roles/network_plugin/cilium/templates/hubble/cronjob.yml.j2
  roles/network_plugin/cilium/templates/hubble/job.yml.j2
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9334 update README to reference docker v2.20.0 tag
  README.md
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/documentation, release-note-none

#9339 fix: remove trailing backslash and yaml indent
  roles/network_plugin/cilium/templates/cilium/config.yml.j2
  roles/network_plugin/cilium/templates/cilium/ds.yml.j2
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, ok-to-test, approved

#9336 [Openstack] Add bastion_allowed_ports to allow custom security group rules on bastion node
  contrib/terraform/openstack/README.md
  contrib/terraform/openstack/kubespray.tf
  contrib/terraform/openstack/modules/compute/main.tf
  contrib/terraform/openstack/modules/compute/variables.tf
  contrib/terraform/openstack/variables.tf
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/applications

#9335 [Openstack] Fix missing permissions for Openstack cloud-controller-manager
  roles/kubernetes-apps/external_cloud_controller/openstack/templates/external-openstack-cloud-controller-manager-roles.yml.j2
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, ok-to-test, approved

#9342 Remove references to 1.22
  README.md
  roles/download/defaults/main.yml
  roles/kubernetes/control-plane/templates/kubescheduler-config.yaml.j2
  roles/kubespray-defaults/defaults/main.yaml
Labels: cncf-cla: yes, size/L, lgtm, approved, kind/flake

#9348 [v2.20] update README to reference docker v2.20.0 tag (#9334)
  README.md
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/documentation

#9260 [kubernetes] Add hashes for 1.25.0,1.25.1,1.25.2
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/M, lgtm, approved

#9345 [Openstack] Fix a race condition in terraform causing ports to not get an IP
  contrib/terraform/openstack/kubespray.tf
  contrib/terraform/openstack/modules/compute/main.tf
  contrib/terraform/openstack/modules/compute/variables.tf
Labels: kind/bug, cncf-cla: yes, size/M, lgtm, ok-to-test, approved

#9353 Remove versions from setting-up-your-first-cluster
  docs/setting-up-your-first-cluster.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/documentation, kind/cleanup
