Repository kubernetes-sigs/kubespray, pull requests merged in 2022-12, with the labels that each got.

#9510 [upcloud] Fixed issue where DNS would be blocked while using allowlist
  contrib/terraform/upcloud/modules/kubernetes-cluster/main.tf
Labels: kind/bug, cncf-cla: yes, size/M, lgtm, ok-to-test, approved

#9533 Add ingress-nginx check for updating README
  roles/download/defaults/main.yml
  tests/scripts/check_readme_versions.sh
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/cleanup

#9530 update dashboard image repo to remove arch flag
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#9529 Update calico image tag
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/S, lgtm, approved, kind/network

#9520 [etcd] make etcd 3.5.6 default
  README.md
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/feature, release-note-none

#9532 [ingress-nginx] upgrade to 1.5.1
  README.md
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/feature

#9506 Update load balancers Versions
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#9534 Corrected vsphere directory
  docs/vsphere.md
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9502 Add Check resolv.conf is empty to avoid CoreDNS crash
  roles/kubernetes/preinstall/tasks/0040-set_facts.yml
Labels: cncf-cla: yes, size/S, lgtm, approved

#9540 Update etcd log-level parameter name
  roles/etcd/templates/etcd.env.j2
  roles/kubernetes/control-plane/templates/kubeadm-config.v1beta3.yaml.j2
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/feature

#9537 reset: RedHat based distro with major version >=8
  roles/reset/tasks/main.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved

#9539 [metrics_server]: Enabled HA mode by adding 'metrics_server_replicas'…
  inventory/sample/group_vars/k8s_cluster/addons.yml
  roles/kubernetes-apps/metrics_server/defaults/main.yml
  roles/kubernetes-apps/metrics_server/templates/metrics-server-deployment.yaml.j2
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/feature

#9536 Terraform Openstack: replace deprecated template provider with suppo…
  contrib/terraform/openstack/modules/compute/main.tf
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved

#9544 support containerd 1.6.11
  README.md
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9551 follow containerd1.16.12
  README.md
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note-none

#9491 Disable 'Check that IP range is enough for the nodes' when calico is used
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved

#9527 [kube-ovn]: update version v1.10.7
  README.md
  roles/download/defaults/main.yml
  roles/network_plugin/kube-ovn/defaults/main.yml
  roles/network_plugin/kube-ovn/templates/cni-kube-ovn-crd.yml.j2
  roles/network_plugin/kube-ovn/templates/cni-kube-ovn.yml.j2
  roles/network_plugin/kube-ovn/templates/cni-ovn.yml.j2
Labels: cncf-cla: yes, size/XL, lgtm, ok-to-test, approved, kind/network

#9543 Allow `containerd-common` to execute multiple times per play
  roles/container-engine/containerd-common/meta/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/container-managers

#9556 Fix a pre-upgrade node drain rescue task failure when `kube_override_hostname` is set
  roles/upgrade/pre-upgrade/tasks/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#9517 [containerd] Add config for unpriviledged ports and icmp
  roles/container-engine/containerd/defaults/main.yml
  roles/container-engine/containerd/templates/config.toml.j2
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/container-managers

#9554 [feat] Upgrade metrics server to v0.6.2
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#9561 Add XDG related Helm paths to be removed
  roles/reset/tasks/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#9557 Add hashes for 1.25.5, 1.24.9, 1.23.15 and make v1.25.5 default
  README.md
  inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
  roles/download/defaults/main.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/feature, release-note-none

#9573 Calico in etcd mode requires hostNetwork
  roles/kubernetes-apps/policy_controller/calico/templates/calico-kube-controllers.yml.j2
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9564 Support dual stack IPv4 & IPv6 networking for flannel
  roles/network_plugin/flannel/templates/cni-flannel.yml.j2
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/network

#9569 rename ansible groups to use _ instead of
  contrib/terraform/hetzner/templates/inventory.tpl
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9580 Upgrade Calico to v3.24.5
  README.md
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#9574 upcloud: Delete default reclaim policy
  roles/kubernetes-apps/persistent_volumes/upcloud-csi/templates/upcloud-csi-storage-class.yml.j2
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/applications

#9576 Remove include task in play, deprecated in favor of import_playbook
  recover-control-plane.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved

#9575 Use the correct api version and resourcer type. The current values wo…
  roles/kubernetes/control-plane/templates/secrets_encryption.yaml.j2
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/cleanup

#9581 Fix annotation typo
  inventory/sample/group_vars/k8s_cluster/k8s-net-kube-router.yml
  roles/network_plugin/kube-router/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9583 Feature/add flannel wireguard encryption backend as option
  docs/flannel.md
  inventory/sample/group_vars/k8s_cluster/k8s-net-flannel.yml
  roles/network_plugin/flannel/tasks/main.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/feature

#9592 Fix missing control plane taint in kubeadm
  roles/kubernetes/control-plane/templates/kubeadm-config.v1beta3.yaml.j2
  roles/kubernetes/control-plane/templates/kubeadm-controlplane.v1beta3.yaml.j2
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved

#9590 fix kube token dir permissions
  roles/kubernetes/tokens/tasks/main.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9597 Remove immutable flag from /var/lib/kubelet subdirs
  roles/reset/tasks/main.yml
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, ok-to-test, approved

#9604 [argocd] update argocd to v2.5.5
  README.md
  inventory/sample/group_vars/k8s_cluster/addons.yml
  roles/kubernetes-apps/argocd/defaults/main.yml
  roles/kubernetes-apps/argocd/tasks/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#9553 crio: test: use the new crio_registries variable in test
  tests/common/_docker_hub_registry_mirror.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9605 [helm] upgrade to 3.10.3
  README.md
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved

#9610 fix(apps): cinder: wrong rbac for csi-snapshotter-role
  roles/kubernetes-apps/csi_driver/cinder/templates/cinder-csi-controllerplugin-rbac.yml.j2
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9614 Fix checksum of ciliumcli v0.12.5 for arm64
  roles/download/defaults/main.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved

#9617 Allow custom timeout for kubeadm init
  roles/kubernetes/control-plane/tasks/kubeadm-setup.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#9563 Remove CNI BIN dependency for cilium
  roles/network_plugin/cilium/meta/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#9619 Fix some typos in docs file
  docs/ansible.md
  docs/dns-stack.md
  docs/docker.md
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/documentation

#9618 Added terraform script for Flatcar Linux on Hetzner
  contrib/terraform/hetzner/README.md
  contrib/terraform/hetzner/default.tfvars
  contrib/terraform/hetzner/main.tf
  contrib/terraform/hetzner/modules/kubernetes-cluster-flatcar/main.tf
  contrib/terraform/hetzner/modules/kubernetes-cluster-flatcar/outputs.tf
  contrib/terraform/hetzner/modules/kubernetes-cluster-flatcar/templates/machine.yaml.tmpl
  contrib/terraform/hetzner/modules/kubernetes-cluster-flatcar/variables.tf
  contrib/terraform/hetzner/modules/kubernetes-cluster-flatcar/versions.tf
  contrib/terraform/hetzner/variables.tf
Labels: cncf-cla: yes, size/L, lgtm, ok-to-test, approved, kind/feature

#9620 fix(k8s-certs-renew): Use kube_apiserver_port instead of hard-coding
  roles/kubernetes/control-plane/templates/k8s-certs-renew.sh.j2
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#9608 [feat] Add custom options to coredns kubernets plugin
  docs/dns-stack.md
  inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
  roles/kubernetes-apps/ansible/defaults/main.yml
  roles/kubernetes-apps/ansible/templates/coredns-config.yml.j2
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/feature

#9596 Cluster support for ovn-central.
  roles/network_plugin/kube-ovn/defaults/main.yml
  roles/network_plugin/kube-ovn/tasks/main.yml
  roles/network_plugin/kube-ovn/templates/cni-ovn.yml.j2
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/network

#9528 Upgrade flannel version to v0.20.1
  README.md
  roles/download/defaults/main.yml
  roles/network_plugin/flannel/templates/cni-flannel.yml.j2
Labels: cncf-cla: yes, size/S, lgtm, approved, kind/network

#9515 Drop calico v3.21 support
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/cleanup

#9594 Remove ovn.kubernetes.io/ovs_dp_type from nodeSelector
  roles/network_plugin/kube-ovn/templates/cni-ovn.yml.j2
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9209 optimize cgroups settings for node reserved
  docs/cgroups.md
  inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
  roles/container-engine/containerd/templates/containerd.service.j2
  roles/container-engine/cri-dockerd/templates/cri-dockerd.service.j2
  roles/container-engine/cri-o/templates/crio.conf.j2
  roles/container-engine/docker/templates/docker.service.j2
  roles/kubernetes/node/defaults/main.yml
  roles/kubernetes/node/templates/kubelet-config.v1beta1.yaml.j2
  roles/kubernetes/node/templates/kubelet.service.j2
Labels: cncf-cla: yes, size/L, lgtm, ok-to-test, approved
