Repository kubernetes-sigs/kubespray, pull requests merged in 2023-06, with the labels that each got.

#10149 [#10148] The download.timeout can be changed.
  roles/download/tasks/download_file.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#10162 Solves #2933: Allow http_proxy, https_proxy and no_proxy environment variables in cert-manager playbook
  roles/kubernetes-apps/ingress_controller/cert_manager/defaults/main.yml
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/cert-manager.yml.j2
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/feature

#10174 fix missing newline in template which breaks nginx-ingress deployment
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/ingressclass-nginx.yml.j2
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#10139 Add labels to kube-vip static pods
  roles/kubernetes/node/templates/manifests/kube-vip.manifest.j2
Labels: cncf-cla: yes, size/XS, lgtm, approved

#10164 [2.22] MetalLB backport
  docs/metallb.md
  roles/kubernetes-apps/metallb/defaults/main.yml
  roles/kubernetes-apps/metallb/tasks/main.yml
  roles/kubernetes-apps/metallb/templates/metallb.yaml.j2
  tests/files/packet_centos7-flannel-addons-ha.yml
Labels: kind/bug, cncf-cla: yes, size/L, lgtm, ok-to-test, approved

#10170 Add node_taints to aws_inventory script (#10168)
  contrib/aws_inventory/kubespray-aws-inventory.py
  docs/aws.md
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/feature

#10180 update README for v2.22.0
  README.md
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/documentation

#10181 [2.22] Fix dockerfile build error by add some package (#10127)
  Dockerfile
  test-infra/vagrant-docker/Dockerfile
Labels: cncf-cla: yes, size/XS, lgtm, approved

#10175 [krew] add krew_no_upgrade_check
  roles/kubernetes-apps/krew/defaults/main.yml
  roles/kubernetes-apps/krew/templates/krew.j2
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/feature

#10183 Fix metrics-server for k8s 1.26
  roles/kubernetes-apps/metrics_server/templates/metrics-server-deployment.yaml.j2
Labels: cncf-cla: yes, size/XS, lgtm, approved

#10034 Upgrade tests dependencies
  .gitlab-ci.yml
  .gitlab-ci/packet.yml
  Dockerfile
  contrib/inventory_builder/tox.ini
  pipeline.Dockerfile
  playbooks/ansible_version.yml
  requirements-2.11.txt
  requirements-2.12.txt
  requirements.txt
  roles/adduser/molecule/default/molecule.yml
  roles/adduser/molecule/default/tests/test_default.py
  roles/bastion-ssh-config/molecule/default/molecule.yml
  roles/bastion-ssh-config/molecule/default/tests/test_default.py
  roles/bootstrap-os/molecule/default/molecule.yml
  roles/container-engine/containerd/molecule/default/molecule.yml
  roles/container-engine/cri-dockerd/molecule/default/molecule.yml
  roles/container-engine/cri-o/molecule/default/molecule.yml
  roles/container-engine/gvisor/molecule/default/molecule.yml
  roles/container-engine/kata-containers/molecule/default/molecule.yml
  roles/container-engine/youki/molecule/default/molecule.yml
  tests/requirements-2.11.txt
  tests/requirements-2.12.txt
  tests/requirements.txt
  tests/scripts/testcases_prepare.sh
Labels: cncf-cla: yes, size/L, lgtm, approved, kind/feature

#10182 remove cri-o using crio_bin_files
  roles/container-engine/cri-o/tasks/reset.yml
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, ok-to-test, approved

#10187 [2.22] Fix metrics-server for k8s 1.26 (#10183)
  roles/kubernetes-apps/metrics_server/templates/metrics-server-deployment.yaml.j2
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved

#10186 [2.22] Fix Dockerfile for newest directory layout (#10128)
  Dockerfile
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved

#10188 Remove unused flannel_cni_download_url
  inventory/sample/group_vars/all/offline.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/cleanup

#10131 Don't let find search filesystem mounts in docker build run step
  Dockerfile
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#10165 Kubelet csr approver fixes
  playbooks/upgrade_cluster.yml
  roles/kubernetes-apps/helm/tasks/main.yml
  roles/kubernetes-apps/helm/vars/amazon.yml
  roles/kubernetes-apps/helm/vars/centos-9.yml
  roles/kubernetes-apps/helm/vars/centos.yml
  roles/kubernetes-apps/helm/vars/debian.yml
  roles/kubernetes-apps/helm/vars/fedora.yml
  roles/kubernetes-apps/helm/vars/redhat-9.yml
  roles/kubernetes-apps/helm/vars/redhat.yml
  roles/kubernetes-apps/helm/vars/suse.yml
  roles/kubernetes-apps/helm/vars/ubuntu.yml
Labels: kind/bug, cncf-cla: yes, size/M, lgtm, ok-to-test, approved

#10166 Permit custom names for API server lb/proxy containers.
  docs/ha-mode.md
  roles/kubernetes/node/defaults/main.yml
  roles/kubernetes/node/templates/manifests/haproxy.manifest.j2
  roles/kubernetes/node/templates/manifests/nginx-proxy.manifest.j2
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/feature

#10200 bump nodelocaldns version to 1.22.20
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#10167 Enable interruptible jobs' pipelines
  .gitlab-ci.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#10201 Update KUBESPRAY_VERSION in CI and Readme for v2.22.1
  .gitlab-ci.yml
  README.md
  docs/ansible_collection.md
  galaxy.yml
Labels: cncf-cla: yes, size/S, lgtm, approved, kind/flake

#10208 fix gce-pd-csi driver
  README.md
  roles/download/defaults/main.yml
  roles/kubernetes-apps/csi_driver/gcp_pd/tasks/main.yml
  roles/kubernetes-apps/csi_driver/gcp_pd/templates/gcp-pd-csi-controller.yml.j2
  roles/kubernetes-apps/csi_driver/gcp_pd/templates/gcp-pd-csi-node.yml.j2
  roles/kubernetes-apps/csi_driver/gcp_pd/templates/gcp-pd-csi-sc-regional.yml.j2
  roles/kubernetes-apps/csi_driver/gcp_pd/templates/gcp-pd-csi-sc-zonal.yml.j2
  roles/kubernetes-apps/csi_driver/gcp_pd/templates/gcp-pd-csi-setup.yml.j2
Labels: cncf-cla: yes, size/L, lgtm, ok-to-test, approved

#10211 Use a uniform way to get the local path of the binaries
  roles/container-engine/kata-containers/tasks/main.yml
  roles/download/tasks/prep_kubeadm_images.yml
  roles/kubernetes/control-plane/tasks/main.yml
  roles/kubernetes/node/tasks/install.yml
  roles/network_plugin/cni/tasks/main.yml
Labels: cncf-cla: yes, size/S, lgtm, approved, kind/feature

#10204 helm: fix pyyaml package on RH distros
  roles/kubernetes-apps/helm/vars/centos-7.yml
  roles/kubernetes-apps/helm/vars/centos-9.yml
  roles/kubernetes-apps/helm/vars/centos.yml
  roles/kubernetes-apps/helm/vars/redhat-7.yml
  roles/kubernetes-apps/helm/vars/redhat-9.yml
  roles/kubernetes-apps/helm/vars/redhat.yml
  roles/kubernetes-apps/helm/vars/suse.yml
Labels: cncf-cla: yes, size/S, lgtm, approved

#10192 [flatcar] add python dependency check for helm-apps
  roles/kubernetes-apps/helm/tasks/main.yml
  roles/kubernetes-apps/helm/tasks/pyyaml-flatcar.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/feature

#10210 [podSecurityConfiguration]: fix apiVersion and change default policy …
  roles/kubernetes/control-plane/defaults/main/main.yml
  roles/kubernetes/control-plane/templates/podsecurity.yaml.j2
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/api-change

#10216 exclude terraform.tfstate backups in .gitignore
  .gitignore
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/cleanup

#10219 [containerd]: bump to 1.7.2
  README.md
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/container-managers

#10222 Add CI VM for debian12
  test-infra/image-builder/roles/kubevirt-images/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/flake

#10224 [calico] add hashes for v3.26.0
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#10223 [ingress-nginx] upgrade to 1.8.0
  README.md
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#10230 Fix etcdctl copy operation
  roles/etcdctl/tasks/main.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved

#10225 [helm] upgrade to 3.12.1
  README.md
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/S, lgtm, approved

#10176 [argocd] allow change argocd url
  roles/kubernetes-apps/argocd/defaults/main.yml
  roles/kubernetes-apps/argocd/tasks/main.yml
  roles/kubernetes-apps/argocd/templates/argocd-namespace.yml.j2
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/feature

#10227 Added terraform support for NIFCLOUD
  .gitlab-ci/terraform.yml
  contrib/terraform/nifcloud/.gitignore
  contrib/terraform/nifcloud/README.md
  contrib/terraform/nifcloud/generate-inventory.sh
  contrib/terraform/nifcloud/main.tf
  contrib/terraform/nifcloud/modules/kubernetes-cluster/main.tf
  contrib/terraform/nifcloud/modules/kubernetes-cluster/outputs.tf
  contrib/terraform/nifcloud/modules/kubernetes-cluster/templates/userdata.tftpl
  contrib/terraform/nifcloud/modules/kubernetes-cluster/terraform.tf
  contrib/terraform/nifcloud/modules/kubernetes-cluster/variables.tf
  contrib/terraform/nifcloud/output.tf
  contrib/terraform/nifcloud/sample-inventory/cluster.tfvars
  contrib/terraform/nifcloud/sample-inventory/group_vars
  contrib/terraform/nifcloud/terraform.tf
  contrib/terraform/nifcloud/variables.tf
Labels: cncf-cla: yes, size/XL, lgtm, ok-to-test, approved, kind/feature

#10221 Add Debian 12(bookworm) support and CI
  .gitlab-ci/packet.yml
  README.md
  docs/ci.md
  roles/container-engine/docker/vars/debian-bookworm.yml
  roles/kubernetes/preinstall/vars/debian-12.yml
  tests/cloud_playbooks/roles/packet-ci/defaults/main.yml
  tests/files/packet_debian12-calico.yml
  tests/files/packet_debian12-docker.yml
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/feature

#10228 fix parsing of RHSM proxy configuration (#10060)
  roles/bootstrap-os/tasks/bootstrap-redhat.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#10124 [2.21] Adding the missing rsync utility
  Dockerfile
Labels: cncf-cla: yes, size/XS, ok-to-test, approved

#10120 Update download_hash.sh script
  scripts/download_hash.sh
Labels: cncf-cla: yes, size/S, lgtm, approved, kind/feature

#10199 bump coredns version to 1.10.1
  README.md
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#10226 [argocd] update argocd to v2.7.4
  README.md
  inventory/sample/group_vars/k8s_cluster/addons.yml
  roles/download/defaults/main.yml
  roles/kubernetes-apps/argocd/defaults/main.yml
Labels: cncf-cla: yes, size/S, lgtm, approved

#10233 [feature] Correct CoreDNS versions for kubernetes releases
  roles/download/defaults/main.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved, kind/feature

#10232 Update Calico to lowercase and fix broken calico link in README
  README.md
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#10235 [calico] add hashes for v3.26.1
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#10054 update local path provisioner version and remove psp
  README.md
  inventory/sample/group_vars/k8s_cluster/addons.yml
  roles/download/defaults/main.yml
  roles/kubernetes-apps/external_provisioner/local_path_provisioner/tasks/main.yml
  roles/kubernetes-apps/external_provisioner/local_path_provisioner/templates/local-path-storage-cm.yml.j2
  roles/kubernetes-apps/external_provisioner/local_path_provisioner/templates/local-path-storage-cr.yml.j2
  roles/kubernetes-apps/external_provisioner/local_path_provisioner/templates/local-path-storage-psp-cr.yml.j2
  roles/kubernetes-apps/external_provisioner/local_path_provisioner/templates/local-path-storage-psp-rb.yml.j2
  roles/kubernetes-apps/external_provisioner/local_path_provisioner/templates/local-path-storage-psp.yml.j2
  tests/files/packet_almalinux8-calico.yml
Labels: cncf-cla: yes, size/L, lgtm, approved

#10205 bump flannel version to v0.22.0 and flannel-cni-plugin version to v1.1.2
  README.md
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#10237 local_path_provisioner: fix invalid podhelper yaml
  roles/kubernetes-apps/external_provisioner/local_path_provisioner/defaults/main.yml
  roles/kubernetes-apps/external_provisioner/local_path_provisioner/templates/local-path-storage-cm.yml.j2
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved

#10236 clean up outdate os files
  roles/container-engine/docker/vars/debian-stretch.yml
  roles/container-engine/docker/vars/ubuntu-16.yml
  test-infra/image-builder/roles/kubevirt-images/defaults/main.yml
  tests/cloud_playbooks/roles/packet-ci/defaults/main.yml
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/cleanup

#10241 add growpart azure enabled
  roles/kubernetes/preinstall/defaults/main.yml
  roles/kubernetes/preinstall/tasks/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#10121 Split defaults main file
  contrib/offline/README.md
  contrib/offline/generate_list.sh
  docs/offline-environment.md
  roles/download/defaults/main/checksums.yml
  roles/download/defaults/main/main.yml
  scripts/download_hash.py
  tests/scripts/check_readme_versions.sh
Labels: cncf-cla: yes, size/XXL, lgtm, approved, kind/feature

#10239 Updates the broken links in ingress-controller and kubernetes-apps un…
  docs/ingress_controller/alb_ingress_controller.md
  docs/ingress_controller/ingress_nginx.md
  docs/kubernetes-apps/rbd_provisioner.md
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/documentation

#10169 Add flag to prevent running helm update
  roles/helm-apps/tasks/main.yml
  roles/helm-apps/vars/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#10215 Add option to set SSL_CERT_FILE for offline installation using custom CA for https proxy
  docs/proxy.md
  inventory/sample/group_vars/all/all.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/feature

#10081 Disable fapolicyd service
  roles/kubernetes/preinstall/defaults/main.yml
  roles/kubernetes/preinstall/tasks/0080-system-configurations.yml
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, ok-to-test, approved

#10245 tests: cleanup stale packet namespace automatically
  .gitlab-ci/packet.yml
  tests/Makefile
  tests/cloud_playbooks/cleanup-packet.yml
  tests/cloud_playbooks/roles/cleanup-packet-ci/tasks/main.yml
  tests/cloud_playbooks/roles/packet-ci/tasks/cleanup-old-vms.yml
  tests/cloud_playbooks/roles/packet-ci/tasks/create-vms.yml
  tests/cloud_playbooks/roles/packet-ci/tasks/main.yml
Labels: kind/bug, cncf-cla: yes, size/M, lgtm, approved

#10252 Stop firewalld for rockylinux8 on Vagrant
  Vagrantfile
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#10242 fix etcdctl copy operation in crio
  roles/etcdctl/tasks/main.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved

#10184 Add system-upgrade to upgrade-cluster playbook
  docs/upgrades.md
  playbooks/upgrade_cluster.yml
  roles/kubespray-defaults/defaults/main.yaml
  roles/upgrade/system-upgrade/tasks/apt.yml
  roles/upgrade/system-upgrade/tasks/main.yml
  roles/upgrade/system-upgrade/tasks/yum.yml
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/feature

#10260 metallb: increase wait timeout from 30s to 2m
  roles/kubernetes-apps/metallb/tasks/main.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/failing-test

#10259 Upgrade ansible in Dockerfile
  Dockerfile
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#10261 Update doc after ansible-core upgrade to 2.14
  docs/ansible.md
Labels: cncf-cla: yes, size/S, lgtm, approved, kind/documentation

#10177 using configmap to configure calico cni config
  roles/network_plugin/calico/tasks/install.yml
  roles/network_plugin/calico/templates/calico-config.yml.j2
  roles/network_plugin/calico/templates/calico-node.yml.j2
  roles/network_plugin/calico/templates/cni-calico.conflist.j2
Labels: cncf-cla: yes, size/L, lgtm, approved, kind/network

#10254 Fix outdated tag and experimental ansible-lint rules
  .ansible-lint
  contrib/azurerm/roles/generate-inventory/tasks/main.yml
  contrib/azurerm/roles/generate-inventory_2/tasks/main.yml
  contrib/dind/roles/dind-host/tasks/main.yaml
  contrib/network-storage/glusterfs/roles/glusterfs/client/tasks/setup-Debian.yml
  contrib/network-storage/glusterfs/roles/glusterfs/server/tasks/main.yml
  contrib/network-storage/glusterfs/roles/glusterfs/server/tasks/setup-Debian.yml
  contrib/network-storage/heketi/roles/provision/tasks/bootstrap/tear-down.yml
  contrib/network-storage/heketi/roles/provision/tasks/bootstrap/topology.yml
  contrib/network-storage/heketi/roles/provision/tasks/bootstrap/volumes.yml
  contrib/network-storage/heketi/roles/provision/tasks/topology.yml
  contrib/network-storage/heketi/roles/tear-down-disks/tasks/main.yml
  contrib/network-storage/heketi/roles/tear-down/tasks/main.yml
  extra_playbooks/migrate_openstack_provider.yml
  roles/container-engine/containerd/tasks/reset.yml
  roles/container-engine/cri-o/tasks/main.yaml
  roles/container-engine/cri-o/tasks/reset.yml
  roles/container-engine/docker/tasks/main.yml
  roles/container-engine/docker/tasks/reset.yml
  roles/container-engine/docker/tasks/set_facts_dns.yml
  roles/container-engine/docker/tasks/systemd.yml
  roles/download/tasks/check_pull_required.yml
  roles/download/tasks/download_container.yml
  roles/download/tasks/prep_download.yml
  roles/etcd/tasks/join_etcd-events_member.yml
  roles/etcd/tasks/join_etcd_member.yml
  roles/etcd/tasks/upd_ca_trust.yml
  roles/helm-apps/tasks/main.yml
  roles/kubernetes-apps/krew/tasks/krew.yml
  roles/kubernetes-apps/network_plugin/kube-router/tasks/main.yml
  roles/kubernetes/control-plane/tasks/main.yml
  roles/kubernetes/control-plane/tasks/pre-upgrade.yml
  roles/kubernetes/node-label/tasks/main.yml
  roles/kubernetes/preinstall/tasks/0020-set_facts.yml
  roles/kubernetes/preinstall/tasks/0120-growpart-azure-centos-7.yml
  roles/network_plugin/calico/rr/tasks/main.yml
  roles/network_plugin/calico/rr/tasks/update-node.yml
  roles/network_plugin/calico/tasks/install.yml
  roles/network_plugin/calico/tasks/peer_with_calico_rr.yml
  roles/network_plugin/cilium/tasks/apply.yml
  roles/recover_control_plane/etcd/tasks/main.yml
  roles/recover_control_plane/etcd/tasks/recover_lost_quorum.yml
  roles/remove-node/pre-remove/tasks/main.yml
  roles/reset/tasks/main.yml
  roles/win_nodes/kubernetes_patch/tasks/main.yml
  test-infra/image-builder/roles/kubevirt-images/tasks/main.yml
  tests/cloud_playbooks/create-aws.yml
  tests/cloud_playbooks/create-do.yml
  tests/cloud_playbooks/create-gce.yml
  tests/cloud_playbooks/delete-gce.yml
  tests/cloud_playbooks/upload-logs-gcs.yml
  tests/testcases/010_check-apiserver.yml
  tests/testcases/015_check-nodes-ready.yml
  tests/testcases/020_check-pods-running.yml
  tests/testcases/030_check-network.yml
  tests/testcases/040_check-network-adv.yml
Labels: cncf-cla: yes, size/L, lgtm, approved, kind/cleanup

#10265 DOCU: Add github container registry to `docs/offline-environment.md`
  docs/offline-environment.md
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/documentation

#10258 Fix RHEL subscription activation key by removing auto_attach and syspurpose
  roles/bootstrap-os/tasks/bootstrap-redhat.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved
