Repository kubernetes-sigs/kubespray, pull requests merged in 2023-03, with the labels that each got.

#9829 [kubernetes] Add hashes for 1.26.2, 1.25.7, 1.24.11
  README.md
  inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
  roles/download/defaults/main.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: cncf-cla: yes, size/M, lgtm, approved, kind/feature

#9835 feat(Dockerfile): openssh-client support
  Dockerfile
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#9828 fix(contrib/terraform): do not set ssh port
  contrib/terraform/terraform.py
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/cleanup

#9842 Drop remaining part for supporting ansible 2.9 and 2.10
  docs/ansible.md
  tests/scripts/testcases_prepare.sh
Labels: cncf-cla: yes, size/S, lgtm, approved, kind/documentation

#9846 Downgrade version of coredns to 1.8.6 for compatibility with 1.23-1.24
  roles/download/defaults/main.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9836 feat(contrib/terraform): support custom ssh port
  contrib/terraform/terraform.py
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#9845 Drop crun_bin_dir unused var
  roles/container-engine/crun/defaults/main.yml
  roles/container-engine/crun/tasks/main.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved

#9819 Network plugin custom
  .ansible-lint
  .gitlab-ci/packet.yml
  .yamllint
  docs/ci.md
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
  roles/network_plugin/custom_cni/defaults/main.yml
  roles/network_plugin/custom_cni/tasks/main.yml
  roles/network_plugin/meta/main.yml
  tests/files/custom_cni/README.md
  tests/files/custom_cni/cilium.yaml
  tests/files/custom_cni/values.yaml
  tests/files/packet_debian11-custom-cni.yml
Labels: cncf-cla: yes, size/XXL, lgtm, ok-to-test, approved, kind/feature

#9768 fix(upgrade-cluster): retry other masters upgrade
  roles/kubernetes/control-plane/tasks/kubeadm-upgrade.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9827 Add support to install ContainerD on any Linux Distributions
  roles/container-engine/containerd/defaults/main.yml
  roles/container-engine/containerd/tasks/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#9852 upgrade kubevip to v0.5.11
  README.md
  roles/download/defaults/main.yml
  roles/kubernetes/node/defaults/main.yml
  roles/kubernetes/node/templates/manifests/kube-vip.manifest.j2
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9856 Cilium hubble certgen Job and CronJob wrong args
  roles/network_plugin/cilium/templates/hubble/cronjob.yml.j2
  roles/network_plugin/cilium/templates/hubble/job.yml.j2
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, ok-to-test, approved

#9834 node: fix default kubelet/runtime cgroups when kube_reserved is false
  inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
  roles/kubernetes/node/defaults/main.yml
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, ok-to-test, approved

#9850 the url of multus has been moved
  README.md
  Vagrantfile
  inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/documentation

#9849 [helm] upgrade to 3.11.1
  README.md
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/S, lgtm, approved

#9837 Update nodes in etc hosts after cluster scale
  roles/kubernetes/preinstall/defaults/main.yml
  roles/kubernetes/preinstall/tasks/0090-etchosts.yml
  roles/kubernetes/preinstall/tasks/main.yml
Labels: kind/bug, cncf-cla: yes, size/L, lgtm, ok-to-test, approved

#9855 upgrade rancher local-path-provisioner to v0.0.23
  README.md
  inventory/sample/group_vars/k8s_cluster/addons.yml
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9718 calico: cilium: use localhost lb by default on kube-proxy replacement
  docs/calico.md
  docs/cilium.md
  inventory/sample/group_vars/all/all.yml
  roles/kubespray-defaults/defaults/main.yaml
  roles/network_plugin/calico/templates/kubernetes-services-endpoint.yml.j2
  tests/files/packet_almalinux8-calico-ha-ebpf.yml
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/cleanup

#9861 Update check calico version command
  roles/network_plugin/calico/tasks/check.yml
Labels: kind/bug, cncf-cla: yes, size/M, lgtm, ok-to-test, approved

#9871 [2.21] Cilium hubble certgen Job and CronJob wrong args (#9856)
  roles/network_plugin/cilium/templates/hubble/cronjob.yml.j2
  roles/network_plugin/cilium/templates/hubble/job.yml.j2
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, approved

#9859 Markdown Updates To Cluster Upgrade Docs
  docs/upgrades.md
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/documentation

#9872 fix cri-o arm64 v1.26.0 wrong archive checksum
  roles/download/defaults/main.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9781 fix(kubernetes): Also apply kubeadm patches during upgrade
  roles/kubernetes/control-plane/tasks/kubeadm-upgrade.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#9782 Improve method to get binary checksums
  scripts/download_hash.sh
Labels: cncf-cla: yes, size/L, lgtm, approved, kind/flake

#9862 Fix uniontech os installation failure
  roles/container-engine/containerd/defaults/main.yml
  roles/container-engine/containerd/tasks/main.yml
  roles/kubernetes/preinstall/defaults/main.yml
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
  roles/kubernetes/preinstall/tasks/0040-set_facts.yml
Labels: kind/bug, cncf-cla: yes, size/M, lgtm, approved

#9873 Optimze detecting if calico exists
  roles/network_plugin/calico/tasks/check.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/network

#9443 Modified the default value of cilium IPAM and added the support for r…
  docs/cilium.md
  roles/network_plugin/cilium/defaults/main.yml
  roles/network_plugin/cilium/templates/cilium/config.yml.j2
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved

#9878 README: add mention to custom_cni
  README.md
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/documentation

#9882 fix typo word
  roles/network_plugin/calico/tasks/peer_with_calico_rr.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/cleanup

#9892 [containerd] add hashes for 1.7.0
  README.md
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/container-managers

#9902 Fix Cilium template error
  docs/cilium.md
  roles/network_plugin/cilium/defaults/main.yml
  roles/network_plugin/cilium/templates/cilium/config.yml.j2
Labels: kind/bug, cncf-cla: yes, size/M, lgtm, approved

#9883 Add Retry and Ignore Error for Checking calico ready
  roles/network_plugin/calico/tasks/check.yml
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, ok-to-test, approved

#9900 [kubernetes] Add hashes for 1.26.3, 1.25.8, 1.24.12
  README.md
  inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
  roles/download/defaults/main.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: cncf-cla: yes, size/M, lgtm, approved, kind/feature

#9904 fix allow unsupported distribution
  inventory/sample/group_vars/all/all.yml
  roles/container-engine/containerd/defaults/main.yml
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved

#9906 Add MrFreezeex as reviewer
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/feature

#9911 Add download retries option
  roles/download/defaults/main.yml
  roles/download/tasks/download_container.yml
  roles/download/tasks/download_file.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/feature

#9876 Fix ciliums hubble relay configuration
  roles/network_plugin/cilium/templates/hubble/config.yml.j2
  roles/network_plugin/cilium/templates/hubble/deploy.yml.j2
  roles/network_plugin/cilium/templates/hubble/service.yml.j2
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved

#9914 feat: support cilium 1.13.1
  roles/network_plugin/cilium/templates/cilium/ds.yml.j2
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/network

#9869 fix(contrib/terraform): do not add access_ip when not wanted
  contrib/terraform/terraform.py
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9674 Add IPv6 listen directive to haproxy proxy if enable_dual_stack_networks
  roles/kubernetes/node/templates/loadbalancer/haproxy.cfg.j2
  roles/kubernetes/node/templates/loadbalancer/nginx.conf.j2
Labels: cncf-cla: yes, size/S, lgtm, approved

#9864 [2.21] Fix cilium's hubble ui configuration (#9735)
  roles/network_plugin/cilium/templates/hubble/config.yml.j2
  roles/network_plugin/cilium/templates/hubble/deploy.yml.j2
Labels: kind/bug, cncf-cla: yes, size/L, lgtm, approved

#9669 fix(download): validate mirrors on localhost
  roles/download/tasks/download_file.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9880 cilium: Fix the configuration of tls for hubble
  roles/network_plugin/cilium/templates/hubble/config.yml.j2
  roles/network_plugin/cilium/templates/hubble/deploy.yml.j2
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/network

#9060 replace bash for loop when checking API server SANs
  roles/kubernetes/control-plane/tasks/kubeadm-setup.yml
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/cleanup

#9929 Delete the probe option of cilium_kube_proxy_replacement
  inventory/sample/group_vars/k8s_cluster/k8s-net-cilium.yml
  roles/network_plugin/cilium/defaults/main.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9922 fix(cert manager): Fix cert_manager_trusted_internal_ca manifest
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/cert-manager.yml.j2
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, ok-to-test, approved

#9932 cilium: Removing duplicates in the configuration of tls for hubble
  roles/network_plugin/cilium/templates/hubble/deploy.yml.j2
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/network

#9934 Fix the kube-bench 4.1.1 to enhance security
  roles/kubernetes/node/tasks/kubelet.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#9930 docs(argocd): ArgoCD no longer uses the pod name as initial password
  inventory/sample/group_vars/k8s_cluster/addons.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/documentation

#9939 Fix the kube-bench 1.2.20 to enhance security
  docs/vars.md
  roles/kubernetes/control-plane/defaults/main/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#9940 corrected reference link to valid one
  docs/calico.md
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/documentation

#9944 updated link for baremetel consideration
  docs/ingress_controller/ingress_nginx.md
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/documentation

#9943 Support extended settings for the Debian os family
  roles/kubernetes/preinstall/defaults/main.yml
  roles/kubernetes/preinstall/tasks/0020-set_facts.yml
  roles/kubernetes/preinstall/tasks/0040-verify-settings.yml
  roles/kubernetes/preinstall/tasks/main.yml
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, approved
