Repository kubernetes-sigs/kubespray, pull requests merged in 2023-12, with the labels that each got.

#10673 [2.21] Ensure that CI is available
  .gitlab-ci.yml
  .gitlab-ci/packet.yml
  .gitlab-ci/vagrant.yml
  README.md
  Vagrantfile
  contrib/terraform/exoscale/default.tfvars
  contrib/terraform/exoscale/modules/kubernetes-cluster/main.tf
  contrib/terraform/exoscale/modules/kubernetes-cluster/output.tf
  contrib/terraform/exoscale/modules/kubernetes-cluster/versions.tf
  docs/ci.md
  roles/container-engine/cri-o/molecule/default/molecule.yml
  roles/kubernetes/preinstall/tasks/0063-networkmanager-dns.yml
  scripts/premoderator.sh
  test-infra/image-builder/roles/kubevirt-images/defaults/main.yml
  tests/cloud_playbooks/roles/packet-ci/defaults/main.yml
  tests/files/packet_fedora37-calico-selinux.yml
  tests/files/packet_fedora37-calico-swap-selinux.yml
  tests/files/packet_fedora37-crio.yml
  tests/files/packet_fedora38-docker-calico.yml
  tests/files/packet_fedora38-docker-weave.yml
  tests/files/packet_fedora38-kube-ovn.yml
  tests/files/vagrant_fedora37-kube-router.rb
  tests/files/vagrant_fedora37-kube-router.yml
  tests/requirements-2.11.txt
  tests/requirements-2.12.txt
  tests/scripts/testcases_run.sh
Labels: cncf-cla: yes, size/L, lgtm, approved, kind/flake

#10633 Factorize some identical playbooks steps into their own sub-playbooks
  playbooks/boilerplate.yml
  playbooks/cluster.yml
  playbooks/install_etcd.yml
  playbooks/recover_control_plane.yml
  playbooks/remove_node.yml
  playbooks/reset.yml
  playbooks/scale.yml
  playbooks/upgrade_cluster.yml
Labels: cncf-cla: yes, size/L, lgtm, ok-to-test, approved, kind/cleanup

#10618 add dnsPolicy: ClusterFirstWithHostNet to DaemonSets with hostNetwork: true
  roles/kubernetes-apps/csi_driver/cinder/templates/cinder-csi-nodeplugin.yml.j2
  roles/kubernetes-apps/external_cloud_controller/openstack/templates/external-openstack-cloud-controller-manager-ds.yml.j2
  roles/network_plugin/calico/templates/calico-node.yml.j2
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#10635 [2.21] Downgrade version of coredns to 1.8.6 for compatibility with 1.23-1.24 (#9846)
  roles/download/defaults/main.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#10687 Using ctr pull instead of nerdctl
  roles/download/defaults/main/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#10665 [2.21] fix containerd config_path error (#9770)
  roles/container-engine/containerd/defaults/main.yml
  roles/container-engine/containerd/tasks/main.yml
  roles/container-engine/containerd/templates/config.toml.j2
Labels: kind/bug, cncf-cla: yes, size/M, lgtm, approved, kind/container-managers

#10667 Jinja syntax pre-commit validation
  .gitlab-ci/lint.yml
  .pre-commit-config.yaml
  tests/scripts/check-templates.py
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/feature

#10669 [calico] Add version 3.26.4 and make it default
  README.md
  roles/download/defaults/main/checksums.yml
  roles/download/defaults/main/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#10675 Final ipaddr deprecation cleanup
  tests/cloud_playbooks/roles/packet-ci/tasks/create-vms.yml
  tests/testcases/030_check-network.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/cleanup

#10680 Updated AWS ALB ingress controller version
  docs/ingress_controller/alb_ingress_controller.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/documentation

#10695 Remove unneeded workaround for removing kubeadm DNS
  roles/kubernetes-apps/ansible/tasks/cleanup_dns.yml
  roles/kubernetes-apps/ansible/tasks/main.yml
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/cleanup

#10587 Use systemd for disabling swap when it's used
  roles/kubernetes/preinstall/tasks/0010-swapoff.yml
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, ok-to-test, approved

#10699 Update 0040-verify-settings.yml
  roles/kubernetes/preinstall/tasks/0040-verify-settings.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#10661 Add VannTen as reviewer
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/documentation

#10702 Remove legacy crio packaging cleanup
  roles/container-engine/cri-o/defaults/main.yml
  roles/container-engine/cri-o/tasks/cleanup.yaml
  roles/container-engine/cri-o/tasks/main.yaml
Labels: kind/bug, cncf-cla: yes, size/L, lgtm, ok-to-test, approved

#10626 Decouple kubespray-defaults from download
  .ansible-lint-ignore
  Dockerfile
  contrib/offline/README.md
  contrib/offline/generate_list.sh
  docs/offline-environment.md
  extra_playbooks/migrate_openstack_provider.yml
  inventory/sample/group_vars/all/all.yml
  pipeline.Dockerfile
  roles/kubespray-defaults/defaults/main/checksums.yml
  roles/kubespray-defaults/defaults/main/download.yml
  roles/kubespray-defaults/defaults/main/main.yml
  roles/kubespray-defaults/meta/main.yml
  roles/kubespray-defaults/tasks/main.yaml
  scripts/download_hash.py
  scripts/download_hash.sh
  tests/scripts/check_readme_versions.sh
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/cleanup

#10706 [2.23] kubernetes: hashes for 1.27.8, 1.26.11, default to 1.27.8
  README.md
  contrib/terraform/exoscale/default.tfvars
  contrib/terraform/exoscale/modules/kubernetes-cluster/main.tf
  contrib/terraform/exoscale/modules/kubernetes-cluster/output.tf
  contrib/terraform/exoscale/modules/kubernetes-cluster/versions.tf
  roles/download/defaults/main/checksums.yml
  roles/kubernetes/preinstall/tasks/0040-verify-settings.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: cncf-cla: yes, size/L, lgtm, ok-to-test, approved, kind/api-change

#10704 [2.22] Add hashes for kubernetes 1.26.11, 1.26.10
  .gitlab-ci.yml
  .gitlab-ci/lint.yml
  .gitlab-ci/molecule.yml
  .gitlab-ci/packet.yml
  .gitlab-ci/vagrant.yml
  README.md
  Vagrantfile
  contrib/terraform/exoscale/default.tfvars
  contrib/terraform/exoscale/modules/kubernetes-cluster/main.tf
  contrib/terraform/exoscale/modules/kubernetes-cluster/output.tf
  contrib/terraform/exoscale/modules/kubernetes-cluster/versions.tf
  docs/ci.md
  inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
  pipeline.Dockerfile
  roles/container-engine/cri-o/molecule/default/molecule.yml
  roles/download/defaults/main.yml
  roles/kubernetes/preinstall/tasks/0040-verify-settings.yml
  roles/kubernetes/preinstall/tasks/0063-networkmanager-dns.yml
  roles/kubespray-defaults/defaults/main.yaml
  test-infra/image-builder/roles/kubevirt-images/defaults/main.yml
  tests/cloud_playbooks/roles/packet-ci/defaults/main.yml
  tests/constraints.txt
  tests/files/packet_fedora37-calico-selinux.yml
  tests/files/packet_fedora37-calico-swap-selinux.yml
  tests/files/packet_fedora37-crio.yml
  tests/files/packet_fedora38-docker-calico.yml
  tests/files/packet_fedora38-docker-weave.yml
  tests/files/packet_fedora38-kube-ovn.yml
  tests/files/vagrant_fedora37-kube-router.rb
  tests/files/vagrant_fedora37-kube-router.yml
Labels: cncf-cla: yes, size/L, lgtm, ok-to-test, approved, kind/api-change

#10610 etcd: use dynamic group for certs generation check
  roles/etcd/tasks/check_certs.yml
  roles/etcd/tasks/gen_certs_script.yml
  roles/etcd/vars/main.yml
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/cleanup

#10652 Revert "Update etcd-servers for apiserver (#8253)"
  roles/kubernetes/control-plane/tasks/kubeadm-fix-apiserver.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#10711 Fix the path of download.yml
  contrib/offline/README.md
  contrib/offline/generate_list.sh
  docs/offline-environment.md
  scripts/download_hash.py
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, approved

#10639 Disable podCIDR allocation from control-plane when using calico
  roles/kubernetes/control-plane/meta/main.yml
  roles/kubernetes/control-plane/templates/kubeadm-config.v1beta3.yaml.j2
  roles/network_plugin/calico/meta/main.yml
  roles/network_plugin/calico/tasks/check.yml
  roles/network_plugin/calico/tasks/install.yml
  roles/network_plugin/calico/templates/calico-config.yml.j2
  roles/network_plugin/calico_defaults/defaults/main.yml
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, ok-to-test, approved

#10607 Configuring PodNodeSelector via variables
  docs/hardening.md
  roles/kubernetes/control-plane/defaults/main/main.yml
  roles/kubernetes/control-plane/tasks/kubeadm-setup.yml
  roles/kubernetes/control-plane/templates/podnodeselector.yaml.j2
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/feature

#10671 [containerd] add hashes for versions 1.6.25-26 and 1.7.9-11 make v1.7.11 default
  README.md
  roles/kubespray-defaults/defaults/main/checksums.yml
  roles/kubespray-defaults/defaults/main/download.yml
Labels: cncf-cla: yes, size/S, lgtm, approved, kind/container-managers

#10700 chore(Dockerfile): python requirements file
  Dockerfile
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, ok-to-test, approved

#10715 [2.23] backport: disable podCIDR allocation from control-plane when using calico
  roles/kubernetes/control-plane/meta/main.yml
  roles/kubernetes/control-plane/templates/kubeadm-config.v1beta3.yaml.j2
  roles/network_plugin/calico/meta/main.yml
  roles/network_plugin/calico/tasks/check.yml
  roles/network_plugin/calico/tasks/install.yml
  roles/network_plugin/calico/templates/calico-config.yml.j2
  roles/network_plugin/calico_defaults/defaults/main.yml
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, approved

#10708 chore(Dockerfile): best practices
  Dockerfile
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/feature

#10608 support disable dns autoscaler when use CoreDNS
  roles/kubernetes-apps/ansible/tasks/coredns.yml
  roles/kubespray-defaults/defaults/main/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#10709 Removed DEPRECATED --logtostderr from metrics-server
  roles/kubernetes-apps/metrics_server/templates/metrics-server-deployment.yaml.j2
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/cleanup

#10725 CI: Document the 'all-in-one' layout + small refactoring
  .gitlab-ci/packet.yml
  docs/test_cases.md
  tests/cloud_playbooks/create-gce.yml
  tests/cloud_playbooks/roles/packet-ci/defaults/main.yml
  tests/cloud_playbooks/roles/packet-ci/tasks/main.yml
  tests/cloud_playbooks/roles/packet-ci/templates/inventory.j2
  tests/cloud_playbooks/roles/packet-ci/vars/main.yml
  tests/files/packet_amazon-linux-2-all-in-one.yml
  tests/files/packet_ubuntu20-all-in-one-docker.yml
  tests/files/packet_ubuntu20-calico-aio-ansible-2_11.yml
  tests/files/packet_ubuntu20-calico-all-in-one-ansible-2_11.yml
  tests/files/packet_ubuntu20-calico-all-in-one-hardening.yml
  tests/files/packet_ubuntu20-calico-all-in-one.yml
  tests/files/packet_ubuntu22-all-in-one-docker.yml
  tests/files/packet_ubuntu22-calico-all-in-one.yml
  tests/templates/inventory-gce.j2
Labels: cncf-cla: yes, size/M, lgtm, approved, kind/documentation

#10726 [2.22] fix(multus): loop_control template error when item is None (#10347)
  roles/kubernetes-apps/network_plugin/multus/tasks/main.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved

#10666 [etcd]: add etcd distributed tracing flags
  inventory/sample/group_vars/etcd.yml
  roles/etcd/defaults/main.yml
  roles/etcd/templates/etcd.env.j2
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/feature

#10438 Fix calico-node in etcd mode
  roles/network_plugin/calico/templates/calico-config.yml.j2
  roles/network_plugin/calico/templates/calico-node.yml.j2
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, ok-to-test, approved

#10731 docs: improve format for offline/README.md
  contrib/offline/README.md
Labels: cncf-cla: yes, size/XS, lgtm, approved

#10732 systemd-resolved: use a drop-in for kubespray dns
  roles/kubernetes/preinstall/tasks/0061-systemd-resolved.yml
  roles/kubernetes/preinstall/templates/resolved.conf.j2
  roles/reset/tasks/main.yml
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, approved

#10738 Deprecate and remove containerd_registries and containerd_insecure_registries variables.
  docs/containerd.md
  roles/container-engine/containerd/defaults/main.yml
  tests/common/_docker_hub_registry_mirror.yml
  tests/files/packet_ubuntu22-calico-all-in-one.yml
Labels: cncf-cla: yes, size/S, lgtm, approved

#10678 Fix modprobe module on Flatcar
  roles/kubernetes/node/tasks/main.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#10740 support other other runtime tool for manage-offline-container-images
  contrib/offline/manage-offline-container-images.sh
Labels: cncf-cla: yes, size/M, lgtm, approved, kind/feature

#10739 [kubernetes] Make kubernetes v1.28.5 default
  README.md
  inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
  roles/kubespray-defaults/defaults/main/checksums.yml
  roles/kubespray-defaults/defaults/main/main.yml
Labels: cncf-cla: yes, size/M, lgtm, approved, kind/feature
