Repository kubernetes-sigs/kubespray, pull requests merged in 2023-10, with the labels that each got.

#10474 UpCloud: UpCloud terraform provider v2.12.0 with strict server groups
  contrib/terraform/upcloud/README.md
  contrib/terraform/upcloud/cluster-settings.tfvars
  contrib/terraform/upcloud/modules/kubernetes-cluster/main.tf
  contrib/terraform/upcloud/modules/kubernetes-cluster/output.tf
  contrib/terraform/upcloud/modules/kubernetes-cluster/variables.tf
  contrib/terraform/upcloud/modules/kubernetes-cluster/versions.tf
  contrib/terraform/upcloud/sample-inventory/cluster.tfvars
  contrib/terraform/upcloud/variables.tf
  contrib/terraform/upcloud/versions.tf
Labels: cncf-cla: yes, size/L, lgtm, ok-to-test, approved, kind/feature

#10485 Update metallb example configs
  inventory/sample/group_vars/k8s_cluster/addons.yml
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/documentation

#10489 [kube-router] Add option to disable bgp-graceful-restart (10488)
  inventory/sample/group_vars/k8s_cluster/k8s-net-kube-router.yml
  roles/network_plugin/kube-router/defaults/main.yml
  roles/network_plugin/kube-router/templates/kube-router.yml.j2
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#10501 Added templating to coredns error plugin
  roles/kubernetes-apps/ansible/defaults/main.yml
  roles/kubernetes-apps/ansible/templates/coredns-config.yml.j2
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/feature

#10512 Fix restart network task cannot be skipped
  roles/reset/tasks/main.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved

#10493 [ingress-nginx] upgrade to 1.9.0
  README.md
  roles/download/defaults/main/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/feature

#10513 [docker] Ability to define GPG key path for Docker APT
  docs/docker.md
  roles/container-engine/docker/defaults/main.yml
  roles/container-engine/docker/tasks/main.yml
  tests/files/packet_debian12-docker.yml
  tests/files/packet_ubuntu22-aio-docker.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/container-managers

#10527 Ingress nginx controller v1.9.3
  README.md
  roles/download/defaults/main/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#10525 [containerd] add hashes for version 1.7.7
  README.md
  roles/download/defaults/main/checksums.yml
  roles/download/defaults/main/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/container-managers

#10526 [calico] Make version 3.26.3 default
  README.md
  roles/download/defaults/main/checksums.yml
  roles/download/defaults/main/main.yml
Labels: cncf-cla: yes, size/S, lgtm, approved

#10518 Cleanup a deprecation warning (ipaddr filter)
  galaxy.yml
  roles/kubernetes/control-plane/tasks/kubeadm-setup.yml
  roles/kubernetes/preinstall/tasks/0020-set_facts.yml
  roles/kubernetes/preinstall/tasks/0040-verify-settings.yml
  roles/network_plugin/calico/tasks/install.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/cleanup

#10464 Migrate node-role.kubernetes.io/master to node-role.kubernetes.io/con…
  docs/metallb.md
  inventory/sample/group_vars/k8s_cluster/addons.yml
  roles/kubernetes-apps/ansible/templates/coredns-deployment.yml.j2
  roles/kubernetes-apps/ansible/templates/dashboard.yml.j2
  roles/kubernetes-apps/ansible/templates/dns-autoscaler.yml.j2
  roles/kubernetes-apps/cloud_controller/oci/templates/oci-cloud-provider.yml.j2
  roles/kubernetes-apps/csi_driver/azuredisk/templates/azure-csi-azuredisk-controller.yml.j2
  roles/kubernetes-apps/csi_driver/vsphere/templates/vsphere-csi-controller-deployment.yml.j2
  roles/kubernetes-apps/external_cloud_controller/hcloud/templates/external-hcloud-cloud-controller-manager-ds-with-networks.yml.j2
  roles/kubernetes-apps/external_cloud_controller/hcloud/templates/external-hcloud-cloud-controller-manager-ds.yml.j2
  roles/kubernetes-apps/external_cloud_controller/huaweicloud/templates/external-huawei-cloud-controller-manager-ds.yml.j2
  roles/kubernetes-apps/external_cloud_controller/openstack/templates/external-openstack-cloud-controller-manager-ds.yml.j2
  roles/kubernetes-apps/external_cloud_controller/vsphere/templates/external-vsphere-cloud-controller-manager-ds.yml.j2
  roles/kubernetes-apps/metallb/defaults/main.yml
  roles/kubernetes-apps/metrics_server/templates/metrics-server-deployment.yaml.j2
  roles/kubernetes-apps/policy_controller/calico/templates/calico-kube-controllers.yml.j2
  roles/kubernetes/control-plane/tasks/kubeadm-setup.yml
  roles/kubernetes/control-plane/templates/kubeadm-config.v1beta3.yaml.j2
  roles/kubernetes/control-plane/templates/kubeadm-controlplane.v1beta3.yaml.j2
  roles/network_plugin/calico/templates/calico-apiserver.yml.j2
  roles/network_plugin/calico/templates/calico-typha.yml.j2
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/deprecation

#10515 Retries ssh connection for Gather node certs
  roles/etcd/tasks/gen_nodes_certs_script.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#10519 Correct cilium metrics port mapping
  roles/network_plugin/cilium/templates/hubble/deploy.yml.j2
  roles/network_plugin/cilium/templates/hubble/service.yml.j2
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved

#10520 terraform-aws: variable driven ami selection
  contrib/terraform/aws/README.md
  contrib/terraform/aws/variables.tf
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/feature

#10543 [kubernetes] Add hashes for kubernetes 1.27.7, 1.26.10, 1.25.15
  README.md
  inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
  roles/download/defaults/main/checksums.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: cncf-cla: yes, size/M, lgtm, approved, kind/feature

#10541 [kubernetes] Add hashes for kubernetes 1.28.3, 1.27.7, 1.26.10
  README.md
  inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
  roles/download/defaults/main/checksums.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: cncf-cla: yes, size/M, lgtm, approved, kind/feature

#10532 Migrate node-role.kubernetes.io/master to node-role.kubernetes.io/control-plane
  roles/kubernetes/control-plane/tasks/kubeadm-setup.yml
  roles/kubernetes/control-plane/templates/kubeadm-config.v1beta3.yaml.j2
  roles/kubernetes/control-plane/templates/kubeadm-controlplane.v1beta3.yaml.j2
  roles/upgrade/pre-upgrade/tasks/main.yml
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved

#10562 [release-2.23] Add crictl 1.26.1 for Kubernetes v1.26
  roles/download/defaults/main/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/flake

#10563 [release-2.23] Change default cri-o versions for Kubernetes 1.25, 1.26
  roles/download/defaults/main/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/flake

#10569 [release-2.23] [ingress-nginx] Fix nginx controller leader election RBAC permissions
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/ds-ingress-nginx-controller.yml.j2
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/role-ingress-nginx.yml.j2
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, approved

#10564 Add crictl 1.26.1 for Kubernetes v1.26
  roles/download/defaults/main/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/flake

#10566 [etcd] add 3.5.10 hashes
  roles/download/defaults/main/checksums.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/feature

#10567 [helm] upgrade to 3.13.1
  README.md
  roles/download/defaults/main/checksums.yml
  roles/download/defaults/main/main.yml
Labels: cncf-cla: yes, size/S, lgtm, approved

#10568 [argocd] update argocd to v2.8.4
  README.md
  inventory/sample/group_vars/k8s_cluster/addons.yml
  roles/download/defaults/main/checksums.yml
  roles/download/defaults/main/main.yml
  roles/kubernetes-apps/argocd/defaults/main.yml
Labels: cncf-cla: yes, size/S, lgtm, approved

#10552 Add kubectl alias support
  docs/vars.md
  roles/kubernetes/control-plane/defaults/main/main.yml
  roles/kubernetes/control-plane/tasks/main.yml
Labels: cncf-cla: yes, size/S, lgtm, approved

#10565 Change default cri-o versions for Kubernetes 1.26
  roles/download/defaults/main/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/container-managers

#10559 Cherry-pick: [download] Don't fail on 304 Not Modified (#10452)
  roles/download/tasks/download_file.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#10556 Remove always tag applied on bootstrap
  playbooks/cluster.yml
  playbooks/scale.yml
  playbooks/upgrade_cluster.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#10516 Use calico_pool_blocksize from cluster when existing
  roles/network_plugin/calico/tasks/install.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/network

#10533 `remove_default_searchdomains` inconsistent default value
  roles/kubernetes/preinstall/templates/resolved.conf.j2
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#10545 Fix metallb example yaml
  inventory/sample/group_vars/k8s_cluster/addons.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#10522 Add kube-vip in sample addons.yml
  inventory/sample/group_vars/k8s_cluster/addons.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/feature

#10154 Spicify the runc path when we use the containerd container engine and change the bin_dir path.
  roles/container-engine/containerd/defaults/main.yml
  roles/container-engine/containerd/templates/config.toml.j2
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/container-managers

#10500 [cert-manager] Upgrade to v1.12.5
  README.md
  roles/download/defaults/main/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#10540 etcd/backup: native ansible modules instead of shell
  roles/etcd/handlers/backup_cleanup.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/cleanup
