Repository kubernetes-sigs/kubespray, pull requests merged in 2023-07, with the labels that each got.

#10269 Upgrade cilium version to 1.13.4
  README.md
  roles/download/defaults/main/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#10267 [cilium] add custom vars for clusterrole cilium operator
  inventory/sample/group_vars/k8s_cluster/k8s-net-cilium.yml
  roles/network_plugin/cilium/defaults/main.yml
  roles/network_plugin/cilium/templates/cilium-operator/cr.yml.j2
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/feature

#10264 link update for aws_alb_ingress_controller
  docs/ingress_controller/alb_ingress_controller.md
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved

#9798 Upgrade versions
  roles/container-engine/docker/vars/debian.yml
  roles/container-engine/docker/vars/fedora.yml
  roles/container-engine/docker/vars/kylin.yml
  roles/container-engine/docker/vars/redhat-7.yml
  roles/container-engine/docker/vars/redhat.yml
  roles/container-engine/docker/vars/ubuntu.yml
  roles/container-engine/docker/vars/uniontech.yml
  roles/download/defaults/main/checksums.yml
  roles/download/defaults/main/main.yml
  scripts/download_hash.py
  scripts/download_hash.sh
Labels: cncf-cla: yes, size/XXL, lgtm, approved, kind/feature

#10271 Clean up calicoctl_alternate_download_url
  inventory/sample/group_vars/all/offline.yml
  roles/download/defaults/main/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/cleanup

#10277 project: fix galaxy ansible-lint rule
  .ansible-lint
  CHANGELOG.md
  galaxy.yml
  meta/runtime.yml
Labels: cncf-cla: yes, size/S, lgtm, approved, kind/cleanup

#10281 [ingress-nginx] upgrade to 1.8.1
  README.md
  roles/download/defaults/main/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#10291 bugfix: fix grep command without -w option causing prefix matched whi…
  roles/etcd/tasks/configure.yml
  roles/etcd/tasks/join_etcd-events_member.yml
  roles/etcd/tasks/join_etcd_member.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#10288 reset_confirmation in reset.yml
  playbooks/reset.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#10295 Bump versions
  README.md
  roles/download/defaults/main/checksums.yml
  roles/download/defaults/main/main.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/feature

#10300 [kubernetes] Add hashes for kubernetes 1.27.4, 1.26.7, 1.25.12
  README.md
  inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
  roles/download/defaults/main/checksums.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: cncf-cla: yes, size/M, lgtm, approved, kind/feature

#10304 improve security with CIS Kubernetes V1.23 Benchmark item number 4.1.9
  roles/kubernetes/node/tasks/kubelet.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#10303 fix: define undefined variable for reset
  playbooks/reset.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#10308 Update README
  README.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/documentation

#10309 Add CPU Management Policies on the Node
  docs/vars.md
  roles/kubernetes/node/templates/kubelet-config.v1beta1.yaml.j2
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/feature
