Repository kubernetes-sigs/kubespray, pull requests merged in 2023-01, with the labels that each got.

#9627 cleanup: replace node-role.kubernetes.io/master
  roles/network_plugin/calico/templates/calico-apiserver.yml.j2
  roles/network_plugin/canal/templates/canal-calico-kube-controllers.yml.j2
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/cleanup

#9625 Reset role: Remove kube-ovn log directories
  roles/reset/tasks/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/cleanup

#9595 Add enableServicesElection env variable.
  docs/kube-vip.md
  roles/kubernetes/node/defaults/main.yml
  roles/kubernetes/node/templates/manifests/kube-vip.manifest.j2
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/applications

#9636 Fix wording in amazonlinux.md
  docs/amazonlinux.md
Labels: cncf-cla: yes, size/XS, approved, kind/flake

#9621 Minor cleanup of README.md and two other docs
  README.md
  docs/ansible.md
  docs/ingress_controller/ingress_nginx.md
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/documentation

#9430 Skip removing worker nodes if kube_control_plane is not set
  roles/remove-node/post-remove/tasks/main.yml
  roles/remove-node/pre-remove/tasks/main.yml
  roles/remove-node/remove-etcd-node/tasks/main.yml
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, ok-to-test, approved

#9640 Increase the fedora memory at CI to fix the CI broken
  roles/container-engine/cri-o/molecule/default/molecule.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#9452 Added override variable, additional server groups and cloudinit config
  contrib/terraform/openstack/README.md
  contrib/terraform/openstack/kubespray.tf
  contrib/terraform/openstack/modules/compute/main.tf
  contrib/terraform/openstack/modules/compute/templates/cloudinit.yaml
  contrib/terraform/openstack/modules/compute/templates/cloudinit.yaml.tmpl
  contrib/terraform/openstack/modules/compute/variables.tf
  contrib/terraform/openstack/modules/compute/versions.tf
  contrib/terraform/openstack/variables.tf
  contrib/terraform/openstack/versions.tf
Labels: cncf-cla: yes, size/L, lgtm, ok-to-test, approved, kind/feature

#9631 calico: add vxlan-v6.calico to the list of NM unmanaged interfaces
  roles/kubernetes/preinstall/tasks/0062-networkmanager-unmanaged-devices.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/network

#9633 Add retry to avoid 'unknown' state for calicoctl
  roles/network_plugin/calico/tasks/check.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/network

#9635 feat(coredns): Forward extra domains to coredns kubernetes plugin
  docs/dns-stack.md
  inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
  roles/kubernetes-apps/ansible/templates/coredns-config.yml.j2
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#9281 streamline ansible_default_ipv4 gathering loop
  roles/kubespray-defaults/tasks/fallback_ips.yml
  roles/kubespray-defaults/tasks/fallback_ips_gather.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/cleanup

#9639 Update Calico VXLAN offload docs because Calico changed the default value.
  docs/calico.md
  roles/network_plugin/calico/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#9562 Add CI for rockylinux9 and cilium
  .gitlab-ci/packet.yml
  docs/ci.md
  tests/files/packet_rockylinux9-cilium.yml
Labels: cncf-cla: yes, size/S, lgtm, approved, kind/cleanup

#9644 Update containerd version : containerd1.6.15.
  README.md
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#9606 Creates a pipeline image and eliminates "pipeline bloat" from the Kubespray image
  .gitlab-ci.yml
  .gitlab-ci/build.yml
  .gitlab-ci/molecule.yml
  .gitlab-ci/vagrant.yml
  Dockerfile
  pipeline.Dockerfile
Labels: cncf-cla: yes, size/L, lgtm, approved, kind/cleanup, needs-ok-to-test

#9646 feature request: add cyclinder to reviewers
  OWNERS_ALIASES
  tests/scripts/check_typo.sh
Labels: cncf-cla: yes, size/XS, lgtm, approved

#9560 Skip retry operation with containerd when etcd installed on host VM
  reset.yml
  roles/reset/tasks/main.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9657 Fixes VM creation bug in Ubuntu 20 Calico AIO test
  pipeline.Dockerfile
  tests/cloud_playbooks/roles/packet-ci/tasks/create-vms.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/failing-test

#9648 Build pipeline image even on schedules and master
  .gitlab-ci/build.yml
Labels: kind/bug, cncf-cla: yes, size/XS, ok-to-test, approved

#9664 Add missing defaults for external_vsphere_* variables in the csi_driver/vsphere role
  roles/kubernetes-apps/csi_driver/vsphere/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/cleanup

#9659 Update cri-dockerd version
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved

#9654 [argocd] update argocd to v2.5.6
  README.md
  inventory/sample/group_vars/k8s_cluster/addons.yml
  roles/kubernetes-apps/argocd/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#9599 Support OVN Interconnect
  inventory/sample/group_vars/k8s_cluster/k8s-net-kube-ovn.yml
  roles/network_plugin/kube-ovn/defaults/main.yml
  roles/network_plugin/kube-ovn/templates/cni-kube-ovn.yml.j2
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/feature

#9661 [cert-manager] update cert-manager to v1.11.0
  README.md
  roles/download/defaults/main.yml
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/cert-manager.crds.yml.j2
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/cert-manager.yml.j2
Labels: cncf-cla: yes, size/L, lgtm, ok-to-test, approved, kind/feature

#9645 doc: don't set calico_vxlan_mode_ipv6=vxlanAlways when kernel < 3.12
  docs/calico.md
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/documentation

#9668 Update pause image version to v3.8
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/feature

#9224 [multus] added support for mixed type of container engine
  roles/kubernetes-apps/network_plugin/multus/tasks/main.yml
  roles/network_plugin/multus/tasks/main.yml
  roles/network_plugin/multus/templates/multus-daemonset.yml.j2
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/feature

#9566 add containerd config_path
  roles/container-engine/containerd/tasks/main.yml
  roles/container-engine/containerd/templates/config.toml.j2
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved

#9658 Terraform gcp extra ingress firewall
  contrib/terraform/gcp/README.md
  contrib/terraform/gcp/main.tf
  contrib/terraform/gcp/modules/kubernetes-cluster/main.tf
  contrib/terraform/gcp/modules/kubernetes-cluster/variables.tf
  contrib/terraform/gcp/variables.tf
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/feature

#9662 enable back kubelet_authorization_mode_webhook by default
  docs/hardening.md
  roles/kubernetes-apps/cluster_roles/tasks/main.yml
  roles/kubernetes-apps/cluster_roles/templates/node-webhook-cr.yml.j2
  roles/kubernetes-apps/cluster_roles/templates/node-webhook-crb.yml.j2
  roles/kubespray-defaults/defaults/main.yaml
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/cleanup

#9671 bump cni-plugins version to v1.2.0
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/feature

#9681 Add crio-related URLs to offline.yml
  inventory/sample/group_vars/all/offline.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#9676 [feature] add mzaian to reviewers
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/feature

#9675 [flannel] update to v0.20.2 & make it default
  README.md
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#9682 [argocd] update argocd to v2.5.7
  README.md
  inventory/sample/group_vars/k8s_cluster/addons.yml
  roles/kubernetes-apps/argocd/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#9680 feat(calico): add possibility to enable calico floatingIPs feature
  roles/network_plugin/calico/defaults/main.yml
  roles/network_plugin/calico/tasks/install.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#9684 supplement the omit cni-version in readme.md
  README.md
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/documentation

#9685 Add k8s hashes for 1.25.6, 1.23.16 , and make v1.25.6 default
  README.md
  inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
  roles/download/defaults/main.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/feature

#9678 [containerd] add hashes for 1.5.x
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/S, lgtm, approved, kind/feature

#9688 Add k8s 1.24.10 hashes
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/S, lgtm, approved, kind/feature

#9609 kubeadm/etcd: use config to download certificate
  roles/kubernetes/kubeadm/tasks/kubeadm_etcd_node.yml
  roles/kubernetes/kubeadm/templates/kubeadm-client.conf.v1beta3.j2
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, ok-to-test, approved

#9691 Update KUBESPRAY_VERSION and kube_version_min_required (with hashes cleanup)
  .gitlab-ci.yml
  roles/download/defaults/main.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: cncf-cla: yes, size/L, lgtm, approved, kind/flake

#9686 reword confusing etcd download url comment
  inventory/sample/group_vars/all/offline.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/documentation, kind/cleanup

#9698 Cleanup v1.23.x missing references/conditions/hashes
  README.md
  roles/download/defaults/main.yml
  roles/kubernetes/preinstall/tasks/0040-set_facts.yml
Labels: cncf-cla: yes, size/M, lgtm, approved, kind/cleanup

#9694 9693: Fix comma-separated-list splitting of kubelet_enforce_node_allocatable
  roles/kubernetes/node/templates/kubelet-config.v1beta1.yaml.j2
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9697 Add jmespath back to Dockerfile image
  Dockerfile
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved

#9673 Add DNS configuration for cert-manager
  inventory/sample/group_vars/k8s_cluster/addons.yml
  roles/kubernetes-apps/ingress_controller/cert_manager/defaults/main.yml
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/cert-manager.yml.j2
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/feature

#9700 [2.21] Fix comma-separated-list splitting of kubelet_enforce_node_allo…
  roles/kubernetes/node/templates/kubelet-config.v1beta1.yaml.j2
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9714 ci: document the CI environment
  docs/ci-setup.md
Labels: cncf-cla: yes, size/L, lgtm, approved, kind/documentation

#9707 Add ruamel.yaml to docker image
  Dockerfile
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved

#9702 update equinox terraform code to fix kubespray CI
  .gitignore
  .gitlab-ci/terraform.yml
  contrib/terraform/equinix/README.md
  contrib/terraform/equinix/hosts
  contrib/terraform/equinix/kubespray.tf
  contrib/terraform/equinix/output.tf
  contrib/terraform/equinix/provider.tf
  contrib/terraform/equinix/sample-inventory/cluster.tfvars
  contrib/terraform/equinix/sample-inventory/group_vars
  contrib/terraform/equinix/variables.tf
  contrib/terraform/metal/output.tf
  contrib/terraform/metal/versions.tf
  contrib/terraform/terraform.py
Labels: cncf-cla: yes, size/L, lgtm, approved, kind/feature

#9699 Update fedora35 vagrant box url
  .gitlab-ci.yml
  .gitlab-ci/lint.yml
  Vagrantfile
  contrib/terraform/openstack/modules/compute/versions.tf
  contrib/terraform/openstack/versions.tf
  pipeline.Dockerfile
  test-infra/vagrant-docker/Dockerfile
  tests/scripts/vagrant-validate.sh
Labels: cncf-cla: yes, size/M, lgtm, approved, kind/failing-test

#9708 [argocd] update argocd to v2.5.8
  README.md
  inventory/sample/group_vars/k8s_cluster/addons.yml
  roles/kubernetes-apps/argocd/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#9721 [2.21] Backport hotfix to Dockerfile image
  Dockerfile
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved

#9722 fix moved url in multus.md
  docs/multus.md
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9723 [argocd] update argocd to v2.5.9
  README.md
  inventory/sample/group_vars/k8s_cluster/addons.yml
  roles/kubernetes-apps/argocd/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#9724 fix docs for cert_manager.md
  docs/cert_manager.md
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9728 fix typo word for docs.
  README.md
  docs/upgrades/migrate_docker2containerd.md
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9727 Update containerd version : containerd1.6.16.
  README.md
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/container-managers

#9732 [kubernetes] Make kubernetes v1.26 default
  README.md
  inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
  roles/download/defaults/main.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved, kind/feature

#9734 Update kubevip to v0.5.8
  README.md
  roles/download/defaults/main.yml
  roles/kubernetes/node/defaults/main.yml
  roles/kubernetes/node/templates/manifests/kube-vip.manifest.j2
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/applications

#9735 Fix cilium's hubble ui configuration
  roles/network_plugin/cilium/templates/hubble/config.yml.j2
  roles/network_plugin/cilium/templates/hubble/deploy.yml.j2
Labels: kind/bug, cncf-cla: yes, size/L, lgtm, ok-to-test, approved

#9731 Adjust the table style to make it easier to read
  docs/ansible.md
  docs/arch.md
  docs/aws.md
  docs/encrypting-secret-data-at-rest.md
  docs/vsphere-csi.md
  docs/vsphere.md
Labels: cncf-cla: yes, size/L, lgtm, ok-to-test, approved, kind/documentation

#9729 fix: with_item to with_dict
  docs/containerd.md
  docs/offline-environment.md
  roles/container-engine/containerd/tasks/main.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: kind/bug, cncf-cla: yes, size/M, lgtm, ok-to-test, approved
