Repository kubernetes-sigs/kubespray, pull requests merged in 2023-02, with the labels that each got.

#9737 tests: Update ara 1.5.7 to 1.6.1
  tests/requirements-2.11.txt
  tests/requirements-2.12.txt
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#9730 Optimize the document for readability
  README.md
  RELEASE.md
  docs/azure-csi.md
  docs/azure.md
  docs/cloud.md
  docs/equinix-metal.md
  docs/etcd.md
  docs/ha-mode.md
  docs/integration.md
  docs/kube-ovn.md
  docs/kubernetes-reliability.md
  docs/nodes.md
  docs/offline-environment.md
  docs/setting-up-your-first-cluster.md
  docs/upgrades.md
  docs/vars.md
Labels: cncf-cla: yes, size/M, lgtm, approved, kind/documentation

#9751 [2.21] Backport "fix with item to with dict"
  docs/containerd.md
  docs/offline-environment.md
  roles/container-engine/containerd/tasks/main.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: kind/bug, cncf-cla: yes, size/M, lgtm, approved

#9753 [argocd] update argocd to v2.5.10
  README.md
  inventory/sample/group_vars/k8s_cluster/addons.yml
  roles/kubernetes-apps/argocd/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#9745 Replace nodelocaldns label
  roles/kubernetes-apps/ansible/templates/nodelocaldns-daemonset.yml.j2
  roles/kubernetes-apps/ansible/templates/nodelocaldns-second-daemonset.yml.j2
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9736 feat(cinder-csi): Allow deletionPolicy to be configurable
  roles/kubernetes-apps/snapshots/cinder-csi/defaults/main.yml
  roles/kubernetes-apps/snapshots/cinder-csi/templates/cinder-csi-snapshot-class.yml.j2
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#9755 fix: add ipamconfigs resource for calico
  roles/network_plugin/calico/templates/calico-apiserver.yml.j2
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9713 Add PSS labels to metallb namespace
  roles/kubernetes-apps/metallb/templates/metallb.yml.j2
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9742 skip ensuring ntp packages in coreos
  roles/kubernetes/preinstall/tasks/0081-ntp-configurations.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9752 Catch ShellCheck errors in pre-commit stage.
  .pre-commit-config.yaml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#9763 correct typo hhttps -> https
  contrib/terraform/equinix/sample-inventory/cluster.tfvars
  docs/ci-setup.md
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/cleanup

#9764 Fix a bug in removing kubelet data dir
  roles/reset/tasks/main.yml
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, ok-to-test, approved

#9766 add proxy_env variable to apt_key cleanup task
  roles/container-engine/cri-o/tasks/cleanup.yaml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9774 Copy contrib/ to Dockerfile
  Dockerfile
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved

#9778 Fix cni documentation
  docs/cni.md
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/documentation

#9785 Enable control plane load balancing for kube-vip
  docs/kube-vip.md
  roles/kubernetes/node/defaults/main.yml
  roles/kubernetes/node/templates/manifests/kube-vip.manifest.j2
Labels: cncf-cla: yes, size/S, lgtm, approved, kind/feature

#9789 fix ingress url not found issue
  docs/ingress_controller/ingress_nginx.md
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9783 Update the description of runc in offline.yml
  inventory/sample/group_vars/all/offline.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved

#9791 Fix CentOS Extras repo url for Oracle Linux 7 aarch64
  roles/bootstrap-os/tasks/bootstrap-centos.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9770 Fix containerd config_path error when containerd_registries is configed
  roles/container-engine/containerd/defaults/main.yml
  roles/container-engine/containerd/tasks/main.yml
  roles/container-engine/containerd/templates/config.toml.j2
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved

#9786 Fix kubernetes-app/argocd: download related things with the download role
  roles/download/defaults/main.yml
  roles/kubernetes-apps/argocd/tasks/main.yml
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/cleanup

#9800 Update nodelocaldns to 1.22.18
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9802 update docker image tag to v2.21.0 in README.md
  README.md
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/documentation

#9780 fix(crio): First runc then crictl
  roles/container-engine/cri-o/meta/main.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9793 fix(kubelet): no cloud config for external cloud provider
  roles/kubernetes/node/templates/kubelet.env.v1beta1.j2
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9799 fixed clinet to client
  roles/etcd/tasks/gen_certs_script.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/cleanup

#9806 fix calico rbac issue
  roles/network_plugin/calico/templates/calico-cr.yml.j2
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved

#9805 feature: add vim to kubespray docker image
  Dockerfile
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#9797 Add CI for containerd insecure_registries
  tests/files/packet_ubuntu22-calico-aio.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/cleanup

#9788 add krew_download_url to offline.yml
  inventory/sample/group_vars/all/offline.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9810 Reducing the image size
  Dockerfile
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9814 [containerd] add hashes for 1.6.17 , 1.6.8
  README.md
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/S, lgtm, approved, release-note-none, kind/container-managers

#9818 [ingress-nginx] upgrade to 1.6.4
  README.md
  roles/download/defaults/main.yml
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/admission-webhook-job.yml.j2
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/clusterrole-ingress-nginx.yml.j2
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/role-ingress-nginx.yml.j2
Labels: cncf-cla: yes, size/M, lgtm, approved

#9821 Dockerfile optimization
  pipeline.Dockerfile
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved

#9796 docs: small vsphere docs fixes
  docs/vsphere-csi.md
  docs/vsphere.md
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/documentation

#9823 Use var etcd_deployment_type instead of etcd_kubeadm_enabled
  recover-control-plane.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/cleanup

#9822 Reducing the number of layers and commands
  Dockerfile
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/flake

#9832 add image garbage collection
  docs/vars.md
  roles/kubernetes/node/templates/kubelet-config.v1beta1.yaml.j2
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/feature

#9687 Add resources section to all containers releated to Vsphere CSI driver
  roles/kubernetes-apps/csi_driver/vsphere/defaults/main.yml
  roles/kubernetes-apps/csi_driver/vsphere/templates/vsphere-csi-controller-deployment.yml.j2
  roles/kubernetes-apps/csi_driver/vsphere/templates/vsphere-csi-node.yml.j2
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/applications

#9767 [feature] add mzaian to approvers
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/feature

#9831 upcloud: add server groups and target port for lb
  contrib/terraform/upcloud/README.md
  contrib/terraform/upcloud/cluster-settings.tfvars
  contrib/terraform/upcloud/main.tf
  contrib/terraform/upcloud/modules/kubernetes-cluster/main.tf
  contrib/terraform/upcloud/modules/kubernetes-cluster/variables.tf
  contrib/terraform/upcloud/modules/kubernetes-cluster/versions.tf
  contrib/terraform/upcloud/sample-inventory/cluster.tfvars
  contrib/terraform/upcloud/variables.tf
  contrib/terraform/upcloud/versions.tf
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/feature

#9839 Add rsync in Dockerfile
  Dockerfile
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved, needs-ok-to-test

#9840 Replace semicolons by commas in options
  roles/kubernetes/preinstall/tasks/0063-networkmanager-dns.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9838 [containerd] add hashes for 1.6.19
  README.md
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/container-managers
