Repository kubernetes-sigs/kubespray, pull requests merged in 2023-04, with the labels that each got.

#9951 [helm] upgrade to 3.11.2
  README.md
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/S, lgtm, approved

#9952 [ingress-nginx] upgrade to 1.7.0
  README.md
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#9950 [calico] add v3.25.1 and make it default
  README.md
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#9949 Documentation: Fix collection URL
  docs/ansible_collection.md
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/documentation

#9953 [argocd] update argocd to v2.6.7
  README.md
  inventory/sample/group_vars/k8s_cluster/addons.yml
  roles/download/defaults/main.yml
  roles/kubernetes-apps/argocd/defaults/main.yml
Labels: cncf-cla: yes, size/S, lgtm, approved

#9958 Add bind address variable to OCCM
  roles/kubernetes-apps/external_cloud_controller/openstack/defaults/main.yml
  roles/kubernetes-apps/external_cloud_controller/openstack/templates/external-openstack-cloud-controller-manager-ds.yml.j2
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/api-change

#9954 [containerd] add hashes for 1.6.20
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/container-managers

#9962 fix resatrt k8s components
  roles/kubernetes/preinstall/handlers/main.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved

#9964 [cert-manager] Upgrade to v1.11.1
  README.md
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/feature

#9959 [cilium] fix rbac and upgrade hubble v0.11.0 (#3)
  roles/download/defaults/main.yml
  roles/network_plugin/cilium/defaults/main.yml
  roles/network_plugin/cilium/templates/cilium-operator/cr.yml.j2
  roles/network_plugin/cilium/templates/hubble/cronjob.yml.j2
  roles/network_plugin/cilium/templates/hubble/deploy.yml.j2
  roles/network_plugin/cilium/templates/hubble/job.yml.j2
  roles/network_plugin/cilium/templates/hubble/service.yml.j2
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved

#9946 [vSphere-csi-driver] Custom namespace fails playbook
  roles/kubernetes-apps/csi_driver/vsphere/tasks/main.yml
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, ok-to-test, approved

#9967 use var: kube_apiserver_address
  roles/kubernetes/control-plane/templates/kubeadm-config.v1beta3.yaml.j2
Labels: cncf-cla: yes, size/XS, lgtm, approved

#9963 Adding checksum verification kubectl
  Dockerfile
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/cleanup

#9970 remove invalid character
  roles/container-engine/crictl/tasks/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/cleanup

#9971 Adding checksum verification kubectl
  pipeline.Dockerfile
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/cleanup

#9979 Change nerdctl snapshotter to overlayfs by default
  roles/container-engine/nerdctl/templates/nerdctl.toml.j2
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#9973 disable rhsm repo when rhel_enable_repos is false
  roles/bootstrap-os/tasks/bootstrap-redhat.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9977 [feature] Update CoreDNS manifests
  roles/kubernetes-apps/ansible/templates/coredns-clusterrole.yml.j2
  roles/kubernetes-apps/ansible/templates/coredns-deployment.yml.j2
  roles/kubernetes-apps/ansible/templates/coredns-sa.yml.j2
Labels: cncf-cla: yes, size/M, lgtm, approved, kind/feature

#9974 [etcd] fix make-ssl-etcd.sh.j2; move pem files only if any new certs exist
  roles/etcd/templates/make-ssl-etcd.sh.j2
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9978 Support multi-arch using the same image name
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/feature

#9982 kube.py support kubeconfig
  plugins/modules/kube.py
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/feature

#9120 Support for MetalLB v0.13.9 with CRD
  README.md
  docs/metallb.md
  inventory/sample/group_vars/k8s_cluster/addons.yml
  roles/download/defaults/main.yml
  roles/kubernetes-apps/metallb/tasks/main.yml
  roles/kubernetes-apps/metallb/templates/layer2.yaml.j2
  roles/kubernetes-apps/metallb/templates/layer3.yaml.j2
  roles/kubernetes-apps/metallb/templates/metallb-config.yml.j2
  roles/kubernetes-apps/metallb/templates/metallb.yml.j2
  roles/kubernetes-apps/metallb/templates/pools.yaml.j2
Labels: cncf-cla: yes, size/XXL, lgtm, ok-to-test, approved, kind/feature

#9988 Small fix about doc file
  docs/_sidebar.md
  docs/kube-router.md
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/documentation

#9990 fix calico v3.25.1 checksums mismatch
  roles/download/defaults/main.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#9993 add kube-profile config to the scheduler
  docs/hardening.md
  roles/kubernetes/control-plane/templates/kubeadm-config.v1beta3.yaml.j2
  tests/files/packet_ubuntu20-calico-aio-hardening.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#9865 Suggest to run `reset.yml` playbook for first-time users
  README.md
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/documentation

#9992 use string for ipv6 forward conf
  roles/kubernetes/preinstall/tasks/0080-system-configurations.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#9938 Updates requirements to the latest available versions
  Dockerfile
  requirements-2.11.txt
  requirements-2.12.txt
Labels: kind/bug, cncf-cla: yes, size/M, lgtm, ok-to-test, approved

#10005 Update kube-vip to v0.5.12
  README.md
  roles/download/defaults/main.yml
  roles/kubernetes/node/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#9996 [feature] Update dns-autoscaler
  roles/download/defaults/main.yml
  roles/kubernetes-apps/ansible/templates/dns-autoscaler.yml.j2
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/feature

#10022 [helm] upgrade to 3.11.3
  README.md
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/S, lgtm, approved

#10024 [nerdctl] upgrade to version 1.3.1
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/S, lgtm, approved, kind/feature

#9999 [cri-o] Bump versions to 1.26.3, 1.25.3, 1.24.5
  roles/download/defaults/main.yml
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/container-managers

#10013 Add Retry for restart kube-controller-manager
  roles/kubernetes/preinstall/handlers/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#10026 [feat] Update metrics server to v0.6.3
  inventory/sample/group_vars/k8s_cluster/addons.yml
  roles/download/defaults/main.yml
  roles/kubernetes-apps/metrics_server/defaults/main.yml
  roles/kubernetes-apps/metrics_server/templates/metrics-server-deployment.yaml.j2
  roles/kubernetes-apps/metrics_server/templates/resource-reader.yaml.j2
Labels: cncf-cla: yes, size/M, lgtm, approved, kind/feature
