Repository kubernetes-sigs/kubespray, pull requests merged in 2023-08, with the labels that each got.

#10339 Add ErikJiang as reviewer
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/feature

#10108 Use supported version of fedora in CI
  .gitlab-ci/packet.yml
  .gitlab-ci/vagrant.yml
  README.md
  Vagrantfile
  docs/ci.md
  roles/container-engine/cri-o/molecule/default/molecule.yml
  roles/kubernetes/preinstall/tasks/0063-networkmanager-dns.yml
  test-infra/image-builder/roles/kubevirt-images/defaults/main.yml
  tests/cloud_playbooks/roles/packet-ci/defaults/main.yml
  tests/files/packet_fedora37-calico-selinux.yml
  tests/files/packet_fedora37-calico-swap-selinux.yml
  tests/files/packet_fedora37-crio.yml
  tests/files/packet_fedora38-docker-calico.yml
  tests/files/packet_fedora38-docker-weave.yml
  tests/files/packet_fedora38-kube-ovn.yml
  tests/files/vagrant_fedora37-kube-router.rb
  tests/files/vagrant_fedora37-kube-router.yml
Labels: cncf-cla: yes, size/M, lgtm, approved, kind/cleanup

#10315 tests/packet-ci: sanitize branch name for kubernetes labels
  tests/cloud_playbooks/roles/packet-ci/defaults/main.yml
  tests/cloud_playbooks/roles/packet-ci/tasks/cleanup-old-vms.yml
  tests/cloud_playbooks/roles/packet-ci/tasks/create-vms.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/flake

#10338 Set/keep owner/group root/root when unarchiving kata-containers
  roles/container-engine/kata-containers/tasks/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/container-managers

#10332 Allow to override etcd listen-metrics-urls configuration
  docs/etcd.md
  roles/etcd/templates/etcd.env.j2
  roles/kubernetes/control-plane/templates/kubeadm-config.v1beta3.yaml.j2
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/feature

#10346 not requiring 'v' in youki version
  scripts/download_hash.sh
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/cleanup

#10347 fix(multus): loop_control template error when item is None
  roles/kubernetes-apps/network_plugin/multus/tasks/main.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#10314 project: resolve ansible-lint key-order rule
  .ansible-lint
  contrib/os-services/roles/prepare/tasks/main.yml
  roles/container-engine/containerd/tasks/main.yml
  roles/container-engine/validate-container-engine/tasks/main.yml
  roles/download/tasks/download_container.yml
  roles/download/tasks/download_file.yml
  roles/etcdctl/tasks/main.yml
  roles/kubernetes-apps/metallb/tasks/main.yml
  roles/kubernetes/control-plane/tasks/kubeadm-setup.yml
  roles/kubernetes/node/tasks/facts.yml
  roles/kubernetes/preinstall/tasks/0020-set_facts.yml
  roles/kubernetes/preinstall/tasks/0040-verify-settings.yml
  roles/kubernetes/preinstall/tasks/0070-system-packages.yml
  roles/kubernetes/preinstall/tasks/0090-etchosts.yml
  roles/network_plugin/calico/tasks/check.yml
  roles/network_plugin/calico/tasks/install.yml
  roles/network_plugin/calico/tasks/pre.yml
  roles/network_plugin/kube-router/tasks/main.yml
  roles/network_plugin/macvlan/tasks/main.yml
  roles/upgrade/pre-upgrade/tasks/main.yml
  roles/win_nodes/kubernetes_patch/tasks/main.yml
  tests/testcases/030_check-network.yml
Labels: cncf-cla: yes, size/L, lgtm, approved, kind/cleanup

#10357 fix: not mount tls when 'cilium_hubble_tls_generate' is false
  roles/network_plugin/cilium/templates/hubble/deploy.yml.j2
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/network

#10032 Removes Ansible reinstall in CI pipeline
  .gitlab-ci.yml
  .gitlab-ci/lint.yml
  .gitlab-ci/molecule.yml
  .gitlab-ci/vagrant.yml
  pipeline.Dockerfile
  requirements.txt
  tests/scripts/testcases_prepare.sh
  tests/scripts/vagrant_clean.sh
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/cleanup

#10144 clean up /etc/hosts file if populate_inventory_to_hosts_file is false
  roles/kubernetes/preinstall/tasks/0090-etchosts.yml
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/cleanup

#10365 [helm] upgrade to 3.12.3
  README.md
  roles/download/defaults/main/checksums.yml
  roles/download/defaults/main/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#10359 [kubernetes] Make 1.27.4 default
  .gitlab-ci/molecule.yml
  .gitlab-ci/packet.yml
  README.md
  inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
  roles/download/defaults/main/checksums.yml
  roles/download/defaults/main/main.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: cncf-cla: yes, size/M, lgtm, approved, kind/feature

#10364 [argocd] update argocd to v2.8.0
  README.md
  inventory/sample/group_vars/k8s_cluster/addons.yml
  roles/kubernetes-apps/argocd/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#10368 [containerd] Make containerd 1.7.3 default
  README.md
  roles/download/defaults/main/checksums.yml
  roles/download/defaults/main/main.yml
Labels: cncf-cla: yes, size/S, lgtm, approved, kind/container-managers

#10372 Move runroot from crio.conf to storage.conf
  roles/container-engine/cri-o/tasks/main.yaml
  roles/container-engine/cri-o/templates/crio.conf.j2
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/container-managers

#10371 fix argocd install not working using the kubespray docker image
  Dockerfile
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#10370 Add kubelet topology manager policy on the node
  docs/vars.md
  roles/kubernetes/node/templates/kubelet-config.v1beta1.yaml.j2
Labels: cncf-cla: yes, size/S, lgtm, approved, kind/feature

#10363 fix: flatcar bootstrap
  roles/bootstrap-os/files/bootstrap.sh
  roles/kubernetes/preinstall/tasks/0081-ntp-configurations.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#10369 Update checksum values
  README.md
  roles/download/defaults/main/checksums.yml
  roles/download/defaults/main/main.yml
Labels: cncf-cla: yes, size/L, lgtm, approved, kind/feature

#10385 Install etcdutl file by default
  roles/etcd/tasks/install_docker.yml
  roles/etcd/tasks/install_etcdctl_docker.yml
  roles/etcd/tasks/install_host.yml
  roles/etcd/tasks/main.yml
  roles/etcdctl/tasks/main.yml
  roles/etcdctl_etcdutl/tasks/main.yml
  roles/etcdctl_etcdutl/templates/etcdctl.sh.j2
  roles/kubernetes/control-plane/tasks/kubeadm-etcd.yml
Labels: cncf-cla: yes, size/L, lgtm, approved, kind/feature

#10392 [kubernetes] Make 1.27.5 default
  README.md
  inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
  roles/download/defaults/main/checksums.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: cncf-cla: yes, size/M, lgtm, approved, kind/feature

#10198 Add huawei cloud controller
  inventory/sample/group_vars/all/all.yml
  inventory/sample/group_vars/all/huaweicloud.yml
  roles/kubernetes-apps/external_cloud_controller/huaweicloud/defaults/main.yml
  roles/kubernetes-apps/external_cloud_controller/huaweicloud/tasks/huaweicloud-credential-check.yml
  roles/kubernetes-apps/external_cloud_controller/huaweicloud/tasks/main.yml
  roles/kubernetes-apps/external_cloud_controller/huaweicloud/templates/external-huawei-cloud-config-secret.yml.j2
  roles/kubernetes-apps/external_cloud_controller/huaweicloud/templates/external-huawei-cloud-config.j2
  roles/kubernetes-apps/external_cloud_controller/huaweicloud/templates/external-huawei-cloud-controller-manager-ds.yml.j2
  roles/kubernetes-apps/external_cloud_controller/huaweicloud/templates/external-huawei-cloud-controller-manager-role-bindings.yml.j2
  roles/kubernetes-apps/external_cloud_controller/huaweicloud/templates/external-huawei-cloud-controller-manager-roles.yml.j2
  roles/kubernetes-apps/external_cloud_controller/meta/main.yml
Labels: cncf-cla: yes, size/L, lgtm, ok-to-test, approved, kind/feature

#10391 fix not-found service error
  contrib/os-services/roles/prepare/tasks/main.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#10395 Change maximal_ansible_version to 2.15
  playbooks/ansible_version.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved

#10397 [containerd] add hashes for 1.7.4-5
  README.md
  roles/download/defaults/main/checksums.yml
  roles/download/defaults/main/main.yml
Labels: cncf-cla: yes, size/S, lgtm, approved, kind/container-managers

#10400 [feat] Update metrics server to v0.6.4
  roles/download/defaults/main/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/feature
