Repository kubernetes-sigs/kubespray, pull requests merged in 2024-07, with the labels that each got.

#11310 [ingress-nginx] Enable to fix the nodePort of ingress-nginx service
  inventory/sample/group_vars/k8s_cluster/addons.yml
  roles/kubernetes-apps/ingress_controller/ingress_nginx/defaults/main.yml
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/svc-ingress-nginx.yml.j2
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, release-note, kind/feature

#11324 CI: rework pipeline: short/extended based on labels
  .gitlab-ci.yml
  .gitlab-ci/build.yml
  .gitlab-ci/lint.yml
  .gitlab-ci/molecule.yml
  .gitlab-ci/packet.yml
  .gitlab-ci/pre-commit-dynamic-stub.yml
  .gitlab-ci/terraform.yml
  .gitlab-ci/vagrant.yml
  Vagrantfile
  docs/developers/ci-setup.md
  pipeline.Dockerfile
  tests/Makefile
  tests/cloud_playbooks/roles/packet-ci/defaults/main.yml
  tests/cloud_playbooks/roles/packet-ci/templates/vm.yml.j2
  tests/files/packet_almalinux8-calico-ha-ebpf.yml
  tests/files/packet_almalinux8-calico-nodelocaldns-secondary.yml
  tests/files/packet_almalinux8-calico.yml
  tests/files/packet_almalinux8-docker.yml
  tests/files/packet_almalinux8-kube-ovn.yml
  tests/files/packet_rockylinux8-calico.yml
  tests/files/packet_rockylinux9-calico.yml
  tests/files/packet_rockylinux9-cilium.yml
  tests/files/packet_ubuntu22-all-in-one-docker.yml
  tests/files/packet_ubuntu22-calico-all-in-one.yml
  tests/files/packet_ubuntu24-all-in-one-docker.yml
  tests/files/packet_ubuntu24-calico-all-in-one.yml
  tests/files/packet_ubuntu24-calico-etcd-datastore.yml
  tests/files/vagrant_ubuntu20-flannel.rb
  tests/files/vagrant_ubuntu20-flannel.yml
  tests/scripts/vagrant-install.sh
Labels: cncf-cla: yes, size/XL, lgtm, approved, kind/cleanup, release-note-none, ci-extended

#11261 [kubernetes] Add hashes for kubernetes 1.30 (#11109)
  roles/kubespray-defaults/defaults/main/checksums.yml
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, release-note, kind/feature

#11341 [cert-manager] upgrade to v1.14.7
  README.md
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/cert-manager.crds.yml.j2
  roles/kubespray-defaults/defaults/main/download.yml
Labels: cncf-cla: yes, size/L, lgtm, ok-to-test, approved, release-note, kind/feature

#11344 CI: remove centos7 and weave jobs from test pipeline
  .gitlab-ci/packet.yml
  .gitlab-ci/vagrant.yml
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, release-note, ci-extended

#11335 Make calico-kube-controllers log level configurable
  roles/kubernetes-apps/policy_controller/calico/defaults/main.yml
  roles/kubernetes-apps/policy_controller/calico/templates/calico-kube-controllers.yml.j2
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note, kind/feature

#11336 Make local_volume_provisioner log level configurable
  roles/kubernetes-apps/external_provisioner/local_volume_provisioner/defaults/main.yml
  roles/kubernetes-apps/external_provisioner/local_volume_provisioner/templates/local-volume-provisioner-ds.yml.j2
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note, kind/feature

#11343 [kubernetes] Support kubernetes 1.30
  README.md
  inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
  roles/kubespray-defaults/defaults/main/download.yml
  roles/kubespray-defaults/defaults/main/main.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, release-note, kind/feature, ci-extended

#11351 [kubernetes] Add hashes for kubernetes 1.29.6
  roles/kubespray-defaults/defaults/main/checksums.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/feature, release-note-none

#11360 Fix CentOS 7 yum repo baseurl update
  roles/bootstrap-os/tasks/centos.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, release-note, kind/feature, kind/failing-test

#11354 Increase ansible timeout to 300
  ansible.cfg
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature, release-note-none

#11374 Bump Cinder CSI Plugin to v1.30.0
  README.md
  roles/kubespray-defaults/defaults/main/download.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note, kind/feature

#11358 Bump: OpenStack Cloud Controller Manager to 1.30.0
  roles/kubernetes-apps/external_cloud_controller/openstack/defaults/main.yml
  roles/kubespray-defaults/defaults/main/download.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note, kind/feature

#11388 Fix etcd not starting up when using a custom access address
  roles/etcd/templates/openssl.conf.j2
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note

#11370 Limit nodes in gather ansible_default_ipv4
  roles/kubespray-defaults/tasks/fallback_ips.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature, release-note-none

#11396 Rename systemd module to systemd_service
  contrib/os-services/roles/prepare/tasks/main.yml
  roles/bootstrap-os/tasks/clearlinux.yml
  roles/bootstrap-os/tasks/flatcar.yml
  roles/container-engine/containerd/handlers/main.yml
  roles/container-engine/containerd/tasks/main.yml
  roles/container-engine/cri-dockerd/handlers/main.yml
  roles/container-engine/cri-o/handlers/main.yml
  roles/container-engine/docker/handlers/main.yml
  roles/container-engine/docker/tasks/reset.yml
  roles/etcd/handlers/main.yml
  roles/etcd/tasks/configure.yml
  roles/kubernetes/control-plane/handlers/main.yml
  roles/kubernetes/control-plane/tasks/main.yml
  roles/kubernetes/kubeadm/handlers/main.yml
  roles/kubernetes/node/handlers/main.yml
  roles/kubernetes/preinstall/tasks/0080-system-configurations.yml
  roles/recover_control_plane/etcd/tasks/recover_lost_quorum.yml
  roles/reset/tasks/main.yml
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, release-note, kind/feature

#11391 Make kubernetes v1.30.3 default
  README.md
  inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
  roles/kubespray-defaults/defaults/main/checksums.yml
  roles/kubespray-defaults/defaults/main/download.yml
  roles/kubespray-defaults/defaults/main/main.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, release-note, kind/feature

#11387 Provide missing advertise-address flag to kube-apiserver
  roles/kubernetes/control-plane/templates/kubeadm-config.v1beta3.yaml.j2
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note

#11372 [containerd/tracing]: fix containerd tracing templating
  roles/container-engine/containerd/templates/config.toml.j2
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note

#11367 fix kube_reserved so it only controls kubeReservedCgroup
  docs/operations/cgroups.md
  inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
  roles/kubernetes/node/defaults/main.yml
  roles/kubernetes/node/templates/kubelet-config.v1beta1.yaml.j2
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, release-note

#11355 [release-2.25] Bump Kubernetes to 1.29.6
  README.md
  inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
  roles/kubespray-defaults/defaults/main/checksums.yml
  roles/kubespray-defaults/defaults/main/main.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, release-note, kind/feature, do-not-merge/hold

#11334 Make netchecker log levels configurable
  roles/kubernetes-apps/ansible/defaults/main.yml
  roles/kubernetes-apps/ansible/templates/netchecker-agent-ds.yml.j2
  roles/kubernetes-apps/ansible/templates/netchecker-agent-hostnet-ds.yml.j2
  roles/kubernetes-apps/ansible/templates/netchecker-server-deployment.yml.j2
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, release-note, kind/feature

#11407 [kubernetes] Add hashes for kubernetes 1.29.7, 1.28.[11-12]
  roles/kubespray-defaults/defaults/main/checksums.yml
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, release-note, kind/feature
