Repository kubernetes-sigs/kubespray, pull requests merged in 2024-08, with the labels that each got.

#11260 Add support for LB in upcloud private zone
  contrib/terraform/upcloud/cluster-settings.tfvars
  contrib/terraform/upcloud/main.tf
  contrib/terraform/upcloud/modules/kubernetes-cluster/main.tf
  contrib/terraform/upcloud/modules/kubernetes-cluster/variables.tf
  contrib/terraform/upcloud/variables.tf
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, release-note, kind/api-change

#11357 Update cni-kube-ovn.yml.j2
  roles/network_plugin/kube-ovn/templates/cni-kube-ovn.yml.j2
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note

#11368 Add generic post upgrade hooks for node
  roles/upgrade/post-upgrade/tasks/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature, release-note-none

#11384 Bugfix/code inspection
  .pre-commit-config.yaml
  galaxy.yml
  requirements.txt
  tests/requirements.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/cleanup, release-note-none

#11413 [containerd] add hashes for versions '1.6.32-34', 'v1.7.17-20' and make v1.7.20 default
  README.md
  roles/kubespray-defaults/defaults/main/checksums.yml
  roles/kubespray-defaults/defaults/main/download.yml
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, release-note, kind/container-managers

#11406 fix kylin OS choose NetworkManager
  roles/reset/defaults/main.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note

#11408 [release-2.25] Make kubernetes v1.29.7 default
  README.md
  inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
  roles/kubespray-defaults/defaults/main/checksums.yml
  roles/kubespray-defaults/defaults/main/main.yml
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, release-note, kind/feature

#11401 Restart kube-proxy pods only on configmap changes
  roles/kubernetes/kubeadm/tasks/main.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/feature, release-note-none

#10948 Avoid empty "supersede domain-name-servers" directives for dhclient.conf
  roles/kubernetes/preinstall/tasks/0020-set_facts.yml
  roles/kubernetes/preinstall/tasks/0100-dhclient-hooks.yml
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, lifecycle/stale, ok-to-test, approved

#10934 fix: skip multus when not defined
  roles/kubernetes-apps/network_plugin/multus/tasks/main.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#11419 [release-2.25] [containerd] Add hashes for versions '1.6.32-34', 'v1.7.17-20' and Make v1.7.20 default
  README.md
  roles/kubespray-defaults/defaults/main/checksums.yml
  roles/kubespray-defaults/defaults/main/download.yml
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, release-note, kind/container-managers

#10698 bump cni version to v1.4.0
  roles/kubespray-defaults/defaults/main/download.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#11422 fix: use super-admin.conf for kube-vip on first master when it exists
  roles/kubernetes/node/tasks/loadbalancer/kube-vip.yml
  roles/kubernetes/node/templates/manifests/kube-vip.manifest.j2
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, ok-to-test, approved, release-note-none

#11439 Correct resolvconf typo
  roles/kubernetes/preinstall/tasks/0020-set_facts.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note-none

#11444 [release-2.25] fix: use super-admin.conf for kube-vip on first master when it exists (#11422 v2.25 backport)
  roles/kubernetes/node/tasks/loadbalancer/kube-vip.yml
  roles/kubernetes/node/templates/manifests/kube-vip.manifest.j2
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, release-note

#11445 [kube-ovn] update version to 1.12.21
  README.md
  roles/kubespray-defaults/defaults/main/download.yml
  roles/network_plugin/kube-ovn/templates/cni-kube-ovn-crd.yml.j2
  roles/network_plugin/kube-ovn/templates/cni-kube-ovn.yml.j2
  roles/network_plugin/kube-ovn/templates/cni-ovn.yml.j2
Labels: cncf-cla: yes, size/XXL, lgtm, ok-to-test, approved, release-note

#11440 Cleanup NetworkManager dns.conf on Reset
  roles/reset/tasks/main.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note

#11453 Add tico88612 as reviewer
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/flake, release-note-none

#11455 Add hashes for Kubernetes 1.30.4 and set default
  README.md
  inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
  roles/kubespray-defaults/defaults/main/checksums.yml
  roles/kubespray-defaults/defaults/main/main.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, release-note, kind/feature

#11250 Update node-feature-discovery to v0.16.4
  README.md
  roles/kubernetes-apps/node_feature_discovery/templates/nfd-api-crds.yaml.j2
  roles/kubernetes-apps/node_feature_discovery/templates/nfd-clusterrole.yaml.j2
  roles/kubernetes-apps/node_feature_discovery/templates/nfd-master.yaml.j2
  roles/kubernetes-apps/node_feature_discovery/templates/nfd-role.yaml.j2
  roles/kubespray-defaults/defaults/main/download.yml
Labels: cncf-cla: yes, size/XL, lgtm, ok-to-test, approved, release-note

#11463 [ingress-nginx] upgrade to 1.11.2
  README.md
  docs/ingress/ingress_nginx.md
  roles/kubespray-defaults/defaults/main/download.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note, kind/feature

#11080 Add containerd config options
  inventory/sample/group_vars/all/containerd.yml
  roles/container-engine/containerd/defaults/main.yml
  roles/container-engine/containerd/templates/config.toml.j2
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, release-note, kind/feature

#11459 fix reset network for tencent OS
  roles/reset/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note

#11435 fix double pop of access_ip
  contrib/terraform/terraform.py
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note-none

#11473 Remove kubeadm_version and use kube_version instead
  inventory/sample/group_vars/all/offline.yml
  roles/download/tasks/prep_kubeadm_images.yml
  roles/kubespray-defaults/defaults/main/download.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, release-note, kind/cleanup

#11474 Adjust preinstall check task name since we allow an empty kube_node group
  roles/kubernetes/preinstall/tasks/0040-verify-settings.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/cleanup, release-note-none

#11457 fix static api server advertise address
  roles/kubernetes/control-plane/templates/kubeadm-config.v1beta3.yaml.j2
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note

#11352 Fix: remove --config option from kubeadm upgrade (#11350)
  roles/kubernetes/control-plane/tasks/kubeadm-upgrade.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note

#11478 [containerd] add hashes for versions v1.7.21 and make v1.7.21 default
  README.md
  roles/kubespray-defaults/defaults/main/checksums.yml
  roles/kubespray-defaults/defaults/main/download.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note, kind/container-managers

#11476 [calico] Update calico to v3.27.4 to fix high cpu issues
  README.md
  roles/kubespray-defaults/defaults/main/checksums.yml
  roles/kubespray-defaults/defaults/main/download.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note

#11483 Adding myself (VannTen) as approver
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note-none

#11234 Calico v3.28.[0-1] checksums and change calico default version
  README.md
  roles/kubespray-defaults/defaults/main/checksums.yml
  roles/kubespray-defaults/defaults/main/download.yml
  roles/network_plugin/calico/templates/calico-apiserver.yml.j2
  roles/network_plugin/calico/templates/calico-node.yml.j2
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, release-note, kind/feature

#11458 [CI] Add a CI job to test cluster upgrading, and fix bug of testcases_run.sh
  .gitlab-ci/packet.yml
  tests/files/packet_ubuntu22-calico-all-in-one-upgrade.yml
  tests/scripts/testcases_run.sh
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/feature, release-note-none

#11479 Add conditional checking on ubuntu kernel unattended_upgrades disabling
  roles/bootstrap-os/tasks/debian.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/feature, release-note-none

#11486 upgrade helm to v3.15.4
  README.md
  roles/kubespray-defaults/defaults/main/checksums.yml
  roles/kubespray-defaults/defaults/main/download.yml
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, release-note

#11484 Print the name of faulty jinja templates in pre-commit
  tests/scripts/check-templates.py
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/feature, release-note-none

#11488 fix: incorrect member matching when removing etcd nodes
  roles/remove-node/remove-etcd-node/tasks/main.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note

#11376 Feat: Gateway API CRDs install support
  inventory/sample/group_vars/k8s_cluster/addons.yml
  roles/kubernetes-apps/gateway_api/defaults/main.yml
  roles/kubernetes-apps/gateway_api/tasks/main.yml
  roles/kubernetes-apps/gateway_api/templates/experimental-install.yaml.j2
  roles/kubernetes-apps/gateway_api/templates/standard-install.yaml.j2
  roles/kubernetes-apps/meta/main.yml
Labels: cncf-cla: yes, size/XXL, lgtm, ok-to-test, approved, release-note, kind/feature
