Repository kubernetes-sigs/kubespray, pull requests merged in 2024-03, with the labels that each got.

#10966 Add configuration to create cilium CNI plugin file when cilium>=1.14.0
  roles/network_plugin/cilium/templates/cilium/config.yml.j2
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#10981 fix ssh_args in ansible.cfg no effect
  ansible.cfg
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#10985 [2.24] Add configuration to create cilium CNI plugin file when cilium>=1.14.0 (#10966)
  roles/network_plugin/cilium/templates/cilium/config.yml.j2
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#10960 [calico] Add hashes and make v3.27.2 default
  README.md
  roles/kubespray-defaults/defaults/main/checksums.yml
  roles/kubespray-defaults/defaults/main/download.yml
Labels: cncf-cla: yes, size/S, lgtm, approved

#10713 scripts: refactor scripts/download_hash.sh
  scripts/download_hash.sh
Labels: cncf-cla: yes, size/L, lgtm, approved, kind/feature

#10996 Delete old leftover script
  roles/kubernetes/preinstall/gen-gitinfos.sh
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/cleanup, ¯\_(ツ)_/¯

#10968 Upgrade Nerdctl version to 1.7.4
  roles/kubespray-defaults/defaults/main/checksums.yml
  roles/kubespray-defaults/defaults/main/download.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved

#10984 Upgrade ansible-core to 2.16.4
  docs/ansible.md
  meta/runtime.yml
  playbooks/ansible_version.yml
  requirements.txt
  roles/container-engine/docker/tasks/main.yml
  tests/Makefile
  tests/cloud_playbooks/create-gce.yml
  tests/cloud_playbooks/delete-gce.yml
  tests/cloud_playbooks/upload-logs-gcs.yml
  tests/requirements.txt
Labels: cncf-cla: yes, size/L, lgtm, ok-to-test, approved

#11014 Cleanup unused CI tooling
  tests/Makefile
  tests/README.md
  tests/cloud_playbooks/create-aws.yml
  tests/cloud_playbooks/create-do.yml
  tests/cloud_playbooks/delete-aws.yml
  tests/cloud_playbooks/templates/boto.j2
  tests/cloud_playbooks/templates/gcs_life.json.j2
  tests/local_inventory/host_vars/localhost
  tests/local_inventory/hosts.cfg
  tests/requirements.yml
  tests/scripts/ansibl8s_test.sh
  tests/support/aws.groovy
  tests/templates/inventory-aws.j2
  tests/templates/inventory-do.j2
  tests/templates/inventory-gce.j2
Labels: cncf-cla: yes, size/XL, lgtm, approved, kind/cleanup

#11015 spelling: scrapper -> scraper
  roles/kubernetes-apps/ansible/templates/dashboard.yml.j2
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/cleanup

#10997 fix: config hostname as string type in kubeadmConfig rendering
  roles/kubernetes/control-plane/templates/kubeadm-config.v1beta3.yaml.j2
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, approved

#11023 Allow specifying CPU Manager Policy Options
  docs/vars.md
  roles/kubernetes/node/templates/kubelet-config.v1beta1.yaml.j2
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved

#10971 Make proxy protocol in upcloud LB configurable
  contrib/terraform/upcloud/cluster-settings.tfvars
  contrib/terraform/upcloud/main.tf
  contrib/terraform/upcloud/modules/kubernetes-cluster/main.tf
  contrib/terraform/upcloud/modules/kubernetes-cluster/variables.tf
  contrib/terraform/upcloud/variables.tf
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/api-change

#11021 make kube-vip LeaderElection variables configurable
  docs/kube-vip.md
  roles/kubernetes/node/defaults/main.yml
  roles/kubernetes/node/templates/manifests/kube-vip.manifest.j2
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/feature

#10983 Refactor bootstrap-os
  roles/bootstrap-os/tasks/amazon.yml
  roles/bootstrap-os/tasks/bootstrap-coreos.yml
  roles/bootstrap-os/tasks/centos.yml
  roles/bootstrap-os/tasks/clearlinux.yml
  roles/bootstrap-os/tasks/debian.yml
  roles/bootstrap-os/tasks/fedora-coreos.yml
  roles/bootstrap-os/tasks/fedora.yml
  roles/bootstrap-os/tasks/flatcar.yml
  roles/bootstrap-os/tasks/main.yml
  roles/bootstrap-os/tasks/opensuse-leap.yml
  roles/bootstrap-os/tasks/opensuse-tumbleweed.yml
  roles/bootstrap-os/tasks/opensuse.yml
  roles/bootstrap-os/tasks/redhat.yml
  roles/bootstrap-os/tasks/ubuntu.yml
  roles/bootstrap-os/vars/fedora-coreos.yml
  roles/bootstrap-os/vars/flatcar.yml
Labels: cncf-cla: yes, size/L, lgtm, approved, kind/cleanup, kind/design

#10999 kubespray-defaults: regenerate checksums and bump various versions
  roles/kubespray-defaults/defaults/main/checksums.yml
  roles/kubespray-defaults/defaults/main/download.yml
Labels: cncf-cla: yes, size/XL, lgtm, ok-to-test, approved, kind/feature

#11035 [kubernetes] Add hashes for kubernetes 1.29.3, 1.28.8, 1.27.12
  README.md
  inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
  roles/kubespray-defaults/defaults/main/checksums.yml
  roles/kubespray-defaults/defaults/main/main.yml
Labels: cncf-cla: yes, size/M, lgtm, approved, kind/feature

#11031 Change hard-coded URLs to use variables for easier offline deployment
  inventory/sample/group_vars/all/offline.yml
  roles/kubespray-defaults/defaults/main/download.yml
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved

#11010 Cleanup of kubernetes/preinstall
  roles/bootstrap-os/tasks/fedora.yml
  roles/kubernetes/preinstall/defaults/main.yml
  roles/kubernetes/preinstall/tasks/0020-set_facts.yml
  roles/kubernetes/preinstall/tasks/0070-system-packages.yml
Labels: cncf-cla: yes, size/M, lgtm, approved, kind/cleanup
