Repository kubernetes-sigs/kubespray, pull requests merged in 2024-11, with the labels that each got.

#11668 [cert-manager] upgrade to v1.15.3
  README.md
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/cert-manager.crds.yml.j2
  roles/kubernetes-apps/ingress_controller/cert_manager/templates/cert-manager.yml.j2
  roles/kubespray-defaults/defaults/main/download.yml
Labels: cncf-cla: yes, size/XXL, lgtm, ok-to-test, approved, release-note, kind/feature

#11629 [2.25] Update KUBESPRAY_VERSION in galaxy.yml to v2.25.2 and Update Readme.md to v2.25.1
  README.md
  galaxy.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/cleanup, release-note-none

#11677 etcd: throttle restart for availability
  roles/etcd/handlers/main.yml
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, ok-to-test, approved, release-note

#11667 Remove `shell` module usage from CI testcases
  tests/testcases/030_check-network.yml
  tests/testcases/040_check-network-adv.yml
Labels: cncf-cla: yes, size/L, lgtm, ok-to-test, approved, kind/cleanup, release-note-none, tide/merge-method-merge, ci-extended

#11633 Cleanup: remove in-tree cloud provider support
  README.md
  contrib/terraform/openstack/README.md
  docs/_sidebar.md
  docs/advanced/gcp-lb.md
  docs/ansible/vars.md
  docs/cloud_controllers/openstack.md
  docs/cloud_controllers/vsphere.md
  docs/cloud_providers/aws.md
  docs/cloud_providers/azure.md
  docs/cloud_providers/cloud.md
  inventory/sample/group_vars/all/all.yml
  inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
  roles/kubernetes-apps/cloud_controller/oci/defaults/main.yml
  roles/kubernetes-apps/cloud_controller/oci/tasks/credentials-check.yml
  roles/kubernetes-apps/cloud_controller/oci/tasks/main.yml
  roles/kubernetes-apps/cloud_controller/oci/templates/controller-manager-config.yml.j2
  roles/kubernetes-apps/cloud_controller/oci/templates/oci-cloud-provider.yml.j2
  roles/kubernetes-apps/cluster_roles/files/oci-rbac.yml
  roles/kubernetes-apps/cluster_roles/tasks/main.yml
  roles/kubernetes-apps/cluster_roles/tasks/oci.yml
  roles/kubernetes-apps/external_cloud_controller/meta/main.yml
  roles/kubernetes-apps/meta/main.yml
  roles/kubernetes-apps/persistent_volumes/meta/main.yml
  roles/kubernetes-apps/persistent_volumes/openstack/defaults/main.yml
  roles/kubernetes-apps/persistent_volumes/openstack/tasks/main.yml
  roles/kubernetes-apps/persistent_volumes/openstack/templates/openstack-storage-class.yml.j2
  roles/kubernetes/control-plane/defaults/main/main.yml
  roles/kubernetes/control-plane/templates/kubeadm-config.v1beta3.yaml.j2
  roles/kubernetes/kubeadm/defaults/main.yml
  roles/kubernetes/node/defaults/main.yml
  roles/kubernetes/node/tasks/cloud-credentials/azure-credential-check.yml
  roles/kubernetes/node/tasks/cloud-credentials/openstack-credential-check.yml
  roles/kubernetes/node/tasks/cloud-credentials/vsphere-credential-check.yml
  roles/kubernetes/node/tasks/main.yml
  roles/kubernetes/node/templates/cloud-configs/aws-cloud-config.j2
  roles/kubernetes/node/templates/cloud-configs/azure-cloud-config.j2
  roles/kubernetes/node/templates/cloud-configs/gce-cloud-config.j2
  roles/kubernetes/node/templates/cloud-configs/openstack-cloud-config.j2
  roles/kubernetes/node/templates/cloud-configs/vsphere-cloud-config.j2
  roles/kubernetes/node/templates/kubelet.env.v1beta1.j2
  roles/kubernetes/preinstall/tasks/0020-set_facts.yml
  roles/kubernetes/preinstall/tasks/0040-verify-settings.yml
  roles/kubespray-defaults/defaults/main/main.yml
  roles/network_plugin/calico/tasks/check.yml
  roles/network_plugin/calico/tasks/pre.yml
  tests/testcases/040_check-network-adv.yml
Labels: cncf-cla: yes, size/XXL, lgtm, ok-to-test, approved, release-note-action-required, kind/documentation, kind/cleanup, tide/merge-method-merge

#11688 Simplify package selection + fix openEuler package
  roles/kubernetes/preinstall/files/pkgs-schema.json
  roles/kubernetes/preinstall/tasks/0040-verify-settings.yml
  roles/kubernetes/preinstall/tasks/0070-system-packages.yml
  roles/kubernetes/preinstall/vars/main.yml
Labels: kind/bug, cncf-cla: yes, size/L, lgtm, ok-to-test, approved, release-note, kind/cleanup, tide/merge-method-merge, ci-extended

#11691 Fix coredns version constraint
  roles/kubespray-defaults/defaults/main/download.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note-none

#11692 Add a new crio_root variable in order to store CRI-O data on somethin…
  roles/container-engine/cri-o/defaults/main.yml
  roles/container-engine/cri-o/templates/crio.conf.j2
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note, kind/feature

#11558 Add support to use exisitng fips with terraform openstack
  contrib/terraform/openstack/README.md
  contrib/terraform/openstack/modules/compute/variables.tf
  contrib/terraform/openstack/modules/ips/main.tf
  contrib/terraform/openstack/modules/ips/outputs.tf
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, release-note, kind/feature

#11693 preinstall: fix checking that excluded host are cached
  roles/kubernetes/preinstall/tasks/0040-verify-settings.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note

#11657 Adds `nodelocaldns_additional_configs` to facilitate additional CoreDNS config options
  docs/advanced/dns-stack.md
  roles/kubernetes-apps/ansible/defaults/main.yml
  roles/kubernetes-apps/ansible/templates/nodelocaldns-config.yml.j2
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, release-note, kind/feature

#11695 Bump: pause container upgrade to 3.10
  roles/kubespray-defaults/defaults/main/download.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note, kind/feature

#11701 Disable blank issue option in Github UI
  .github/ISSUE_TEMPLATE/config.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note-none, ci-short

#11702 Remove no_log in CI tests
  tests/testcases/015_check-nodes-ready.yml
  tests/testcases/020_check-pods-running.yml
  tests/testcases/030_check-network.yml
  tests/testcases/040_check-network-adv.yml
  tests/testcases/roles/cluster-dump/tasks/main.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/cleanup, release-note-none, ci-short

#11703 remove nameless extraArgs entry
  roles/kubernetes/control-plane/templates/kubeadm-config.v1beta4.yaml.j2
  roles/kubernetes/kubeadm/tasks/kubeadm_etcd_node.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note

#11709 Remove deprecated key from kubeadmconfig/v1beta4
  roles/kubernetes/control-plane/templates/kubeadm-config.v1beta4.yaml.j2
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note

#11530 [CI] Use Kubernetes GC to clean kubevirt VMs (packet-* jobs)
  .gitlab-ci.yml
  .gitlab-ci/packet.yml
  tests/Makefile
  tests/cloud_playbooks/cleanup-packet.yml
  tests/cloud_playbooks/create-packet.yml
  tests/cloud_playbooks/delete-packet.yml
  tests/cloud_playbooks/roles/cleanup-packet-ci/tasks/main.yml
  tests/cloud_playbooks/roles/packet-ci/tasks/cleanup-old-vms.yml
  tests/cloud_playbooks/roles/packet-ci/tasks/create-vms.yml
  tests/cloud_playbooks/roles/packet-ci/tasks/delete-vms.yml
  tests/cloud_playbooks/roles/packet-ci/tasks/main.yml
  tests/cloud_playbooks/roles/packet-ci/templates/inventory.j2
  tests/cloud_playbooks/roles/packet-ci/templates/vm.yml.j2
  tests/cloud_playbooks/roles/packet-ci/vars/main.yml
  tests/common/_kubespray_test_settings.yml
  tests/common_vars.yml
  tests/scripts/testcases_cleanup.sh
  tests/scripts/testcases_run.sh
Labels: cncf-cla: yes, size/XL, lgtm, ok-to-test, approved, kind/feature, release-note-none, tide/merge-method-merge, ci-extended

#11710 Stricter kubeadm validation (config and runtime checks)
  roles/download/tasks/prep_kubeadm_images.yml
  roles/kubernetes/control-plane/tasks/kubeadm-secondary.yml
  roles/kubernetes/control-plane/tasks/kubeadm-setup.yml
  roles/kubernetes/control-plane/tasks/kubeadm-upgrade.yml
  roles/kubernetes/control-plane/templates/kubeadm-controlplane.yaml.j2
  roles/kubernetes/kubeadm/tasks/kubeadm_etcd_node.yml
  roles/kubernetes/kubeadm/tasks/main.yml
  roles/kubernetes/kubeadm/templates/kubeadm-client.conf.j2
  roles/kubernetes/kubeadm_common/defaults/main.yml
  tests/files/packet_ubuntu22-calico-all-in-one.yml
  tests/files/packet_ubuntu24-calico-etcd-datastore.yml
Labels: cncf-cla: yes, size/L, lgtm, ok-to-test, approved, release-note-action-required, kind/cleanup

#11707 Include scripts and conf files in the ansible collection
  galaxy.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note

#11714 fix task naming in bootstrap-os
  roles/bootstrap-os/tasks/clear-linux-os.yml
  roles/bootstrap-os/tasks/rhel.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note

#11694 Fix pretty-printing of coredns and nodelocaldns configmaps
  roles/kubernetes-apps/ansible/templates/coredns-config.yml.j2
  roles/kubernetes-apps/ansible/templates/nodelocaldns-config.yml.j2
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, ok-to-test, approved, release-note

#11724 Bump version of community.general
  galaxy.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note

#11620 Partial Cilium 1.16+ Support & Add vars for configuring cilium IP load balancer pools and bgp v1 & v2 apis
  docs/CNI/cilium.md
  inventory/sample/group_vars/k8s_cluster/k8s-net-cilium.yml
  roles/kubespray-defaults/defaults/main/main.yml
  roles/network_plugin/cilium/defaults/main.yml
  roles/network_plugin/cilium/tasks/apply.yml
  roles/network_plugin/cilium/templates/cilium-operator/cr.yml.j2
  roles/network_plugin/cilium/templates/cilium-operator/deploy.yml.j2
  roles/network_plugin/cilium/templates/cilium/cilium-bgp-advertisement.yml.j2
  roles/network_plugin/cilium/templates/cilium/cilium-bgp-cluster-config.yml.j2
  roles/network_plugin/cilium/templates/cilium/cilium-bgp-node-config-override.yml.j2
  roles/network_plugin/cilium/templates/cilium/cilium-bgp-peer-config.yml.j2
  roles/network_plugin/cilium/templates/cilium/cilium-bgp-peering-policy.yml.j2
  roles/network_plugin/cilium/templates/cilium/cilium-loadbalancer-ip-pool.yml.j2
  roles/network_plugin/cilium/templates/cilium/config.yml.j2
  roles/network_plugin/cilium/templates/cilium/cr.yml.j2
  roles/network_plugin/cilium/templates/cilium/ds.yml.j2
Labels: cncf-cla: yes, size/XL, lgtm, ok-to-test, approved, release-note, kind/feature

#11744 Update rockylinux9 base image to 9.5
  test-infra/image-builder/roles/kubevirt-images/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note, kind/failing-test

#11741 Fix the format of the list of images extracted from kubeadm
  roles/download/tasks/prep_kubeadm_images.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note

#11736 Update README.md to fix several doc links for OpenStack and vSphere
  README.md
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/documentation, release-note-none

#11737 Bump: Kubernetes default version v1.31.3
  README.md
  roles/kubespray-defaults/defaults/main/checksums.yml
  roles/kubespray-defaults/defaults/main/main.yml
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, release-note, kind/feature

#11738 Bump: OpenStack Cloud Controller Manager to v1.31.1
  inventory/sample/group_vars/all/openstack.yml
  roles/kubespray-defaults/defaults/main/download.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note, kind/feature

#11665 Add support for ntpsec
  docs/advanced/ntp.md
  roles/kubernetes/preinstall/defaults/main.yml
  roles/kubernetes/preinstall/tasks/0081-ntp-configurations.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, release-note, kind/feature

#11748 Remove inventory_builder and re-organize docs
  .pre-commit-config.yaml
  README.md
  contrib/dind/README.md
  contrib/dind/dind-cluster.yaml
  contrib/dind/group_vars/all/all.yaml
  contrib/dind/group_vars/all/distro.yaml
  contrib/dind/hosts
  contrib/dind/kubespray-dind.yaml
  contrib/dind/requirements.txt
  contrib/dind/roles/dind-cluster/tasks/main.yaml
  contrib/dind/roles/dind-host/tasks/main.yaml
  contrib/dind/roles/dind-host/templates/inventory_builder.sh.j2
  contrib/dind/run-test-distros.sh
  contrib/dind/test-most_distros-some_CNIs.env
  contrib/dind/test-some_distros-kube_router_combo.env
  contrib/dind/test-some_distros-most_CNIs.env
  contrib/inventory_builder/inventory.py
  contrib/inventory_builder/requirements.txt
  contrib/inventory_builder/setup.cfg
  contrib/inventory_builder/setup.py
  contrib/inventory_builder/test-requirements.txt
  contrib/inventory_builder/tests/test_inventory.py
  contrib/inventory_builder/tox.ini
  docs/_sidebar.md
  docs/ansible/ansible.md
  docs/ansible/inventory.md
  docs/getting_started/getting-started.md
  docs/getting_started/setting-up-your-first-cluster.md
  docs/operations/mirror.md
  inventory/sample/inventory.ini
Labels: cncf-cla: yes, size/XXL, lgtm, ok-to-test, approved, release-note, kind/documentation, kind/cleanup, tide/merge-method-merge, ci-short

#11751 support asymmetric encryption algorithms in ClusterConfigration
  roles/kubernetes/control-plane/defaults/main/main.yml
  roles/kubernetes/control-plane/templates/kubeadm-config.v1beta4.yaml.j2
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note, kind/feature

#11756 Revert "support asymmetric encryption algorithms in ClusterConfigration"
  roles/kubernetes/control-plane/defaults/main/main.yml
  roles/kubernetes/control-plane/templates/kubeadm-config.v1beta4.yaml.j2
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note-none, ci-short

#11755 containerd: always use config_path
  roles/container-engine/containerd/defaults/main.yml
  roles/container-engine/containerd/tasks/main.yml
  roles/container-engine/containerd/templates/config.toml.j2
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, release-note, kind/cleanup

#11754 Remove leftover CI for ansible-core 2.11 (apparently)
  tests/files/packet_ubuntu20-calico-all-in-one-ansible-2_11.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/cleanup, release-note-none, ci-short

#11757 Support Configuring EncryptionAlgorithm in Kubeadm v1beta4
  roles/kubernetes/control-plane/templates/kubeadm-config.v1beta4.yaml.j2
  roles/kubernetes/kubeadm/tasks/main.yml
  roles/kubespray-defaults/defaults/main/main.yml
  tests/files/packet_debian12-calico.yml
  tests/files/packet_rockylinux9-cilium.yml
  tests/files/packet_ubuntu20-flannel-ha.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, release-note, kind/feature

#11759 Remove jsonschema from dependencies
  requirements.txt
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/cleanup, release-note-none

#11760 Remove pip and rpm packaging support
  contrib/packaging/rpm/kubespray.spec
  setup.cfg
  setup.py
Labels: cncf-cla: yes, size/L, lgtm, ok-to-test, approved, release-note, kind/cleanup, ci-short
