Repository kubernetes-sigs/kubespray, pull requests merged in 2024-04, with the labels that each got.

#11028 configure crio to use kube reserved cgroup
  roles/container-engine/cri-o/tasks/main.yaml
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, ok-to-test, approved

#11036 [etcd] make etcd 3.5.12 default
  README.md
  roles/kubespray-defaults/defaults/main/download.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/feature

#11042 revert crictl version
  roles/kubespray-defaults/defaults/main/download.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved

#11016 Remove access to cluster from anonymous users
  docs/vars.md
  inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
  roles/kubernetes/control-plane/defaults/main/main.yml
  roles/kubernetes/control-plane/tasks/kubeadm-secondary.yml
  roles/kubernetes/control-plane/tasks/kubeadm-setup.yml
  roles/kubernetes/control-plane/tasks/kubeadm-upgrade.yml
  roles/kubernetes/control-plane/templates/kubeadm-controlplane.v1beta3.yaml.j2
  roles/kubernetes/kubeadm/defaults/main.yml
  roles/kubernetes/kubeadm/tasks/main.yml
  roles/kubernetes/kubeadm/templates/kubeadm-client.conf.v1beta3.j2
  roles/kubespray-defaults/defaults/main/main.yml
  tests/files/packet_debian11-calico-upgrade.yml
  tests/files/packet_ubuntu20-calico-all-in-one-hardening.yml
  tests/files/packet_ubuntu20-calico-etcd-kubeadm.yml
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/feature

#11022 Fix calico host local ipam
  roles/network_plugin/calico/templates/calico-node.yml.j2
  roles/network_plugin/calico/templates/calico-typha.yml.j2
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved

#11068 Document "Remove access to cluster from anonymous users"
  docs/hardening.md
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/documentation

#11058 change debian12 network manage service from networking to systemd-netw…
  roles/reset/defaults/main.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#11070 Update kubelet-csr-approver to v1.1.0
  roles/kubernetes-apps/kubelet-csr-approver/defaults/main.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#11041 Update Volume Snapshot Controller to 7.0.2
  roles/kubernetes-apps/snapshots/snapshot-controller/templates/rbac-snapshot-controller.yml.j2
  roles/kubernetes-apps/snapshots/snapshot-controller/templates/snapshot-controller.yml.j2
  roles/kubespray-defaults/defaults/main/download.yml
Labels: kind/bug, cncf-cla: yes, size/M, lgtm, ok-to-test, approved

#11061 Update kubelet systemd service default allowed IP addresses for cluster hardening
  docs/hardening.md
  roles/kubernetes/node/defaults/main.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#11073 fix kubespray-defaults: Check for kubespray.boostrap-os FQCN
  roles/kubespray-defaults/tasks/main.yaml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#11074 fix reset/main.yml lsattr command error when kubelet has symbolic link
  roles/reset/tasks/main.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#11075 fix python regex matching problem when finding docker packages
  roles/container-engine/docker/tasks/reset.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#11088 fix: Remove the archived debian apt repository when installing docker-engine
  roles/container-engine/docker/tasks/main.yml
Labels: cncf-cla: yes, size/S, lgtm, approved

#11044 bump skopeo version and checksum
  roles/kubespray-defaults/defaults/main/checksums.yml
  roles/kubespray-defaults/defaults/main/download.yml
  scripts/download_hash.sh
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, ok-to-test, approved

#11083 set default containerd_version to v1.7.15 and add checksums
  README.md
  roles/kubespray-defaults/defaults/main/checksums.yml
  roles/kubespray-defaults/defaults/main/download.yml
Labels: cncf-cla: yes, size/L, lgtm, ok-to-test, approved, kind/feature

#11079 feat(calico): add support filters on bgppeers per node definition
  roles/network_plugin/calico/tasks/peer_with_router.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#11077 fix: 🐛 calico-cni-plugin missing RBAC
  roles/network_plugin/calico/templates/calico-cr.yml.j2
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#11103 [containerd/tracing]: add distributed tracing config flags
  roles/container-engine/containerd/defaults/main.yml
  roles/container-engine/containerd/templates/config.toml.j2
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/feature

#11106 feat: Add support for cilium 1.15 and update cilium to v1.15.4
  README.md
  docs/cilium.md
  inventory/sample/group_vars/k8s_cluster/k8s-net-cilium.yml
  roles/kubespray-defaults/defaults/main/download.yml
  roles/network_plugin/cilium/defaults/main.yml
  roles/network_plugin/cilium/templates/cilium-operator/cr.yml.j2
  roles/network_plugin/cilium/templates/cilium/config.yml.j2
  roles/network_plugin/cilium/templates/cilium/cr.yml.j2
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved

#11111 Enclose the cpu type with quotation marks in kubelet-config.v1beta1
  roles/kubernetes/node/templates/kubelet-config.v1beta1.yaml.j2
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved

#11066 ntp: add config to filter and set ntp interfaces
  roles/kubernetes/preinstall/defaults/main.yml
  roles/kubernetes/preinstall/templates/ntp.conf.j2
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/feature

#10988 containerd: allow to configure fallback server
  docs/containerd.md
  roles/container-engine/containerd/templates/hosts.toml.j2
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/feature

#11089 fix: updating the calico-crds
  roles/network_plugin/calico/templates/calico-apiserver.yml.j2
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved

#11131 Fine grained OS packages installation
  roles/kubernetes/preinstall/defaults/main.yml
  roles/kubernetes/preinstall/files/pkgs-schema.json
  roles/kubernetes/preinstall/tasks/0020-set_facts.yml
  roles/kubernetes/preinstall/tasks/0040-verify-settings.yml
  roles/kubernetes/preinstall/tasks/0070-system-packages.yml
  roles/kubernetes/preinstall/vars/amazon.yml
  roles/kubernetes/preinstall/vars/centos.yml
  roles/kubernetes/preinstall/vars/debian-11.yml
  roles/kubernetes/preinstall/vars/debian-12.yml
  roles/kubernetes/preinstall/vars/debian.yml
  roles/kubernetes/preinstall/vars/fedora.yml
  roles/kubernetes/preinstall/vars/main.yml
  roles/kubernetes/preinstall/vars/redhat.yml
  roles/kubernetes/preinstall/vars/suse.yml
  roles/kubernetes/preinstall/vars/ubuntu.yml
Labels: cncf-cla: yes, size/L, lgtm, approved, kind/design, tide/merge-method-merge

#11141 Add Calico v3.27.3 and make it default
  README.md
  roles/kubespray-defaults/defaults/main/checksums.yml
  roles/kubespray-defaults/defaults/main/download.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature

#11034 ingress-nginx: added ability to enable opentelemetry nginx module
  roles/kubernetes-apps/ingress_controller/ingress_nginx/defaults/main.yml
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/ds-ingress-nginx-controller.yml.j2
  roles/kubespray-defaults/defaults/main/download.yml
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved

#11142 [containerd] add hashes for versions '1.6.30-31', 'v1.7.16' and make v1.7.16 default
  README.md
  roles/kubespray-defaults/defaults/main/checksums.yml
  roles/kubespray-defaults/defaults/main/download.yml
Labels: cncf-cla: yes, size/S, lgtm, approved, kind/container-managers
