Repository kubernetes-sigs/kubespray, pull requests merged in 2024-12, with the labels that each got.

#11761 Remove some leftover from removed mitogen support
  Makefile
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/cleanup, release-note-none, ci-short

#11758 Optimize CA cert hash calculation with community.crypto
  galaxy.yml
  requirements.txt
  roles/kubernetes/control-plane/defaults/main/main.yml
  roles/kubernetes/kubeadm/tasks/main.yml
  roles/kubernetes/kubeadm/templates/kubeadm-client.conf.j2
  roles/kubespray-defaults/defaults/main/main.yml
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, release-note, kind/cleanup

#11767 Fix sample inventory kube_version to 1.31.3
  inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature, release-note-none

#11770 calico: stop recording calico_kubelet_name
  roles/network_plugin/calico/tasks/pre.yml
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, ok-to-test, approved, release-note

#11771 updated link for migrate_docker2containerd.md
  docs/operations/upgrades.md
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/documentation, release-note-none, ci-short

#11781 containerd: add After=dbus.service
  roles/container-engine/containerd/templates/containerd.service.j2
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/cleanup, release-note-none

#11786 Remove testfiles which are not used in the CI.
  docs/developers/ci.md
  tests/files/packet_centos8-calico-ha-once-localhost.yml
  tests/files/packet_centos8-calico-ha.yml
  tests/files/packet_centos8-flannel-addons-ha.yml
  tests/files/packet_centos8-multus-calico.yml
  tests/files/packet_centos8-weave-upgrade-ha.yml
  tests/files/packet_ubuntu20-docker-weave-sep.yml
  tests/files/packet_ubuntu22-all-in-one-docker.yml
  tests/files/packet_ubuntu24-all-in-one-docker.yml
  tests/files/packet_ubuntu24-calico-all-in-one.yml
  tests/files/vagrant_centos8-kube-router.rb
  tests/files/vagrant_centos8-kube-router.yml
  tests/files/vagrant_ubuntu20-weave-medium.rb
  tests/files/vagrant_ubuntu20-weave-medium.yml
Labels: cncf-cla: yes, size/L, lgtm, ok-to-test, approved, kind/cleanup, release-note-none, tide/merge-method-merge, ci-extended

#11796 CI: remove IDEMPOT_CHECK
  .gitlab-ci.yml
  tests/scripts/testcases_run.sh
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/cleanup, release-note-none, ci-short

#11779 apiserver: fix incorrect path to admission plugins config files
  roles/kubernetes/control-plane/templates/admission-controls.yaml.j2
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note

#11797 CI: build collection before runnings tests
  .gitlab-ci/packet.yml
  tests/files/packet_debian11-calico-collection.yml
  tests/scripts/testcases_run.sh
Labels: kind/bug, cncf-cla: yes, size/M, lgtm, ok-to-test, approved, release-note-none, tide/merge-method-merge

#11792 Fix flakey test + cleanup in testcases/030-checknetwork
  tests/testcases/030_check-network.yml
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/flake, release-note-none, tide/merge-method-merge

#11700 Convert kubernetes-apps to use kubectl directly
  roles/kubernetes-apps/ansible/tasks/coredns.yml
  roles/kubernetes-apps/ansible/tasks/dashboard.yml
  roles/kubernetes-apps/ansible/tasks/etcd_metrics.yml
  roles/kubernetes-apps/ansible/tasks/main.yml
  roles/kubernetes-apps/ansible/tasks/netchecker.yml
  roles/kubernetes-apps/ansible/tasks/nodelocaldns.yml
  roles/kubernetes-apps/ansible/templates/dashboard.yml.j2
  roles/kubernetes-apps/ansible/vars/main.yml
  roles/kubernetes-apps/defaults/main.yml
  roles/kubernetes-apps/vars/main.yml
Labels: cncf-cla: yes, size/L, lgtm, ok-to-test, approved, release-note-none, kind/design, tide/merge-method-merge

#11805 remove legacy kubelet container pre-upgrade tasks
  roles/kubernetes/node/tasks/main.yml
  roles/kubernetes/node/tasks/pre_upgrade.yml
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/cleanup, release-note-none

#11803 Fix Ansible example values for OpenStack controller
  docs/cloud_controllers/openstack.md
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/documentation, release-note-none, ci-short

#11808 Revert "apiserver: fix incorrect path to admission plugins config files (#11779)"
  roles/kubernetes/control-plane/templates/admission-controls.yaml.j2
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note-none

#11809 CI: test hardening setup in normal CI run
  .gitlab-ci/packet.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature, release-note-none

#11816 Add iproute(2) package checking
  roles/bootstrap-os/tasks/amzn.yml
  roles/bootstrap-os/tasks/centos.yml
  roles/bootstrap-os/tasks/clear-linux-os.yml
  roles/bootstrap-os/tasks/debian.yml
  roles/bootstrap-os/tasks/fedora.yml
  roles/bootstrap-os/tasks/opensuse.yml
  roles/bootstrap-os/tasks/rhel.yml
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, release-note, kind/feature

#11814 Add ResourceQuota plugin configuration
  roles/kubernetes/control-plane/defaults/main/main.yml
  roles/kubernetes/control-plane/templates/resourcequota.yaml.j2
  roles/kubernetes/control-plane/vars/main.yaml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, release-note, kind/feature

#11818 Update ansible-lint pre-commit + drop jsonschema dep
  .pre-commit-config.yaml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/cleanup, release-note-none, ci-short

#11817 Only consider host in 'k8s_cluster' when checking if ip is a cached fact
  roles/kubernetes/preinstall/tasks/0040-verify-settings.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note

#11678 Fix using the default network manager in reset.yml
  roles/reset/defaults/main.yml
  roles/reset/tasks/main.yml
Labels: kind/bug, cncf-cla: yes, size/M, lgtm, ok-to-test, approved, release-note

#11828 Bump: Kubernetes default version v1.31.4
  README.md
  inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
  roles/kubespray-defaults/defaults/main/checksums.yml
  roles/kubespray-defaults/defaults/main/main.yml
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, release-note, kind/feature

#11798 [calico] Add version 3.29.1 and make it default
  README.md
  roles/kubespray-defaults/defaults/main/checksums.yml
  roles/kubespray-defaults/defaults/main/download.yml
  roles/network_plugin/calico/templates/calico-apiserver.yml.j2
  roles/network_plugin/calico/templates/calico-cr.yml.j2
Labels: cncf-cla: yes, size/L, lgtm, ok-to-test, approved, release-note, kind/feature

#11832 Bump: Helm upgrade to v3.16.4
  README.md
  roles/kubespray-defaults/defaults/main/checksums.yml
  roles/kubespray-defaults/defaults/main/download.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, release-note, kind/feature

#11827 Update SECURITY_CONTACTS with active maintainers
  SECURITY_CONTACTS
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/documentation, release-note-none, ci-short

#11833 Bump: Containerd upgrade to 1.7.24 & runc upgrade to v1.2.3
  README.md
  roles/kubespray-defaults/defaults/main/checksums.yml
  roles/kubespray-defaults/defaults/main/download.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, release-note, kind/feature, kind/container-managers

#11819 Cleanups in kubernetes/preinstall (DNS stuff)
  roles/container-engine/docker/tasks/set_facts_dns.yml
  roles/kubernetes-apps/ansible/tasks/main.yml
  roles/kubernetes-apps/ansible/templates/coredns-config.yml.j2
  roles/kubernetes/preinstall/defaults/main.yml
  roles/kubernetes/preinstall/tasks/0020-set_facts.yml
  roles/kubernetes/preinstall/tasks/0040-verify-settings.yml
  roles/kubernetes/preinstall/tasks/0060-resolvconf.yml
  roles/kubernetes/preinstall/tasks/0063-networkmanager-dns.yml
  roles/kubernetes/preinstall/tasks/0100-dhclient-hooks.yml
  roles/kubernetes/preinstall/templates/resolved.conf.j2
  roles/kubernetes/preinstall/vars/main.yml
  roles/kubespray-defaults/defaults/main/main.yml
Labels: cncf-cla: yes, size/L, lgtm, ok-to-test, approved, kind/cleanup, release-note-none, tide/merge-method-merge

#11793 Use debug stdout callback in ci rather than manual debug
  .gitlab-ci.yml
  tests/testcases/010_check-apiserver.yml
  tests/testcases/015_check-nodes-ready.yml
  tests/testcases/020_check-pods-running.yml
  tests/testcases/030_check-network.yml
  tests/testcases/040_check-network-adv.yml
Labels: cncf-cla: yes, size/L, lgtm, ok-to-test, approved, kind/cleanup, release-note-none, tide/merge-method-merge

#11844 Add option to skip network plugin installation
  roles/kubernetes/preinstall/tasks/0040-verify-settings.yml
  roles/network_plugin/meta/main.yml
Labels: cncf-cla: yes, size/S, lgtm, approved, release-note, kind/feature
