Repository kubernetes-sigs/kubespray, pull requests merged in 2024-09, with the labels that each got.

#11492 upgrade nerdctl to v1.7.6
  roles/kubespray-defaults/defaults/main/checksums.yml
  roles/kubespray-defaults/defaults/main/download.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, release-note

#11493 Remove systemd version + ostree check for docker TasksMax
  roles/container-engine/docker/tasks/systemd.yml
  roles/container-engine/docker/templates/docker.service.j2
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, release-note, kind/cleanup

#11499 Allow for configuring etcd progress notify interval
  inventory/sample/group_vars/etcd.yml
  roles/etcd/defaults/main.yml
  roles/etcd/templates/etcd.env.j2
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note, kind/feature

#11246 Drop support for RHEL 7 / CentOS 7
  README.md
  Vagrantfile
  contrib/dind/group_vars/all/distro.yaml
  docs/CNI/calico.md
  docs/CRI/docker.md
  docs/developers/ci.md
  docs/developers/vagrant.md
  docs/operating_systems/centos.md
  inventory/sample/group_vars/all/offline.yml
  playbooks/ansible_version.yml
  roles/bootstrap-os/molecule/default/molecule.yml
  roles/bootstrap-os/tasks/centos.yml
  roles/bootstrap-os/tasks/redhat.yml
  roles/container-engine/docker-storage/defaults/main.yml
  roles/container-engine/docker-storage/files/install_container_storage_setup.sh
  roles/container-engine/docker-storage/tasks/main.yml
  roles/container-engine/docker-storage/templates/docker-storage-setup.j2
  roles/container-engine/docker/meta/main.yml
  roles/container-engine/docker/templates/docker.service.j2
  roles/kubernetes-apps/container_engine_accelerator/nvidia_gpu/vars/centos-7.yml
  roles/kubernetes/preinstall/defaults/main.yml
  roles/kubernetes/preinstall/tasks/0120-growpart-azure-centos-7.yml
  roles/kubernetes/preinstall/tasks/main.yml
  roles/kubernetes/preinstall/vars/main.yml
  roles/kubespray-defaults/defaults/main/main.yml
  test-infra/image-builder/roles/kubevirt-images/defaults/main.yml
  tests/cloud_playbooks/roles/packet-ci/defaults/main.yml
  tests/files/packet_centos8-calico-ha-once-localhost.yml
  tests/files/packet_centos8-calico-ha.yml
  tests/files/packet_centos8-flannel-addons-ha.yml
  tests/files/packet_centos8-multus-calico.yml
  tests/files/packet_centos8-weave-upgrade-ha.yml
  tests/files/vagrant_centos8-kube-router.rb
  tests/files/vagrant_centos8-kube-router.yml
Labels: cncf-cla: yes, size/L, lgtm, ok-to-test, approved, release-note-action-required, kind/cleanup

#11508 boostrap-os: use import_tasks instead of symlinks
  roles/bootstrap-os/tasks/debian.yml
  roles/bootstrap-os/tasks/openEuler.yml
  roles/bootstrap-os/tasks/opensuse-leap.yml
  roles/bootstrap-os/tasks/opensuse-tumbleweed.yml
  roles/bootstrap-os/tasks/ubuntu.yml
Labels: kind/bug, cncf-cla: yes, size/M, lgtm, ok-to-test, approved, release-note

#11511 Update KUBESPRAY_VERSION in CI and Readme for v2.26.0
  .gitlab-ci.yml
  README.md
  galaxy.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, release-note, kind/flake

#11394 Cleanup master terminology (start fixing issue #11353)
  contrib/terraform/openstack/README.md
  docs/ansible/ansible.md
  docs/operations/etcd.md
  extra_playbooks/migrate_openstack_provider.yml
  extra_playbooks/upgrade-only-k8s.yml
  inventory/sample/group_vars/all/all.yml
  inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
  playbooks/remove_node.yml
  playbooks/upgrade_cluster.yml
  roles/etcd/handlers/main.yml
  roles/etcd/tasks/configure.yml
  roles/etcd/tasks/main.yml
  roles/etcd/tasks/refresh_config.yml
  roles/kubernetes-apps/metrics_server/tasks/main.yml
  roles/kubernetes-apps/metrics_server/templates/metrics-server-deployment.yaml.j2
  roles/kubernetes/control-plane/defaults/main/main.yml
  roles/kubernetes/control-plane/handlers/main.yml
  roles/kubernetes/control-plane/tasks/encrypt-at-rest.yml
  roles/kubernetes/control-plane/tasks/kubeadm-fix-apiserver.yml
  roles/kubernetes/control-plane/tasks/kubeadm-setup.yml
  roles/kubernetes/control-plane/tasks/kubeadm-upgrade.yml
  roles/kubernetes/control-plane/tasks/kubelet-fix-client-cert-rotation.yml
  roles/kubernetes/control-plane/tasks/pre-upgrade.yml
  roles/kubernetes/kubeadm/tasks/main.yml
  roles/kubernetes/node/defaults/main.yml
  roles/kubernetes/node/tasks/main.yml
  roles/kubernetes/node/templates/kubelet-config.v1beta1.yaml.j2
  roles/kubernetes/preinstall/tasks/0040-verify-settings.yml
  roles/kubernetes/preinstall/tasks/0050-create_directories.yml
  roles/kubernetes/tokens/tasks/check-tokens.yml
  roles/kubernetes/tokens/tasks/gen_tokens.yml
  roles/kubespray-defaults/defaults/main/main.yml
  roles/kubespray-defaults/tasks/no_proxy.yml
  roles/network_plugin/calico/templates/calico-node.yml.j2
  roles/recover_control_plane/control-plane/tasks/main.yml
  roles/remove-node/post-remove/tasks/main.yml
  tests/scripts/testcases_run.sh
Labels: cncf-cla: yes, size/L, lgtm, ok-to-test, approved, release-note, kind/cleanup, ci-extended

#11434 Update multus to v4.1.0 and clarify cilium compatibility
  docs/CNI/multus.md
  roles/kubernetes-apps/network_plugin/multus/tasks/main.yml
  roles/kubespray-defaults/defaults/main/download.yml
  roles/network_plugin/multus/defaults/main.yml
  roles/network_plugin/multus/templates/multus-daemonset.yml.j2
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, release-note, kind/feature

#11512 Add favicon in Kubespray website
  index.html
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/documentation, release-note-none

#11277 Fix openssl SAN check on newer versions of OpenSSL
  roles/kubernetes/control-plane/tasks/kubeadm-setup.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note-none

#11513 Refactor and expand download_hash.py
  scripts/download_hash.py
Labels: cncf-cla: yes, size/L, lgtm, ok-to-test, approved, kind/feature, release-note-none, tide/merge-method-merge

#11525 Remove refs to rhel7 in Vagrantfile
  Vagrantfile
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/cleanup, release-note-none

#11516 [2.24] Update to last patch versions (crio, kubernetes, containerd, runc, nerdctl, etcd)
  .gitlab-ci.yml
  .gitlab-ci/molecule.yml
  .gitlab-ci/terraform.yml
  .gitlab-ci/vagrant.yml
  README.md
  Vagrantfile
  pipeline.Dockerfile
  roles/kubespray-defaults/defaults/main/checksums.yml
  roles/kubespray-defaults/defaults/main/download.yml
  roles/kubespray-defaults/defaults/main/main.yml
  tests/Makefile
  tests/files/vagrant_ubuntu20-flannel.rb
  tests/files/vagrant_ubuntu20-flannel.yml
  tests/scripts/vagrant-install.sh
Labels: cncf-cla: yes, size/XL, lgtm, ok-to-test, approved, release-note, kind/api-change, tide/merge-method-merge

#11441 fix: Swap roles kubespray-defaults & bootstrap-os
  docs/operating_systems/bootstrap-os.md
  playbooks/facts.yml
  roles/kubespray-defaults/tasks/main.yaml
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, ok-to-test, approved, release-note

#11526 Remove useless file
  run.rc
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/cleanup, release-note-none

#11534 Fix: download hash crictl link
  scripts/download_hash.py
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note-none

#11411 Fix CI: elastx cleanup security groups
  scripts/openstack-cleanup/main.py
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, release-note

#11550 Move the CRI endpoint setting to kubelet config
  roles/kubernetes/node/templates/kubelet-config.v1beta1.yaml.j2
  roles/kubernetes/node/templates/kubelet.env.v1beta1.j2
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/cleanup, release-note-none

#11544 Allow setting annotations on ingress-nginx service
  inventory/sample/group_vars/k8s_cluster/addons.yml
  roles/kubernetes-apps/ingress_controller/ingress_nginx/defaults/main.yml
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/svc-ingress-nginx.yml.j2
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note, kind/feature

#11551 [2.24] Update KUBESPRAY_VERSION in galaxy.yml to v2.24.4 and Update Readme.md to v2.24.3
  README.md
  galaxy.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, release-note, kind/flake

#11529 Remove unused test infrastructure
  tests/run-tests.sh
  tests/shebang-unit
Labels: cncf-cla: yes, size/XXL, lgtm, ok-to-test, approved, kind/cleanup, release-note-none

#11535 CI: cleanup '-scale' tests infra
  docs/developers/test_cases.md
  tests/cloud_playbooks/roles/packet-ci/templates/inventory.j2
  tests/cloud_playbooks/roles/packet-ci/vars/main.yml
  tests/scripts/testcases_run.sh
  tests/templates/fake_hosts.yml.j2
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/cleanup, release-note-none

#11471 Update the list of admission plugins which needs config
  roles/kubernetes/control-plane/tasks/kubeadm-setup.yml
  roles/kubernetes/control-plane/vars/main.yaml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, release-note, kind/feature, tide/merge-method-merge

#11527 Cleanup Vagrantfile and allow to use multiples inventories
  Vagrantfile
  docs/developers/vagrant.md
  tests/Makefile
Labels: cncf-cla: yes, size/L, lgtm, ok-to-test, approved, kind/feature, kind/cleanup, release-note-none, tide/merge-method-merge

#11501 Make sure the Reset cleanup is more complete
  roles/reset/tasks/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note

#11521 Use in inventory variables rather than patch files for kubeadm_patches
  docs/ansible/vars.md
  inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
  inventory/sample/patches/kube-controller-manager+merge.yaml
  inventory/sample/patches/kube-scheduler+merge.yaml
  roles/kubernetes/control-plane/meta/main.yml
  roles/kubernetes/control-plane/tasks/kubeadm-setup.yml
  roles/kubernetes/control-plane/tasks/kubeadm-upgrade.yml
  roles/kubernetes/control-plane/templates/kubeadm-config.v1beta3.yaml.j2
  roles/kubernetes/control-plane/templates/kubeadm-controlplane.v1beta3.yaml.j2
  roles/kubernetes/kubeadm/meta/main.yml
  roles/kubernetes/kubeadm/tasks/main.yml
  roles/kubernetes/kubeadm/templates/kubeadm-client.conf.v1beta3.j2
  roles/kubernetes/kubeadm_common/defaults/main.yml
  roles/kubernetes/kubeadm_common/tasks/main.yml
  tests/files/packet_ubuntu24-calico-etcd-datastore.yml
Labels: cncf-cla: yes, size/L, lgtm, ok-to-test, approved, release-note-action-required, kind/feature, tide/merge-method-merge

#10643 Refactor kubernetes/node templates
  docs/ansible/vars.md
  roles/kubernetes/node/defaults/main.yml
  roles/kubernetes/node/templates/kubelet-config.v1beta1.yaml.j2
  roles/kubernetes/node/templates/kubelet.env.v1beta1.j2
  roles/kubespray-defaults/defaults/main/main.yml
  tests/files/packet_ubuntu24-calico-all-in-one.yml
Labels: cncf-cla: yes, size/L, lgtm, ok-to-test, approved, release-note-action-required, kind/cleanup, tide/merge-method-merge

#11554 update containerd 1.7.22
  README.md
  roles/kubespray-defaults/defaults/main/checksums.yml
  roles/kubespray-defaults/defaults/main/download.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note, kind/container-managers

#11533 [kubernetes] Support kubernetes 1.31.1
  README.md
  inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
  roles/container-engine/cri-o/tasks/load_vars.yml
  roles/container-engine/cri-o/vars/v1.31.yml
  roles/kubespray-defaults/defaults/main/checksums.yml
  roles/kubespray-defaults/defaults/main/download.yml
  roles/kubespray-defaults/defaults/main/main.yml
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, release-note, kind/feature

#11564 fix: vsphere image repositories, tags and docs
  docs/CSI/vsphere-csi.md
  inventory/sample/group_vars/all/vsphere.yml
  roles/kubernetes-apps/csi_driver/vsphere/defaults/main.yml
  roles/kubernetes-apps/csi_driver/vsphere/templates/vsphere-csi-controller-config.yml.j2
  roles/kubernetes-apps/csi_driver/vsphere/templates/vsphere-csi-controller-deployment.yml.j2
  roles/kubernetes-apps/csi_driver/vsphere/templates/vsphere-csi-controller-rbac.yml.j2
  roles/kubernetes-apps/csi_driver/vsphere/templates/vsphere-csi-node.yml.j2
  roles/kubernetes-apps/external_cloud_controller/vsphere/defaults/main.yml
  roles/kubernetes-apps/external_cloud_controller/vsphere/templates/external-vsphere-cloud-controller-manager-ds.yml.j2
Labels: kind/bug, cncf-cla: yes, size/M, lgtm, ok-to-test, approved, release-note

#11572 [etcd] make etcd 3.5.16 default
  README.md
  roles/kubespray-defaults/defaults/main/checksums.yml
  roles/kubespray-defaults/defaults/main/download.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, release-note, kind/feature

#11574 [runc] Make runc v1.1.14 default
  roles/kubespray-defaults/defaults/main/checksums.yml
  roles/kubespray-defaults/defaults/main/download.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note, kind/feature

#11575 [nerdctl] Make nerdctl 1.7.7 default
  roles/kubespray-defaults/defaults/main/checksums.yml
  roles/kubespray-defaults/defaults/main/download.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note, kind/feature

#11581 [kubernetes] Add hashes for kubernetes 1.29.8, 1.29.9, 1.30.5
  roles/kubespray-defaults/defaults/main/checksums.yml
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, release-note, kind/feature

#11568 Only require minimum structure in inventory, part II
  roles/kubernetes-apps/metrics_server/defaults/main.yml
  roles/kubernetes-apps/metrics_server/tasks/main.yml
  roles/kubernetes-apps/metrics_server/templates/metrics-server-deployment.yaml.j2
  roles/kubernetes/control-plane/templates/kubeadm-config.v1beta3.yaml.j2
  roles/kubernetes/control-plane/templates/kubeadm-controlplane.v1beta3.yaml.j2
  roles/kubernetes/node/defaults/main.yml
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/cleanup, release-note-none, tide/merge-method-merge

#11477 [doc] Add previously undocumented options in Terraform/Openstack
  contrib/terraform/openstack/README.md
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/documentation, release-note-none

#11273 Added containernetworking-plugins to fcos bootstrap packages
  roles/bootstrap-os/defaults/main.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note-none

#11570 feat(calico): add support for numAllowedLocalASNumbers on bgppeers per node definition
  docs/CNI/calico.md
  docs/calico_peer_example/new-york.yml
  docs/calico_peer_example/paris.yml
  roles/network_plugin/calico/tasks/peer_with_router.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, release-note, kind/feature

#11466 Update cluster-role for cilium to prevent errors in agent startup
  roles/network_plugin/cilium/templates/cilium/cr.yml.j2
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note

#11578 Add Fedora 39/40 images in test-infra
  test-infra/image-builder/roles/kubevirt-images/defaults/main.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/feature, release-note-none

#11230 Added variables cilium_enable_host_firewall and cilium_policy_audit_mode for configmap/cilium-config
  docs/CNI/cilium.md
  inventory/sample/group_vars/k8s_cluster/k8s-net-cilium.yml
  roles/network_plugin/cilium/defaults/main.yml
  roles/network_plugin/cilium/templates/cilium/config.yml.j2
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, release-note

#11584 [cri-o] Switch binaries to libexecdir
  roles/container-engine/cri-o/defaults/main.yml
  roles/container-engine/cri-o/tasks/main.yaml
  roles/container-engine/cri-o/tasks/reset.yml
  roles/container-engine/cri-o/vars/v1.28.yml
  roles/container-engine/cri-o/vars/v1.29.yml
  roles/container-engine/cri-o/vars/v1.31.yml
  roles/container-engine/youki/tasks/main.yml
  roles/kubespray-defaults/defaults/main/checksums.yml
  roles/kubespray-defaults/defaults/main/download.yml
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, release-note

#11585 Update containerd `containerd_max_container_log_line_size` default value to 16384
  docs/developers/ci-setup.md
  inventory/sample/group_vars/all/containerd.yml
  roles/container-engine/containerd/defaults/main.yml
  tests/common/_docker_hub_registry_mirror.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note

#11576 [2.25] Update to last patch versions (containerd, runc, nerdctl, etcd)
  README.md
  roles/kubespray-defaults/defaults/main/checksums.yml
  roles/kubespray-defaults/defaults/main/download.yml
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, release-note, kind/feature
