Repository kubernetes-sigs/kubespray, pull requests merged in 2025-07, with the labels that each got.

#12360 Replace deprecated MAINTAINER with OCI-compliant LABEL in Dockerfile
  test-infra/image-builder/roles/kubevirt-images/templates/Dockerfile
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/cleanup, release-note-none

#12346 Cilium: Pass cluster DNS to hubble.peerService in values.yaml.j2
  inventory/sample/group_vars/k8s_cluster/k8s-net-cilium.yml
  roles/network_plugin/cilium/defaults/main.yml
  roles/network_plugin/cilium/templates/values.yaml.j2
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, release-note

#12371 Adding proper quotation
  roles/kubernetes/control-plane/templates/apiserver-tracing.yaml.j2
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note-none

#12379 [CI] Add CI Image for Rocky Linux 10
  test-infra/image-builder/roles/kubevirt-images/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, release-note

#12349 Allow vagrant jobs to be triggered manually in Gitlab UI
  .gitlab-ci/vagrant.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/feature, release-note-none

#12380 Fix kubespray reset shouldn't remove /etc/dnsmasq files
  roles/reset/tasks/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note

#12368 Add header configuration in containerd hosts.toml
  inventory/sample/group_vars/all/containerd.yml
  roles/container-engine/containerd/defaults/main.yml
  roles/container-engine/containerd/tasks/main.yml
  roles/container-engine/containerd/templates/hosts.toml.j2
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, release-note, kind/feature

#12381 CI: fix broken debugging
  tests/testcases/020_check-pods-running.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved, release-note-none

#12289 fix: Use crun in the cri-o distribution and don't use crun role from …
  roles/container-engine/cri-o/defaults/main.yml
  roles/container-engine/cri-o/meta/main.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note-none

#12258 Fixed syntax error in _bgp_config dict
  roles/network_plugin/calico/tasks/install.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note

#12267 openstack : add the external_openstack_lbaas_member_subnet_id variable
  docs/cloud_controllers/openstack.md
  roles/kubernetes-apps/external_cloud_controller/openstack/defaults/main.yml
  roles/kubernetes-apps/external_cloud_controller/openstack/templates/external-openstack-cloud-config.j2
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note, kind/feature

#12398 Fix: nodelocaldns capabilities usage
  roles/kubernetes-apps/ansible/templates/nodelocaldns-daemonset.yml.j2
  roles/kubernetes-apps/ansible/templates/nodelocaldns-second-daemonset.yml.j2
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved, release-note

#12410 Patch versions updates - July 2025 k8s patch day
  Dockerfile
  README.md
  pipeline.Dockerfile
  roles/kubespray_defaults/vars/main/checksums.yml
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/feature, release-note-none

#12377 feature: support containerd static binary
  README.md
  docs/CRI/containerd.md
  roles/container-engine/containerd/molecule/default/molecule.yml
  roles/kubespray_defaults/defaults/main/download.yml
  roles/kubespray_defaults/defaults/main/main.yml
  roles/kubespray_defaults/vars/main/checksums.yml
  scripts/component_hash_update/src/component_hash_update/components.py
  tests/files/debian11-calico-collection.yml
  tests/files/debian11-calico-upgrade-once.yml
  tests/files/debian11-calico-upgrade.yml
  tests/files/debian11-custom-cni.yml
  tests/files/debian11-kubelet-csr-approver.yml
  tests/files/debian11-macvlan.yml
Labels: cncf-cla: yes, size/L, lgtm, approved, release-note, kind/feature, tide/merge-method-merge, ci-extended

#12423 doc: modify section order, remove redundant section
  docs/operations/nodes.md
Labels: cncf-cla: yes, size/L, lgtm, ok-to-test, approved, kind/documentation, release-note-none

#12353 Remove --auth-anonymous if kube_api_anonymous_auth is undefined
  roles/kubernetes/control-plane/templates/kubeadm-config.v1beta3.yaml.j2
  roles/kubernetes/control-plane/templates/kubeadm-config.v1beta4.yaml.j2
  roles/kubespray_defaults/defaults/main/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note, kind/feature

#12430 Fix Missing cilium_enable_bgp_control_plane Config
  roles/network_plugin/cilium/templates/values.yaml.j2
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note-none
