Repository kubernetes-sigs/kubespray, pull requests merged in 2025-09, with the labels that each got.

#12517 fix: typo
  Dockerfile
  docs/external_storage_provisioners/scheduler_plugins.md
  pipeline.Dockerfile
  roles/container-engine/cri-o/templates/crio.conf.j2
  roles/kubernetes-apps/ansible/templates/nodelocaldns-second-daemonset.yml.j2
  scripts/Dockerfile.j2
  scripts/pipeline.Dockerfile.j2
  tests/files/almalinux9-calico.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/cleanup, release-note-none, ci-short

#12514 fix: provide an option to ignore sysctl errors about unknown keys
  inventory/sample/group_vars/all/all.yml
  roles/kubernetes/node/tasks/main.yml
  roles/kubernetes/preinstall/defaults/main.yml
  roles/kubernetes/preinstall/tasks/0080-system-configurations.yml
  roles/kubespray_defaults/defaults/main/main.yml
  roles/network_plugin/macvlan/tasks/main.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, release-note, kind/feature

#12518 Patch versions updates
  roles/kubespray_defaults/vars/main/checksums.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note-none

#12525 Releng: Galaxy version to 2.28.2
  galaxy.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/cleanup, release-note-none

#12524 [release-2.28] Fix automated cherrypick failure in UpgradeConfiguration.node
  roles/kubernetes/control-plane/templates/kubeadm-config.v1beta4.yaml.j2
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note

#12542 Upgrade cilium from 1.17.7 to 1.18.1
  README.md
  docs/CNI/cilium.md
  roles/kubespray_defaults/defaults/main/download.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature, release-note-none

#12545 Upgrade local-path-provisioner from 0.0.24 to 0.0.32
  README.md
  inventory/sample/group_vars/k8s_cluster/addons.yml
  roles/kubespray_defaults/defaults/main/download.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature, release-note-none

#12387 coredns: set deploy replicas when dns autoscaler is disabled
  roles/kubernetes-apps/ansible/defaults/main.yml
  roles/kubernetes-apps/ansible/templates/coredns-deployment.yml.j2
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note, kind/feature

#12568 Upgrade cilium related images
  roles/kubespray_defaults/defaults/main/download.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature, release-note-none
