Repository kubernetes-sigs/kubespray, pull requests merged in 2025-01, with the labels that each got.

#11846 [ingress-nginx] upgrade to 1.12.0
  README.md
  docs/ingress/ingress_nginx.md
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/admission-webhook-configuration.yml.j2
  roles/kubernetes-apps/ingress_controller/ingress_nginx/templates/ds-ingress-nginx-controller.yml.j2
  roles/kubespray-defaults/defaults/main/download.yml
Labels: cncf-cla: yes, size/S, lgtm, approved, release-note, kind/feature, kind/network

#11859 Ignore Mem preflight errors on ubuntu upgrade testcase
  tests/files/packet_ubuntu22-calico-all-in-one-upgrade.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note-none, kind/failing-test

#11860 enable bash completion tasks for Suse OS family
  roles/kubernetes/control-plane/tasks/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note, kind/cleanup

#11854 Update KUBESPRAY_VERSION in CI and Readme for v2.27.0
  .gitlab-ci.yml
  docs/ansible/ansible.md
  galaxy.yml
Labels: cncf-cla: yes, size/S, lgtm, approved, release-note, kind/flake

#11864 Increase the control plane memory requirement to 2GB
  README.md
  tests/files/packet_ubuntu22-all-in-one-docker.yml
  tests/files/packet_ubuntu22-calico-all-in-one-upgrade.yml
  tests/files/packet_ubuntu22-calico-all-in-one.yml
  tests/files/packet_ubuntu24-all-in-one-docker.yml
  tests/files/packet_ubuntu24-calico-all-in-one.yml
  tests/files/packet_ubuntu24-calico-etcd-datastore.yml
Labels: cncf-cla: yes, size/M, lgtm, approved, release-note

#11849 Add Flatcar 4081.2.1 image to test-infra
  test-infra/image-builder/roles/kubevirt-images/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature, release-note-none

#11852 Structured AuthorizationConfiguration
  inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
  roles/kubernetes/control-plane/tasks/main.yml
  roles/kubernetes/control-plane/templates/kubeadm-config.v1beta3.yaml.j2
  roles/kubernetes/control-plane/templates/kubeadm-config.v1beta4.yaml.j2
  roles/kubespray-defaults/defaults/main/main.yml
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, release-note, kind/feature

#11857 add containerd registry mirror certificate configuration
  roles/container-engine/containerd/defaults/main.yml
  roles/container-engine/containerd/templates/hosts.toml.j2
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note, kind/feature

#11883 Add `manual` option to the `external_cloud_provider` variable
  inventory/sample/group_vars/all/all.yml
  roles/kubernetes/preinstall/tasks/0040-verify-settings.yml
  roles/kubespray-defaults/defaults/main/main.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, release-note, kind/feature

#11889 Update CI test from AlmaLinux8 to AlmaLinux9
  .gitlab-ci/packet.yml
  Vagrantfile
  docs/developers/ci.md
  roles/bootstrap-os/molecule/default/molecule.yml
  roles/container-engine/containerd/molecule/default/molecule.yml
  roles/container-engine/cri-dockerd/molecule/default/molecule.yml
  roles/container-engine/cri-o/molecule/default/molecule.yml
  roles/container-engine/gvisor/molecule/default/molecule.yml
  roles/container-engine/youki/molecule/default/molecule.yml
  test-infra/image-builder/roles/kubevirt-images/defaults/main.yml
  tests/cloud_playbooks/roles/packet-ci/defaults/main.yml
  tests/files/packet_almalinux8-calico.yml
  tests/files/packet_almalinux9-calico-ha-ebpf.yml
  tests/files/packet_almalinux9-calico-nodelocaldns-secondary.yml
  tests/files/packet_almalinux9-calico-remove-node.yml
  tests/files/packet_almalinux9-calico.yml
  tests/files/packet_almalinux9-crio.yml
  tests/files/packet_almalinux9-docker.yml
  tests/files/packet_almalinux9-kube-ovn.yml
Labels: cncf-cla: yes, size/L, lgtm, approved, release-note, kind/feature, ci-extended

#11875 Changed to use first_kube_control_plane to parse kubeadm_certificate_key
  roles/kubernetes/control-plane/tasks/kubeadm-secondary.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note

#11886 Contrib: upload2artifactory.py
  contrib/offline/README.md
  contrib/offline/upload2artifactory.py
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, release-note, kind/feature, ci-short

#11885 [kubernetes] Support Kubernetes v1.32.0 with RHEL8
  README.md
  docs/_sidebar.md
  docs/operating_systems/centos.md
  docs/operating_systems/rhel.md
  docs/operations/kernel-requirements.md
  inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
  roles/kubespray-defaults/defaults/main/checksums.yml
  roles/kubespray-defaults/defaults/main/download.yml
  roles/kubespray-defaults/defaults/main/main.yml
  tests/files/packet_almalinux8-calico.yml
  tests/files/packet_amazon-linux-2-all-in-one.yml
  tests/files/packet_rockylinux8-calico.yml
Labels: cncf-cla: yes, size/L, lgtm, approved, release-note, kind/feature

#11892 Cleanup OWNERS files in each folders
  contrib/terraform/OWNERS
  logo/OWNERS
  roles/container-engine/kata-containers/OWNERS
  roles/kubernetes-apps/csi_driver/OWNERS
  roles/kubernetes-apps/external_cloud_controller/openstack/OWNERS
  roles/kubernetes-apps/ingress_controller/alb_ingress_controller/OWNERS
  roles/kubernetes-apps/metallb/OWNERS
  roles/kubernetes-apps/network_plugin/kube-router/OWNERS
  roles/kubernetes-apps/persistent_volumes/aws-ebs-csi/OWNERS
  roles/network_plugin/kube-ovn/OWNERS
  roles/network_plugin/kube-router/OWNERS
  roles/network_plugin/macvlan/OWNERS
  roles/recover_control_plane/OWNERS
  test-infra/image-builder/OWNERS
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/cleanup, release-note-none, ci-short

#11891 Overhaul of the python hashes updater
  scripts/component_hash_update/pyproject.toml
  scripts/component_hash_update/src/component_hash_update/__init__.py
  scripts/component_hash_update/src/component_hash_update/components.py
  scripts/component_hash_update/src/component_hash_update/download.py
  scripts/component_hash_update/src/component_hash_update/list_releases.graphql
  scripts/download_hash.py
  scripts/get_node_ids.sh
Labels: cncf-cla: yes, size/XL, lgtm, approved, kind/feature, release-note-none, tide/merge-method-merge, ci-short

#11898 Run CI without the sample inventory
  .gitlab-ci/lint.yml
  Vagrantfile
  tests/Makefile
  tests/scripts/testcases_run.sh
  tests/testcases/030_check-network.yml
Labels: cncf-cla: yes, size/S, lgtm, approved, kind/cleanup, release-note-none, tide/merge-method-merge

#11899 CI: remove retry from jobs
  .gitlab-ci.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/cleanup, release-note-none, ci-extended

#11903 CI: cleanup vars identical to kubespray defaults
  tests/common_vars.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/cleanup, release-note-none

#11914 calico: don't set calico-node cpu limits by default
  roles/network_plugin/calico/templates/calico-node.yml.j2
  roles/network_plugin/calico_defaults/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, release-note, kind/cleanup

#11905 Update README.md versions automatically in pre-commit
  .gitlab-ci.yml
  .pre-commit-config.yaml
  README.md
  scripts/readme_versions.md.j2
  scripts/render_readme_version.yml
  tests/scripts/check_readme_versions.sh
Labels: cncf-cla: yes, size/L, lgtm, approved, kind/feature, release-note-none, tide/merge-method-merge, ci-short

#11917 fix Calico typha deployment issue: #11916
  roles/network_plugin/calico/templates/calico-typha.yml.j2
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note

#11919 Fix: hide 'ansible managed' balises in README.md
  README.md
  scripts/render_readme_version.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved, release-note-none, ci-short

#11904 CI: cleanup dependencies, pre-commit autoupdate
  .pre-commit-config.yaml
  tests/requirements.txt
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/cleanup, release-note-none

#11858 Drop explicit k8s_cluster group in CI inventory
  tests/cloud_playbooks/roles/packet-ci/tasks/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/cleanup, release-note-none

#11901 Cleanup of preinstall assertions
  roles/etcd/tasks/main.yml
  roles/kubernetes/preinstall/tasks/0040-verify-settings.yml
  roles/kubespray-defaults/tasks/main.yaml
Labels: cncf-cla: yes, size/L, lgtm, approved, release-note-action-required, kind/cleanup, tide/merge-method-merge

#11824 Remove krew support
  README.md
  docs/ansible/ansible.md
  inventory/sample/group_vars/all/offline.yml
  inventory/sample/group_vars/k8s_cluster/addons.yml
  roles/kubernetes-apps/krew/defaults/main.yml
  roles/kubernetes-apps/krew/tasks/krew.yml
  roles/kubernetes-apps/krew/tasks/main.yml
  roles/kubernetes-apps/krew/templates/krew.j2
  roles/kubernetes-apps/krew/templates/krew.yml.j2
  roles/kubernetes-apps/meta/main.yml
  roles/kubespray-defaults/defaults/main/checksums.yml
  roles/kubespray-defaults/defaults/main/download.yml
  roles/kubespray-defaults/defaults/main/main.yml
  roles/reset/tasks/main.yml
  scripts/readme_versions.md.j2
  tests/files/packet_ubuntu20-flannel-ha-once.yml
Labels: cncf-cla: yes, size/L, lgtm, ok-to-test, approved, release-note-action-required, kind/cleanup

#11895 Updated sample in inventory
  inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
  inventory/sample/group_vars/k8s_cluster/kube_control_plane.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, release-note, kind/documentation, ci-short

#11831 network: add ipv6 only global option
  .gitlab-ci/vagrant.yml
  Vagrantfile
  contrib/terraform/terraform.py
  docs/ansible/vars.md
  inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
  roles/container-engine/cri-dockerd/templates/cri-dockerd.service.j2
  roles/etcd/tasks/configure.yml
  roles/etcd/templates/openssl.conf.j2
  roles/kubernetes/client/tasks/main.yml
  roles/kubernetes/control-plane/tasks/kubeadm-secondary.yml
  roles/kubernetes/control-plane/tasks/kubeadm-setup.yml
  roles/kubernetes/control-plane/templates/kubeadm-config.v1beta3.yaml.j2
  roles/kubernetes/control-plane/templates/kubeadm-config.v1beta4.yaml.j2
  roles/kubernetes/control-plane/templates/kubeadm-controlplane.yaml.j2
  roles/kubernetes/kubeadm/templates/kubeadm-client.conf.j2
  roles/kubernetes/node/defaults/main.yml
  roles/kubernetes/node/templates/loadbalancer/haproxy.cfg.j2
  roles/kubernetes/node/templates/loadbalancer/nginx.conf.j2
  roles/kubernetes/preinstall/tasks/0080-system-configurations.yml
  roles/kubernetes/preinstall/tasks/0090-etchosts.yml
  roles/kubespray-defaults/defaults/main/main.yml
  roles/kubespray-defaults/tasks/main.yaml
  roles/kubespray-defaults/tasks/no_proxy.yml
  roles/network_plugin/calico/tasks/check.yml
  roles/network_plugin/calico/tasks/install.yml
  roles/network_plugin/calico/templates/calico-config.yml.j2
  roles/network_plugin/calico/templates/calico-node.yml.j2
  roles/network_plugin/calico_defaults/defaults/main.yml
  roles/network_plugin/flannel/templates/cni-flannel.yml.j2
  roles/network_plugin/kube-ovn/templates/cni-kube-ovn.yml.j2
  roles/network_plugin/kube-ovn/templates/cni-ovn.yml.j2
  roles/remove-node/remove-etcd-node/tasks/main.yml
  roles/reset/tasks/main.yml
  tests/files/vagrant_ubuntu24-calico-ipv6only-stack.rb
  tests/files/vagrant_ubuntu24-calico-ipv6only-stack.yml
  tests/testcases/030_check-network.yml
  tests/testcases/040_check-network-adv.yml
Labels: cncf-cla: yes, size/L, lgtm, ok-to-test, approved, release-note, kind/feature, ci-extended

#11923 Add timestamp to kaniko builds
  .gitlab-ci/build.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/feature, release-note-none, ci-short

#11927 dependabot: add group for molecule
  .github/dependabot.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/flake, release-note-none, ci-short

#11937 Bugfix/11936 - backup: "{{ leave_etc_backup_files }}"
  roles/kubernetes/preinstall/defaults/main.yml
  roles/kubernetes/preinstall/tasks/0063-networkmanager-dns.yml
  roles/kubernetes/preinstall/tasks/0080-system-configurations.yml
  roles/kubernetes/preinstall/tasks/0090-etchosts.yml
  roles/kubernetes/preinstall/tasks/0100-dhclient-hooks.yml
  roles/kubernetes/preinstall/tasks/0110-dhclient-hooks-undo.yml
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, ok-to-test, approved, release-note
