Repository kubernetes-sigs/kubespray, pull requests merged in 2025-03, with the labels that each got.

#12001 `kubeadm config validate` flag for debugging and development
  roles/download/tasks/prep_kubeadm_images.yml
  roles/kubernetes/control-plane/tasks/kubeadm-secondary.yml
  roles/kubernetes/control-plane/tasks/kubeadm-setup.yml
  roles/kubernetes/kubeadm/tasks/kubeadm_etcd_node.yml
  roles/kubernetes/kubeadm/tasks/main.yml
  roles/kubespray-defaults/defaults/main/main.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/feature, release-note-none

#11981 Bump node-local-dns (k8s-dns-node-cache) image
  roles/kubespray-defaults/defaults/main/download.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note, kind/feature

#11929 CI: Put pre-commit cache under CI_PROJECT_DIR
  .ansible-lint
  .gitlab-ci/lint.yml
  .pre-commit-config.yaml
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, approved, release-note-none, ci-short

#12003 Make kubernetes 1.32.2 default
  Dockerfile
  README.md
  inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
  pipeline.Dockerfile
  roles/kubespray-defaults/defaults/main/checksums.yml
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, release-note, kind/feature

#11989 Feature: configure crio default capabilities
  docs/CRI/cri-o.md
  roles/container-engine/cri-o/defaults/main.yml
  roles/container-engine/cri-o/templates/crio.conf.j2
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, release-note, kind/feature

#12012 [calico] Make calico v3.29.2, update hashes for other releases
  README.md
  roles/kubespray-defaults/defaults/main/checksums.yml
Labels: cncf-cla: yes, size/S, lgtm, approved, release-note

#12011 [containerd] Make containerd v2.0.3, update hashes for other releases
  README.md
  roles/kubespray-defaults/defaults/main/checksums.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, release-note, kind/feature, kind/container-managers

#12020 Make main_access_ip cacheable in facts
  roles/kubespray-defaults/tasks/main.yaml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note

#12018 Fix: CRI-O default capabilities follow with the upstream
  docs/CRI/cri-o.md
  roles/container-engine/cri-o/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note-action-required, kind/documentation, kind/cleanup

#11890 Adapt checksums and versions to new hashes updater
  README.md
  roles/container-engine/cri-o/defaults/main.yml
  roles/container-engine/cri-o/tasks/load_vars.yml
  roles/container-engine/cri-o/tasks/reset.yml
  roles/container-engine/cri-o/templates/crio.conf.j2
  roles/download/tasks/download_file.yml
  roles/download/templates/kubeadm-images.yaml.j2
  roles/etcd/tasks/install_host.yml
  roles/etcdctl_etcdutl/tasks/main.yml
  roles/kubernetes-apps/argocd/defaults/main.yml
  roles/kubernetes-apps/gateway_api/defaults/main.yml
  roles/kubernetes-apps/meta/main.yml
  roles/kubernetes-apps/metallb/templates/metallb.yaml.j2
  roles/kubernetes/control-plane/defaults/main/main.yml
  roles/kubernetes/control-plane/tasks/kubeadm-upgrade.yml
  roles/kubernetes/control-plane/tasks/main.yml
  roles/kubernetes/control-plane/templates/kubeadm-config.v1beta3.yaml.j2
  roles/kubernetes/control-plane/templates/kubeadm-config.v1beta4.yaml.j2
  roles/kubernetes/node/defaults/main.yml
  roles/kubernetes/preinstall/tasks/0040-verify-settings.yml
  roles/kubespray-defaults/defaults/main/checksums.yml
  roles/kubespray-defaults/defaults/main/download.yml
  roles/kubespray-defaults/defaults/main/main.yml
  roles/kubespray-defaults/vars/main.yml
  roles/network_plugin/calico/tasks/check.yml
  roles/network_plugin/calico/tasks/install.yml
  roles/network_plugin/calico/tasks/peer_with_router.yml
  roles/network_plugin/calico/templates/calico-apiserver.yml.j2
  roles/network_plugin/cilium/defaults/main.yml
  roles/network_plugin/cilium/tasks/check.yml
  roles/network_plugin/cilium/templates/cilium-operator/cr.yml.j2
  roles/network_plugin/cilium/templates/cilium/config.yml.j2
  roles/network_plugin/cilium/templates/cilium/cr.yml.j2
  roles/network_plugin/cilium/templates/cilium/ds.yml.j2
  scripts/Dockerfile.j2
  scripts/pipeline.Dockerfile.j2
  scripts/readme_versions.md.j2
Labels: cncf-cla: yes, size/XXL, lgtm, ok-to-test, approved, release-note-action-required, kind/cleanup, tide/merge-method-merge, ci-extended

#12024 Update patch versions: cri-o, cri-dockerd, gvisor, etcd, cilium-cli, cni
  README.md
  roles/kubespray-defaults/defaults/main/checksums.yml
Labels: cncf-cla: yes, size/L, lgtm, ok-to-test, approved, release-note-none

#12023 Fix syntax error in k8s-net-cilium.yml
  inventory/sample/group_vars/k8s_cluster/k8s-net-cilium.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note-none

#11986 cilium 1.17: fix etcd trusted-ca-file config var
  roles/network_plugin/cilium/templates/cilium/config.yml.j2
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note

#12029 [release-2.26] Remove: tox testing from pre-commit
  .gitlab-ci/packet.yml
  .pre-commit-config.yaml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, release-note-none, kind/failing-test

#12030 CI: only define `mode` in tests if needeed
  tests/cloud_playbooks/roles/packet-ci/defaults/main.yml
  tests/files/packet_almalinux8-calico.yml
  tests/files/packet_almalinux9-calico-nodelocaldns-secondary.yml
  tests/files/packet_almalinux9-calico.yml
  tests/files/packet_almalinux9-crio.yml
  tests/files/packet_almalinux9-docker.yml
  tests/files/packet_almalinux9-kube-ovn.yml
  tests/files/packet_debian11-calico-collection.yml
  tests/files/packet_debian11-calico-upgrade-once.yml
  tests/files/packet_debian11-calico-upgrade.yml
  tests/files/packet_debian11-custom-cni.yml
  tests/files/packet_debian11-docker.yml
  tests/files/packet_debian11-kubelet-csr-approver.yml
  tests/files/packet_debian11-macvlan.yml
  tests/files/packet_debian12-calico.yml
  tests/files/packet_debian12-cilium.yml
  tests/files/packet_debian12-custom-cni-helm.yml
  tests/files/packet_debian12-docker.yml
  tests/files/packet_fedora39-calico-selinux.yml
  tests/files/packet_fedora39-calico-swap-selinux.yml
  tests/files/packet_fedora39-crio.yml
  tests/files/packet_fedora40-docker-calico.yml
  tests/files/packet_openeuler24-calico.yml
  tests/files/packet_opensuse-docker-cilium.yml
  tests/files/packet_rockylinux8-calico.yml
  tests/files/packet_rockylinux9-calico.yml
  tests/files/packet_rockylinux9-cilium.yml
  tests/files/packet_ubuntu20-calico-etcd-kubeadm.yml
  tests/files/packet_ubuntu20-crio.yml
  tests/files/vagrant_fedora39-kube-router.yml
  tests/files/vagrant_ubuntu24-calico-dual-stack.yml
  tests/files/vagrant_ubuntu24-calico-ipv6only-stack.yml
Labels: cncf-cla: yes, size/M, lgtm, approved, kind/cleanup, release-note-none

#12031 [release-2.27] Patch versions update
  .gitlab-ci/packet.yml
  README.md
  inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
  roles/kubespray-defaults/defaults/main/checksums.yml
  roles/kubespray-defaults/defaults/main/download.yml
  roles/kubespray-defaults/defaults/main/main.yml
Labels: cncf-cla: yes, size/L, lgtm, approved, release-note, kind/feature, tide/merge-method-merge

#11386 Upcloud: Added support for routers and gateways
  contrib/terraform/upcloud/README.md
  contrib/terraform/upcloud/cluster-settings.tfvars
  contrib/terraform/upcloud/main.tf
  contrib/terraform/upcloud/modules/kubernetes-cluster/main.tf
  contrib/terraform/upcloud/modules/kubernetes-cluster/variables.tf
  contrib/terraform/upcloud/modules/kubernetes-cluster/versions.tf
  contrib/terraform/upcloud/variables.tf
  contrib/terraform/upcloud/versions.tf
Labels: cncf-cla: yes, size/L, lgtm, ok-to-test, approved, release-note, kind/feature

#12035 [calico] fix: kubecontrollersconfigurations list permission
  roles/kubernetes-apps/policy_controller/calico/templates/calico-kube-cr.yml.j2
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note

#12040 CI: cleanup leftover files
  .gitlab-ci/pre-commit-dynamic-stub.yml
Labels: cncf-cla: yes, size/S, lgtm, approved, kind/cleanup, release-note-none

#12052 Bump kube patch versions
  Dockerfile
  README.md
  pipeline.Dockerfile
  roles/kubespray-defaults/defaults/main/checksums.yml
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, release-note, kind/feature

#12045 vagrant: allow to config vagrant with separate etcd
  Vagrantfile
  tests/files/vagrant_fedora39-kube-router.rb
  tests/files/vagrant_ubuntu20-kube-router-sep.rb
Labels: cncf-cla: yes, size/S, lgtm, approved, kind/feature, release-note-none

#12051 Cleanup unneeded vagrant python packages from test deps
  tests/requirements.txt
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/cleanup, release-note-none

#11880 Add Auto-Labeling of Issues Based on OS Selection
  .github/ISSUE_TEMPLATE/bug-report.yaml
  .github/workflows/auto-label-os.yml
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, release-note-none, ci-short

#12057 Check separately for 'v'-prefixed versions for ones which are derived
  roles/kubernetes/preinstall/tasks/0040-verify-settings.yml
Labels: cncf-cla: yes, size/S, lgtm, approved, kind/cleanup, release-note-none

#12058 Ensure correct `AuthorizationConfiguration` API version during upgrades
  roles/kubernetes/control-plane/tasks/main.yml
  roles/kubernetes/control-plane/templates/kubeadm-config.v1beta3.yaml.j2
  roles/kubernetes/control-plane/templates/kubeadm-config.v1beta4.yaml.j2
  roles/kubespray-defaults/defaults/main/main.yml
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, ok-to-test, approved, release-note-none

#12028 fix: ensure CoreDNS is kept disabled on kubeadm upgrade
  roles/kubernetes/control-plane/templates/kubeadm-config.v1beta4.yaml.j2
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note

#11950 fix issue with floating-ip
  contrib/terraform/openstack/modules/ips/main.tf
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note-none

#11960 Feat: offline installation registry support macOS
  contrib/offline/manage-offline-container-images.sh
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note, kind/feature

#12015 Refactor control plane upgrades with reconfiguration support
  roles/kubernetes/control-plane/defaults/main/main.yml
  roles/kubernetes/control-plane/tasks/check-api.yml
  roles/kubernetes/control-plane/tasks/kubeadm-setup.yml
  roles/kubernetes/control-plane/tasks/kubeadm-upgrade.yml
  roles/kubernetes/control-plane/templates/kubeadm-config.v1beta4.yaml.j2
Labels: kind/bug, cncf-cla: yes, size/L, lgtm, ok-to-test, approved, release-note, ci-extended

#12063 [release-2.26] Revert "Limit nodes in gather ansible_default_ipv4 (#11370)"
  roles/kubespray-defaults/tasks/fallback_ips.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved, release-note

#12067 Fix path in vagrant.md documentation
  docs/developers/vagrant.md
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/documentation, release-note-none, ci-short

#12077 Update calico crd archive checksum
  roles/kubespray-defaults/defaults/main/checksums.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note-none

#12074 Upgrade CI for openSuse 15.6
  .gitlab-ci/packet.yml
  Vagrantfile
  docs/developers/ci.md
  docs/operating_systems/opensuse.md
  test-infra/image-builder/roles/kubevirt-images/defaults/main.yml
  tests/files/packet_opensuse15-6-calico.yml
  tests/files/packet_opensuse15-6-docker-cilium.yml
Labels: cncf-cla: yes, size/S, lgtm, approved, release-note, kind/flake

#12079 CI: fix wrong git config env variables
  .gitlab-ci.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, approved, release-note-none

#12075 fix(ingress-nginx): Upgrade ingress-nginx to v1.12.1 and webhook certgen image to v1.5.2
  README.md
  roles/kubespray-defaults/defaults/main/download.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note, kind/feature, kind/network

#12060 Support kube-proxy nftables mode
  docs/ansible/vars.md
  inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
  roles/kubernetes/node/tasks/main.yml
  roles/kubernetes/preinstall/tasks/0040-verify-settings.yml
  roles/kubernetes/preinstall/vars/main.yml
  tests/files/packet_almalinux9-calico.yml
  tests/files/packet_opensuse15-6-calico.yml
  tests/files/packet_ubuntu24-calico-etcd-datastore.yml
Labels: cncf-cla: yes, size/M, lgtm, approved, release-note

#12082 [release-2.27] [calico] Fix v3.29.2 crds archive checksum
  roles/kubespray-defaults/defaults/main/checksums.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note-none, kind/failing-test

#12086 fix: missing 'v' prefix in offline image tags
  RELEASE.md
  contrib/offline/generate_list.sh
  docs/CNI/cilium.md
  docs/operations/upgrades.md
  inventory/sample/group_vars/k8s_cluster/addons.yml
  inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
  inventory/sample/group_vars/k8s_cluster/k8s-net-cilium.yml
  inventory/sample/group_vars/k8s_cluster/k8s-net-kube-router.yml
  roles/kubernetes-apps/metallb/templates/metallb.yaml.j2
  roles/kubespray-defaults/defaults/main/download.yml
Labels: kind/bug, cncf-cla: yes, size/M, lgtm, ok-to-test, approved, release-note

#12066 Upgrade kube-router
  README.md
  roles/kubespray-defaults/defaults/main/download.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, release-note, kind/feature, ci-extended

#12080 [release-2.27] Bump ingress-nginx to 1.12.1 and certgen to 1.5.2
  README.md
  roles/kubespray-defaults/defaults/main/download.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note, kind/feature

#11998 Ensure metrics port exists for nodelocaldns/nodelocaldns-second daemonsets
  roles/kubernetes-apps/ansible/templates/nodelocaldns-daemonset.yml.j2
  roles/kubernetes-apps/ansible/templates/nodelocaldns-second-daemonset.yml.j2
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note, kind/feature

#12085 fix(remove-node): Ensure safety and validation for node removal process
  docs/getting_started/getting-started.md
  playbooks/remove_node.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, release-note, kind/cleanup

#12053 Add github workflow to auto update hashes daily
  .github/dependabot.yml
  .github/workflows/upgrade-patch-versions-schedule.yml
  .github/workflows/upgrade-patch-versions.yml
Labels: cncf-cla: yes, size/L, lgtm, approved, kind/feature, release-note-none

#12091 [contrib] Remove heketi and glusterfs
  contrib/network-storage/glusterfs/README.md
  contrib/network-storage/glusterfs/glusterfs.yml
  contrib/network-storage/glusterfs/group_vars
  contrib/network-storage/glusterfs/inventory.example
  contrib/network-storage/glusterfs/roles/bootstrap-os
  contrib/network-storage/glusterfs/roles/glusterfs/README.md
  contrib/network-storage/glusterfs/roles/glusterfs/client/defaults/main.yml
  contrib/network-storage/glusterfs/roles/glusterfs/client/meta/main.yml
  contrib/network-storage/glusterfs/roles/glusterfs/client/tasks/main.yml
  contrib/network-storage/glusterfs/roles/glusterfs/client/tasks/setup-Debian.yml
  contrib/network-storage/glusterfs/roles/glusterfs/client/tasks/setup-RedHat.yml
  contrib/network-storage/glusterfs/roles/glusterfs/server/defaults/main.yml
  contrib/network-storage/glusterfs/roles/glusterfs/server/meta/main.yml
  contrib/network-storage/glusterfs/roles/glusterfs/server/tasks/main.yml
  contrib/network-storage/glusterfs/roles/glusterfs/server/tasks/setup-Debian.yml
  contrib/network-storage/glusterfs/roles/glusterfs/server/tasks/setup-RedHat.yml
  contrib/network-storage/glusterfs/roles/glusterfs/server/templates/test-file.txt
  contrib/network-storage/glusterfs/roles/glusterfs/server/vars/Debian.yml
  contrib/network-storage/glusterfs/roles/glusterfs/server/vars/RedHat.yml
  contrib/network-storage/glusterfs/roles/kubernetes-pv/ansible/tasks/main.yaml
  contrib/network-storage/glusterfs/roles/kubernetes-pv/ansible/templates/glusterfs-kubernetes-endpoint-svc.json.j2
  contrib/network-storage/glusterfs/roles/kubernetes-pv/ansible/templates/glusterfs-kubernetes-endpoint.json.j2
  contrib/network-storage/glusterfs/roles/kubernetes-pv/ansible/templates/glusterfs-kubernetes-pv.yml.j2
  contrib/network-storage/glusterfs/roles/kubernetes-pv/meta/main.yaml
  contrib/network-storage/heketi/README.md
  contrib/network-storage/heketi/heketi-tear-down.yml
  contrib/network-storage/heketi/heketi.yml
  contrib/network-storage/heketi/inventory.yml.sample
  contrib/network-storage/heketi/requirements.txt
  contrib/network-storage/heketi/roles/prepare/tasks/main.yml
  contrib/network-storage/heketi/roles/provision/defaults/main.yml
  contrib/network-storage/heketi/roles/provision/handlers/main.yml
  contrib/network-storage/heketi/roles/provision/tasks/bootstrap.yml
  contrib/network-storage/heketi/roles/provision/tasks/bootstrap/deploy.yml
  contrib/network-storage/heketi/roles/provision/tasks/bootstrap/storage.yml
  contrib/network-storage/heketi/roles/provision/tasks/bootstrap/tear-down.yml
  contrib/network-storage/heketi/roles/provision/tasks/bootstrap/topology.yml
  contrib/network-storage/heketi/roles/provision/tasks/bootstrap/volumes.yml
  contrib/network-storage/heketi/roles/provision/tasks/cleanup.yml
  contrib/network-storage/heketi/roles/provision/tasks/glusterfs.yml
  contrib/network-storage/heketi/roles/provision/tasks/glusterfs/label.yml
  contrib/network-storage/heketi/roles/provision/tasks/heketi.yml
  contrib/network-storage/heketi/roles/provision/tasks/main.yml
  contrib/network-storage/heketi/roles/provision/tasks/secret.yml
  contrib/network-storage/heketi/roles/provision/tasks/storage.yml
  contrib/network-storage/heketi/roles/provision/tasks/storageclass.yml
  contrib/network-storage/heketi/roles/provision/tasks/topology.yml
  contrib/network-storage/heketi/roles/provision/templates/glusterfs-daemonset.json.j2
  contrib/network-storage/heketi/roles/provision/templates/heketi-bootstrap.json.j2
  contrib/network-storage/heketi/roles/provision/templates/heketi-deployment.json.j2
  contrib/network-storage/heketi/roles/provision/templates/heketi-service-account.json.j2
  contrib/network-storage/heketi/roles/provision/templates/heketi-storage.json.j2
  contrib/network-storage/heketi/roles/provision/templates/heketi.json.j2
  contrib/network-storage/heketi/roles/provision/templates/storageclass.yml.j2
  contrib/network-storage/heketi/roles/provision/templates/topology.json.j2
  contrib/network-storage/heketi/roles/tear-down-disks/defaults/main.yml
  contrib/network-storage/heketi/roles/tear-down-disks/tasks/main.yml
  contrib/network-storage/heketi/roles/tear-down/tasks/main.yml
Labels: cncf-cla: yes, size/XXL, lgtm, approved, release-note, kind/cleanup, ci-short

#12093 Cleanup old things in contrib/
  contrib/kvm-setup/README.md
  contrib/kvm-setup/group_vars/all
  contrib/kvm-setup/kvm-setup.yml
  contrib/kvm-setup/roles/kvm-setup/tasks/main.yml
  contrib/kvm-setup/roles/kvm-setup/tasks/sysctl.yml
  contrib/kvm-setup/roles/kvm-setup/tasks/user.yml
  contrib/mitogen/mitogen.yml
Labels: cncf-cla: yes, size/L, lgtm, approved, release-note, kind/cleanup, tide/merge-method-merge, ci-short

#12092 Remove unused manifest (docs)
  contrib/misc/clusteradmin-rbac.yml
Labels: cncf-cla: yes, size/S, lgtm, approved, kind/cleanup, release-note-none, ci-short

#12097 auto-update: use a branch prefix rather than suffix
  .github/dependabot.yml
  .github/workflows/upgrade-patch-versions.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/cleanup, release-note-none

#12098 component_hash_update: remove obsolete todos
  scripts/component_hash_update/src/component_hash_update/download.py
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/cleanup, release-note-none, ci-short
