Repository kubernetes-sigs/kubespray, pull requests merged in 2025-05, with the labels that each got.

#12120 Etcd Certificates are not generated when adding nodes to an existing cluster with scale.yml
  playbooks/cluster.yml
  playbooks/install_etcd.yml
  playbooks/scale.yml
  playbooks/upgrade_cluster.yml
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, release-note-none

#12123 fix: correct indent of cpuManagerPolicyOptions
  roles/kubernetes/node/templates/kubelet-config.v1beta1.yaml.j2
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note

#12177 Fix path to facts.yml in node facts refresh section
  docs/operations/upgrades.md
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note, kind/documentation, ci-short

#12166 docs: Fix offline-environment.md to add 'v' prefix of some versions
  docs/operations/offline-environment.md
  inventory/sample/group_vars/all/offline.yml
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, release-note, kind/documentation

#12170 update containerd.options key name
  docs/CRI/containerd.md
  roles/container-engine/containerd/defaults/main.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note-none

#12165 Feat: add `dns_autoscaler_affinity` and remove in-place values
  roles/kubernetes-apps/ansible/defaults/main.yml
  roles/kubernetes-apps/ansible/templates/dns-autoscaler.yml.j2
  tests/files/ubuntu22-calico-all-in-one-upgrade.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, release-note, kind/failing-test, tide/merge-method-merge

#12164 Remove versions from inventory sample
  inventory/sample/group_vars/all/oci.yml
  inventory/sample/group_vars/all/openstack.yml
  inventory/sample/group_vars/all/vsphere.yml
  inventory/sample/group_vars/k8s_cluster/addons.yml
  inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
  inventory/sample/group_vars/k8s_cluster/k8s-net-cilium.yml
  inventory/sample/group_vars/k8s_cluster/k8s-net-custom-cni.yml
  inventory/sample/group_vars/k8s_cluster/k8s-net-kube-router.yml
Labels: cncf-cla: yes, size/M, lgtm, approved, kind/cleanup, release-note-none

#12191 Move cilium_deploy_additionnaly to kubespray-default
  roles/etcd/tasks/check_certs.yml
  roles/etcd/tasks/gen_certs_script.yml
  roles/etcd/tasks/main.yml
  roles/kubernetes/kubeadm/tasks/main.yml
  roles/kubernetes/preinstall/tasks/0040-verify-settings.yml
  roles/kubespray-defaults/defaults/main/download.yml
  roles/kubespray-defaults/defaults/main/main.yml
  roles/network_plugin/cilium/defaults/main.yml
  roles/network_plugin/cilium/tasks/check.yml
  roles/network_plugin/meta/main.yml
Labels: cncf-cla: yes, size/M, lgtm, approved, kind/cleanup, release-note-none

#12173 fix: arm64 checksums for youki and kata-containers
  roles/kubespray-defaults/defaults/main/checksums.yml
  roles/kubespray-defaults/defaults/main/download.yml
Labels: kind/bug, cncf-cla: yes, size/M, lgtm, ok-to-test, approved, release-note

#12201 kubedns_version no longer used
  docs/operations/upgrades.md
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/documentation, release-note-none, ci-short

#12197 Fix `'item' is undefined` error caused by indentation
  roles/kubernetes/control-plane/tasks/main.yml
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note-none

#12189 Feat: Gateway API early installation
  playbooks/cluster.yml
  roles/kubernetes-apps/meta/main.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, release-note, kind/feature

#12185 Move package installation to bootstrap-os
  playbooks/boilerplate.yml
  playbooks/facts.yml
  roles/bootstrap-os/defaults/main.yml
  roles/bootstrap-os/meta/main.yml
  roles/bootstrap-os/tasks/amzn.yml
  roles/bootstrap-os/tasks/centos.yml
  roles/bootstrap-os/tasks/clear-linux-os.yml
  roles/bootstrap-os/tasks/debian.yml
  roles/bootstrap-os/tasks/fedora.yml
  roles/bootstrap-os/tasks/main.yml
  roles/bootstrap-os/tasks/opensuse.yml
  roles/bootstrap-os/tasks/rhel.yml
  roles/container-engine/containerd/molecule/default/prepare.yml
  roles/container-engine/cri-o/molecule/default/prepare.yml
  roles/kubernetes/preinstall/defaults/main.yml
  roles/kubernetes/preinstall/tasks/0040-verify-settings.yml
  roles/kubernetes/preinstall/tasks/main.yml
  roles/kubernetes/preinstall/vars/main.yml
  roles/kubespray-defaults/defaults/main/main.yml
  roles/network_facts/meta/main.yml
  roles/network_facts/tasks/main.yaml
  roles/network_facts/tasks/no_proxy.yml
  roles/system_packages/defaults/main.yml
  roles/system_packages/tasks/main.yml
  roles/system_packages/vars/main.yml
  roles/validate_inventory/meta/main.yml
  roles/validate_inventory/tasks/main.yml
  scripts/assert-sorted-checksums.yml
Labels: cncf-cla: yes, size/XL, lgtm, approved, kind/cleanup, release-note-none, tide/merge-method-merge, ci-full

#12206 Don't run upgrade-patch jobs on forks
  .github/workflows/upgrade-patch-versions-schedule.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/cleanup, release-note-none

#12207 CI: enable all jobs on daily CI
  .gitlab-ci/kubevirt.yml
  .gitlab-ci/molecule.yml
  .gitlab-ci/vagrant.yml
Labels: cncf-cla: yes, size/M, lgtm, approved, kind/feature, release-note-none

#12143 fix: do not mount hubble-ui tls volume when cilium_hubble_tls_generate is false
  roles/network_plugin/cilium/templates/hubble/deploy.yml.j2
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note

#12202 Rename kubespray-defaults to kubespray_defaults
  contrib/offline/README.md
  contrib/offline/generate_list.sh
  contrib/offline/generate_list.yml
  docs/advanced/proxy.md
  docs/ansible/vars.md
  docs/operating_systems/bootstrap-os.md
  docs/operations/offline-environment.md
  extra_playbooks/migrate_openstack_provider.yml
  extra_playbooks/upgrade-only-k8s.yml
  inventory/sample/group_vars/all/all.yml
  playbooks/boilerplate.yml
  playbooks/cluster.yml
  playbooks/install_etcd.yml
  playbooks/recover_control_plane.yml
  playbooks/remove_node.yml
  playbooks/reset.yml
  playbooks/scale.yml
  playbooks/upgrade_cluster.yml
  roles/bootstrap-os/meta/main.yml
  roles/container-engine/containerd/molecule/default/converge.yml
  roles/container-engine/containerd/molecule/default/prepare.yml
  roles/container-engine/cri-dockerd/molecule/default/converge.yml
  roles/container-engine/cri-dockerd/molecule/default/prepare.yml
  roles/container-engine/cri-o/molecule/default/converge.yml
  roles/container-engine/cri-o/molecule/default/prepare.yml
  roles/container-engine/gvisor/molecule/default/converge.yml
  roles/container-engine/gvisor/molecule/default/prepare.yml
  roles/container-engine/kata-containers/molecule/default/converge.yml
  roles/container-engine/kata-containers/molecule/default/prepare.yml
  roles/container-engine/youki/molecule/default/converge.yml
  roles/container-engine/youki/molecule/default/prepare.yml
  roles/kubespray-defaults/tasks/main.yml
  roles/kubespray_defaults/defaults/main/checksums.yml
  roles/kubespray_defaults/defaults/main/download.yml
  roles/kubespray_defaults/defaults/main/main.yml
  roles/kubespray_defaults/vars/main.yml
  roles/network_facts/meta/main.yml
  roles/validate_inventory/meta/main.yml
  roles/validate_inventory/tasks/main.yml
  scripts/assert-sorted-checksums.yml
  scripts/component_hash_update/src/component_hash_update/download.py
  scripts/propagate_ansible_variables.yml
  tests/testcases/030_check-network.yml
Labels: cncf-cla: yes, size/L, lgtm, approved, release-note, kind/cleanup, tide/merge-method-merge

#12140 Feat: add Cilium LB IP Pool configuration to support ranges
  docs/CNI/cilium.md
  inventory/sample/group_vars/k8s_cluster/k8s-net-cilium.yml
  roles/network_plugin/cilium/templates/cilium/cilium-loadbalancer-ip-pool.yml.j2
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, release-note, kind/feature, kind/documentation

#12200 create cilium_operator_tolerations variable in group_var
  roles/network_plugin/cilium/defaults/main.yml
  roles/network_plugin/cilium/templates/cilium-operator/deploy.yml.j2
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note, kind/feature

#12205 Cleanup CI scripts
  .gitlab-ci/molecule.yml
  scripts/gen_tags.sh
  scripts/gitlab-branch-cleanup/.gitignore
  scripts/gitlab-branch-cleanup/README.md
  scripts/gitlab-branch-cleanup/main.py
  scripts/gitlab-branch-cleanup/requirements.txt
  scripts/premoderator.sh
  tests/scripts/molecule_logs.sh
Labels: cncf-cla: yes, size/L, lgtm, approved, kind/cleanup, release-note-none

#12208 kubernetes_audit: Remove redundant defaults filter
  roles/kubernetes/control-plane/tasks/kubeadm-setup.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved, kind/cleanup, release-note-none

#12203 Rename bootstrap-os to bootstrap_os
  .gitlab-ci/molecule.yml
  docs/ansible/ansible.md
  docs/operating_systems/bootstrap-os.md
  extra_playbooks/upgrade-only-k8s.yml
  playbooks/facts.yml
  roles/bootstrap-os/tasks/main.yml
  roles/bootstrap_os/defaults/main.yml
  roles/bootstrap_os/files/bootstrap.sh
  roles/bootstrap_os/handlers/main.yml
  roles/bootstrap_os/meta/main.yml
  roles/bootstrap_os/molecule/default/converge.yml
  roles/bootstrap_os/molecule/default/molecule.yml
  roles/bootstrap_os/molecule/default/tests/test_default.py
  roles/bootstrap_os/tasks/amzn.yml
  roles/bootstrap_os/tasks/centos.yml
  roles/bootstrap_os/tasks/clear-linux-os.yml
  roles/bootstrap_os/tasks/debian.yml
  roles/bootstrap_os/tasks/fedora-coreos.yml
  roles/bootstrap_os/tasks/fedora.yml
  roles/bootstrap_os/tasks/flatcar.yml
  roles/bootstrap_os/tasks/main.yml
  roles/bootstrap_os/tasks/openEuler.yml
  roles/bootstrap_os/tasks/opensuse-leap.yml
  roles/bootstrap_os/tasks/opensuse-tumbleweed.yml
  roles/bootstrap_os/tasks/opensuse.yml
  roles/bootstrap_os/tasks/rhel.yml
  roles/bootstrap_os/tasks/ubuntu.yml
  roles/bootstrap_os/vars/fedora-coreos.yml
  roles/bootstrap_os/vars/flatcar.yml
  roles/container-engine/containerd/molecule/default/prepare.yml
  roles/container-engine/cri-dockerd/molecule/default/prepare.yml
  roles/container-engine/cri-o/molecule/default/prepare.yml
  roles/container-engine/gvisor/molecule/default/prepare.yml
  roles/container-engine/kata-containers/molecule/default/prepare.yml
  roles/container-engine/youki/molecule/default/prepare.yml
  roles/kubernetes/preinstall/tasks/0050-create_directories.yml
  roles/kubernetes/preinstall/tasks/0080-system-configurations.yml
  roles/kubernetes/preinstall/tasks/main.yml
  roles/system_packages/tasks/main.yml
Labels: cncf-cla: yes, size/L, lgtm, approved, release-note, kind/cleanup, tide/merge-method-merge

#12211 rename-without-hypens: remove-node/pre-remove
  playbooks/remove_node.yml
  roles/container-engine/validate-container-engine/tasks/main.yml
  roles/remove-node/pre-remove/tasks/main.yml
  roles/remove_node/pre_remove/defaults/main.yml
  roles/remove_node/pre_remove/tasks/main.yml
Labels: cncf-cla: yes, size/M, lgtm, approved, kind/cleanup, release-note-none, tide/merge-method-merge

#12213 Stop cleaning up containerd packages
  roles/container-engine/containerd-common/defaults/main.yml
  roles/container-engine/containerd/tasks/main.yml
  roles/container-engine/containerd/tasks/reset.yml
  roles/container-engine/containerd/vars/debian.yml
  roles/container-engine/containerd/vars/ubuntu.yml
Labels: cncf-cla: yes, size/M, lgtm, approved, kind/cleanup, release-note-none

#12204 Patch versions updates
  roles/kubespray_defaults/defaults/main/checksums.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/feature, release-note-none

#12172 feat: add trigger to restart kube-apiserver when config files change
  roles/kubernetes/control-plane/tasks/kubeadm-setup.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/feature, release-note-none

#12219 Fix broken workaround for separate etcd setup
  .gitlab-ci/kubevirt.yml
  roles/etcd/tasks/gen_certs_script.yml
  tests/files/ubuntu24-ha-separate-etcd.yml
Labels: kind/bug, cncf-cla: yes, size/M, lgtm, approved, release-note-none, tide/merge-method-merge

#12217 download: Only download dnsautoscaler image if needed
  roles/kubespray_defaults/defaults/main/download.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, kind/cleanup, release-note-none

#12216 Improve logging of kubeadm init failure of first control plane node
  roles/kubernetes/control-plane/tasks/kubeadm-setup.yml
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/feature, release-note-none

#12225 CI: remove ci-not-authorized job
  .gitlab-ci.yml
  .gitlab-ci/kubevirt.yml
  .gitlab-ci/molecule.yml
  .gitlab-ci/terraform.yml
  .gitlab-ci/vagrant.yml
Labels: cncf-cla: yes, size/M, lgtm, approved, kind/cleanup, release-note-none

#12212 improve ntp package conflict handling
  roles/kubernetes/preinstall/defaults/main.yml
  roles/kubernetes/preinstall/tasks/0081-ntp-configurations.yml
  roles/kubespray_defaults/defaults/main/main.yml
  roles/system_packages/tasks/main.yml
  roles/system_packages/vars/main.yml
  scripts/assert-sorted-checksums.yml
  tests/files/almalinux9-calico.yml
  tests/files/debian12-cilium.yml
  tests/files/ubuntu24-calico-etcd-datastore.yml
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, release-note

#12226 Patch versions updates
  Dockerfile
  README.md
  pipeline.Dockerfile
  roles/kubespray_defaults/defaults/main/checksums.yml
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved, kind/feature, release-note-none

#12222 release-2.26: Fix broken workaround for separate etcd setup
  roles/etcd/tasks/gen_certs_script.yml
Labels: kind/bug, cncf-cla: yes, size/M, lgtm, approved, release-note-none

#12072 Add support for hubble-export-file-max-backups and max-size-mb variables
  roles/network_plugin/cilium/defaults/main.yml
  roles/network_plugin/cilium/templates/cilium/config.yml.j2
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note, kind/feature, ci-short

#11964 Fix: Using the `./manage-offline-container-images.sh register` command does not create a new container but registers the image in the existing container registry.
  contrib/offline/manage-offline-container-images.sh
Labels: kind/bug, cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note

#12234 Move checksums to kubespray_defaults/vars
  roles/kubespray_defaults/vars/main/checksums.yml
  roles/kubespray_defaults/vars/main/main.yml
  scripts/component_hash_update/src/component_hash_update/download.py
Labels: cncf-cla: yes, size/XS, lgtm, approved, release-note, kind/cleanup

#12101 Refactor Cilium CNI installation
  README.md
  docs/CNI/cilium.md
  roles/kubespray_defaults/defaults/main/download.yml
  roles/kubespray_defaults/vars/main/checksums.yml
  roles/network_plugin/cilium/defaults/main.yml
  roles/network_plugin/cilium/tasks/apply.yml
  roles/network_plugin/cilium/tasks/check.yml
  roles/network_plugin/cilium/tasks/install.yml
  roles/network_plugin/cilium/templates/cilium-operator/cr.yml.j2
  roles/network_plugin/cilium/templates/cilium-operator/crb.yml.j2
  roles/network_plugin/cilium/templates/cilium-operator/deploy.yml.j2
  roles/network_plugin/cilium/templates/cilium-operator/sa.yml.j2
  roles/network_plugin/cilium/templates/cilium/config.yml.j2
  roles/network_plugin/cilium/templates/cilium/cr.yml.j2
  roles/network_plugin/cilium/templates/cilium/crb.yml.j2
  roles/network_plugin/cilium/templates/cilium/ds.yml.j2
  roles/network_plugin/cilium/templates/cilium/sa.yml.j2
  roles/network_plugin/cilium/templates/cilium/secret.yml.j2
  roles/network_plugin/cilium/templates/hubble/config.yml.j2
  roles/network_plugin/cilium/templates/hubble/cr.yml.j2
  roles/network_plugin/cilium/templates/hubble/crb.yml.j2
  roles/network_plugin/cilium/templates/hubble/cronjob.yml.j2
  roles/network_plugin/cilium/templates/hubble/deploy.yml.j2
  roles/network_plugin/cilium/templates/hubble/job.yml.j2
  roles/network_plugin/cilium/templates/hubble/sa.yml.j2
  roles/network_plugin/cilium/templates/hubble/service.yml.j2
  roles/network_plugin/cilium/templates/values.yaml.j2
  tests/files/debian12-cilium-svc-proxy.yml
  tests/files/debian12-cilium.yml
  tests/files/opensuse15-6-docker-cilium.yml
  tests/files/rockylinux9-cilium.yml
  tests/files/ubuntu20-cilium-sep.yml
Labels: cncf-cla: yes, size/XXL, lgtm, ok-to-test, approved, release-note-action-required, kind/feature, kind/design, tide/merge-method-merge, ci-extended

#12174 Allow stopping ubuntu unattended-upgrades
  roles/bootstrap_os/defaults/main.yml
  roles/bootstrap_os/tasks/ubuntu.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, release-note, kind/feature

#12156 Move some approvers to emeritus
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/S, lgtm, approved, kind/cleanup, release-note-none, ci-short

#12229 Removed equinix provider
  .gitlab-ci/terraform.yml
  contrib/terraform/equinix/README.md
  contrib/terraform/equinix/hosts
  contrib/terraform/equinix/kubespray.tf
  contrib/terraform/equinix/output.tf
  contrib/terraform/equinix/provider.tf
  contrib/terraform/equinix/sample-inventory/cluster.tfvars
  contrib/terraform/equinix/sample-inventory/group_vars
  contrib/terraform/equinix/variables.tf
  docs/_sidebar.md
  docs/cloud_providers/equinix-metal.md
Labels: cncf-cla: yes, size/XL, lgtm, ok-to-test, approved, kind/cleanup, release-note-none, ci-short

#12241 Chore: upgrade galaxy.yml version
  README.md
  docs/ansible/ansible.md
  galaxy.yml
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved, kind/documentation, kind/cleanup, release-note-none

#12245 Cleanup assert after 2.28
  roles/validate_inventory/tasks/main.yml
Labels: cncf-cla: yes, size/M, lgtm, approved, kind/cleanup, release-note-none

#12239 docs: remove obsolete cgroups variables
  docs/operations/cgroups.md
Labels: cncf-cla: yes, size/S, lgtm, approved, kind/documentation, release-note-none, ci-short

#12230 Removed weave support
  .github/ISSUE_TEMPLATE/bug-report.yaml
  README.md
  contrib/terraform/openstack/README.md
  docs/CNI/weave.md
  docs/_sidebar.md
  docs/advanced/arch.md
  docs/ansible/ansible.md
  docs/operations/upgrades.md
  inventory/sample/group_vars/k8s_cluster/k8s-cluster.yml
  inventory/sample/group_vars/k8s_cluster/k8s-net-weave.yml
  roles/kubernetes-apps/network_plugin/meta/main.yml
  roles/kubernetes-apps/network_plugin/weave/tasks/main.yml
  roles/kubernetes/preinstall/tasks/0050-create_directories.yml
  roles/kubespray_defaults/defaults/main/download.yml
  roles/kubespray_defaults/defaults/main/main.yml
  roles/network_plugin/meta/main.yml
  roles/network_plugin/weave/defaults/main.yml
  roles/network_plugin/weave/meta/main.yml
  roles/network_plugin/weave/tasks/main.yml
  roles/network_plugin/weave/templates/10-weave.conflist.j2
  roles/network_plugin/weave/templates/weave-net.yml.j2
  roles/reset/tasks/main.yml
  roles/validate_inventory/tasks/main.yml
  scripts/collect-info.yaml
  scripts/readme_versions.md.j2
Labels: cncf-cla: yes, size/XL, lgtm, ok-to-test, approved, release-note-action-required, kind/cleanup

#12228 Remove tag 'master'
  docs/ansible/ansible.md
  playbooks/cluster.yml
  roles/etcd/tasks/main.yml
  roles/kubernetes/preinstall/tasks/0050-create_directories.yml
  roles/validate_inventory/tasks/main.yml
Labels: cncf-cla: yes, size/S, lgtm, approved, release-note-action-required, kind/cleanup

#12178 Update load balancers versions to Nginx 1.28.0, Haproxy 3.1.7
  roles/kubespray_defaults/defaults/main/download.yml
Labels: cncf-cla: yes, size/XS, lgtm, ok-to-test, approved, release-note, kind/feature
